rero/rero-ils

rero_ils/config.py
rero_ils/modules/cli.py
rero_ils/modules/selfcheck/api.py
rero_ils/modules/selfcheck/cli.py
tests/api/selfcheck/test_selfcheck.py

* Allows the patron to do a renewal on the selfcheck machine.
* Adds CLI for selfcheck terminal creation.
* Adds renew handler..
Lauren-D <laurent.dubois@itld-solutions.be>

sip2: implements selfcheck renewal

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.3.0

---

rero_ils/es_templates/v7/record.json

* Readds unintentionally deleted values from elastic search record
template.

search: restore ES settings in the template

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py

- translations: translate v1.4.0
- release: v1.3.1
- Release `v1.3.1`.

release v1.3.1

---

rero_ils/theme/templates/rero_ils/search.html

public search: fix loading assets

---

rero_ils/modules/cli.py
rero_ils/modules/loans/cli.py
rero_ils/modules/operation_logs/cli.py
rero_ils/modules/patrons/cli.py
tests/unit/test_cli.py

* Uses JsonWriter to write json files.

global: use JsonWriter

---

rero_ils/modules/cli.py

* Deletes old unused `translate` function.

cli: delete unused function

---

rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json

search: add isbn text search

---

Dockerfile.base

instance: install procps to monitor processes

---

rero_ils/modules/loans/api.py

Adds rank position information into loan dump to easily display this
information into UI.
Related to https://github.com/rero/rero-ils-ui/pull/647

circulation: add rank position information

---

rero_ils/modules/monitoring.py

Co-Authored-by: Peter weber <peter.weber@rero.ch>

monitoring: fix ES duplicate display

---

rero_ils/modules/patrons/views.py

patrons: add email field on authenticate service

---

data/circulation_policies.json

fixtures: allow only one circulation policy

---

rero_ils/modules/circ_policies/api.py
tests/api/circ_policies/test_circ_policies_rest.py
tests/ui/circ_policies/test_circ_policies_api.py

circulation: allow only one default policy

---

rero_ils/modules/documents/api.py
rero_ils/modules/holdings/api.py

* Makes document is_available more fault tolerant for holding problems.

documents: reinforce availability robustness

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json

document: fix multiple relatedTo

---

rero_ils/modules/documents/jsonschemas/documents/document_classification-v0.0.1.json

* Moves part of the title in the description.
* Completes the description.
- To fix rero/rero-ils#2053

documents: fix assigning agency title, description

---

rero_ils/modules/patrons/cli.py

Fixes problem when user record is not created
for users having two profiles.

patrons: fix problem with importing users

---

poetry.lock
rero_ils/modules/cli.py
rero_ils/modules/selfcheck/api.py
rero_ils/modules/selfcheck/cli.py
tests/api/selfcheck/test_selfcheck.py

* Adds some CLI command to manage selfcheck terminals.
* Improves error messages in SIP2 handlers.
* Updates invenio-sip2 package.

sip2: improve command line utilities

---

rero_ils/config.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/mappings/v7/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/cli.py
rero_ils/modules/ext.py
rero_ils/modules/loans/logs/api.py
rero_ils/modules/notifications/cli.py
rero_ils/modules/operation_logs/api.py
rero_ils/modules/operation_logs/cli.py
rero_ils/modules/operation_logs/es_templates/v7/operation_logs.json
rero_ils/modules/operation_logs/extensions.py
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/operation_logs/listener.py
rero_ils/modules/patrons/listener.py
rero_ils/modules/stats/__init__.py
rero_ils/modules/stats/api.py
rero_ils/modules/stats/cli.py
scripts/setup
setup.py
tests/api/operation_logs/test_operation_logs_rest.py
tests/conftest.py
tests/data/data.json
tests/ui/loans/test_loans_operation_logs.py
tests/ui/operation_logs/test_operation_logs_api.py

* Enables operation logs for ill requests and items.
* Adds library information for the acquisition order lines.
* Creates operation logs when an resource is deleted.
* Fixes operation logs JSONSchema which contains several errors as it
was not used.
* Creates a hashed user pid at the operation logs creation.
* Removes useless debug messages.
* Adds a new configuration to validate the operation logs.
* Adds a cli to dump the statistics.
- https://tree.taiga.io/project/rero21-reroils/us/1848?milestone=293019
- bootstrap + setup
- `poetry run invenio stats dumps`

stats: compute stats for pricing

---

rero_ils/modules/items/serializers/json.py

items: add temporary location name by serializer

---

rero_ils/config.py
rero_ils/modules/acq_accounts/serializers.py
tests/api/test_serializers.py

Adds ES stored data into account serializer.

acquisitions: adds an account serializer

---

rero_ils/modules/loans/api.py
tests/ui/loans/test_loans_api.py

tests: fix unit test about loan overdue

---

rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/imports/api.py

* Makes import from BNF more stable.

documents: improve BNF import

---

rero_ils/manual_translations.txt

operation logs: translate trigger actions

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
tests/api/conftest.py
tests/data/data.json
tests/data/documents.json
tests/data/holdings.json

documents: set `adminMetadata` as required field.

---

rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

English currently translated at 100.0% (2605 of 2605 strings)
French currently translated at 100.0% (2605 of 2605 strings)
German currently translated at 100.0% (2605 of 2605 strings)
Italian currently translated at 98.0% (2555 of 2605 strings)
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/de/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/it/
Translation: RERO+/rero-ils
* …

translations: complete the v1.4.0 translations

---

data/users.json
rero_ils/modules/patrons/cli.py
rero_ils/utils.py

* Fixes users creation cli for data without pid.

users: fix CLI for user creation

---

rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

* Adds link to swisscovery.
* Improves order of blocks.

homepage: adaptation of the wallis homepage

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.4.1

---

rero_ils/theme/templates/security/email/reset_instructions.html
rero_ils/theme/templates/security/email/reset_instructions.txt
rero_ils/theme/templates/security/email/reset_notice.html
rero_ils/theme/templates/security/email/reset_notice.txt

translation: fix "Your Libray"

---

rero_ils/modules/notifications/dispatcher.py
tests/ui/notifications/test_notifications_api.py

notification: fix availability date

---

rero_ils/modules/cli.py

* Fixes problem when trying to load a record and its pid
is already reserved in database, system will now register
the pid and assign the new loaded record to it.

cli: fix create_or_update when pid is reserved

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.4.2

---

poetry.lock
rero_ils/modules/selfcheck/api.py

* Updates poetry.lock.
* Fixes missing language and translation.
* Adds alert message when item is requested.

dependencies: update invenio-sip2

---

rero_ils/accounts_views.py

users: improve user login error

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py

release: v1.4.3

---

rero_ils/modules/documents/jsonschemas/documents/document_classification-v0.0.1.json

document: fix `classification_musicale_instruments`

---

rero_ils/modules/ill_requests/permissions.py

ill requests: fix edit permission.

---

rero_ils/modules/items/api/circulation.py
tests/ui/items/test_items_api.py
tests/ui/notifications/test_notifications_api.py

Closes rero/rero-ils#2063.
Co-authored-by: Renaud Michotte <renaud.michotte@gmail.com>

item: fix issue availability

---

rero_ils/modules/documents/listener.py

document: add item `second_call_number` into ES

---

rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
tests/unit/test_ill_requests_jsonschema.py

ILL requests: allow free text into year field

---

rero_ils/modules/loans/logs/api.py
rero_ils/theme/templates/rero_ils/footer.html

circulation: fix item serial checkout

---

poetry.lock
rero_ils/modules/loans/api.py
rero_ils/modules/selfcheck/api.py

* Removes translated date format for circulation.
* Removes useless pycountry import.
* Bumps invenio-sip2 to v0.6.7.

sip2: fix date format

---

rero_ils/modules/cli.py
rero_ils/modules/monitoring.py
rero_ils/modules/operation_logs/api.py
tests/ui/test_monitoring.py

* Adds OperationLogsSearch class.
* Makes monitoring of operation logs better.

monitoring: improve operation logs monitoring

---

rero_ils/theme/templates/rero_ils/_frontpage_block_global.html
rero_ils/theme/templates/rero_ils/_frontpage_block_rbnj.html
rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

* Fixes links on the VS frontpage as asked by the organisation.
* Fixes the *Renouvaud* URL as the service changed it.
- Check changed files

theme: fix links on the frontpages

---

rero_ils/modules/documents/jsonschemas/documents/document_document_relation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_part_of-v0.0.1.json

documents: add autocomplete for document link

---

rero_ils/modules/documents/serializers.py

* adds `<record xmlns="http://www.loc.gov/MARC21/slim"
type="Bibliographic"` niveau to XML dump.

sru: add one more level

---

rero_ils/modules/cli.py

indexer: add from and until date

---

rero_ils/accounts_views.py

* Verify the user exist during a post login.

users: verify that user exists when logging in

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/templates/email/booking/eng.txt
rero_ils/modules/notifications/templates/email/booking/fre.txt
rero_ils/modules/notifications/templates/email/booking/ger.txt
rero_ils/modules/notifications/templates/email/booking/ita.txt
tests/api/notifications/test_notifications_rest.py

* Replace checkin patron information by the request patron information
in the booking notification email.
* Speed up `get_first_loan_by_state` method.
* Closes #2197.

notifications: add request patron information

---

setup.py

tasks: add the holdings deletion task

---

poetry.lock

acquisitions: fix poetry.lock file

---

rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

English currently translated at 100.0% (2605 of 2605 strings)
French currently translated at 100.0% (2605 of 2605 strings)
German currently translated at 100.0% (2605 of 2605 strings)
Italian currently translated at 100.0% (2605 of 2605 strings)
Spanish currently translated at 90.0% (2345 of 2605 strings)
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/de/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/it/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/es/
Translation: RERO+/rero-ils
Co-authored-by: Pascal Repond …

translations: translate v1.5.0

---

rero_ils/theme/templates/rero_ils/_frontpage_block_bulle.html
rero_ils/theme/templates/rero_ils/_frontpage_block_global.html
rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

- To update the frontpage with a new text. 

homepage: add warning about request on bulle page

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.4.6

---

poetry.lock
pyproject.toml

* Uses `invenio-sip2` version 0.6.7.

selfcheck: force the version

---

rero_ils/theme/templates/rero_ils/_frontpage_block_test.html

* Updates the link to the RERO+ Twitter account.
* Updates the text as the software is in production now.
- To update the demo website frontpage. 

theme: update the demo website frontpage

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/theme/assets/scss/rero_ils/header.scss
rero_ils/theme/templates/rero_ils/footer.html
rero_ils/theme/templates/rero_ils/header.html
rero_ils/theme/templates/rero_ils/page.html
rero_ils/theme/templates/rero_ils/search.html

* Fixes mobile menu.
* Fixes 'back button' position.
* Adds background color on footer.
* Keeps main search bar always visible.

design: improve responsive interface

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json

editor: remove imported fields on quick list

---

rero_ils/modules/loans/api.py

Adds pickup location specific name into loan data dumped for
circulation.

items: fix loans circulation dump

---

rero_ils/modules/documents/jsonschemas/documents/document_copyright_date-v0.0.1.json

document: remove pattern on `copyrightDate` field

---

rero_ils/modules/documents/utils.py

Closes rero/rero-ils#2213.
:heavy_exclamation_mark: Need to reindex all documents with corporate bodies including subdivisions

document: fix corporate bodies subdivision serialization

---

rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json

document: no default value for `subject.source`

---

rero_ils/modules/items/api/issue.py

issues: fix late issue generation.

---

rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/templates/email/booking/eng.txt
rero_ils/modules/notifications/templates/email/booking/fre.txt
rero_ils/modules/notifications/templates/email/booking/ger.txt
rero_ils/modules/notifications/templates/email/booking/ita.txt
tests/api/notifications/test_notifications_rest.py

notifications: fix pickup name for booking

---

poetry.lock
pyproject.toml
rero_ils/modules/selfcheck/api.py

* Checks if item is already checked out or requested
* Adds screen message on checkout error.
* Bumps invenio-sip2 to v0.6.10.

sip2: improve selfcheck checkout

---

rero_ils/modules/documents/utils.py

* Changes corporate body subdivisions if repeated to a dot.

documents: Fix subdivisions separator

---

rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/templates/email/availability/eng.txt
rero_ils/modules/notifications/templates/email/availability/fre.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/availability/ita.txt

notifications: Fix wrong pick-up location name

---

rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

- To fix typos on the VS frontpage (de)
- Check changed file.

theme: fix typos on the VS frontpage (de)

---

rero_ils/modules/monitoring.py
rero_ils/modules/notifications/dispatcher.py
tests/api/notifications/test_notifications_rest.py

* Avoids to send an incomplete email in case of error during the
notification generation.
* Fixes resend email every 15 minutes.
* Fixes bad logger messages.
* Adds traceback to the notification error logs.

notifications: do not send email in case of error

---

rero_ils/modules/utils.py

* Time stamps will not be deleted any more after 300 seconds.

monitoring: time stamp without expiration

---

rero_ils/modules/patrons/api.py

patrons: ignore created loans at patrons deletion

---

rero_ils/modules/selfcheck/api.py

* Fixes attribute error when we raise a 'NoCirculationAction` exception.

selfcheck: fix attibute error

---

rero_ils/modules/locations/api.py
tests/api/notifications/test_notifications_rest.py

* Handles deletion of location used as pickup or transaction location.

locations: fix delete locations used in loans

---

rero_ils/modules/selfcheck/api.py

* Uses default checkout logic.
* Adapts returned messages in `ItemNotAvailableError`.

selfcheck: fix checkout on item with pick-up status

---

rero_ils/config.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/mappings/v7/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_orders/serializers.py
tests/data/acquisition.json

* Fixes account facet for orders resource.
* Sets order date facet type for new `date-range` facet type.

acquisition: fix order facets configuration

---

data/libraries.json
rero_ils/modules/libraries/api.py
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
rero_ils/modules/libraries/models.py
tests/data/data.json
tests/ui/libraries/test_libraries_api.py
tests/unit/test_libraries_jsonschema.py

* Adds acquisition setting into the library resource schema. Shipping
and/or billing informations are allowed. For each section, we can
specify a name, email, phone and an address.

library: update resource for acquisition settings

---

rero_ils/modules/items/views/api_views.py
rero_ils/modules/loans/api.py

items: fix requested loans by library list

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/theme/templates/rero_ils/page.html
tests/unit/test_documents_dojson.py

* Fixes error 500 for translated url's in related resources.

documents: do not translate URL in detailed view

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.4.10

---

rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

* Changes the link to the PDF with ILL prices in French and German for
the frontpage of the organisation 2 (vs).
- Update the VS frontpage. 

theme: change the link for ILL prices

---

rero_ils/theme/templates/rero_ils/professional.html

Seems important for the editor performance.
* Add html tags to the professional angular application.

professional: fix angular assets

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py

release: v1.4.11

---

rero_ils/modules/loans/api.py

Dumping of a requested item fails when nor item nor holding hasn't any
call numbers.

loans: fix requested items dump

---

rero_ils/filter.py
rero_ils/modules/documents/templates/rero_ils/_documents_description.html
rero_ils/modules/documents/templates/rero_ils/_other_edition.html
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/modules/ext.py
rero_ils/modules/utils.py
rero_ils/theme/assets/scss/rero_ils/documents/detailed.scss
tests/ui/documents/test_documents_filter.py
tests/ui/test_filters.py
tests/unit/test_utils.py

documents: display all fields on the detail view

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_electronic_locator-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_scale_cartographic-v0.0.1.json
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
tests/unit/test_documents_jsonschema.py

* Closes #2080.
* Closes #2310.

editor: remove default values on optional fields

---

rero_ils/modules/cli.py

* Adds a cli for creation of documents with assoziated items.

documents: create documents with item CLI

---

CONTRIBUTING.rst
README.rst
SECURITY.rst

* Closes #2411.
- To add a minimal security policy. 

documentation: add a minimal security policy

---

rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/dumpers.py
rero_ils/modules/acq_orders/views.py
rero_ils/modules/libraries/dumpers.py
setup.py
tests/api/test_dumpers.py
tests/ui/acq_orders/test_acq_orders_api.py

* Creates dumper classes for acquisitions resources. These dumpers will
be used for order notification generation.
* Creates order notification preview endpoint.

acquisition: create acquisition resources dumpers

---

rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

English currently translated at 100.0% (2606 of 2606 strings)
French currently translated at 100.0% (2606 of 2606 strings)
German currently translated at 100.0% (2606 of 2606 strings)
Italian currently translated at 100.0% (2606 of 2606 strings)
Spanish currently translated at 89.7% (2339 of 2606 strings)
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/de/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/it/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/es/
Translation: RERO+/rero-ils
Co-authored-by: Nicolas Prongué …

translations: complete v1.5.0 translations

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.5.0

---

rero_ils/filter.py
rero_ils/modules/acq_accounts/extensions.py
rero_ils/modules/acq_orders/dumpers.py
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/eng.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/fre.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/ger.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/ita.tpl.txt
rero_ils/modules/acq_orders/views.py
rero_ils/modules/contributions/views.py
rero_ils/modules/ext.py
rero_ils/modules/vendors/api.py
rero_ils/modules/vendors/dumpers.py
rero_ils/theme/templates/rero_ils/address_block/eng.tpl.txt
rero_ils/theme/templates/rero_ils/address_block/fre.tpl.txt
rero_ils/theme/templates/rero_ils/address_block/ger.tpl.txt
rero_ils/theme/templates/rero_ils/address_block/ita.tpl.txt
setup.py
tests/api/acq_orders/test_acq_orders_views.py
tests/api/test_dumpers.py
tests/data/data.json
tests/ui/acq_orders/test_acq_orders_api.py
tests/ui/test_filters.py

* Adds dumpers class on `Vendor` resource.
* Adds API endpoint to preview an acquisition order.
* Creates vendor order notification templates.

acquisition: order notification preview

---

poetry.lock
pyproject.toml

* Fixes problems with new jsonschema version 4.0.0.
* Updates all other dependencies.

dependencies: fix jsonschema

---

rero_ils/modules/loans/utils.py

circulation: fix loan end_date

---

rero_ils/jsonschemas/common/languages-v0.0.1.json

documents: add `roh-latn` to language scripts

---

rero_ils/modules/loans/cli.py
rero_ils/modules/loans/utils.py

* Fixes problems prevented creation of loan during setup.
- run `setup`

circulation: fix loan fixtures for setup

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_receipt_lines/api.py
rero_ils/modules/acq_receipt_lines/listener.py
rero_ils/modules/acq_receipt_lines/mappings/v7/acq_receipt_lines/acq_receipt_line-v0.0.1.json
rero_ils/modules/acq_receipts/mappings/v7/acq_receipts/acq_receipt-v0.0.1.json
rero_ils/modules/ext.py
tests/ui/acq_receipt_lines/test_acq_receipt_lines_api.py

https://tree.taiga.io/project/rero21-reroils/task/2310

acquisition: calculate account expenditure

---

rero_ils/modules/acq_receipt_lines/api.py
rero_ils/modules/acq_receipt_lines/listener.py
rero_ils/modules/acq_receipt_lines/mappings/v7/acq_receipt_lines/acq_receipt_line-v0.0.1.json
rero_ils/modules/acq_receipts/api.py
tests/api/acq_receipt_lines/test_acq_receipt_lines_rest.py
tests/ui/acq_receipts/test_acq_receipts_api.py

acquisition: add field total_amount in ES

---

rero_ils/modules/acq_receipts/views.py
tests/api/acq_receipts/test_acq_receipts_views.py

* Removals of the `receipt_lines` parameter which is not necessary.

acquisition: improve entrypoint to create lines

---

rero_ils/config.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/extensions.py
rero_ils/modules/acq_orders/listener.py
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_orders/serializers.py
tests/api/acq_orders/test_acq_orders_rest.py
tests/ui/acq_orders/test_acq_orders_api.py

* Adds ordered and received item quantity into special `rero+json`
serializer.

acquisition: add serialization for `Acqorder` resource

---

.coveragerc
RELEASE-NOTES.rst
rero_ils/modules/api.py
rero_ils/modules/cli/__init__.py
rero_ils/modules/cli/fixtures.py
rero_ils/modules/cli/index.py
rero_ils/modules/cli/reroils.py
rero_ils/modules/cli/users.py
rero_ils/modules/cli/utils.py
rero_ils/modules/selfcheck/cli.py
rero_ils/modules/tasks.py
run-tests.sh
scripts/create_csvs
scripts/setup
scripts/setup_csv
scripts/update
setup.py
tests/api/documents/test_marcxml_rest_api.py
tests/api/patrons/test_patrons_views.py
tests/unit/test_cli_fixtures.py
tests/unit/test_cli_index.py
tests/unit/test_cli_utils.py
tests/unit/test_csv.py

indexer: use different queues for indexing

---

rero_ils/modules/cli/index.py
scripts/setup
scripts/setup_csv
scripts/update

setup: fix setup script

---

scripts/setup

acquisition:  fix setup script after bad rebase

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py

release: v1.6.1

---

rero_ils/modules/documents/jsonschemas/documents/document_admin_metadata-v0.0.1.json

documents: fix core level

---

rero_ils/modules/documents/api.py
rero_ils/modules/utils.py

documents: validate JSON references

---

rero_ils/modules/api.py
rero_ils/modules/ebooks/tasks.py
tests/ui/ebooks/test_ebooks_receivers.py

* Adds document schema to new records.

ebook: fix import

---

rero_ils/modules/documents/views.py
rero_ils/modules/notifications/subclasses/booking.py
rero_ils/modules/notifications/subclasses/internal.py
rero_ils/modules/notifications/subclasses/transit.py
tests/api/notifications/test_notifications_rest.py
tests/ui/notifications/test_notifications_api.py

notifications: fix request notification without recipient

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_receipts/api.py
rero_ils/modules/api.py
rero_ils/modules/libraries/api.py
rero_ils/modules/organisations/api.py
tests/api/acq_accounts/test_acq_accounts_rest.py
tests/api/acq_orders/test_acq_orders_rest.py
tests/api/acq_receipts/test_acq_receipts_rest.py
tests/api/libraries/test_libraries_rest.py
tests/api/organisations/test_organisations_rest_api.py

- Checks to delete an acquisition receipt.
- Rewritten get_links_to_me function for acq_accounts and acq_orders.

acquisition: can delete acquisition receipt

---

rero_ils/modules/notifications/subclasses/reminder.py

For UCLouvain reminder notifications, we need to include the item
informations into the context use to build the email template.

notifications: fix reminders notification template

---

rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json

documents: delete default value on identifiedby field

---

rero_ils/modules/items/api/issue.py

items: find item creation problem

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/models.py
tests/api/holdings/test_temporary_items.py
tests/data/data.json
tests/fixtures/metadata.py

https://tree.taiga.io/project/rero21-reroils/task/2351

items: add temporary item types

---

rero_ils/modules/cli/index.py
rero_ils/modules/contributions/mappings/v7/contributions/contribution-v0.0.1.json
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
tests/api/conftest.py
tests/api/test_search.py

* Closes rero#2526.
Data Migration Instructions:
* run `poetry run invenio reroils index update_mapping -s -a contributions -a documents -a items`.
- Resolve rero#2526.
- Try to search an item barcode you should have one or few results.

documents: fixes too many results

---

rero_ils/modules/documents/api.py
rero_ils/modules/utils.py
tests/ui/test_utils_app.py

documents: fix reference exist test

---

poetry.lock
pyproject.toml

* Fixes poetry warning message during the bootstrap step.

dependencies: update the dependencies lock file

---

rero_ils/config.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/holdings/models.py
rero_ils/modules/locations/api.py
rero_ils/modules/patrons/api.py
tests/api/holdings/test_holdings_rest.py

Allow to request an holding
https://tree.taiga.io/project/rero21-reroils/task/2352

holdings: allow request for holding

---

rero_ils/query.py
tests/api/operation_logs/test_operation_logs_rest.py
tests/data/data.json
tests/fixtures/circulation.py

* Closes #2530.
* Closes #2531.

operation logs: fix query if the user is both patron and librarian role

---

rero_ils/modules/documents/views.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/items/views/api_views.py
tests/api/circulation/test_locations_restrictions.py
tests/api/documents/test_documents_rest.py
tests/api/locations/test_locations_rest.py

Implemented get pickup locations for holdings
https://tree.taiga.io/project/rero21-reroils/task/2362

holdings: get pickup locations for holding

---

rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
rero_ils/translations/zh_Hant/LC_MESSAGES/messages.po

Arabic currently translated at 56.6% (1479 of 2609 strings)
Chinese currently translated at 11.6% (303 of 2609 strings)
English currently translated at 100.0% (2617 of 2617 strings)
French currently translated at 100.0% (2617 of 2617 strings)
German currently translated at 100.0% (2617 of 2617 strings)
Italian currently translated at 100.0% (2617 of 2617 strings)
Spanish currently translated at 89.5% (2344 of 2617 strings)
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/ar/
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/zh_Hant/
Translate-URL: …

translations: translate v1.7.0

---

CHANGES.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.7.0

---

rero_ils/modules/locations/api.py
tests/ui/locations/test_locations_other.py

* Adds temporary location to item links to me.
* Closes #2578.

locations: fix temporary deletion

---

rero_ils/config.py
rero_ils/modules/cli/utils.py
rero_ils/modules/contributions/api.py
rero_ils/modules/documents/tasks.py
rero_ils/modules/documents/utils_mef.py
tests/api/documents/test_documents_tasks.py
tests/data/data.json

* Implements ABC class for identifiedBy replacement.
* Rewrites contribution identifiedBy replacement.
* Implements identifiedBy subjects replacement for the types `bf:Person` and `bf:Organisation`

documents: replace identifiedBy subjects with $ref

---

rero_ils/modules/acq_accounts/dumpers.py
rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/eng.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/fre.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/ger.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/ita.tpl.txt
rero_ils/modules/acq_orders/views.py
rero_ils/modules/documents/dumpers.py
rero_ils/modules/documents/utils.py
rero_ils/modules/documents/views.py

* Adds some metadata into the available keys dictionary to create the
acquisition order notification.
* Updates acquisition order notification templates with more metadata.
* Cleans some code statements using "sourcery" plugin.

notifications: improve acquisition notification template

---

rero_ils/config.py
rero_ils/query.py
tests/api/holdings/test_holdings_rest.py
tests/api/items/test_items_rest.py

holdings/items: remove query filter and add a sort on the holdings

---

rero_ils/modules/circ_policies/api.py
rero_ils/modules/loans/utils.py
rero_ils/modules/notifications/tasks.py
rero_ils/modules/notifications/utils.py
rero_ils/modules/patron_transactions/api.py
tests/api/loans/test_loans_rest.py
tests/fixtures/circulation.py
tests/ui/notifications/test_notifications_utils.py

If the `CircPolicy` related to a reminder notification doesn't define
any corresponding reminder, an `IndexError` exception was raised and
caused processing troubles.

notification: fix notification fee amount calculation

---

rero_ils/config.py
rero_ils/theme/templates/rero_ils/page.html
rero_ils/theme/views.py

The name of the organization has been added in the title tag
to allow for proper indexing by search robots.

add organisation name on the title tag

---

rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json

professional: fix patron type creation

---

poetry.lock
pyproject.toml

* Uses a git tag to select an flask-wiki version.

deployment: fix flask-wiki

---

CHANGES.md
data/acq_accounts.json
pyproject.toml
rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html
rero_ils/version.py
scripts/bootstrap

- change the ui version when it will be released
- rebase on translations when they are done

release: v1.8.0

---

rero_ils/modules/items/views/api_views.py

The item availability API didn't respect rest API standards.

item: fix item availability API.

---

rero_ils/modules/holdings/api.py

holdings: serial issue isn't new acquisition

---

rero_ils/modules/documents/jsonschemas/documents/document_responsibility_statement-v0.0.1.json

document: set `responsibilities` as essential field

---

rero_ils/modules/patrons/views.py

patrons: use ISO format for dates into API

---

rero_ils/modules/libraries/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/subclasses/booking.py
rero_ils/modules/notifications/subclasses/internal.py
rero_ils/modules/notifications/subclasses/transit.py
tests/api/notifications/test_notifications_rest.py
tests/data/data.json
tests/ui/libraries/test_libraries_api.py
tests/ui/notifications/test_notifications_api.py

notifications: refactoring email getter function

---

rero_ils/modules/documents/jsonschemas/documents/document_electronic_locator-v0.0.1.json

document: fix `educationalSheet` translation

---

rero_ils/modules/loans/api.py

When asking for requested loans (user requests), we need to expose the
request date in addition to the transaction date.
Refactor some code lines in more pythonic way.

items: dump `request date` for any loan request

---

rero_ils/modules/documents/jsonschemas/documents/document_types-v0.0.1.json
rero_ils/modules/documents/static/images/icon_docmaintype_teaching_material.svg

document: add `teaching material` document type

---

rero_ils/config.py
setup.py
tests/ui/test_invenio_celery_tasks_endpoints.py

* Adds `invenio_celery.tasks` endpoint for documents.

document: fix invenio_celery.tasks endpoints.

---

poetry.lock
pyproject.toml

dependencies: fix

---

rero_ils/modules/api.py
rero_ils/modules/documents/api.py
rero_ils/modules/patrons/api.py

* Catches record creates errors and logs them

modules: add logging to create

---

rero_ils/modules/holdings/api.py

holding: fix delete all items for issue

---

rero_ils/query.py

item: add a organisation filter

---

rero_ils/modules/cli/reroils.py
rero_ils/modules/contributions/api.py
rero_ils/modules/contributions/cli.py
rero_ils/modules/contributions/models.py
rero_ils/modules/contributions/tasks.py
rero_ils/modules/contributions/views.py
rero_ils/modules/documents/utils.py
setup.py
tests/api/contributions/test_contributions_rest.py

contribution: online update

---

rero_ils/modules/contributions/api.py
rero_ils/modules/contributions/cli.py

contribution: fix update-contributions

---

rero_ils/modules/contributions/tasks.py
rero_ils/modules/documents/tasks.py
rero_ils/modules/ebooks/tasks.py
rero_ils/modules/holdings/tasks.py
rero_ils/modules/items/tasks.py
rero_ils/modules/loans/tasks.py
tests/ui/loans/test_loans_api.py

monitoring: better time stamps

---

rero_ils/modules/documents/utils.py
tests/unit/test_documents_dojson.py

documents: fix publication statement text dumping

---

rero_ils/modules/holdings/listener.py
rero_ils/modules/items/api/record.py
rero_ils/modules/notifications/templates/email/booking/eng.txt
rero_ils/modules/notifications/templates/email/booking/fre.txt
rero_ils/modules/notifications/templates/email/booking/ger.txt
rero_ils/modules/notifications/templates/email/booking/ita.txt
rero_ils/modules/notifications/templates/email/request/eng.txt
rero_ils/modules/notifications/templates/email/request/fre.txt
rero_ils/modules/notifications/templates/email/request/ger.txt
rero_ils/modules/notifications/templates/email/request/ita.txt
rero_ils/modules/notifications/templates/email/transit_notice/eng.txt
rero_ils/modules/notifications/templates/email/transit_notice/fre.txt
rero_ils/modules/notifications/templates/email/transit_notice/ger.txt
rero_ils/modules/notifications/templates/email/transit_notice/ita.txt

Solves issue #2494 
* rero/rero-ils-ui#822

Add call numbers in notification request for provisional items, filter serial items by issue status received

---

rero_ils/modules/errors.py
rero_ils/modules/selfcheck/api.py
tests/api/selfcheck/test_selfcheck.py

* Adds exception in circulation operation.

selfcheck: fix item not found.

---

rero_ils/alembic/2b0af71048a7_add_request_expiration_date.py
rero_ils/alembic/54134957af7d_loan_checkout_location_pid.py
rero_ils/alembic/90d857fb5c23_unpaid_subscription_limit.py

* Updates alembic scripts to avoid an elasticsearch timeout

alembic: fix elasticsearch timeout

---

rero_ils/modules/loans/utils.py
tests/ui/circulation/test_actions_extend.py

The extension duration calculation didn't take care about the
`from_end_date` configuration parameter. This will cause problem if an
organisation set this parameter to True because loan `end_date` after a
renewal will be set to any time of the day.

circulation: fix extension duration calculation.

---

rero_ils/modules/loans/logs/api.py

* Uses filter to retrieve main title of the document.
* Closes https://github.com/rero/rero-ils/issues/2581.
When we do a checkout (or checkin) of a document which de first title isn't a main title, operation logs on loan failed.

operation log: fix document title for loan

---

.github_changelog_generator

- add task label to ignore list

documentation: update changelog parameters

---

rero_ils/alembic/ce4923ba5286_delete_expired_items_temporary_locations.py
rero_ils/config.py
rero_ils/modules/items/api/api.py
rero_ils/modules/items/tasks.py
tests/api/test_tasks.py
tests/ui/items/test_items_api.py

* Indexes the field item.temporary_location.end_date.
* Closes #2694

items: delete obsolete temporary locations

---

rero_ils/modules/loans/listener.py
run-tests.sh
tests/ui/circulation/test_actions_extend.py

tests: fix `test_fees_after_extend` uni test

---

rero_ils/modules/cli/fixtures.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/dnb/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/kul/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/ugent/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
scripts/setup
tests/unit/test_cli_fixtures.py

* Fixes creation of contribution.
* Adds subjects to `get_all_mef_records.

dojson: fix contribution

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/dnb/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/kul/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/jsonschemas/documents/document_work_access_point-v0.0.1.json
tests/unit/test_documents_dojson.py
tests/unit/test_documents_dojson_slsp.py

* Fixes work access points $t.
* Fixes bf:KeyTitle tag 222

dojson: fix work access point and title

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json

- Change labels for `enumerationAndChronology` and
`supplementaryContent` to `Collection` and `Supplements`
Closes #1769

style(holdings): change unclear labels

---

rero_ils/modules/patron_transaction_events/api.py
tests/api/patron_transaction_events/test_patron_payments_rest.py

patron transaction: fix 'dispute' creation.

---

tests/api/circulation/test_actions_views_validate_request.py
tests/ui/circulation/test_actions_checkin.py

Impoves the automatic request validation unitest to validate that the
request expiration date is correct.
Closes rero/rero-ils#2679.

circulation: improve automatic request validation unitest

---

rero_ils/modules/locations/api.py
tests/ui/locations/test_locations_api.py
tests/ui/locations/test_locations_other.py

location: add holdings relations as reason to keep

---

rero_ils/modules/documents/views.py

* Allows display of drafts without type.
- Fixes https://github.com/rero/rero-ils/issues/2623

documents: draft view

---

rero_ils/alembic/05555c03fe49_correct_holdings_items_count.py
rero_ils/alembic/ce4923ba5286_delete_expired_items_temporary_locations.py

* Uses Holding reindex to correct holdings items_count and public_items_count.

alembic: fix 05555c03fe49

---

rero_ils/modules/cli/utils.py

fixtures: extract json

---

data/acq_accounts.json
data/budgets.json
data/libraries.json
data/organisations.json
scripts/setup

* Adds acquisition settings for all libraries.
* Adds acquisition accounts for all libraries.
* Fixes #2850 

fixtures: ensure better indexing of acqz data

---

rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

homepage: add viewcode on ill link for the vs skin

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
tests/api/acq_accounts/test_acq_accounts_rest.py

* Removes validation on name and number fields.
* Closes #2817.

acquisition account: remove validation on fields

---

pyproject.toml

* Deletes duplicated reroils cli entpoints from invenio cli.

cli: fix reroils endpoints

---

rero_ils/modules/contributions/api.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/imports/serializers/serializers.py
scripts/setup

* Integrates IdRef, GND and RERO identifiers in the document index.

document: agent identifiers

---

rero_ils/config.py
rero_ils/modules/contributions/utils.py
rero_ils/modules/documents/commons/subjects.py
rero_ils/modules/documents/serializers/__init__.py
rero_ils/modules/documents/serializers/base.py
rero_ils/modules/documents/serializers/ris.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/ext.py
rero_ils/modules/response.py
tests/api/documents/test_export_serializers.py
tests/conftest.py
tests/data/data.json
tests/fixtures/metadata.py

* Adds RIS serializer.
* Adds link to RIS in detail view.

documents: expose RIS metadata

---

rero_ils/modules/notifications/templates/email/at_desk/ger.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/booking/ger.txt
rero_ils/modules/notifications/templates/email/due_soon/ger.txt
rero_ils/modules/notifications/templates/email/overdue/ger.txt
rero_ils/modules/notifications/templates/email/recall/ger.txt
rero_ils/modules/notifications/templates/email/request/ger.txt

translations: replace 'Leser' by 'Kunde' in German

---

rero_ils/modules/notifications/subclasses/at_desk.py

An AT_DESK notification can be cancelled if no previous request has been
done on it.

notification: Fix AT_DESK notification

---

tests/api/notifications/test_notifications_rest.py

Some unitest are randomize to to the fact that AT_DESK and AVAILABILITY
notification could be operated during the same process cycle. So we
can't determine which notification is the last one received in the
mailbox. To solve this problem, we need to check into the two last
messages.

notifications: fix random unitest

---

rero_ils/modules/documents/jsonschemas/documents/document_electronic_locator-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json

items : adds protocol rtsp for URL pattern in jsonschemas of item and document
* Adds protocol rtsp for URL pattern in jsonschemas of item and document.
* Closes rero/rero-ils#2892.

items : adds protocol rtsp for URL pattern in jsonschemas of item and document

---

rero_ils/modules/commons.py
rero_ils/modules/documents/commons/subjects.py
tests/unit/documents/test_identifiers.py

* Add classes and methods to have a best document identifiers management.
* Add a behavior to render an identifier with a specific format
(depending of the desired output purpose).

document: identifiers management

---

poetry.lock
pyproject.toml
rero_ils/config.py
rero_ils/theme/templates/rero_ils/page_wiki.html

* updates flask-wiki to `v0.1.0` with EasyMDE integration

help: update flask-wiki

---

rero_ils/alembic/0387b753585f_correct_subjects_bf_Organization.py

documents: fix alembic bf:Organization

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py

* Improves mapping for SLSP dojson.
* Closes #2565.

documents: dojson SLSP

---

rero_ils/config.py
rero_ils/modules/views.py
rero_ils/theme/templates/rero_ils/frontpage.html
rero_ils/theme/views.py

* Closes #2762.
* Adds configurable robots.txt endpoint.
* Adds configurable link in Test message.
Co-Authored-by: Peter weber <peter.weber@rero.ch>

ui: robots.txt and test message

---

rero_ils/modules/loans/api.py
rero_ils/modules/loans/extensions.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
tests/api/loans/test_loans_rest.py

Set last_end_date to end_date at checkin before the end_date is set to transaction_date.
Closes #2637 
Solves issue #2637 
* rero/rero-ils-ui/pull/827

loans: set last_end_date of loan to end_date.

---

rero_ils/theme/templates/rero_ils/page_wiki.html

When fixing the version, I made an error in the CDN URL, the wrong js file is fetched and creates JS errors in the rero-ils help.
Quick-fix candidate for prod deployment.

help: fix easy-mde CDN

---

rero_ils/alembic/21a994dc2beb_add_library_pid_to_ill_request_.py
rero_ils/modules/ill_requests/extensions.py
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/stats/api.py
tests/api/stats/conftest.py
tests/api/stats/test_stats_rest.py
tests/fixtures/circulation.py

* Corrects `number_of_satisfied_ill_request`
with status pending|closed|validated.
* Corrects "Number of librarians" to include all librarians.
* Closes #2847 

stats: completions and corrections

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/extensions.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/views.py
rero_ils/modules/users/api.py
rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
rero_ils/modules/utils.py
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
tests/api/users/test_users_profile_updates.py
tests/unit/test_locations_jsonschema.py
tests/unit/test_patrons_jsonschema.py

* Adds a better 'email' format validation for all RERO-ILS resources.
* Simplify JSON schema defining fields with 'email' format.
* Adds length constraints for some `User` resource fields.
* Closes rero/rero-ils#2765.
* Closes rero/rero-ils#2838.

resource: improve data validation against JSONSchema

---

rero_ils/modules/holdings/listener.py

holdings: fix items updates

---

.github/workflows/continuous-integration-test.yml

test: fix github actions

---

rero_ils/config.py
rero_ils/es_templates/v7/record.json
rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_receipt_lines/dumpers.py
rero_ils/modules/acq_receipts/mappings/v7/acq_receipts/acq_receipt-v0.0.1.json
rero_ils/modules/commons/__init__.py
rero_ils/modules/commons/identifiers.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/dumpers.py
rero_ils/modules/documents/listener.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/query.py
rero_ils/modules/ebooks/tasks.py
rero_ils/modules/holdings/cli.py
rero_ils/query.py
tests/api/documents/test_documents_rest.py
tests/api/test_external_services.py
tests/ui/documents/test_documents_api.py
tests/unit/documents/test_identifiers.py

* Adds a new nested key into the document resource mapping to search on
combination of key/value identifiers.
* Adds a filter to search on this nested field by query string.
* Adds shortcut key to search on ISSN identifiers.
* Adds an analyzer to allow search on identifiers with or without special
characters.
* Fixes some ES DSL query using `identifierBy` key.
* Closes rero/rero-ils#2783.
* Closes rero/rero-ils#2446.
* Closes rero/rero-ils#1893.

document: nested identifiedBy

---

rero_ils/theme/templates/rero_ils/_frontpage_block_global.html

global front page: fix link to new ill request

---

rero_ils/config.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/items/tasks.py
tests/ui/holdings/test_serial_claims.py

* Keeps automatic creation of late issues.
* Fixes #2890

serials: disable automatic generation of claims

---

data/libraries.json
data/organisations.json
rero_ils/alembic/fc45b1b998b8_holdings_affiliated_to_libraries.py
rero_ils/modules/ebooks/tasks.py
rero_ils/modules/ebooks/utils.py
rero_ils/modules/libraries/api.py
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
rero_ils/modules/locations/api.py
rero_ils/modules/organisations/jsonschemas/organisations/organisation-v0.0.1.json
tests/api/organisations/test_organisations_rest_api.py
tests/data/data.json
tests/data/xml/ebook1.xml
tests/ui/ebooks/test_ebooks_receivers.py

e-books: holdings affiliated to libraries

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
tests/unit/documents/test_documents_dojson.py

dojson: fix rero 260

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/dnb/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/kul/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/ugent/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
tests/unit/documents/test_documents_dojson.py
tests/unit/documents/test_documents_dojson_slsp.py

* Implements dojson: abbreviated title.
* Implements dojson: scale (maps) and cartographicAttributes.
* Implements dojson: work access point.
* Implements dojson: temporal coverage.
* Closes #2878.

dojson: convert 4 last fields

---

rero_ils/modules/cli/fixtures.py
rero_ils/modules/contributions/api.py
rero_ils/modules/documents/tasks.py
rero_ils/modules/documents/utils_mef.py
tests/api/documents/test_documents_rest.py
tests/api/documents/test_documents_tasks.py
tests/data/data.json
tests/data/documents.json
tests/fixtures/metadata.py
tests/ui/contributions/test_contributions_api.py
tests/ui/documents/test_documents_api.py
tests/unit/documents/test_documents_dojson_marc21.py
tests/unit/documents/test_documents_jsonschema.py
tests/unit/documents/test_subjects.py
tests/unit/test_cli_fixtures.py
tests/utils.py

contributions: get also deleted MEF records

---

rero_ils/alembic/21a994dc2beb_add_library_pid_to_ill_request_.py

alembic: more robust ill request operation log

---

.gitignore
rero_ils/config.py
rero_ils/modules/acq_orders/serializers/__init__.py
rero_ils/modules/acq_orders/serializers/csv.py
rero_ils/modules/acq_orders/serializers/json.py
rero_ils/modules/api.py
rero_ils/modules/documents/serializers/base.py
rero_ils/modules/extensions.py
tests/api/acq_orders/test_acq_orders_serializers.py
tests/unit/test_csv.py

* Adds csv serializers.
* Adds .python-version to .gitignore.
* Removes useless `print()` method.
* rero/rero-ils-ui#866

acquisition: export orders

---

rero_ils/theme/templates/rero_ils/_frontpage_block_global.html

fix: ill link on the frontpage

---

tests/unit/documents/test_documents_dojson_marc21.py

translations: fix unitest

---

rero_ils/alembic/a941628259e1_add_keys_into_loan_index.py
rero_ils/config.py
rero_ils/modules/acq_orders/serializers.py
rero_ils/modules/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/listener.py
rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/models.py
rero_ils/modules/loans/query.py
rero_ils/modules/loans/serializers.py
rero_ils/modules/locations/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/dumpers.py
rero_ils/modules/serializers/base.py
rero_ils/query.py
tests/api/items/test_items_rest.py
tests/api/loans/test_loans_rest.py
tests/api/test_serializers.py
tests/ui/loans/test_loans_api.py
tests/ui/patrons/test_patrons_dumpers.py

* Adds metadata on each hit for loan search serialization.
* Adds loans facets configuration.
* Fixes loan indexer configuration.
* Improves code coverage.

loans: loans serializations.

---

rero_ils/config.py
rero_ils/modules/acq_accounts/serializers/__init__.py
rero_ils/modules/acq_accounts/serializers/csv.py
rero_ils/modules/acq_accounts/serializers/json.py
rero_ils/modules/acq_orders/serializers/__init__.py
rero_ils/modules/acq_orders/serializers/csv.py
rero_ils/modules/commons/identifiers.py
rero_ils/modules/documents/serializers/base.py
tests/api/acq_accounts/test_acq_accounts_serializers.py

* Adds csv serializers
* Closes #2899.
* rero/rero-ils-ui#870
* rero/ng-core#504

acquisition: export accounts

---

rero_ils/theme/assets/scss/rero_ils/thumbnail.scss

documents: fix the thumbnail size on different devices

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.12.0

---

rero_ils/modules/acq_order_lines/api.py

* Closes rero#2688.
* rero/rero-ils-ui#875
- see the issue

acquisition: fix deletion of order lines already received

---

rero_ils/theme/templates/rero_ils/header.html

test instances: allow message translation

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution_role-v0.0.1.json

* Closes https://github.com/rero/rero-ils/issues/1419

fix(contributions): show most used roles first

---

rero_ils/config.py
rero_ils/theme/templates/rero_ils/_frontpage_block_test.html
rero_ils/theme/templates/rero_ils/footer.html

* Adds an env variable for privacy policy URL for app footer
* Deletes irreleveant links for test instances

update links: privacy policy and test instances

---

rero_ils/modules/ebooks/utils.py
tests/ui/ebooks/test_ebooks_receivers.py

ebooks: fix deletion of holdings

---

poetry.lock
pyproject.toml

update flask-wiki to 0.2.1

---

rero_ils/modules/patron_transactions/utils.py

* Removes translated key in dictionnary.

patron transactions: fix incremental overdue fees

---

rero_ils/modules/notifications/subclasses/at_desk.py

notifications: fix notification at desk

---

rero_ils/config.py
rero_ils/theme/templates/rero_ils/footer.html

* Point ILS link to current release page
* RERO becomes RERO+
* Fix environment variable and link to privacy policy

 templates: update footer info

---

rero_ils/modules/contributions/api.py
rero_ils/modules/documents/api.py

* adds `subject_imported` $ref contribution replace refs.
* fixes contribution replace refs and minimizes MEF access.

documents: fix reindexing documents

---

rero_ils/dojson/utils.py
rero_ils/modules/cli/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/jsonschemas/documents/document_temporal_coverage-v0.0.1.json
tests/unit/documents/test_documents_dojson.py

dojson: better code

---

CONTRIBUTING.rst

documentation: update contributing guide

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json

holdings: fix json schema

---

data/templates.json

fixtures: fix incorrect patron template

---

data/role_policies.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/vendors/permissions.py
tests/api/organisations/test_organisations_permissions.py
tests/api/patron_types/test_patron_types_permissions.py
tests/api/vendors/test_vendors_permissions.py
tests/data/data.json
tests/data/role_policies.json
tests/utils.py

* Refactoring vendor policy access.
* Adapts unitest.

permissions: refactoring vendor policy

---

data/role_policies.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/item_types/permissions.py
tests/api/item_types/test_item_types_permissions.py
tests/data/role_policies.json

* Refactoring item type policy access.
* Adapts unitest.

permissions: refactoring item type policy

---

rero_ils/config.py
rero_ils/modules/contributions/permissions.py
tests/api/contributions/test_contributions_permissions.py

* Refactoring contibution policy access.
* Adapts unitest.

permissions: refactoring contribution policy

---

data/role_policies.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/ext.py
rero_ils/modules/ill_requests/permissions.py
rero_ils/modules/libraries/permissions.py
rero_ils/modules/permissions.py
tests/api/ill_requests/test_ill_requests_permissions.py
tests/data/role_policies.json

permissions: refactoring ILL request policy

---

scripts/setup
scripts/setup_csv

* Fixes overwhelming majority of ebooks compared to other document
types.

setup: limit number of ebooks in test instances

---

poetry.lock
pyproject.toml
rero_ils/modules/errors.py
rero_ils/modules/selfcheck/api.py
rero_ils/modules/selfcheck/utils.py
tests/api/selfcheck/test_selfcheck.py

* Uses username or email as user login.
* Adds `PatronBarcodeNotFound` exception.
* Updates invenio-sip2 dependency.
* Closes #2987.

selfcheck: fix user authentication

---

.gitignore
rero_ils/config.py
rero_ils/modules/acq_accounts/serializers/__init__.py
rero_ils/modules/acq_accounts/serializers/csv.py
rero_ils/modules/acq_accounts/serializers/json.py
rero_ils/modules/acq_orders/serializers/__init__.py
rero_ils/modules/acq_orders/serializers/csv.py
rero_ils/modules/acq_orders/serializers/json.py
rero_ils/modules/api.py
rero_ils/modules/commons/identifiers.py
rero_ils/modules/documents/serializers/base.py
tests/api/acq_accounts/test_acq_accounts_serializers.py
tests/api/acq_orders/test_acq_orders_serializers.py
tests/unit/test_csv.py

Merging 'US-Acquisition-export' on 'staging'
Closes https://github.com/rero/rero-ils/issues/2899

Us acquisition export

---

rero_ils/config.py

* Adds key entry on some sources.

import: fix configuration

---

data/libraries.json
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
tests/data/data.json

* Closes #2931.
⚠️  ES Update mappings + update all libraries record.
```python
from rero_ils.modules.libraries.api import Library
pids = [pid for pid in Library.get_all_pids()]
for pid in pids:
record = Library.get_record_by_pid(pid)
record['rollover_settings']['account_transfer'] = 'rollover_no_transfer'
record.update(record, dbcommit=True, reindex=True)
```

libraries: add rollover settings

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.13.0

---

data/role_policies.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/circ_policies/permissions.py
tests/api/circ_policies/test_circ_policies_permissions.py
tests/api/circ_policies/test_circ_policies_rest.py
tests/data/role_policies.json

* Refactoring circulation policies policy access.
* Adapts unitest.

permissions: refactoring circulation policies

---

rero_ils/modules/documents/views.py
tests/ui/documents/test_documents_filter.py

* Closes #2906 (case 2 in public view)

document: fix detailed view variant titles

---

rero_ils/modules/items/api/issue.py

fix irregular holdings

---

rero_ils/modules/cli/fixtures.py

* Excludes operation logs from bulk save.

fixtures: fix bulk_save

---

CHANGELOG.md
pyproject.toml
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/version.py

* Also adds a small correction to translations.

release: v1.13.1

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py

documents: add linked documents button

---

rero_ils/modules/documents/jsonschemas/documents/document_document_relation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_part_of-v0.0.1.json

* Closes #3018.
https://github.com/rero/rero-ils-ui/pull/898

document: link on havested documents is disabled

---

run-tests.sh

Adds exception for `cryptography` package due to dependencies to `dnspython` package.
Co-Authored-by:  Renaud Michotte <renaud.michotte@gmail.com>

general: fix vulnerabilities

---

data/role_policies.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/permissions.py
rero_ils/modules/stats/api.py
rero_ils/modules/stats/extensions.py
rero_ils/modules/stats/models.py
rero_ils/modules/stats/permissions.py
rero_ils/modules/stats/views.py
rero_ils/permissions.py
tests/api/stats/conftest.py
tests/api/stats/test_stats_permissions.py
tests/api/stats/test_stats_rest.py
tests/api/test_record_permissions.py
tests/data/policies/role_policies.json

permissions: refactoring statistics permission policy

---

rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html

ill requests: add warning to check organisation

---

rero_ils/modules/holdings/tasks.py

Sometimes an holding record is already deleted from the database, 
but the index is not up to date. In this case, we need to delete it from index.
* Fixes `delete_standard_holdings_having_no_items` task.

holdings: fix deletion of standard holdings

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

- Addresses RT 428.
Linked to https://github.com/rero/rero-ils-ui/pull/909

document: open electronicLocator in new tab

---

rero_ils/config.py
rero_ils/modules/acquisition/acq_accounts/api.py
rero_ils/modules/acquisition/acq_orders/api.py
rero_ils/modules/acquisition/acq_orders/dumpers.py
rero_ils/modules/acquisition/acq_orders/listener.py
rero_ils/modules/acquisition/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acquisition/acq_orders/serializers/json.py
rero_ils/modules/acquisition/acq_orders/utils.py
rero_ils/modules/acquisition/acq_orders/views.py
rero_ils/modules/acquisition/rollover.py
rero_ils/modules/libraries/api.py
rero_ils/modules/local_fields/mappings/__init__.py
rero_ils/modules/organisations/dumpers.py
rero_ils/modules/patrons/views.py
scripts/setup
tests/api/acq_orders/test_acq_orders_rest.py
tests/ui/patrons/test_patrons_ui.py

* Add API to get order history.
* Add configuration for budget facet for acquisition order.

acquisition: additional features about rollover

---

rero_ils/modules/documents/dumpers.py

acquisition: fix order notification template.

---

rero_ils/modules/cli/utils.py

* Cli for creation and validation for documents with items and or local fields.

document: document with item and or local field

---

rero_ils/config.py
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
rero_ils/translations/ru/LC_MESSAGES/messages.po
rero_ils/translations/zh_Hant/LC_MESSAGES/messages.po
rero_ils/utils.py

translations: translate v1.14.0 and fix

---

tests/ui/circulation/test_actions_extend.py

test: fix interval for fees after extend

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.14.0

---

rero_ils/modules/commons/identifiers.py

* When you asked to an identifier about alternatives only identifier `value` was cloned, other subfields were forgotten (qualifier, note, source, status). This PR fix this problem.
* Closes rero/rero-ils#2880.

fix: fix identifiers alternatives additional info

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.14.1

---

rero_ils/config.py
rero_ils/modules/utils.py
tests/unit/test_utils.py

password: add generator and validator

---

rero_ils/modules/loans/logs/api.py
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
tests/ui/loans/test_loans_operation_logs.py

users: add an option "no_information" for gender

---

rero_ils/alembic/5f0b086e4b82_patron_role_migration.py
rero_ils/alembic/eec683a446e5_merging_rero_ils_branches.py

permissions: alembic script to migrate librarian roles.

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json

serials: allows to edit an expected date

---

.github/workflows/stale.yml

actions: fix stale workflow to not close issues

---

rero_ils/modules/items/serializers/collector.py

items: fix CSV inventory list export

---

rero_ils/modules/contributions/sync.py
rero_ils/modules/documents/api.py
tests/ui/documents/test_documents_api.py

* Fixes role in contributions for indexing.

documents: fix role in contribution

---

rero_ils/modules/imports/api.py
rero_ils/modules/sru/cql_parser.py
tests/api/test_external_services.py
tests/conftest.py
tests/data/xml/loc/loc_without_010.xml

* Corrects transformation errors for bad searches for LOC.

imports: LOC

---

rero_ils/config.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/listener.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/collector.py
rero_ils/modules/items/serializers/csv.py
rero_ils/modules/items/serializers/json.py
tests/ui/circulation/test_actions_checkin.py

⚠️  Data Migration: Update mappings and reindex items.
* Closes #2708.

inventory: add current pending requests

---

rero_ils/modules/holdings/api_views.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/loans/api.py
rero_ils/modules/selfcheck/api.py
tests/api/circulation/test_actions_views_checkin.py

* Adds information what kind of "no circulation action" was happened.

circulation: better logs for no circulation action

---

rero_ils/config.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
tests/api/items/test_items_rest.py

items: fix item inventory sorting problems.

---

rero_ils/modules/items/api/record.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/loans/utils.py
rero_ils/modules/locations/api.py
tests/api/test_availability.py

item: use item temporary location to validate request

---

rero_ils/dojson/utils.py
tests/api/documents/test_documents_rest.py
tests/conftest.py
tests/ui/contributions/test_contributions_api.py
tests/ui/documents/test_documents_api.py
tests/unit/documents/test_documents_dojson.py
tests/unit/documents/test_documents_dojson_marc21.py
tests/unit/documents/test_documents_jsonschema.py
tests/unit/documents/test_subjects.py

* Uses `RERO_ILS_MEF_AGENTS_URL` in tests.

test: better MEF tests

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
tests/unit/documents/test_documents_dojson.py

* Uses correct `DE-101` id's for GND links.
* Corrects SLSP, GND, LOC subjects dojson.

import: fix get_contribution_link

---

rero_ils/modules/monitoring/api.py
rero_ils/modules/monitoring/cli.py
rero_ils/modules/monitoring/views.py
rero_ils/modules/notifications/subclasses/reminder.py
rero_ils/modules/tasks.py
tests/api/items/test_items_rest_views.py
tests/api/test_monitoring_rest.py

monitoring: ES indices

---

rero_ils/modules/libraries/api.py
rero_ils/modules/locations/api.py
rero_ils/modules/stats/api.py
rero_ils/modules/stats/exceptions.py
rero_ils/modules/stats/jsonschemas/stats/stat-v0.0.1.json
rero_ils/modules/stats/mappings/v7/stats/stat-v0.0.1.json
rero_ils/modules/stats/models.py
rero_ils/modules/stats_cfg/api.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/stats/conftest.py
tests/ui/stats/test_stats_reports.py

Data processing for statistics report
* add class for statistics report
* add tests to create reports
https://github.com/rero/rero-ils/issues/3044

statistics: add processing class for statistics report

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/listener.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/listener.py
rero_ils/modules/items/serializers/collector.py
rero_ils/modules/local_fields/api.py
rero_ils/modules/local_fields/dumpers.py
rero_ils/modules/local_fields/extensions.py
tests/ui/local_fields/test_local_fields_api.py

* Adds relations between LocalField and Item.
* Adds relations between LocalField and Document.
* Automatic LocalFields deletion when related resource are deleted.
* Closes rero/rero-ils#3207.

local_fields: improve LocalField interactions with other resources

---

rero_ils/manual_translations.txt
rero_ils/theme/assets/js/reroils/login.js
rero_ils/theme/assets/scss/rero_ils/styles.scss
rero_ils/theme/templates/rero_ils/macros/macro.html

login: add a way to display the password

---

rero_ils/modules/loans/logs/api.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/listener.py
rero_ils/modules/notifications/logs/__init__.py
rero_ils/modules/notifications/logs/api.py
rero_ils/modules/operation_logs/api.py
rero_ils/modules/operation_logs/es_templates/v7/operation_logs.json
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/operation_logs/logs/__init__.py
rero_ils/modules/operation_logs/logs/api.py
tests/api/loans/test_loans_rest.py
tests/ui/loans/test_loans_operation_logs.py

* Closes https://github.com/rero/rero-ils/issues/2639.

operation logs: add the notifications sent

---

rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/views.py
rero_ils/theme/templates/rero_ils/_patron_info_message.html
rero_ils/theme/templates/rero_ils/_patron_info_message_data.html
rero_ils/theme/templates/rero_ils/header.html
tests/ui/test_patron_message.py

patron: change message on expired account

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

The browser console displays an error 404 in the detailed view.
* Closes #2008.

document: fix cover art display

---

rero_ils/config.py
rero_ils/modules/stats/views.py

The libraries are filtered according to the logged-in user.
* Closes #3297.

stats: fix for filtering libraries

---

rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html
rero_ils/modules/ill_requests/views.py
rero_ils/theme/assets/js/reroils/ills_request.js

The system checks if a copy exists in case the url matches the current catalog. The user has the possibility to continue even if the document exists.
* Closes #3138.

ILL request: check if item exists in organisation

---

rero_ils/modules/contributions/sync.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/utils_mef.py
rero_ils/modules/utils.py
tests/api/test_monitoring_rest.py

* Fixes get online for records with added sources.
* Fixes set timestamp for cleaning sync errors.

contribution: fix get online

---

rero_ils/modules/api.py
rero_ils/modules/contributions/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/cli.py
rero_ils/modules/loans/utils.py
scripts/setup

setup: fix errors

---

rero_ils/config.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/operation_logs/es_templates/v7/operation_logs.json
tests/api/items/test_items_rest_views.py

Added a new api to return statistics on a item (total and past year).
* Closes #2996.

item operation history: add statistics

---

rero_ils/alembic/add75cbcad66_migrate_obsolete_country_codes.py
rero_ils/dojson/utils.py
rero_ils/jsonschemas/common/countries-v0.0.1.json
tests/data/data.json
tests/unit/documents/test_documents_dojson.py

* Closes #2881.
* Closes #2883.
* :warning: Contains alembic script

jsonschema: upgrade obsolete country codes

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
tests/data/xml/slsp/slsp_anywhere_123.xml
tests/data/xml/slsp/slsp_samuelson.xml
tests/unit/documents/test_documents_dojson.py

import: fix contribution $ref creation

---

rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html
rero_ils/theme/assets/js/reroils/toggle.js
tests/ui/ill_requests/test_ill_requests_ui.py

* Fixes pickup location filter in pro UI.
* Fixes incorrect patron form field "copy".
* Closes #1671.

ill requests: fix forms

---

CHANGELOG.md
poetry.lock
pyproject.toml
rero_ils/version.py
scripts/bootstrap

* Updates rero-invenio-base to `v0.2.1`.

release: v1.16.0

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
tests/unit/documents/test_documents_dojson.py

fix: import tests

---

data/libraries.json
rero_ils/modules/libraries/dumpers.py
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
tests/data/data.json
tests/ui/libraries/test_libraries_dumpers.py

* Adds serial acquisition settings on `Library` resource to allow claim
notification behavior/management.
* Adds serial claim library dumpers.

library: serial acquisition settings

---

rero_ils/config.py
rero_ils/modules/entities/api.py
rero_ils/modules/entities/cli.py
rero_ils/modules/entities/jsonschemas/entities/entity-v0.0.1.json
rero_ils/modules/entities/sync.py
rero_ils/modules/entities/tasks.py
rero_ils/modules/entities/utils.py
tests/api/documents/test_documents_rest.py
tests/api/documents/test_documents_tasks.py
tests/conftest.py
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/documents/test_documents_api.py
tests/ui/documents/test_documents_mapping.py
tests/ui/entities/test_entities_api.py
tests/ui/entities/test_entities_utils.py
tests/unit/documents/test_documents_dojson.py
tests/unit/test_cli_fixtures.py

entities: sync for contributions and concepts

---

rero_ils/modules/acquisition/acq_orders/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/dumpers.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/dumpers.py
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/collector.py
rero_ils/modules/locations/api.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/extensions.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/mappings/v7/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/models.py
rero_ils/modules/notifications/subclasses/circulation.py
rero_ils/modules/notifications/subclasses/claim_issue.py
rero_ils/modules/notifications/templates/email/claim_issue/eng.tpl.txt
rero_ils/modules/notifications/templates/email/claim_issue/fre.tpl.txt
rero_ils/modules/notifications/templates/email/claim_issue/ger.tpl.txt
rero_ils/modules/notifications/templates/email/claim_issue/ita.tpl.txt
tests/api/items/test_items_issue.py
tests/api/test_serializers.py
tests/data/holdings.json
tests/ui/holdings/test_holdings_api.py
tests/ui/notifications/test_notifications_api.py

* Creates claim issue notification type.
* Creates claim issue notification templates.
* Adds some unitest for claim notification.

notification: create claim issue notification

---

rero_ils/modules/sru/cql_parser.py
rero_ils/modules/sru/views.py
tests/unit/test_cql_parser.py

sru: xml save query string handling

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.17.0

---

rero_ils/modules/acquisition/acq_orders/api.py
rero_ils/modules/acquisition/acq_orders/utils.py
rero_ils/modules/acquisition/acq_orders/views.py
rero_ils/modules/ext.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/dumpers.py
rero_ils/modules/items/utils.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/items/views/filters.py
rero_ils/modules/notifications/templates/email/claim_issue/eng.tpl.txt
rero_ils/modules/notifications/templates/email/claim_issue/fre.tpl.txt
rero_ils/modules/notifications/templates/email/claim_issue/ger.tpl.txt
rero_ils/modules/notifications/templates/email/claim_issue/ita.tpl.txt
rero_ils/modules/vendors/api.py
rero_ils/modules/vendors/dumpers.py
tests/api/acq_orders/test_acq_orders_views.py
tests/api/items/test_items_issue.py
tests/data/data.json

* Creates API to preview a claim notification content.
* Creates API to create a real claim.
* In the order preview API response, the recipient suggestions are exposed instead of data used to build the template. This is used by the UI preview component to use these address in the drag/drop section recipient section.

items: claims issue API

---

rero_ils/config.py

facet: fix subjects fiction

---

CHANGELOG.md
pyproject.toml
rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json
rero_ils/version.py

* Also adds a forgotten fix to bf:Organisation labels.

release: v1.17.1

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json

Added defaultValueExpression entry to the jsonschema to allow adding a default value.
* Closes #2777.
UI: https://github.com/rero/rero-ils-ui/pull/977
NG-CORE: https://github.com/rero/ng-core/pull/548

item: add the default value expression function

---

data/vendors.json
rero_ils/config.py
rero_ils/modules/acquisition/acq_orders/api.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/dumpers.py
rero_ils/modules/items/listener.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/serializers/collector.py
rero_ils/modules/items/serializers/json.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/items/views/filters.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/subclasses/circulation.py
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
tests/api/items/test_items_issue.py
tests/api/items/test_items_rest.py
tests/data/acquisition.json
tests/ui/notifications/test_notifications_api.py

* Adds claim notification information into ES data (for facetting)
* Adds claim notification information for item `rero+json` serializer.
* Forces `communication_language` field of `Vendor` resource as required field.

items: claim notification serialization

---

rero_ils/modules/operation_logs/extensions.py
tests/api/documents/test_documents_rest.py

When the current_library parameter is present in the request, it is assigned to the library in the logs operation.
* Closes #3310.

operation logs: assign current library request

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/serializers/json.py
tests/api/items/test_items_serializer.py
tests/api/test_serializers.py

* Closes #2965.
- https://github.com/rero/rero-ils-ui/pull/976

item: add circulation information

---

rero_ils/config.py
rero_ils/dojson/utils.py
rero_ils/modules/apiharvester/cli.py
rero_ils/modules/apiharvester/tasks.py
rero_ils/modules/apiharvester/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/ebooks/receivers.py
rero_ils/modules/imports/api.py
rero_ils/modules/imports/views.py
tests/api/test_external_services.py
tests/ui/apiharvester/test_apiharvester_utils.py

import: SUDOC

---

data/ill_requests.json
rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
tests/data/data.json

- Closes https://github.com/rero/rero-ils/issues/2027.

ill requests: fix professionnal editor

---

rero_ils/config.py
rero_ils/modules/documents/jsonschemas/documents/document_contribution_entity_link-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form_link-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/remote_entities/test_entities_api.py
tests/ui/test_invenio_celery_tasks_endpoints.py

* Updates pattern allowed for linked entity.
* Updates linked entity widget configuration.

document: update type of agent entity field into document JSON schema

---

rero_ils/config.py
rero_ils/modules/entities/local_entities/api.py
rero_ils/modules/entities/local_entities/jsonresolver.py
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json

* Uses default operation log extension.
Implements task: https://tree.taiga.io/project/rero21-reroils/task/2668

entities: configure operation logs for local entities

---

rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

rero+: update vs frontpage

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.18.0

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
scripts/test
tests/unit/documents/test_documents_dojson_marc21.py

SRU: correct unnecessary log for bf:Temporal transformation

---

rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json

* Adds place, temporal and work type on subject filters.

document: add 3 new type of subjects

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_entity_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json

* Adapts entites labels and descriptions to account for local VS textual entities.

entities: adapt labels and descriptions

---

rero_ils/modules/ill_requests/api.py

Returns all ILL requests related to a patron, not yet filtered by request status.

ILL request: update patron circulation statistics

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py

import: fix SLSP scale and cartographic

---

rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/views.py

* Fixes sorting on the pickup location menu.
* Fixes the translation of "Select…" on the pickup location menu.
* Closes #3432.

fix: ill sorting on the pickup location menu

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

document: improved display of genre form field

---

rero_ils/modules/stats/api.py
rero_ils/modules/stats/serializers.py
rero_ils/modules/stats/utils.py

* Create csv file for statistics reports.
* Transform data from list to table for reports with 2 distributions.
The test should be added after rebase of the PR for the permissions, without this PR the test fails.
https://github.com/rero/rero-ils/issues/3044

statistics: add serializer to generate the report csv file

---

rero_ils/config.py
rero_ils/modules/stats/cli.py
rero_ils/modules/stats/tasks.py
rero_ils/modules/stats_cfg/api.py
scripts/setup
tests/api/test_tasks.py
tests/data/data.json
tests/fixtures/metadata.py

Create cli and tasks for statistics report
https://github.com/rero/rero-ils/issues/3044

statistics: add cli and tasks for statistics report

---

rero_ils/config.py
rero_ils/modules/entities/remote_entities/jsonschemas/remote_entities/remote_entity-v0.0.1.json
rero_ils/modules/entities/remote_entities/proxy.py
rero_ils/modules/entities/remote_entities/replace.py
rero_ils/modules/entities/remote_entities/sync.py
tests/api/entities/remote_entities/test_remote_entities_rest.py
tests/data/data.json
tests/data/mef.json
tests/fixtures/metadata.py
tests/ui/entities/remote_entities/test_remote_entities_api.py

entities: add temporal

---

rero_ils/modules/entities/templates/rero_ils/entity_local.html
rero_ils/modules/entities/templates/rero_ils/entity_remote.html

* Adds the display Place, Temploral for the remote entity.

entity: add display for new types

---

rero_ils/modules/cli/utils.py

* Saves created item or lofi records to error file

cli: create_documents_with_items_lofis

---

rero_ils/dojson/utils.py

* Creates more MEF references for SUDOC contributions.

import: better contribution for SUDOC

---

CHANGELOG.md
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.19.0

---

rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json

* Fix characters in jsonschemas descriptions that prevent the strings to be translated.

translations: fix untranslated strings

---

rero_ils/modules/libraries/api.py
rero_ils/modules/locations/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/stats/api/librarian.py
rero_ils/modules/stats/api/pricing.py
rero_ils/modules/stats/api/report.py
rero_ils/modules/stats/exceptions.py
rero_ils/modules/stats/jsonschemas/stats/stat-v0.0.1.json
rero_ils/modules/stats/models.py
tests/ui/stats/test_stats_report.py
tests/ui/stats/test_stats_report_n_deleted_items.py
tests/ui/stats/test_stats_report_n_docs.py
tests/ui/stats/test_stats_report_n_ill_requests.py
tests/ui/stats/test_stats_report_n_items.py
tests/ui/stats/test_stats_report_n_patrons.py
tests/ui/stats/test_stats_report_n_serial_holdings.py
tests/ui/stats/test_stats_report_number_of_ciculation.py

stats: add report computation

---

rero_ils/modules/entities/remote_entities/replace.py

* Fixes wrong source pid for updated MEF records.

remote_entities: fix ReplaceIdentifiedBy

---

rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py

* Fixes repetive qualifiers from tag[010] $b.

import: fix BNF qualifier

---

rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json

* Changes status label and adds a loan_status value for clarity.

ill requests: improve status display

---

rero_ils/config.py
rero_ils/modules/imports/api.py

* Adds import from Renouvaud.
* Closes #3518.

import: Add Renouvaud

---

rero_ils/modules/notifications/api.py

notifications: fix timezone for process_date

---

rero_ils/modules/entities/remote_entities/cli.py

* Displays MEF pids with errors in verbose print.

entity: Add verbose to sync-errors cli.

---

rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/utils.py
rero_ils/modules/items/extensions.py
rero_ils/modules/items/tasks.py
tests/ui/holdings/test_holdings_patterns.py

* Deletes `received_date` from issue if LATE.
* Closes: #3457.

items: fix late issue

---

rero_ils/config.py
rero_ils/modules/patrons/query.py
tests/api/patrons/test_patrons_rest.py

patron: add blocked and expired filters

---

rero_ils/config.py
rero_ils/modules/ill_requests/api.py
rero_ils/query.py
tests/api/ill_requests/test_ill_requests_rest.py

ill_request: add month filter

---

rero_ils/config.py
rero_ils/modules/documents/query.py
rero_ils/modules/documents/serializers/json.py
rero_ils/theme/templates/rero_ils/search.html
tests/api/documents/test_documents_rest.py

* Adds aggregation acquisition.
* Optimizes aggregation year.
* Adds values according to facet results (year, acquisition).
* Changes acquistion filter to include max date.
* Closes #3525.

document: add new acquisition aggregation

---

rero_ils/config.py
rero_ils/modules/acquisition/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acquisition/acq_receipt_lines/dumpers.py
rero_ils/modules/acquisition/acq_receipt_lines/serializers.py
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
rero_ils/modules/vendors/mappings/v7/vendors/vendor-v0.0.1.json

* Uses normalizer for sorting.
* Adds sort config.
* Adds record serializer alias for receipt line.
* Uses default AcqJSONSerializer for receipt line.

acquisition: improve sorting for vendors and orders

---

rero_ils/modules/entities/remote_entities/replace.py
rero_ils/modules/tasks.py

* Adds return value to `scheduler_timestamp`task.

scheduler: better timestamp

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/utils.py
rero_ils/modules/imports/api.py
rero_ils/modules/imports/views.py
tests/api/documents/test_documents_rest.py
tests/api/test_external_services.py
tests/utils.py

* Adds `_text` for SUDOC contribubtion with $ref.

import: fix SUDOC authors facette

---

rero_ils/modules/imports/api.py
rero_ils/modules/imports/serializers/serializers.py
rero_ils/modules/imports/views.py
tests/api/test_external_services.py

* Adds error message and code for failed requests

import: better error code

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py

* Fixes subject creation for work and conferences.

import: fix DNB subject

---

rero_ils/modules/items/api/circulation.py
tests/api/notifications/test_notifications_rest.py
tests/ui/circulation/test_actions_cancel_request.py

* Fixes incorrect test for action CANCEL_REQUEST_5_1_2.
* Closes #3403.
* Closes #3569.

fix(circ): item can wrongfully become at desk

---

rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json

* Adds `pattern` to organisation reference.

item_types: better schema

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/imports/api.py

* Fixes SRU searches for recordid for alama.
* Fixes alma import (SLSP, KUL, Renouvaud) for searches with serial responses.
* Closes: #2992.

import: fix alma import

---

rero_ils/modules/patrons/views.py
tests/api/patrons/test_patrons_rest.py

* Fixes API /info for users without patron.

patron: fix API /info

---

rero_ils/modules/loans/api.py
tests/api/items/test_items_rest.py

feat(loan): add temporary location on item

---

data/remote_entities_big.json
data/remote_entities_small.json
rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
rero_ils/modules/entities/dumpers/document.py
rero_ils/modules/entities/remote_entities/mappings/v7/remote_entities/remote_entity-v0.0.1.json
rero_ils/modules/imports/serializers/serializers.py
tests/data/mef.json
tests/unit/conftest.py

* Replaces `bf:Agent` key with `type` key.

remote_entities: remove bf:Agent

---

rero_ils/modules/collections/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/listener.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
tests/api/collections/test_collections_api.py
tests/data/holdings.json
tests/ui/holdings/test_holdings_item.py
tests/ui/holdings/test_holdings_patterns.py

* Adds `call_numbers` index with all call numbers.
* Adds `issue.inherited_second_call_number`.
* Closes: #3620.

items: better call_number search

---

rero_ils/modules/items/dumpers.py
rero_ils/modules/notifications/subclasses/booking.py
rero_ils/modules/notifications/subclasses/request.py
rero_ils/modules/notifications/templates/email/booking/eng.txt
rero_ils/modules/notifications/templates/email/booking/fre.txt
rero_ils/modules/notifications/templates/email/booking/ger.txt
rero_ils/modules/notifications/templates/email/booking/ita.txt
rero_ils/modules/notifications/templates/email/request/eng.txt
rero_ils/modules/notifications/templates/email/request/fre.txt
rero_ils/modules/notifications/templates/email/request/ger.txt
rero_ils/modules/notifications/templates/email/request/ita.txt

* Adds `Item type` and `Temporary item type` to `booking` and `request` notifications.
* Closes: #3377

notifications: add circulation category

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/serializers/json.py
rero_ils/modules/imports/api.py
rero_ils/modules/imports/views.py

* Fixes year facet for imports.
* Better publication year facet for documents.

facet: fix year

---

rero_ils/modules/templates/permissions.py
tests/api/templates/test_templates_permissions.py
tests/api/templates/test_templates_rest.py

fix(templates): allow private delete for syslib

---

rero_ils/query.py
tests/api/ill_requests/test_ill_requests_rest.py

The "remove_archived" parameter is used to records older than 6 months when the status is different from "Pending".
* Closes rero/rero-ils#3527.

fix(ill): conditional filter

---

rero_ils/modules/collections/api.py
rero_ils/modules/items/dumpers.py
tests/ui/items/test_items_dumpers.py

Add the name of the temporary location as well as
the name of the collections.
* Closes #1321.

feat(item): add extra data on item dumper

---

rero_ils/config.py
rero_ils/modules/patron_transaction_events/listener.py
rero_ils/modules/patron_transaction_events/mappings/v7/patron_transaction_events/patron_transaction_event-v0.0.1.json
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/listener.py
rero_ils/modules/patron_transactions/mappings/v7/patron_transactions/patron_transaction-v0.0.1.json
tests/api/patron_transaction_events/test_patron_transaction_events_rest.py
tests/api/patron_transactions/test_patron_transactions_rest.py

* Adds document and item pid to patron_transaction_events ES.
* Adds item filter to patron_transaction_events.

patron_transaction_events: add item informations

---

rero_ils/modules/selfcheck/api.py

selfcheck translations needs to work outside of the application context.
* Uses `force_locale` method from babel package.
* Closes: rero#3423.

selfcheck: fix messages translations

---

rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
tests/unit/conftest.py
tests/unit/documents/test_documents_dojson_marc21.py

* Adds date and time of latest transaction (tag=005) to marc21 dojson used by SRU.

documents: add 005 to marc21 dojson

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py

* Fixes `_do_work_access_point_creator` date creation.

import: fix work access point

---

rero_ils/config.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/theme/assets/scss/rero_ils/babeltheque.scss
rero_ils/theme/webpack.py
tests/ui/documents/test_documents_filter.py

⚠️  Override configuration to activate a view
RERO_ILS_APP_BABELTHEQUE_ENABLED_VIEWS

feat: babeltheque

---

data/documents_small.json
rero_ils/alembic/bd78d77eb7e3_isfiction.py
rero_ils/config.py
rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/dnb/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/kul/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/ugent/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/models.py
rero_ils/modules/documents/templates/rero_ils/_documents_description.html
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
tests/api/conftest.py
tests/api/documents/test_documents_rest.py
tests/data/data.json
tests/data/documents.json
tests/data/holdings.json
tests/unit/documents/test_documents_dojson.py
tests/unit/documents/test_documents_dojson_unimarc.py

* Changes `fiction` to enum: "Fiction"/"Non-fiction"/"Unspecified"
* Closes: #3677

documents: enum fiction

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_entity_link-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_entity_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json

* Updates contribution oneOf.
* Update subjects oneOf.

fix(document): improve jsonschema oneOf

---

.gitignore
docker-compose.full.yml
docker-compose.yml
docker-services.yml

* Removes version on docker file (obsolete)
* Adds data/files path on gitignore.

chore: remove version on docker files

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json

* Reverts required fields in oneOf.

fix(editor): resolve contribution and subject required subfields

---

CHANGELOG.md
pyproject.toml
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
rero_ils/translations/ru/LC_MESSAGES/messages.po
rero_ils/translations/zh_Hant/LC_MESSAGES/messages.po
rero_ils/version.py
scripts/bootstrap
scripts/setup

* Also fixes two translations.

release: v1.22.1

---

rero_ils/modules/serializers/base.py
tests/api/patron_transaction_events/test_patron_payments_rest.py

* Adds `unknown` in `enrich_bucket_with_data` function for records 
with problems (for example deleted records).
* Closes #3702.

serializer: add `unknown`

---

rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
rero_ils/modules/ebooks/tasks.py
tests/data/data.json
tests/data/xml/ebook2.xml
tests/ui/ebooks/test_ebooks_receivers.py

ebooks: document type

---

poetry.lock

* Fixes dependencies.
* Fixes webpack install.
* Adds favicons.

dependencies: fix vulnerabilities

---

rero_ils/config.py
scripts/test

fix: font-src console error

---

.github/workflows/continuous-integration-test.yml
docker/wait-for-services.sh
poetry.lock
pyproject.toml

* Linked to deprecation of Docker Compose v1 in Github Actions: https://github.com/actions/runner-images/issues/9692

chore(deprecation): update compose commands to v2

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py

* Fixes error for SLSP imports with incorrect 008.

import: fix SLSP

---

poetry.lock
rero_ils/modules/selfcheck/utils.py

sip2: fix format_patron_address

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py

fix(public document view): allow harvested documents with physical items

---

rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json

* Closes https://github.com/rero/rero-ils/issues/3745.

fix(patron barcodes): extend the number of barcodes

---

rero_ils/theme/templates/rero_ils/_frontpage_block_vs.html

chore(prod): adapt VS frontpage

---

rero_ils/config.py
rero_ils/modules/documents/tasks.py
tests/ui/documents/test_documents_api.py

documents: delete drafts

---

docs/conf.py
rero_ils/config.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/utils.py
rero_ils/modules/users/api.py
rero_ils/modules/utils.py
tests/ui/conftest.py
tests/ui/test_views.py

logging: add user information to sentry

---

rero_ils/modules/organisations/api.py
tests/api/organisations/test_organisations_rest_api.py

documents: fix incorrect viewcode

---

rero_ils/theme/templates/rero_ils/login_user.html
scripts/test

- Closes #3789.
- Adds vulnerability exception (tests).

fix: clarify user login for patrons

---

rero_ils/modules/documents/tasks.py

* Maks better timestamps for `delete_orphan_harvested`` and `delete_drafts`.

monitoring: better timestamps

---

rero_ils/modules/patrons/templates/rero_ils/patron_profile.html

patron: Add search bar to patron profile page

---

rero_ils/modules/imports/views.py
rero_ils/modules/items/views/rest.py
tests/api/test_external_services.py

permissions: Add API permissions

---

rero_ils/config.py
rero_ils/es_templates/v7/record.json
rero_ils/modules/documents/dumpers/indexer.py
rero_ils/modules/files/services.py
rero_ils/modules/patrons/views.py
tests/api/documents/test_documents_rest.py
tests/ui/patrons/test_patrons_ui.py

* Adds `files-*` to ES record template.
* Changes `max_files_count` to 2100.

files: change template and max_files_count

---

rero_ils/modules/entities/remote_entities/api.py

* Gets last updated remote entity in `get_entity` function.

remote entities: fix sync

---

rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json

* Closes #3833.
* :warning: Migration requires a full documents reindex !

fix(documents index): add `call_numbers.raw`

---

rero_ils/theme/templates/rero_ils/frontpage.html
rero_ils/theme/templates/rero_ils/header.html
rero_ils/theme/templates/rero_ils/professional.html

* Fixes layer order for admin view.
* Adds ui: css prefix to the angular components.

fix(ui): add ui css prefix

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/tasks.py
tests/ui/documents/test_documents_api.py

documents: update item document_type

---

rero_ils/modules/files/cli.py
rero_ils/modules/files/operations.py
rero_ils/modules/migrations/data/cli.py
tests/api/operation_logs/test_operation_logs_rest.py
tests/fixtures/metadata.py

* Corrects output for migration.data.get cli.
* Adds needed index flush after `ReindexRecordFile` indexing.

migration: fixes and better code

---

rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json

Ref: https://github.com/rero/ng-core/pull/720

chore(user): update config for the datepicker
