rero/rero-ils

deployment/populate.sh
development/docker/populate.sh
reroils_app/config.py

This commit concern the [taiga task 608](https://tree.taiga.io/project/rero21-reroils/task/608), [taiga task 609](https://tree.taiga.io/project/rero21-reroils/task/609), [taiga task 611](https://tree.taiga.io/project/rero21-reroils/task/611)
- update populate
- new data export
ℹ️ See pull request reroils-data https://github.com/rero/reroils-data/pull/43

add new document types

---

Pipfile
data/apisources.yml
rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/apiharvester/__init__.py
rero_ils/modules/apiharvester/cli.py
rero_ils/modules/apiharvester/models.py
rero_ils/modules/apiharvester/signals.py
rero_ils/modules/apiharvester/tasks.py
rero_ils/modules/apiharvester/utils.py
rero_ils/modules/ext.py
rero_ils/modules/mef/__init__.py
rero_ils/modules/mef/api.py
rero_ils/modules/mef/fetchers.py
rero_ils/modules/mef/minters.py
rero_ils/modules/mef/models.py
rero_ils/modules/mef/providers.py
rero_ils/modules/mef/receivers.py
rero_ils/modules/mef/tasks.py
rero_ils/modules/persons/__init__.py
rero_ils/modules/persons/jsonschemas/__init__.py
rero_ils/modules/persons/jsonschemas/persons/mef-person-v0.0.1.json
rero_ils/modules/persons/mappings/__init__.py
rero_ils/modules/persons/mappings/v6/__init__.py
rero_ils/modules/persons/mappings/v6/persons/mef-person-v0.0.1.json
scripts/setup
setup.py
tests/modules/mef/test_mef_fetchers.py
tests/modules/mef/test_mef_minters.py

* NEW: apiharvest module
* NEW: mef module
* NEW: persons module for schema and es mapping
* NEW: automaticly harvest persons from http://mef.test.rero.ch/api/mef
To Test:
```
./scripts/bootstrap
./script/setup
```
Start MEF and ILS server
update source config for mef harvesting locally:
`pipenv run invenio apiharvester source mef http://localhost:5002/api/mef -u`

harvest mef

---

data/users.json

* FIX: correct users with personas data
* BETTER: adapt users data to the organization fixture (Aoste)
Co-authored-by: Nicolas Prongué <nicolas.prongue@rero.ch>
-----------------------------------------------------------------
- `pipenv run invenio fixtures importusers data/users.json -v`
- verify that
- the address of Astrid, Virgile, Simonetta, Helder are  in "Canton Aoste"
- that Astrid and Virgile are librarian, and Simonetta and Helder are patrons

fixtures: users following personas templates

---

rero_ils/bundles.py
rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/documents_items/serializers.py
rero_ils/modules/documents_items/static/js/rero_ils/documents_items.js
rero_ils/modules/documents_items/templates/rero_ils/detailed_view_documents_items.html
rero_ils/modules/items/api.py
rero_ils/modules/items/templates/rero_ils/_item_head.html
rero_ils/modules/items/templates/rero_ils/detailed_view_items.html
rero_ils/modules/items/views.py
rero_ils/modules/locations/api.py
rero_ils/modules/locations/templates/rero_ils/detailed_view_locations.html
rero_ils/modules/members_locations/templates/rero_ils/detailed_view_members_locations.html
rero_ils/modules/organisations/templates/rero_ils/detailed_view_organisations.html
rero_ils/modules/organisations_members/templates/rero_ils/detailed_view_organisations_members.html
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/templates/rero_ils/detailed_view_patrons.html
rero_ils/static/js/rero_ils/tooltips.js
setup.py

needs: https://github.com/rero/reroils-record-editor/pull/5 
* NEW: test of can delete
* NEW: Disable delete button with can delete test
* NEW: Add message on disable delete button
* FIX: cvs export

can delete

---

data/apisources.yml
rero_ils/modules/apiharvester/cli.py
rero_ils/modules/apiharvester/utils.py
rero_ils/modules/ebooks/receivers.py
rero_ils/modules/mef/receivers.py
rero_ils/modules/mef/tasks.py

*FIX: size for harvesting
*BETTER: verbose print
Attention: 
max_result_window set to 20000 in json mapping (not always the same in config.py)
To display max_result_window from ES:
`curl -H "Content-Type: application/json" -GET http://localhost:19200/_all/_settings?pretty`
To make themax_result_window bigger in ES use folowing command (change config.py too):
`curl -H "Content-Type: application/json" -XPUT http://localhost:19200/_all/_settings -d '{ "index" : { "max_result_window" : 10000000}}'`

apiharvester: fix size

---

babel.ini
rero_ils/templates/rero_ils/macros/person.html
rero_ils/templates/rero_ils/search.html
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot

* NEW: translates the sprint 11 features

frontend: translations

---

data/circulation_policies.json
rero_ils/modules/circ_policies/cli.py
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/circ_policies/templates/rero_ils/detailed_view_circ_policies.html

* FIX: closes #125, closes #127
To test:
- get the PR branch
- ./scripts/setup (only if you don't have data in your instance db) 
- run the tests
Display the list of available circulation policies (cipo),  edit or a dd a new one, you should not be able to add a negative value and now the days are marked with a "day(s)"

Circulation policy: issues

---

rero_ils/modules/organisations_libraries/utils.py
rero_ils/modules/utils.py
rero_ils/templates/rero_ils/search.html
run-tests.sh
ui/admin/proxy.conf.json
ui/admin/src/app/app.module.ts
ui/admin/src/app/libraries/exception-dates-edit/exception-dates-edit.component.html
ui/admin/src/app/libraries/libraries-routing.module.ts
ui/admin/src/app/libraries/libraries.service.ts
ui/admin/src/app/libraries/library-form.service.ts
ui/admin/src/app/libraries/library.ts
ui/admin/src/app/libraries/library/library.component.html
ui/admin/src/app/libraries/library/library.component.ts
ui/admin/src/app/libraries/main/main.component.ts

Libraries: Library creation
* NEW: library creation by admin ui
* BETTER: Refactoring library form to implement creation
To test:
- `bootstrap` script
- Check create function with button `Create` on list

Library creation

---

ui/admin/angular.json
ui/admin/src/app/app.module.ts
ui/admin/src/app/libraries/exception-dates-list/exception-dates-list.component.ts

* BETTER: Fix translation
Closes:#163

ADMIN: Fix translation

---

rero_ils/modules/patrons/templates/rero_ils/_patron_profile_head.html
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_personal.html
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
rero_ils/templates/rero_ils/macros/macro.html

* BETTER: implement new layout for patron profile view
* FIX: fix person detailed view for medium devices
* remove an unused class in the rero_ils macros
---------
- log in as a patron (Simonetta or Helder) (the login page is in PR rero/rero-ils#180)
- display the http://localhost:5000/patrons/profile (3 tabs, different screens).

Layout: patron profile

---

rero_ils/config.py
rero_ils/modules/apiharvester/utils.py
rero_ils/modules/cli.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/listener.py
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/documents/serializers.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/modules/ext.py
rero_ils/modules/items/api.py
rero_ils/modules/items/cli.py
rero_ils/modules/items/templates/rero_ils/_item_head.html
rero_ils/modules/items/templates/rero_ils/detailed_view_items.html
rero_ils/modules/items/views.py
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/utils.py
rero_ils/modules/patrons/views.py
rero_ils/static/templates/rero_ils/facets.html
tests/api/test_items_rest.py
tests/data/data.json
tests/ui/documents/test_documents_api.py
tests/ui/items/test_items_api.py
ui/admin/package-lock.json

⚠️ the admin views are not yet back
- FIX: document search view
- FIX: document detailed view
- FIX: patron profile view
- FIX: item detailed view
- BETTER: library facet are based on library pid
Signed-off-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>
- ./scripts/bootstrap
- ./run-tests.sh
- ./scripts/setup

VIEWS: fix $ref relations

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/documents/api.py
rero_ils/modules/item_types/api.py
rero_ils/modules/items/api.py
rero_ils/modules/libraries/api.py
rero_ils/modules/locations/api.py
rero_ils/modules/organisations/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/serializers.py
rero_ils/permissions.py
rero_ils/templates/rero_ils/_editor_button_actions.html
tests/api/test_circ_policies_rest.py
tests/api/test_serializers.py
tests/conftest.py
tests/ui/circ_policies/test_circ_policies_api.py
tests/ui/documents/test_documents_api.py
tests/ui/item_types/test_item_types_api.py
tests/ui/items/test_items_api.py
tests/ui/libraries/test_libraries_api.py
tests/ui/locations/test_locations_api.py
tests/ui/organisations/test_organisations_api.py
tests/ui/organisations/test_organisations_jsonresolver.py
tests/ui/patron_types/test_patron_types_api.py
tests/ui/patron_types/test_patron_types_jsonresolver.py
tests/ui/patrons/test_patrons_api.py

NEW: Implement global can_delete
To Test:
get the PR branch
./run_tests.sh
- Nothing really to test because frontend implementation is planned in Taiga# 775 
- Interface, try to delete any document having items, you should get exception "IlsRecordError.NotDeleted"

RECORDS: can_delete

---

.gitmessage.txt
CONTRIBUTING.rst
INSTALL.rst
Pipfile.lock

* NEW Adds a commit template.
* BETTER Updates accordingly the CONTRIBUTING.rst file.
* Removes unused .rst references in the INSTALL.rst file.
:warning: Do not forget to configure your git repository:
- `git config --local commit.template .gitmessage.txt` OR
- `git config --global commit.template /path/.gitmessage.txt`

repository: commit template

---

rero_ils/modules/circ_policies/api.py
tests/ui/circ_policies/test_circ_policies_utils.py

* FIX Returns only policies when pair exists in settings

Circulation Policies: Locate policy using item/patorn types pair

---

MANIFEST.in
rero_ils/config.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
rero_ils/modules/documents/jsonresolver_mef_person.py
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/listener.py
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/modules/ext.py
rero_ils/modules/mef_persons/jsonschemas/persons/mef_person-v0.0.1.json
rero_ils/modules/mef_persons/templates/rero_ils/_person_unified.html
rero_ils/modules/mef_persons/templates/rero_ils/detailed_view_persons.html
rero_ils/modules/mef_persons/views.py
rero_ils/views.py
scripts/setup
setup.py
tests/api/test_locations_rest.py
tests/conftest.py
tests/data/data.json
tests/ui/documents/test_documents_api.py
tests/ui/documents/test_documents_filter.py
tests/ui/mef_persons/test_mef_persons_ui.py
tests/utils.py

* NEW: $ref to mef in the json file
* BETTER: detailed view document
* BETTER: detailed view person
* NEW: proxy to mef
* NEW: new 10k extraction of documents
* NEW: indexing into mef_persons
**!!!!!! ATTENTION !!!!!!!**
following env variables have to be set:
```
RERO_ILS_MEF_HOST='mef.test.rero.ch'
RERO_ILS_MEF_URL="https://mef.test.rero.ch/api/"
```
For testing the `bootstap` and `setup` script must be lanched!

DATA: $ref for mef persons

---

rero_ils/config.py
rero_ils/filter.py
rero_ils/modules/admin.py
rero_ils/modules/ext.py
rero_ils/permissions.py
rero_ils/templates/rero_ils/macros/header_menus.html

* NEW Adds a configuration for menu categories icons.
* BETTER Attributes categories to organize submenus.
* BETTER Adds filter to remove special characters in categories name.
---
- restart your app
- check the categorisation of menus

user interface: menus structure

---

rero_ils/modules/items/templates/rero_ils/detailed_view_items.html

* FIX Fixes link between item details view and circulation UI
closes #234
- Go to the item detail view of a checked-out or requested item  and click on the patron name and make sure it will take you to the CIRC UI page

CIRCULATION: link from item details to circ UI

---

ui/src/app/circulation/main-checkin-checkout/main-checkin-checkout.component.ts

* FIX Fixes error when scanning a no-checkout item in CIRC UI
* closes #233
** TESTS
- re deploy angular app
- login as a librarian and visit http://localhost:5000/admin/circulation/checkinout?patron=2050124311
- scan an item barcode with item type "No Checkout"
- you will receive the following message "no action possible on this item!"

Circulation UI: Checkout possible according to circ policy

---

.dockerignore
Dockerfile
Dockerfile.base
rero_ils/config.py
ui/src/app/autocomplete/autocomplete.component.ts

* BETTER Improves docker image by removing node_modules.
* FIX Fixes autocomplete for deployement(ContentSecurity headers).
Signed-off-by: Peter Weber <peter.weber@rero.ch>

DEPLOY: autocomplete resolution for deployement

---

ui/src/app/records/custom-editor/libraries/library-form.service.ts
ui/src/app/records/custom-editor/libraries/library.component.html
ui/src/app/records/custom-editor/libraries/library.ts
ui/src/app/shared/time-validator.ts

* NEW Reorders opening hours for 1 day if the second hour is less than the first hour
* BETTER Improves the overlap validator if the second hour is less than the first hour
* FIX Closes #222

library admin: improvement

---

rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
ui/src/app/records/custom-editor/circulation-settings/circulation-policy-form.service.ts
ui/src/app/records/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.html

* BETTER Makes description fields for patron types, item types and circulation policies not required.
* FIX Closes #224

admin: field description not mandatory

---

Pipfile
Pipfile.lock
rero_ils/modules/admin.py
setup.py

* NEW Move to invenio version 3.1.

ALL: invenio 3.1 support

---

rero_ils/config.py
rero_ils/modules/items/api.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/utils.py
tests/api/test_items_rest.py

* NEW Blocks renewal if renewal due date less than checkout due date
* FIX Fixes #231.
- Create the following scenario:
Checked-out item its renewal-due-date is less than its check-out-due-date
The renewal will be rejected
- For all renewals, the renewal-due-date is calculated from current-date

Circulation: renewal due date from current_date

---

ui/src/app/records/search/brief-view/documents-brief-view.component.ts

* FIX removes button add item.
How to test:
- go to document brief view (admin) and note the deletion of the button

Delete add item button in the document search view

---

rero_ils/modules/items/api.py
rero_ils/modules/items/api_views.py
tests/api/test_items_rest.py
ui/src/app/circulation/items.ts

* FIX Fixes #230: allows checkout of in-transit items.
This two scenarios works:
- checkout out an item (having no requests) with loan_status= ITEM_IN_TRANSIT_TO_HOUSE to any patron.
- checkout out an item with loan_status= ITEM_IN_TRANSIT_FOR_PICKUP to any requested patron from any checkout library.

circulation: possibility to check-out in-transit items

---

rero_ils/modules/items/api.py
tests/api/test_items_rest.py

* FIX Fixes #38: renewal is not possible on requested items
Signed-off-by: Aly Badr aly.badr@rero.ch
- UI: no more possible to extend a requested item.

circulation: patron request blocks item renewals

---

rero_ils/modules/loans/api.py
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
ui/src/app/circulation/requested-items-list/requested-items-list.component.html

* BETTER Replace pickup location by pickup library in the patron profile and circulation ui.
* BETTER Remove useless column in the patron profile.
* Changed name variable to be more clear.
- boostrap

user interface: pickup library instead of pickup location

---

rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/__init__.py
rero_ils/modules/patrons/listener.py
rero_ils/modules/patrons/mappings/__init__.py
rero_ils/modules/patrons/mappings/v6/__init__.py
rero_ils/modules/patrons/utils.py
rero_ils/modules/patrons/views.py
tests/api/test_items_rest_views.py
tests/api/test_loans_rest.py
tests/api/test_patrons_rest.py
tests/api/test_patrons_views.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/patrons/test_patrons_api.py
tests/ui/patrons/test_patrons_ui.py
tests/unit/test_patrons_jsonschema.py

* BETTER increase test coverage and add docs for patrons.

global: test coverage and docs for patrons

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/items/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/locations/api.py
rero_ils/modules/organisations/api.py
rero_ils/modules/patrons/api.py
rero_ils/permissions.py
tests/api/test_circ_policies_rest.py
tests/api/test_item_types_rest.py
tests/api/test_items_rest_views.py
tests/api/test_libraries_rest.py
tests/api/test_loans_rest.py
tests/api/test_locations_rest.py
tests/api/test_organisations_rest_api.py
tests/api/test_patron_types_rest.py
tests/api/test_patrons_rest.py
tests/api/test_patrons_views.py
tests/fixtures/circulation.py

* NEW Restricts access to APIs for users of same organisation.
* ./run_tests.sh
* localhost:5000/api/< record_type >/ < pid > 
read/write/delete/update is now available only for records of logged users organisation

rest API: access restriction by organisation read, write, delete, update

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/ext.py
rero_ils/permissions.py
tests/fixtures/circulation.py
tests/ui/test_permissions.py
tests/utils.py

* NEW Fixes issue when edit/delete buttons are displayed for users of other organisations.
* Display a document having items from two organisations (possibly http://localhost:5000/documents/299)
* The edit/delete buttons are only displayed for items of your organisation

views: disabling edit/delete buttons for items of other organisation

---

Pipfile
Pipfile.lock
rero_ils/config.py
rero_ils/views.py
tests/ui/test_views.py

config: Sentry support

---

rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
tests/api/test_patrons_rest.py
tests/ui/patrons/test_patrons_api.py
tests/unit/test_patrons_jsonschema.py

* FIX Fixes problem when patron ids are created twice.
* FIX Fixes problem when users are created with no roles.

fix: patron persistent identifiers

---

rero_ils/es_templates/__init__.py
rero_ils/es_templates/v6/record.json
rero_ils/modules/cli.py
scripts/setup
setup.py

Adds a sharded lowercase and asciifolding analzer using ES templates to be used in several indexes.
How to test:
- `script/bootstrap`
- `script/setup`
-  Kibana console: `GET /_template` to show custom analyzer 

indexing: add a custom text analyzer in ES template

---

rero_ils/modules/item_types/mappings/v6/item_types/item_type-v0.0.1.json
tests/conftest.py
tests/ui/conftest.py
tests/ui/item_types/conftest.py
tests/ui/item_types/test_item_types_api.py
tests/ui/item_types/test_item_types_mapping.py

* Adds analyzer on name and description fields.
* Adds es config on test to support templates.
* Fixes type on description field.
How to test:
- `script/setup`
- `http://localhost:5000/admin/records/item_types`
- Find a term and check if the result is correct (value in fields name or description)

indexing: update item types mapping

---

rero_ils/modules/patron_types/mappings/v6/patron_types/patron_type-v0.0.1.json
tests/conftest.py
tests/ui/patron_types/conftest.py
tests/ui/patron_types/test_patron_types_api.py
tests/ui/patron_types/test_patron_types_mapping.py

* Adds analyzer on name and description fields.
How to test:
* `script/setup`
* http://localhost:5000/admin/records/patron_types
* Find a term and check if the result is correct (value in fields name or description)

indexing: update patron types mapping

---

rero_ils/modules/item_types/mappings/v6/item_types/item_type-v0.0.1.json
rero_ils/modules/patrons/mappings/v6/patrons/patron-v0.0.1.json
tests/conftest.py
tests/data/data.json
tests/ui/conftest.py
tests/ui/item_types/conftest.py
tests/ui/item_types/test_item_types_api.py
tests/ui/item_types/test_item_types_mapping.py
tests/ui/patrons/conftest.py
tests/ui/patrons/test_patrons_mapping.py

* Adds analyzer on first_name, last_name, street and city fields.
* Fixes type on first_name, last_name, street and city fields.
How to test:
* `script/setup`
* http://localhost:5000/admin/records/patrons
* Find a term and check if the result is correct (value in fields name or description)

indexing: update patrons mapping

---

Pipfile
Pipfile.lock
rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/ext.py
rero_ils/modules/items/jsonresolver.py
rero_ils/modules/loans/jsonresolver.py
rero_ils/modules/notifications/__init__.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/jsonschemas/__init__.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/listener.py
rero_ils/modules/notifications/mappings/__init__.py
rero_ils/modules/notifications/mappings/v6/__init__.py
rero_ils/modules/notifications/mappings/v6/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/models.py
rero_ils/modules/notifications/views.py
rero_ils/modules/patrons/jsonresolver.py
setup.py
tests/api/test_notifications_rest.py
tests/data/data.json
tests/fixtures/circulation.py
tests/fixtures/metadata.py
tests/ui/items/test_items_jsonresolver.py
tests/ui/loans/test_loans_jsonresolver.py
tests/ui/notifications/test_notifications_api.py
tests/ui/patrons/test_patrons_jsonresolver.py
tests/unit/conftest.py
tests/unit/test_notifications_jsonschema.py

* Adds notification schema, mappings and required objects
* Integrates `invenio-records` 1.2.0 to have a separate table by resource
* `./scripts/bootstrap`
* `./run-tests.sh`
* `./scripts/setup`

notifications: create data model and api

---

rero_ils/modules/ext.py
rero_ils/modules/items/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/listener.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/mappings/v6/notifications/notification-v0.0.1.json
tests/api/test_notifications_rest.py
tests/data/data.json

* Adds automatically a recall notification when a checked-out item is requested.
* `./scripts/boostrap`
* `./scripts/setup`
* checkout an item to patron A, request the same item by patron B
* go to `http://localhost:5000/api/notifications/` and make sure a new notification is created for Patron A

notifications: create recall notification

---

rero_ils/modules/loans/api.py
rero_ils/modules/loans/listener.py
tests/api/test_notifications_rest.py
tests/ui/notifications/test_notifications_api.py

* Adds automatically an availability notification when a checked-out item is requested.
* `./scripts/boostrap`
* `./scripts/setup`
* request an item to patron A,
* login as librarian and validate the request
* go to `http://localhost:5000/api/notifications/` and make sure a new notification is created for Patron A

notifications: create availability notification

---

rero_ils/config.py
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/tasks.py
tests/api/test_loans_rest.py
tests/api/test_tasks.py

* Adds celery task cronned every morning at 4h00 to create and send overdue and due_soon notifications.

notifications: create periodic task to create and send notifications

---

rero_ils/config.py
rero_ils/modules/documents/serializers.py
rero_ils/modules/items/jsonschemas/form_items/item-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/form_patrons/patron-v0.0.1.json
rero_ils/modules/serializers.py
rero_ils/modules/utils.py
rero_ils/permissions.py
tests/api/test_circ_policies_rest.py
tests/api/test_documents_rest.py
tests/api/test_item_types_rest.py
tests/api/test_items_rest_views.py
tests/api/test_loans_rest.py
tests/api/test_serializers.py
tests/conftest.py
tests/ui/test_permissions.py
tests/utils.py
ui/src/app/records/editor/editor.component.ts
ui/src/app/records/editor/remote-select/remote-select.component.ts
ui/src/app/records/editor/roles-checkboxes/roles-checkboxes.component.html
ui/src/app/records/editor/roles-checkboxes/roles-checkboxes.component.spec.ts
ui/src/app/records/editor/roles-checkboxes/roles-checkboxes.component.ts
ui/src/app/records/records.module.ts
ui/src/app/records/records.service.ts
ui/src/app/records/search/brief-view/patrons-brief-view.component.ts
ui/src/app/records/search/result/result.component.html
ui/src/app/records/search/result/result.component.ts
ui/src/app/records/search/search.component.html
ui/src/app/records/search/search.component.ts

* Limit the libraries to the affiliated library of a librarian logged
user. All libraries are available for a system librarian.
* A system librarian can be created only by a other system librarian.
* remoteRecordFiltersByOwningLibrary form option is not a boolean
anymore, but return the filter field name.

UI: adapt the patron editor for the logged user

---

rero_ils/es_templates/v6/record.json
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/documents/mappings/v6/documents/ebook-v0.0.1.json
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/documents/conftest.py
tests/ui/documents/test_documents_api.py
tests/ui/documents/test_documents_mapping.py

* Adds specific languages analyzers to the template.
* Adds analyzer on documents: title, titlesProper, is_part_of, authors.name, publishers.name, series.name, notes.name, subjects
* Adds analyzer on ebooks: title, titlesProper, is_part_of, authors.name, publishers.name, series.name, abstracts
* Improves facet authors (languages)
How to test:
* `script/bootstrap`
* `script/setup`
* http://localhost:5000
* Find some terms and check if the result is correct

indexing: update document and ebooks mapping

---

rero_ils/config.py
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/documents/mappings/v6/documents/ebook-v0.0.1.json
rero_ils/query.py
tests/api/test_documents_rest.py
tests/data/data.json
tests/fixtures/metadata.py

* Adds fields boosting configuration.
* Improves query parser to use the boosting configuration.
How to test:
* Upgrade Elasticsearch to version 6.6.0 (show in docker-services.yml)
* `script/setup`
* http://localhost:5000
* Find some terms and check if the result is correct (show boosting in config.py)

search: boosting fields on resources

---

data/300.json
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
tests/unit/test_documents_dojson.py

* FIX Fixes #367.
* FIX Updates documents fixtures files.
- `./scripts/setup`.
- display detailed view of documents without publishers data (such as *La salud de la mujer es algo mas que una cuestion medica*).

fixture: fix transformation with no publishers

---

data/300.json
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
tests/unit/test_documents_dojson.py

FIX Ignore empty publisher in dojson conversion.
Signed-off-by: Sébastien Délèze <sebastien.deleze@rero.ch>

document: Publisher format

---

data/300.json
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
tests/unit/test_documents_dojson.py

* FIX Fixes #367.
* FIX Makes sure dojson conversion does not return an empty array for
publishers.
* FIX Asserts in the tests that there's not empty array for publishers.
- `./script/setup` should succeed.

fixtures: fix dojson publishers conversion (3rd time)

---

rero_ils/modules/documents/views.py
rero_ils/modules/libraries/api.py
rero_ils/modules/loans/utils.py
tests/api/test_libraries_rest.py
tests/ui/libraries/test_libraries_api.py
tests/ui/loans/test_loans_api.py

* Fixes issue when a library exception opening day is considered as closed.
* Fixes closes #263.
* Improves the calculation of the due date of a circulation transaction. Now it is based on the transaction library instead of item owning library.

circulation: improve circulation dates

---

INSTALL.rst

The tag name has been changed to `rero/rero-ils-base` in Dockerfile.
But it remains the old tag name here.

documentation: update INSTALL.rst

---

data/users.json
rero_ils/config.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/templates/email/availability/eng.txt
rero_ils/modules/notifications/templates/email/availability/fre.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/availability/ita.txt
rero_ils/modules/notifications/templates/email/availability_eng.txt
rero_ils/modules/notifications/templates/email/due_soon/eng.txt
rero_ils/modules/notifications/templates/email/due_soon/fre.txt
rero_ils/modules/notifications/templates/email/due_soon/ger.txt
rero_ils/modules/notifications/templates/email/due_soon/ita.txt
rero_ils/modules/notifications/templates/email/due_soon_eng.txt
rero_ils/modules/notifications/templates/email/overdue/eng.txt
rero_ils/modules/notifications/templates/email/overdue/fre.txt
rero_ils/modules/notifications/templates/email/overdue/ger.txt
rero_ils/modules/notifications/templates/email/overdue/ita.txt
rero_ils/modules/notifications/templates/email/overdue_eng.txt
rero_ils/modules/notifications/templates/email/recall/eng.txt
rero_ils/modules/notifications/templates/email/recall/fre.txt
rero_ils/modules/notifications/templates/email/recall/ger.txt
rero_ils/modules/notifications/templates/email/recall/ita.txt
rero_ils/modules/notifications/templates/email/recall_eng.txt
rero_ils/modules/patrons/jsonschemas/form_patrons/patron-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
tests/data/data.json

* Adds notification templates by type, language and communication channel.

notification: create notification templates

---

.travis.yml
pytest.ini
run-tests.sh
tests/api/test_documents_rest.py
tests/api/test_external_services.py

* Moves all external services tests to a separate test file.
* Adds script for executing only external services tests.
* Excludes external services tests from main tests script.
- ./run_tests.sh
- ./run_tests.sh external

tests: optional execution of external services tests.

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
tests/unit/test_documents_dojson.py

data model: transform Marc21 fields containing language codes
* Transforms Marc21 fields containing language codes 008, 041
and maps them into data model 'language' property

data model:  transform languages

---

rero_ils/templates/rero_ils/_editor_button_actions.html

* Fixes bad alignment in delete item modal dialog header in the detailed
view document, closes #407.

ui: fix bad alignment in delete item modal header

---

Pipfile
Pipfile.lock
rero_ils/modules/items/api.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/cli.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/mappings/v6/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/utils.py
rero_ils/modules/notifications/api.py
tests/api/test_items_rest.py
tests/api/test_items_rest_views.py
tests/api/test_loans_rest.py
tests/api/test_notifications_rest.py
tests/api/test_patrons_views.py
tests/api/test_tasks.py
tests/fixtures/circulation.py
tests/ui/loans/test_loans_api.py
tests/ui/notifications/test_notifications_api.py
ui/src/app/circulation/items.service.ts
ui/src/app/circulation/items.ts

* Changes loan_pid to pid.
* Improves checkout duration type from int to timedelta.
bootstrap, setup
test circulation transactions

circulation: upgrade to invenio-circulation v1.0.0a16

---

rero_ils/config.py
rero_ils/modules/admin.py
rero_ils/modules/ext.py
rero_ils/modules/holdings/__init__.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/holdings/jsonresolver.py
rero_ils/modules/holdings/jsonschemas/__init__.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/listener.py
rero_ils/modules/holdings/mappings/__init__.py
rero_ils/modules/holdings/mappings/v6/__init__.py
rero_ils/modules/holdings/mappings/v6/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/models.py
rero_ils/modules/holdings/templates/rero_ils/detailed_view_holdings.html
rero_ils/modules/holdings/views.py
rero_ils/modules/items/api.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
setup.py
tests/api/test_holdings_rest.py
tests/api/test_items_rest.py
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/holdings/test_holdings_api.py
tests/ui/holdings/test_holdings_item.py
tests/ui/holdings/test_holdings_jsonresolver.py
tests/ui/items/test_items_api.py
tests/unit/conftest.py
tests/unit/test_holdings_jsonschema.py
tests/utils.py

* Adds holdings level between documents and items.
* Adds automatic holding creation for new items based on item type and item location.
* Adds automatic attaching of new items to a holding record if a valid holding record exists.
* Adds automatic holding deletion once last item is deleted.
* Adds automatic re-linking if necessary to a new holding when item is updated.
* bootstrap, setup
* create an item and make sure `holding` field is added to the item record
* display the created holding record at 'localhost:5000/api/holdings/XX'
* edit the item and change the item type or the location of the item
** make sure the item is re-attached to another holding.
* delete the item and make sure the holding is also deleted by checking '/api/holdings/XX' …

holdings: introduce holding level

---

rero_ils/modules/loans/utils.py
tests/api/test_items_rest.py
tests/api/test_loans_rest.py

* Fixes issue #417
* Improves hours of due date of checkout and renewals to the end of the day.

circulation: due date hours set to end of day

---

.travis.yml
Pipfile
Pipfile.lock
scripts/bootstrap

* Fixes conflicts when dependencies are installed from the Pipefile.
pipenv seems sometimes buggy. All the dependencies has been cleaned.
pipen sync is now used to install the application by default as done in
invenio and the sequential option is used to avoid erratic beaviour.

tests: fix dependencies on travis

---

scripts/bootstrap

I start using **./scripts/bootstrap** file on my computer. With npm 5.6.0.
The script failed and ask it doesn't know `npm ci` command.
As I expected the script to use the virtualenv npm version (6.11.3), I fixed **./scripts/bootstrap** to use npm in the pipenv virtual environment.

installation: fix bootstrap script to use npm 6 instead of local one

---

tests/fixtures/circulation.py
tests/fixtures/metadata.py

* delete duplicates from patron6, 7 and 8
* fix a typo in Sion Library description
* rename item_lib_sion_org2 to item2_lib_sion
@BadrAly: I checked with existing fixtures. No "org" was used. Perhaps it would be better to rename it `item2_lib_sion` than `item2_lib_sion_org`?
Moreover, no `item_lib_sion_org` exists. That's why I prefer to rename it `item2_lib_sion` :wink:

#1011 fix unittest fixtures

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/views.py
rero_ils/modules/holdings/api.py
tests/api/test_availability.py

* add holding availability.
Co-Authored-by: Laurent Dubois <laurent.dubois@uclouvain.be>
how to test:
* run script/bootstrap
* run script/setup

documents: implement record availability

---

rero_ils/modules/documents/listener.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/holdings/templates/rero_ils/detailed_view_holdings.html
rero_ils/modules/holdings/views.py
rero_ils/modules/items/api_views.py

(This is a temporary display of availabilities until US963 is implemented)
* Displays document and item availabilities in document detailed view.
* Displays holding availability in holding detailed view.
* Closes #445
To test:
* Display a document detailed view to see document and items availabilities 
http://localhost:5000/aoste/documents/xxx
* Display a holding detailed view to see document and items availabilities 
http://localhost:5000/aoste/holdings/xx

interface: display record availability in document detailed view

---

data/libraries.json
rero_ils/modules/utils.py

* Improves date_string_to_utc to skip existing timezone.

libraries: fix start date of reroils fixtures

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
run-tests.sh
tests/api/test_external_services.py
tests/unit/test_documents_dojson_unimarc.py

publication statement bnf

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json

* Fixes setup script failure, as the date have some publisher without a
name.

schema: make the name for publisher optional

---

rero_ils/modules/documents/jsonschemas/form_documents/document-v0.0.1.json

Implements US931: task#1016
Test: verify that **publication date** field doesn't appear anymore in editor (add and edit)
Needs to be logged as 'AM'

ui: adapt editor according to publication statement data model

---

scripts/bootstrap

This line: https://github.com/rero/rero-ils/blob/f601159395c99757ce2d2c147c560fe334b45526/scripts/bootstrap#L78
creates some problem: a useless virtualenv is created.
But using `npm install` without `pipenv` will use an older version of
npm.
To avoid this problem, we should inform pipenv which environment it
should use.

#1036 - bootstrap: delete useless virtualenv

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

* NEW Adds a default pull request template, with a review check list.
* BETTER Moves the bug report into the default issue template.

documentation: add a default issue template

---

ui/src/app/records/editor/add-reference/add-reference.component.ts
ui/src/app/records/editor/editor.component.html
ui/src/app/records/editor/editor.component.ts
ui/src/app/records/editor/remote-input/remote-input.component.ts
ui/src/app/records/editor/submit/submit.component.html
ui/src/app/records/editor/submit/submit.component.scss
ui/src/app/records/editor/submit/submit.component.spec.ts
ui/src/app/records/editor/submit/submit.component.ts
ui/src/app/records/records.module.ts

* Disables submit button for invalid async validator.
* Removes useless debug traces.
* Uses core unique validator for remote input component.
- ./scripts/bootstrap
- create a new item with an existing barcode: the submit button should be disabled

editor: fix submit button with async validator

---

rero_ils/manual_translations.txt
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

- `./script/setup`
- ebook document detail view: show the electronic location link into the holding section.

document: display holding electronic location

---

data/item_types.json
rero_ils/modules/item_types/jsonschemas/form_item_types/item_type-v0.0.1.json
rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
rero_ils/modules/locations/jsonschemas/form_locations/location-v0.0.1.json
tests/data/data.json
tests/ui/item_types/test_item_types_api.py
ui/src/app/core/utils.ts
ui/src/app/records/editor/checkbox-is-online/checkbox-is-online.component.html
ui/src/app/records/editor/checkbox-is-online/checkbox-is-online.component.scss
ui/src/app/records/editor/checkbox-is-online/checkbox-is-online.component.spec.ts
ui/src/app/records/editor/checkbox-is-online/checkbox-is-online.component.ts
ui/src/app/records/editor/editor.component.ts
ui/src/app/records/editor/select-item-type-type/select-item-type-type.component.html
ui/src/app/records/editor/select-item-type-type/select-item-type-type.component.scss
ui/src/app/records/editor/select-item-type-type/select-item-type-type.component.spec.ts
ui/src/app/records/editor/select-item-type-type/select-item-type-type.component.ts
ui/src/app/records/records.module.ts
ui/src/app/records/records.service.ts

* Adds custom widgets
* Adds a new column "type" on item_type
* Adds a new column "is_online" on location
- `./script/bootstrap`
- `./script/setup` (only if you never tested Ebook harvesting)
- Test select menu on `item_type` (new and update)
- Test checkbox on `location` (new and update)

form options (for ebook): item type and location for online status

---

tests/api/test_availability.py
tests/api/test_circ_policies_rest.py
tests/api/test_documents_rest.py
tests/api/test_fees.py
tests/api/test_holdings_rest.py
tests/api/test_item_types_rest.py
tests/api/test_items_rest.py
tests/api/test_items_rest_views.py
tests/api/test_libraries_rest.py
tests/api/test_loans_rest.py
tests/api/test_locations_rest.py
tests/api/test_mef_persons_rest.py
tests/api/test_notifications_rest.py
tests/api/test_organisations_rest_api.py
tests/api/test_patron_types_rest.py
tests/api/test_patrons_rest.py
tests/api/test_patrons_views.py
tests/api/test_permissions_librarian.py
tests/api/test_permissions_patron.py
tests/api/test_permissions_sys_librarian.py
tests/api/test_tasks.py
tests/utils.py

* create a `post_dict_to(client, entrypoint, data, headers)` function to replace all `client.post()` functions in tests
* replace all `client.post()` calls in tests

#1019 - Refactoring units testing api calls

---

rero_ils/modules/ebooks/tasks.py

- To fix es indexing problem
- `./scripts/setup` should succeed
- harvest ebooks `pipenv run invenio oaiharvester harvest -n ebooks -a max=100`
- check http://localhost:5000/global/search/documents?size=10&page=1&q= and make sure 100 ebooks exist
- check http://localhost:5000/aoste/search/documents?size=10&page=1&q= and make sure some ebooks exist

ebooks: enable bulk indexing of created records

---

rero_ils/modules/items/templates/rero_ils/detailed_view_items.html

Item detail view contains status, as last field. But no info appears
about the item availability.
The availability appears in other view as a colored circle. Green circle
while available. Red if not available.
This change adds the colored circle before the item status. It also
changes the field description to *Availability*.

#1027 - item availability instead of status

---

Dockerfile
rero_ils/config.py
rero_ils/templates/rero_ils/frontpage.html

Homepage displays current RERO-ILS version. Version as in "release".
It's not so accurate.
To get more precision we use git hash version. We so:
* fetch GIT_HASH environment variable for Docker containers
* if no GIT_HASH environment variable we read files in .git directory
Info : it's not mandatory to have the complete hash. Just 8 first chars is enough.

#971 - ui: display git commit hash on frontpage

---

data/circulation_policies.json
data/item_types.json
data/libraries.json
data/locations.json
data/organisations.json
data/patron_types.json
data/users.json
rero_ils/modules/libraries/api.py
scripts/setup

For the RERO ILS workshops, we need fixtures for a third organisation.
* NEW Adds a third organisation, with it's library, location, system
librarian, default item type, default patron type and default
circulation policy.
* BETTER Adds PID for each resource and `--append` parameters in the
`scripts/setup`, in order to set the PID.
* Fix minor typos in the library api file.
- Taiga task [#1020](https://tree.taiga.io/project/rero21-reroils/task/1020?kanban-status=1224894)
- `./scripts/setup` should succeed
- log in as reroilstest+guillaume@gmail.com (passwd is `cantonale`)
- check the third organisation has a library, a location, a patron type, an item type and a default circulation policy.

fixtures: add data for a third organisation

---

rero_ils/modules/cli.py
rero_ils/modules/providers.py
tests/ui/organisations/test_organisations_api.py

* Closes #563
- To fix issue when sequence is not updated after fixtures record loading
- scripts/setup
- check that sequences are up to date (pgAdmin4)

fixtures: reset sequence to correct value after loading records

---

rero_ils/modules/documents/jsonschemas/form_documents/document-v0.0.1.json
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot

* Implements task 1078 of US1072
* Corrects organisation translation as following:
Organisation = Organisation
OrganisationAsAuthor = Collectivité
* Closes #540.
See #540

translation: correct organisation translation

---

rero_ils/views.py
tests/ui/test_views.py

* Adds a new HTTP endpoint with a JSON POST or PUT method to change the
session language: this will be usefull to change the language from a
pure js application.
- this will allows future angular application to change the language of the frontend interface.
- ./scripts/bootstrap && ./scripts/setup (not required if this was done on the dev branch)
- restart the server and try `curl -d '{"lang":"fr"}' -H "Content-Type: application/json" -X POST http://localhost:5000/language`, the language should be changed.

ui: add a new URL to change the language

---

data/circulation_policies.json

In order to allow renewal on the same day of a checkout during a RERO
ILS workshop, the renewal duration is two days longer than the checkout
duration.
- To adapt third organisation fixtures to workshops needs
- `./scripts/setup/`
- Verify http://localhost:5000/api/circ_policies/12: checkout duration should be 28, but renewal duration 30

fixtures: update third organisation circulation policy

---

ui/src/app/autocomplete/autocomplete.component.html
ui/src/app/autocomplete/autocomplete.component.ts

* Adds a loading wheel during the suggestion loading.
* Removes useless query entry in the suggestions.
* Enter keys submit the quey.
- To solve a strange search input behavious.
- The type a head search input submit the search with the enter key as Google.
- Run the bootstrap script.
- Clear the browser cache.
- Try the type a head search in the front and public search page.

ui: fix typeahead unexpected behaviour

---

run-tests.sh

"No issues detected!" appears a lot while running tests
Bootstrap an instance, then launch server and then:
```bash
./run-tests.sh
```
You can also add useless imports in Python files and then launch `./run-tests.sh` again to see a message like:
```
Use this command to check imports:                                                                                                                      
autoflake --remove-all-unused-imports -r --exclude ui --ignore-init-module-imports .
```

tests: hide "No issues detected!" from autoflake

---

tests/api/test_pid_rest.py
tests/ui/item_types/test_item_types_api.py
tests/ui/locations/test_locations_api.py
tests/ui/test_api.py

Record that failed validation generates a PID. It should not.
If any validation error occurs during a Record validation,
the PID should be canceled in database (using a rollback).
Some tests have been done to check this.

tests: add PID verifications with commit/rollback

---

rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json

- Fixes issue in document editor: when you removed all authors, you were unable to add a new one.
- Modify the jsonschemas (update "minItems" attribute from 0 to 1).
- Closes: #609
Co-Authored-by: Benoit Erken erken.benoit@gmail.com
Co-Authored-by: Laurent Dubois laurent.dubois@itld-solutions.be
Try to improve the next workshop.
- In document editor: let's remove all authors. The authors block should disappear 
and a tab "Authors" must appears on the top of the form.
- when there is no author in your editor, click on the "Authors" tab in order to add a new block "Authors".

document editor: fix add author after removed all authors from the form

---

rero_ils/modules/items/api.py
tests/api/test_items_in_transit.py

* Cancels active loan all the time when a checked-in item has pending reservations.
* Sets loan transaction_date always to datime.now(utc)

circulation: cancel active loan when checked-in item has reservations

---

rero_ils/config.py
rero_ils/query.py

* Uses the aggregation size parameters for the REST API.
* Sets the max aggregation size to 30.
* This size can be changed by the setting env variables only for
documents.
- This has been requested by the PO to perform the workshop.
- Go to all public views and professional document, patron and persons view and expand the aggregators (facets). This will display a maximum of 30 terms. This is relevant only for some such as: subjects, authors, etc.

REST API: set the aggregations size

---

rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
tests/api/test_external_services.py
tests/unit/test_documents_dojson_unimarc.py

* Adds external tests and dojson transformation tests to deal with a poor provisionActivity field.
* Fixes import EAN with some specific provisionActivity (210__) unimarc equivalent field.
- In order to solve EAN import from BNF for ex. 9782072862014
- Try to import 9782072862014 in the document editor and submit.

dojson: fix provisionActivity unimarc transformation

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/utils.py
rero_ils/modules/documents/views.py
tests/api/test_documents_rest.py
tests/api/test_pid_rest.py

- task rero-ils #1147
- Adds "_text" for provisionActivity and series to documents.
- setup

data: Adds dump for documents

---

rero_ils/modules/items/api.py
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
tests/ui/holdings/test_holdings_item.py
tests/ui/patrons/test_patrons_ui.py

* Displays renew button when renewal of checked-out item is possible.
* Hides renew button when circulation policies do not permit the renewal action.
* Increases units testing coverage.
* Corrects indentation of the patron_profile Jinja template.
- Renewal by the patron itself
https://tree.taiga.io/project/rero21-reroils/us/350?milestone=247550
- Login as a patron and visit the patron profile page
- For the checked-out tab, if checked-out items can be renewed, the `renew` button will be displayed
- Click the renew button to change the due date of the current check-out transaction

renewals: add renew buttons for patrons checked-out items

---

rero_ils/modules/items/api.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/listener.py
tests/api/test_items_rest.py
tests/api/test_items_rest_views.py

* Adds organisation $ref field to item json schema.
* Populates the organisation field from the location organisation field.
* Adds item availability to item index.
Implements task https://tree.taiga.io/project/rero21-reroils/task/1164?kanban-status=1224894
- `scripts/setup`:
- display an item @ `~/api/items/<pid>` and make sure the two new fields (availability and organisation) are there

items: create items dump functionality

---

rero_ils/modules/utils.py
scripts/setup

* Adds option for lazy creation of records to the setup.
- The memory consumption is to high for big json files
- run `setup` with option `--lazy`

setup: lazy creation of records

---

data/circulation_policies.json
data/patron_types.json
rero_ils/modules/circ_policies/api.py
rero_ils/modules/cli.py
scripts/setup
tests/ui/circ_policies/test_circ_policies_api.py

* BETTER Corrects item types of circulation policy with pid = 10 and 11.
* NEW Adds new patron type.
* NEW Adds test to check data consistency when ci-po are created.
* Closes #625.
* Closes #626.
* Closes #213 
Some circulation policies have item types and patron types not related to their organisation.
Run `./scripts/setup` -> should proceed as usual with no error 
Then change a patron type or an item type of a circulation policy for one that doesn't belong to the correct organisation in : `data/circulation_policies.json`
Run `./scripts/setup` : the script will raise an error and stop.
Run `./scripts/setup -p` : the script will raise an error and continue.
On rero-ils: open ci-po editor and confirm that patron type and item type …

fix: correct circulation policy

---

Dockerfile.base

* Fixes version of pipenv in Dockerfile.base to version 2018.10.9.
- Can not deploy the image.

deployment: fix pipenv version

---

rero_ils/modules/patrons/jsonschemas/form_patrons/patron-v0.0.1.json

Rewrite 'titleMap' definitions from "communication_channel" and "communication_language". Now, the label are translated to current interface language.

translation: fix patron form editor translation problem

---

run-tests.sh
scripts/bootstrap
scripts/setup

Displays more verbose and more colored info message for scripts.
`./scripts/bootstrap` displays visible messages for each step.
`./scripts/setup` displays messages too. But not as visible as `./scripts/bootstrap`. And not with same color values.
This PR fixes this. It also uses the same way to display messages.
```
docker-compose down
pipenv --rm  # if any pipenv exists
./scripts/bootstrap
docker-compose up -d && ./docker/wait-for-services.sh
./scripts/setup -s -d  # should give an error
```
`./scripts/bootstrap` should give some lines like: `[INFO] Install npm assests`
`./scripts/setup -s -d` gives: `[ERROR] Choose deployment option only`
`./scripts/setup` gives some lines like `[INFO] Organisations:` or some errors if …

scripts: add info message coloration

---

rero_ils/modules/circ_policies/api.py
tests/api/test_circ_policies_rest.py
tests/ui/circ_policies/test_circ_policies_api.py

* Fixes an issue when cipo settings blocked its deletion.
* Closes rero/rero-ils-ui#76
https://tree.taiga.io/project/rero21-reroils/task/1215?kanban-status=1224894
- create a new circulation policy with settings.
- you should be able to delete it.

circulation policy: ignore settings when deleting a policy

---

data/pid_dependencies.json
rero_ils/modules/cli.py

* Adds a cli command for pid fixture dependency checking.
* Adds config file for pid dependency testing.

cli: fixture pid dependency test with config file

---

data/documents_big.json
data/documents_small.json
rero_ils/manual_translations.txt
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
rero_ils/modules/documents/mappings/v6/documents/document.json
rero_ils/modules/documents/utils.py
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
tests/api/test_external_services.py
tests/data/data.json
tests/data/documents.json
tests/unit/test_documents_dojson.py
tests/unit/test_documents_dojson_ebooks.py
tests/unit/test_documents_dojson_unimarc.py
tests/unit/test_documents_jsonschema.py

* Rewrits rero-ils, ebooks and unimarc dojson.
* Updates fixtures.
* Updates tests.
* Updates json schema.
* Updates json mapping.
- https://tree.taiga.io/project/rero21-reroils/us/1090?milestone=250540
- start `setup` and find records with `revisionActivity`

data: rewrite provisionActivity field

---

rero_ils/config.py
rero_ils/modules/documents/api.py
rero_ils/modules/ext.py
rero_ils/modules/items/cli.py
rero_ils/modules/loans/cli.py
rero_ils/modules/persons/api.py
rero_ils/modules/persons/listener.py
rero_ils/modules/persons/mappings/v6/persons/person-v0.0.1.json
scripts/setup
tests/api/test_persons_rest.py
tests/ui/persons/test_persons_api.py

- https://tree.taiga.io/project/rero21-reroils/task/1188?kanban-status=1224894

filter persons view

---

scripts/setup

Document indexation failed in rero-ils
Launch **./script/setup**.

scripts: fix objects indexation

---

.travis.yml
rero_ils/filter.py
rero_ils/modules/documents/views.py
rero_ils/modules/items/views.py
rero_ils/modules/libraries/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/utils.py
rero_ils/translations/messages.pot
tests/api/test_items_rest.py
tests/api/test_loans_rest.py
tests/fixtures/metadata.py
tests/ui/libraries/test_libraries_api.py
tests/ui/loans/test_loans_api.py
tests/unit/test_filter.py

* tests due date timezone
* adds get_timezone() on Library that returns BABEL_DEFAULT_TIMEZONE as default
* changes due date process to take into account Library timezone
* adds library_pid property on Loan objects
Cf. https://tree.taiga.io/project/rero21-reroils/task/1136 and https://github.com/rero/rero-ils/issues/599
It's explained in https://github.com/rero/rero-ils/issues/599 . Pay attention to circulation policy and dates.

loans: improve due date timezone consideration

---

rero_ils/bundles.py
scripts/bootstrap

* Updates bootstrap script to install rero-ils-ui from .tgz if needed.
To simplify rero-ils-ui integration from PR.
To allow its deployment.
1. In RERO-ILS-UI
* `npm run pack`
* Copy path/to/rero-rero-ils-ui-0.0.x.tgz
2. In RERO-ILS
* Go to static folder of invenio instance
* `npm install @rero/rero-ils-ui@latest`
* OPTIONAL: `cat package.json`
* OPTIONAL: You should see: `"@rero/rero-ils-ui": "0.0.8",` (or other latest version)
* Go back to rero-ils project folder
* `./scripts/bootstrap -t path/to/rero-rero-ils-ui-0.0.x.tgz`
* Go to static folder of invenio instance (again)
* `cat package.json`
* You should see: `"@rero/rero-ils-ui": "file:../../../rero-ils-ui/rero-rero-ils-ui-0.0.x.tgz",`
3. Check also `./scripts/bootstrap …

script: add rero-ils-ui install from tgz

---

data/loans.json
data/users.json
rero_ils/modules/fees/api.py
rero_ils/modules/fees/jsonschemas/fees/fee-v0.0.1.json
rero_ils/modules/fees/listener.py
rero_ils/modules/fees/mappings/v6/fees/fee-v0.0.1.json
rero_ils/modules/loans/api.py
rero_ils/modules/loans/cli.py
rero_ils/modules/notifications/tasks.py
scripts/setup
tests/api/test_fees.py
tests/api/test_loans_rest.py
tests/data/data.json

* Adds loan.pid and organisation.currency to the resource fee es index.
* Fixes units testing problem with overdue fees creation.
* Increases fees unit testing fixtures and third organisation fixtures.
* Removes currency field from resource fee.
* Remove the option --fee from the loan creation cli.
https://tree.taiga.io/project/rero21-reroils/task/1231?kanban-status=1224894
- `./script/setup`
- The `fee` es index has a new fields called `loan.pid` and `currency`

fees: create direct link to fee record from the loan pid

---

rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json

- Add sync validator to check start_date and end_date of budget.
- use le PR: https://github.com/rero/ng-core/pull/113 on NG-Core

budget: add new validators to check dates

---

rero_ils/config.py
rero_ils/modules/documents/views.py
rero_ils/templates/rero_ils/head.html
rero_ils/templates/rero_ils/header.html
rero_ils/templates/rero_ils/page.html
tests/ui/test_views.py

* Adds RERO_ILS_THEME_ORGANISATION_CSS_ENDPOINT configuration variable to gives a
way for each organisation to have a specific stylesheet
- It implements [US1200](https://tree.taiga.io/project/rero21-reroils/us/1200?milestone=252915)
1. Launch server
2. Go to each given URL:
* https://localhost:5000/highlands/
* https://localhost:5000/aoste/
* https://localhost:5000/fictive/
* https://localhost:5000/global/
3. Each URL should have a different logo and color in the header

ui: display a different logo/color for each orga.

---

rero_ils/modules/items/api.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/cli.py
rero_ils/modules/notifications/tasks.py
tests/api/test_items_rest_views.py
tests/data/data.json
tests/fixtures/metadata.py

* Adds sort order parameter to the item.requested_loans.library_pid api.
* Improves notification fixtures to have due_soon and recall records.
* Adds sort order parameter to the item.loans.patron_barcode api.
* Fixes item fixtures problem.
https://tree.taiga.io/project/rero21-reroils/task/1263?kanban-status=1224894
`./script/setup`
- sort loans by transaction_date asc:
https://localhost:5000/api/item/requested_loans/1?sort=transaction_date
- sort loans by transaction_date desc:
https://localhost:5000/api/item/requested_loans/1?sort=-transaction_date
- sort checked out items by transaction_date desc:
https://localhost:5000/api/item/loans/<patron_barcode>?sort=-transaction_date
- due_soon and recall notifications …

loans: add parameter to sort pending loans

---

rero_ils/config.py
rero_ils/modules/patron_transactions/__init__.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/jsonresolver.py
rero_ils/modules/patron_transactions/jsonschemas/__init__.py
rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_transactions/mappings/__init__.py
rero_ils/modules/patron_transactions/mappings/v6/__init__.py
rero_ils/modules/patron_transactions/mappings/v6/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_transactions/models.py
setup.py

https://tree.taiga.io/project/rero21-reroils/task/1250?kanban-status=1224894
Other pull requests will follow, only code review is needed.

patron_transaction: create new resource json and mapping.

---

rero_ils/templates/rero_ils/header.html

* fixes the issues 108 of rero-ils-ui, point 11
https://github.com/rero/rero-ils-ui/issues/108, point 11: `Search input does not take all the width in the header in the public view.`
* Run server locally
* Do a search in search bar
* Check that the current view have a search bar that takes all the remaining place after the logo

ui: Search input takes now all the header area

---

rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/mappings/v6/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/documents/api.py
tests/api/test_acq_order_lines_rest.py
tests/data/acquisition.json
tests/ui/acq_order_lines/test_acq_order_lines_jsonresolver.py
tests/ui/acq_order_lines/test_acq_order_lines_mapping.py

* Adds a link between order line and document.
* Removes description field in order line resource
https://tree.taiga.io/project/rero21-reroils/task/1276?kanban-status=1224894
- Should be tested with https://github.com/rero/rero-ils-ui/pull/124

acquisition: link order line to a document

---

rero_ils/config.py
rero_ils/modules/ext.py
rero_ils/modules/notifications/api.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_transaction_events/listener.py
rero_ils/modules/patron_transaction_events/mappings/v6/patron_transaction_events/patron_transaction_event-v0.0.1.json
rero_ils/modules/patron_transaction_events/permissions.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_transactions/mappings/v6/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_transactions/permissions.py
rero_ils/query.py
setup.py
tests/api/test_fees.py
tests/api/test_patron_transaction_events_rest.py
tests/api/test_patron_transactions_rest.py
tests/data/data.json
tests/fixtures/circulation.py
tests/fixtures/metadata.py
tests/ui/patron_transaction_events/test_patron_transaction_events_api.py
tests/ui/patron_transaction_events/test_patron_transaction_events_jsonresolver.py
tests/ui/patron_transactions/test_patron_transactions_api.py
tests/ui/patron_transactions/test_patron_transactions_jsonresolver.py
tests/unit/conftest.py
tests/unit/test_patron_transaction_events_jsonschema.py
tests/unit/test_patron_transactions_jsonschema.py

* Improves relations between Loan, Notifications and Patron transactions.
* Adds config for patron transactions and events.
* Adds fixtures and tests for patron transactions and events.
https://tree.taiga.io/project/rero21-reroils/task/1273?kanban-status=1224894
-  Additional PRs will be created to remove the Fee resource and complete the other tasks
- This PR will be merged to `US659`
- Additional test coverage will be created
`bootstrap`
`setup`
Transactions are available at:
`~/api/patron_transactions/`
`~/api/patron_transaction_events/`

patron_transactions: generate patron transactions and events for overdue

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/cli.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/listener.py
rero_ils/modules/documents/serializers.py
rero_ils/modules/persons/api.py
rero_ils/modules/persons/listener.py
scripts/setup

* Adds atomic persons creation.
* Improves the code for document serializer.
* Cleans the setup.
* Adds person bulk indexing to setup.
* Corrects bulk indexing.
- https://tree.taiga.io/project/rero21-reroils/task/1271
- run setup and see if all persons were created

person: atomic persons creation and indexation

---

rero_ils/modules/fees/listener.py
rero_ils/modules/patrons/listener.py
rero_ils/modules/persons/listener.py

* Fixes patron listener for bulk indexing.
- it was not possible to bulk index patrons
- restart server with worker
- `pipenv run utils reindex -t ptrn --yes-i-know`
- `
pipenv run invenio utils runindex --raise-on-error -c 4 -d` 
- verify worker logs

ES: fix listeners

---

Pipfile
Pipfile.lock

* Forces the werkzeug version < 1.0.
- To solve travis tests failure.
- Check if the travis tests are successful.

tests: fix travis failed with werkzeug==1.0.0

---

rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json

* Updates JSON schemas to allow abstract fields to be edited as a textarea.
- Closes Bug#36 from https://github.com/rero/rero-ils-ui/issues/108
- ./scripts/boostrap
- Go to professional UI, into document editor
- Display "abstract" field group. Each abstract should be now a textarea with default 5 rows height

documents: update schemas about abstract field

---

rero_ils/config.py
rero_ils/modules/permissions.py
rero_ils/modules/serializers.py
rero_ils/modules/utils.py
rero_ils/modules/views.py
rero_ils/query.py
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
setup.py
tests/api/test_record_permissions.py

* Removes update and delete permissions from document serilaizer.
* Removes unused codes.
* Increases test code coverage.
https://tree.taiga.io/project/rero21-reroils/task/1294?kanban-status=1224894
`bootstrap`
record permssions API: `~/api/permissions/<resource_name>/<record_pid>/`

permissions: update and delete permissions api for records

---

rero_ils/config.py

security: authorize unsafe-eval param on script-src

---

rero_ils/modules/holdings/views.py
tests/api/test_items_rest_views.py
tests/ui/holdings/test_holdings_item.py

* Changes the display in the document detailed view for holdings: the
library name replace the library code.
* Closes #776.
- Should fixes #776
- Go to a document detailed view with holding check the holding location in the card header.

ui: display library name instead of code

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
tests/api/test_items_rest_views.py

* Adds the pickup location names into options of the item request button
* Closes #777
- Log as user with 'patron' role
- Search about a item that could be requested
- Expand options of the request button

documents: Add pickup location names for the item request button

---

rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
rero_ils/translations/messages.pot
tests/ui/patrons/test_patrons_ui.py

* Adds an action button to allow cancellation for patrons.
Task 1315 of US1068
https://tree.taiga.io/project/rero21-reroils/task/1315?kanban-status=1224894
1. Login as a patron.
2. Go to profile, pending tab.
3. Cancel a request.
Requests that are ready for pickup can't be cancelled.

public interface: request deletion by patron

---

rero_ils/modules/items/api.py
tests/api/test_items_in_transit.py
tests/api/test_items_rest_views.py

* Closes #770
* Improves finding a location of an item when in circulation.
* Fixes units testing.
Login as reroilstest+elena@gmail.com [AVISE library]:
- checkout `item1` of the `AVISE` library to Broglio,Giulia barcode=`2050124312`
- checkout `item2` of the `AVISE` library to Broglio,Giulia barcode=`2050124312`
Login as reroilstest+simonetta@gmail.com:
- request the item `item1` to pickup location `AOSTE-LYCEE`
- request the item `item2` to pickup location `AOSTE-AVISE`
Login as reroilstest@gmail.com: [LYCEE library]
- checkin `item1`, item status will be `AT_DESK`
- checkin `item2`, item status will be `IN_TRANSIT to AOSTE-AVISE`

circulation: fix some loan scenarios

---

rero_ils/modules/loans/transitions.py
tests/api/test_circ_bug.py

isort: fix isort problems for two files

---

rero_ils/modules/cli.py

* Fixes 'person_source' typo in cli.

cli: fix typo

---

CHANGES.rst
RELEASE-NOTES.rst

- To document RERO ILS `v0.6.0` and `v0.6.1`.
- See the files diff.
- Check also the rendering of [CHANGES.rst](https://github.com/iGormilhit/rero-ils/blob/060-release-changes/CHANGES.rst) and [RELEASE-NOTES.rst](https://github.com/iGormilhit/rero-ils/blob/060-release-changes/RELEASE-NOTES.rst)

release: update changes & release notes for v0.6.0 and v0.6.1

---

rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py

* Keeps 'pendings' tab active after cancel.
Co-Authored-by: Alicia Zangger  <alicia.zangger@rero.ch>
To implement task 1330 of US 1262
https://tree.taiga.io/project/rero21-reroils/task/1330?kanban-status=1224895
1. Login as a patron.
2. Go to your profile, 'pending' tab
3. Cancel a request.
4. You should stay in this tab after action.

public interface: improve patron request deletion

---

rero_ils/modules/patron_transaction_events/api.py

When a 'resolved' patron transaction events was received, the amount of this
event was ignored for the total_amount calculation of the parent transaction

patron_transaction: fix total amount calculation problem

---

rero_ils/modules/items/api_views.py
rero_ils/modules/items/utils.py
tests/api/test_availability.py
tests/api/test_items_rest.py
tests/fixtures/circulation.py

* Removes duplicate fixtures function.
https://tree.taiga.io/project/rero21-reroils/us/657?milestone=254793
- To check if an item can be requested for a given patron barcode and a transaction library PID
`~/item/<item_pid>/can_request/<library_pid>/<patron_barcode>`
API response in this format:
`can_request`: True or False
`reason`:  the reason why the item can not be requested

items: can request api for an item

---

tests/api/test_loans_rest.py
tests/utils.py

* Fixes test that have problem twice a year with daylight saving time
timezone
To fix problems about timezones in tests.
```bash
pipenv run pytest -vvs --no-cov --disable-warnings tests/api/test_loans_rest.py::test_due_soon_loans
```

tests: fix problems with daylight saving time

---

.coveragerc
data/patterns.json
rero_ils/modules/cli.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/mappings/v6/holdings/holding-v0.0.1.json
scripts/setup
tests/conftest.py
tests/data/data.json
tests/data/holdings.json
tests/fixtures/metadata.py
tests/ui/holdings/test_patterns_api.py
tests/unit/test_holdings_jsonschema.py

* Adds holdings_type to holdings record.
* Increments issues according to holdings patterns.
* Adds preview for one or n issues.
* Creates fixtures for holdings with patterns ui and units testing.
* Adds the 10 patterns commonly used in the Virtua Valais database.
* Create seperate json file for the fixtures of holdings and patterns.
`bootstrap` + `setup`
-  List all holdings with patterns:
~/api/holdings/?q=holdings_type:serial
take one holdings pid and display the holdings record to see the pattern:
~/api/holdings/<holding_pid>

serials: introduce serials patterns and captions

---

Pipfile
Pipfile.lock
pytest.ini
run-tests.sh

* Fixes invenio-accounts dependency that causes dependency conflict for
invenio-celery and invenio-base.
* Removes useless security exception.
* Adds security exception due to a bug of a third party tools (pipenv).
* Add new `live_server_scope` options in pytest.ini due to the new 1.1.0 version of pytest-flask.

tests: fix dependencies and security check

---

.editorconfig
Dockerfile
INSTALL.rst
Pipfile
Pipfile.lock
scripts/bootstrap
scripts/console
scripts/server
scripts/setup
scripts/update

* Fixes strange behaviours during the resolution dependencies with
pipenv. This will make the new python packages easy.
* Adds the documentation in the python packages file (Pipefile).
* Adds support of a new version of the python import order check tool (isort>=4.3.10).
* Adds new bootstrap and server command for pipenv.
* Replaces scripts commands by pipenv run:
* bootstrap
* console
* server
* setup
* update
* Adds virtualenv detection in scripts/* for python>3.6.4.
After the integration into the dev branch the documentation should be updated:  https://github.com/rero/rero-ils/blob/master/INSTALL.rst 
The idea is to make the CI travis tests more stable. Moreover it add the …

installation: fix python packages dependencies

---

rero_ils/modules/libraries/api.py
tests/api/test_items_rest.py
tests/utils.py

When timezone difference is positive it happens that the we compare an
hour superior or equal to 24. In these cases tests on loan/items fails.
This commit fixes that and it:
* fixes check_timezone_date() using a modulo 24.
* displays more info if an error happens in check_timezone_date test
* changes get_timezone() description to correspond to reality
* fixes a test that compare an UTC date to an non-UTC date
Because tests failed on timezoned date. March, the 20th we will change the timezone from GMT+1 to GMT+2 which displays errors.
`pipenv run pytest -vvs --no-cov --disable-warnings tests/api/test_items_rest.py`

tests: fix Zürich timezone problems

---

rero_ils/modules/items/api.py
tests/api/test_circ_bug.py
tests/api/test_items_in_transit.py
tests/api/test_items_rest.py
tests/api/test_items_rest_views.py

Applies additional circulation actions after/before a successful checkin/checkout transactions of an item. The additional actions are to address the reroils circulation use cases.
* Returns the receive, cancelled and checkout loans after a successful checkout.
* Returns the checked-in, cancelled, validated loans after a successful automatic validation of a checked-in transaction.
* Creates additonal unit testings.
* Closes #826
https://tree.taiga.io/project/rero21-reroils/task/1338?kanban-status=1224894
`run_tests.py`
the new returned loans, will be used by the frontend

circulation: return all applied actions after a checkin or checkout

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
tests/unit/test_documents_dojson.py
tests/unit/test_documents_dojson_ebooks.py

* Corrects url type filter.
* Displays cover as a link for coverImage type.
To complete US 1262 https://tree.taiga.io/project/rero21-reroils/us/1262?milestone=257446
1. Edit a record to add an electronic location with a type `Covert art` (suggested url: https://d2v9ipibika81v.cloudfront.net/uploads/sites/21/Africa-990x684.jpg)
1. Go to the detailed view in public interface
1. Check that the cover image is a working link

document: fix cover image in public detailed view

---

.travis.yml
Pipfile
Pipfile.lock
rero_ils/config.py
rero_ils/es_templates/v6/__init__.py
rero_ils/modules/cli.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/indexer_utils.py
rero_ils/permissions.py
rero_ils/templates/__init__.py
scripts/setup
tests/conftest.py
tests/ui/test_indexer_utils.py

* Updates Invenio framework from 3.1 to 3.2.1
* Adapts tests regarding new invenio-search module
* Lists all templates at same place in config.py file
* Fixes init() in CLI (for indexes)
* Fixes test_license() in CLI for files that only have comments (#) lines
* Migrates from DynamicPermission to Permission from invenio-access
* Fixes record_to_index() for documents
* Improves regular expression for schema detection for documents
* Changes document mappings name to document-v0.0.1
* Fixes persons indexation in doc. mappings by using `get_record_by_mef_pid()`
Because of https://tree.taiga.io/project/rero21-reroils/task/1307?kanban-status=1224895 …

framework: update to Invenio 3.2.1

---

Pipfile
Pipfile.lock

Tests were broken because of a security breach in bleach <=3.1.1.
* Fixes bleach version to upgrade to bleach > 3.1.1
A problem occurs in tests today:
```bash
PROGRAM: run-tests.sh
….
Checking installed package safety…
Notice: Ignoring CVE(s) 37752
38076: bleach <=3.1.1 resolved (3.1.1 installed)!
The ``bleach.clean`` behavior parsing embedded MathML and SVG content with RCDATA tags in Bleach versions <= 3.1.1 did not match browser behavior and could result in a mutation XSS.
Calls to ``bleach.clean`` with ``strip=False`` and ``math`` or ``svg`` tags and one or more of the RCDATA tags ``script``, ``noscript``, ``style``, ``noframes``, ``iframe``, ``noembed``, or ``xmp`` in the allowed tags whitelist were vulnerable to a mutation XSS. …
```

security: fix bleach XSS security breach

---

rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
tests/unit/test_locations_jsonschema.py

Before this change, the location JSON schema accept that the location was a
pickup location (is_pickup=true) but without pickup_name. This fix change this
behavior ; when a location is defined as pickup location, then the 'pickup_name'
is now required.
Note : the schema already contains behavior for the formly editor
* Closes rero/rero-ils#794.

location: adapt JSON schema for pickup_name required if is_pickup

---

rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
setup.py
tests/api/test_patterns.py
tests/unit/test_holdings_jsonschema.py

These APIs allow to return predicted issues for a given holdings_pid or a given pattern.
* Adds condition to require field patterns for holdings of type serial.
* Creates units tests.
https://tree.taiga.io/project/rero21-reroils/task/1369?kanban-status=1224894
- `scripts/bootstrap` 
- `scripts/setup`
- find holdings records with patterns:
` ~/api/holdings/?&q=holdings_type:serial`
- display predicted issues of a holdings record from the list above:
by default, the api lists the first 10 issues:
`~/api/holding/<holdings_pid>/patterns/preview/`
to display the first 25 issues, use the `size` variable:
`~/api/holding/<holdings_pi>/patterns/preview/?size=25`
- api to return the predicted issues for a given pattern (holding record is not yet created), …

serials: create api to preview predicted issues

---

scripts/bootstrap
scripts/console
scripts/server
scripts/setup
scripts/update

While using bootstrap script, it attempts to install TGZ_FILE.
Something like `[INFO]: Install RERO-ILS-UI from tgz: ` appears. But no
file were given.
* Fixes #856 - by changing `[` tests to `[[` (bash)
Because of #856 issue.
Launch `pipenv run bootstrap` and check that no `[INFO]: Install RERO-ILS-UI from tgz: ` appears.
Then do the same with a TGZ file, for example those from https://github.com/rero/rero-ils-ui/releases/tag/v0.0.12, like : 
`pipenv run bootstrap -t v0.0.12.tar.gz`

bootstrap: fix useless tgz file installation

---

tests/api/test_loans_rest.py
tests/utils.py

As we will enter in GMT+2 in few days, a test failed as it compare wrong
date (first in Zurich timezone and second in UTC one).
We should compare dates in UTC only.
* Compares date in UTC for opening hours of a given library
Because of https://tree.taiga.io/project/rero21-reroils/task/1381
`./run-tests.sh`

test: fix library opening timezone due date

---

rero_ils/config.py
rero_ils/modules/acq_invoices/__init__.py
rero_ils/modules/acq_invoices/api.py
rero_ils/modules/acq_invoices/jsonresolver.py
rero_ils/modules/acq_invoices/jsonschemas/__init__.py
rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
rero_ils/modules/acq_invoices/mappings/__init__.py
rero_ils/modules/acq_invoices/mappings/v6/__init__.py
rero_ils/modules/acq_invoices/mappings/v6/acq_invoices/acq_invoice-v0.0.1.json
rero_ils/modules/acq_invoices/models.py
rero_ils/modules/acq_invoices/serializers.py
rero_ils/modules/vendors/api.py
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
rero_ils/modules/vendors/mappings/v6/vendors/vendor-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
setup.py
tests/api/test_acq_invoices_rest.py
tests/api/test_vendors.py
tests/data/acquisition.json
tests/fixtures/acquisition.py
tests/ui/acq_invoices/test_acq_invoices_jsonresolver.py
tests/ui/vendors/test_vendors_jsonresolver.py

* Adds acquisition invoice resource.
* Adds a function to check if invoice exists before deleting a vendor.
* Adds more currencies to vendors.
* Adds fixtures for tests units.
* Updates tests for vendors.
https://tree.taiga.io/project/rero21-reroils/us/1237?milestone=252915
There is no way to test backend at this time

acquisition: create invoice resource

---

rero_ils/modules/ebooks/utils.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api.py
tests/api/test_patterns.py

When a librarian tries to create a new item on a document, the system
will not try to attach the item to a holding of type serial. if no
holding exists, will attempt to create a new monograph holding for
the new item.
https://tree.taiga.io/project/rero21-reroils/task/1383?kanban-status=1224894

serials: new items will not be attached to holdings of type serial

---

rero_ils/modules/monitoring.py
rero_ils/modules/persons/api.py
rero_ils/modules/serializers.py
rero_ils/permissions.py
setup.py
tests/api/test_monitoring_rest.py
tests/ui/test_monitoring.py

* Adds functionality to monitoring values from DB and ES.
- https://tree.taiga.io/project/rero21-reroils/task/1342
after setup:
- website: localhost:5000/nonitoring/info
- cli: pipenv run invenio monitoring info

monitoring: monitoring for DB and ES

---

Pipfile
Pipfile.lock

Regarding https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1747,
we need to update PyYaml to 5.1.3 and superior to avoid vulnerability.
* Updates PyYaml version
Because of this message: https://travis-ci.org/github/rero/rero-ils/jobs/667170514#L944
```
❯ pipenv check -i 37752
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
Notice: Ignoring CVE(s) 37752
38100: pyyaml <5.3.1 resolved (5.3 installed)!
A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to …
```

vulnerability: fix PyYaml CVE vulnerability

---

Pipfile
Pipfile.lock

Tests were broken because of a security breach in bleach <=3.1.3
* Fixes bleach version to upgrade to bleach >=3.1.4
Tests failed with:
```
38107: bleach <=3.1.3 resolved (3.1.3 installed)!
The ``bleach.clean`` behavior parsing style attributes in bleach before 3.1.4
could result in a regular expression denial of service (ReDoS)
....
versions used a similar regular expression and should be considered vulnerable too.
```
`pipenv check -i 37752`

security: fix bleach ReDOS security breach

---

MANIFEST.in
scripts/all_year_days
tests/api/test_loans_rest.py

The project uses circulation policy to process loan due date.
It uses timezone in UTC and then process date.
To check all is OK about dates, we create a script.
* Adds new `all_year_days` script
* tests test_loans_rest.py all day of current year
https://github.com/rero/rero-ils/commit/ca01c491519d225ffb1fd4471f2903e23b1bc782 resolve some timezone problem. But that's not the first time we encount problems with timezone.
As a result we need to check that all is OK for every year days.
This commit add a new `all_year_days` that permits to launch a command for every day of current year.
You need libfaketime (MacOS, ArchLinux) or faketime (Debian, Ubuntu) on your computer.
To check all is OK, you should do:
```bash
docker-compose up -d …
```

project: improve test on dates

---

data/holdings_small.json
data/items_small.json
rero_ils/modules/documents/api.py
rero_ils/modules/documents/mappings/v6/documents/document.json
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/items/cli.py
rero_ils/permissions.py
tests/api/test_holdings_rest.py
tests/api/test_patterns.py
tests/data/holdings.json
tests/fixtures/metadata.py
tests/ui/holdings/test_holdings_api.py

Enriches the elasticsearch document index with the RDA mode of issuance field equal
to rdami:1003 when indexing a document of type journal.
* Adds extended validation for holdings records.
* Disallows the creation of monograph holdings on journal documents.
* Disallows the creation of serial holdings on monograph documents.
* Revokes the permission to manually create/update/delete the monograph holdings records.
* Regenerates the big and small data files to avoid having monograph holdings created on journal documents.
* Updates tests and fixtures accordingly.
https://tree.taiga.io/project/rero21-reroils/task/1388?kanban-status=1224894
`bootstrap` and `setup`
Not yet possible to test this with the user interface. you have to use the `APIs` to …

serials: distinguish the documents of type journal

---

rero_ils/modules/acq_order_lines/api.py

Updates acquisition order lines resource to remove useless methods.
* Removes methods from order lines resource api.

acquisition: cleanup useless functions of order lines resource

---

data/patron_types.json
rero_ils/modules/ext.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/listener.py
rero_ils/modules/utils.py
tests/api/test_patron_transactions_rest.py
tests/api/test_patrons_rest.py
tests/unit/conftest.py
tests/unit/test_utils.py

When a patron is create/updated, if the patron is linked to a patron type requiring a subscription,
we need to create a subscription transaction if the patron doesn't have any current one.
This is the purpose of this PR.
* Adds a listerner method for patron signals : after_record_create, after_record_update
* Adds unit tests
- Edit a patron_type to have one with a yearly subscription
- Create a new patron and assign it with this patron_type
- Check the patron fee tabs, you should see a new subscription fee
- Update this patron to assign it to a patron_type without subscription
- Update again this patron to re-assign it the patron_type with a subscription
- No new fee should be assign to the patron
- Search for a patron previously linked to the patron_type with subscription
- Edit this …

subscription: adds listener methods to create a subscription if needed

---

Pipfile
Pipfile.lock

Last 1.3.16 sqlalchemy release breaks RERO-ILS tests.
Waiting for Invenio to adapt invenio-admin regarding last SQLAlchemy
release, we limit the version to 1.3.15 to avoid problems.
By curiosity…
`pipenv run bootstrap --ci`

project: fix sqlalchemy last releases problems

---

rero_ils/modules/locations/api.py
rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
tests/unit/test_locations_jsonschema.py

Formly doesn't like the "oneOf" statement present into the schema.
The displayed form contains some empty field for any 'oneOf' possibilities.
Removes 'oneOf' statement from schema and adds extended validation rule solves this problem.

location: correct schema to work well with formly

---

Pipfile.lock
rero_ils/bundles.py

* Changes rero-ils-ui dependency to version 0.1.0.
* Removes macosx specific packages from Pipefile.lock.

ui: move to rero-ils-ui v0.1.0

---

Pipfile
Pipfile.lock
run-tests.sh

* Replaces `pipenv check` with `pipenv run safety check` because pipenv
was not working any more.
- `pipenv check` was not working any more. 
- run `./run-tests.sh`

test: safety check

---

rero_ils/modules/documents/static/scss/rero_ils/thumbnail.scss
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/templates/email/availability/eng.txt
rero_ils/modules/notifications/templates/email/availability/fre.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/availability/ita.txt
rero_ils/modules/notifications/templates/email/due_soon/eng.txt
rero_ils/modules/notifications/templates/email/due_soon/fre.txt
rero_ils/modules/notifications/templates/email/due_soon/ger.txt
rero_ils/modules/notifications/templates/email/due_soon/ita.txt
rero_ils/modules/notifications/templates/email/overdue/eng.txt
rero_ils/modules/notifications/templates/email/overdue/fre.txt
rero_ils/modules/notifications/templates/email/overdue/ger.txt
rero_ils/modules/notifications/templates/email/overdue/ita.txt
rero_ils/modules/notifications/templates/email/recall/eng.txt
rero_ils/modules/notifications/templates/email/recall/fre.txt
rero_ils/modules/notifications/templates/email/recall/ger.txt
rero_ils/modules/notifications/templates/email/recall/ita.txt

* Replaces author with responsibility statement for notifications.
* closes #406
- https://tree.taiga.io/project/rero21-reroils/task/1430
- https://github.com/rero/rero-ils/issues/406
- verify notifications are correctly created with responsibility statement

notification: use responsibility statement

---

rero_ils/modules/notifications/api.py

When you setup RERO-ils, some document don't have any
responsibilityStatement. Which make the setup failed on some loan
creation.
This commit fixes the problem.
Because of errors in SETUP (`Exception loan requested_by_others: 'NoneType' object is not iterable`).
`pipenv run setup`
Check that no errors (in red) appears during create_loans setup.

setup: fix ref. prob. on responsibilityStatement

---

rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
rero_ils/modules/utils.py
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
tests/api/test_patrons_rest.py
tests/unit/test_utils.py

!!! use `rero/zan-US1297-subscriptions` for RERO-ILS-UI
- Assign a patron_type requiring a subscription to patron (Monnet, Philippe). A new subscription fee will be created
- In the public interface, login as this patron (reroilstest+philippe@gmail.com) and display the profile of this patron. An alert box should be displayed to alert there is a pending subscription.

subscriptions: display message when patron has pending subscription

---

rero_ils/config.py
rero_ils/modules/budgets/permissions.py
rero_ils/modules/circ_policies/permissions.py
rero_ils/modules/libraries/permissions.py
rero_ils/modules/permissions.py
rero_ils/modules/utils.py
rero_ils/permissions.py
tests/api/test_circ_policies_rest.py
tests/api/test_item_types_rest.py
tests/api/test_organisations_rest_api.py
tests/api/test_patron_types_rest.py
tests/api/test_permissions_librarian.py
tests/api/test_record_permissions.py

Some ressource permissions defined into the main ReroILS configuration file wasn't correct.
Some resources (circulation policy, patron type, item type, budget, ...) should only be created by
'system_librarian` user. This PR fix this problem
The permission API are updated to take care of main configuration for 'can_delete' permission.
The permission API only checked if the record is linked to other resources (children). If not, despite
the main configuration, it return True. Now, if a ressource has no linked resources, then the API
check also if user has the permission to delete the record.
- Login as Astrid (system_librarian)
- check `~/api/permissions/circ_policies/1`
- You should "can_update" but cannot "can_delete" (due to …

permissions: update permission API and configuration

---

Pipfile
Pipfile.lock

After wtforms 2.3.0, Travis encount problems in external tests.
email_validator make an Exception as explained here:
https://gitter.im/inveniosoftware/invenio?at=5ea0006df39e5c2fbb955db8
This commit avoid this problem by fixing wtforms to a version anterior
to 2.3.0
* Adds your new feature.
* Fixes an existing issue, may closes #issue.
* Improves and existing feature.
Because of problems on our US1293-doo-invenio32 branch with tests: https://travis-ci.org/github/blankoworld/rero-ils/jobs/678065871#L683
Something like that happens: 
```
Exception: Install 'email_validator' for email validation support.
```
As explained [at invenio Gitter room](https://gitter.im/inveniosoftware/invenio?at=5ea0006df39e5c2fbb955db8), we should limit …

test: fix external ones

---

rero_ils/modules/notifications/dispatcher.py

* Uses email from loan pickup_location library as sender email.
* Closes #939
- https://tree.taiga.io/project/rero21-reroils/task/1448
- https://github.com/rero/rero-ils/issues/939
- create notifications and verify correct sender email

notification: use pickup location email as sender

---

Pipfile
Pipfile.lock
rero_ils/config.py
rero_ils/modules/documents/views.py
rero_ils/modules/items/api.py
rero_ils/modules/items/api_views.py
rero_ils/modules/items/utils.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/cli.py
rero_ils/modules/loans/listener.py
rero_ils/modules/loans/transitions.py
rero_ils/modules/loans/utils.py
rero_ils/modules/locations/api.py
rero_ils/modules/notifications/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/views.py
tests/api/test_items_rest.py
tests/api/test_loans_rest.py
tests/ui/items/test_items_api.py
tests/ui/loans/test_loans_api.py
tests/utils.py

Adapts reroils after the upgrade to invenio-circulation v1.0.0a21.
The two transitions ItemOnLoanToItemReturned and ItemOnLoanToItemReturned are
temporarily updated and inserted into reroils until a fix for the issue
https://github.com/inveniosoftware/invenio-circulation/issues/127 is available.
This PR expects the fix for the ITEM_AT_DESK problem in the current version
of invenio-circulation.
Some timezone units testing are disabled until a fix is given in a later PR.
This PR requires the `rero/invenio-circulation.item_at_desk` branch
https://tree.taiga.io/project/rero21-reroils/task/1431?kanban-status=1224894
`bootstrap + run_tests.sh`

circulation: adapt reroils

---

rero_ils/modules/items/api_views.py
tests/api/test_items_rest_views.py

* Adds route to update request pickup location.
https://tree.taiga.io/project/rero21-reroils/task/1438?kanban-status=1224895
Task 1438 of US 1355 - cancel and edit a request
Please do code review. It should be tested with https://github.com/rero/rero-ils-ui/pull/229

loan: update request pickup location

---

CHANGES.rst
RELEASE-NOTES.rst
rero_ils/bundles.py
rero_ils/version.py

* Updates the version number (rero-ils/version.py).
* Updates the RELEASE-NOTES.rst and the CHANGES.rst files.
To publish the `v0.8.0` release.
Check changed files.

release: v0.8.0

---

rero_ils/modules/documents/listener.py
rero_ils/modules/items/api.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/templates/rero_ils/detailed_view_items.html
rero_ils/modules/utils.py
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
tests/api/test_items_rest.py

The item call number is now an optional field in both the
item json schema and item editor. This field is not populated
if not given by the librarian.
The item barcode remains a required field in the item json schema,
on the other side, it is an optional field in the item editor.
If a librarian decides not to add an item barcode, the system
will automatically populate the barcode with the following:
f-current timestamp.
* Adapts schema, tests and files correspondingly.
https://tree.taiga.io/project/rero21-reroils/us/1328?milestone=263424
`bootstrap` + `setup`
in the UI, you should be able to add items without barcodes

item: field call number is now optional

---

Pipfile
Pipfile.lock

Npm fails with error: Requirement.parse('werkzeug>=1.0.0'), {'jsonresolver'}
* Forces the jsonresolver version < 0.3.0.

tests: fix travis

---

rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

This commit adds check to limit to only one pickup location for a library.
Same than https://github.com/rero/rero-ils/pull/969 (closed by error)

location: unique pickup location for a library

---

tests/api/test_items_rest.py

The current units testing ensures that the timestamp of the
generated barcode equals the sysdate timestamp. This was incorrect
because the time of the item creation/barcode generation is different
from the sysdate at running the assert command.
Now we test only if the barcode starts with f-.

tests: fix units testing for generated item barcodes

---

rero_ils/modules/api.py
rero_ils/modules/loans/cli.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/tasks.py
scripts/setup
tests/api/test_notifications_rest.py
tests/ui/notifications/test_notifications_api.py

* Enqueues notifications for asynchron processing.
- https://tree.taiga.io/project/rero21-reroils/task/1449
- run setup and see if the notifications sending is asynchrone (see worker log)

enqueues notifications

---

data/loans.json
data/users.json
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/cli.py
rero_ils/modules/loans/utils.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
tests/api/test_loans_rest.py
tests/api/test_patrons_blocked.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/patrons/test_patrons_api.py
tests/ui/patrons/test_patrons_ui.py
tests/unit/test_patrons_jsonschema.py

In some cases a patron could be blocked by a librarian to restrict its
account. For an example if patron lost its card.
* Adds new jsonschema definition to block patron.
* Displays if patron is blocked on its profile.
* Adds tests to check if patron is blocked or not.
* Reduce patron circulation policy to deny all checkout and requests
from a blocked patron account.
[US299](https://tree.taiga.io/project/rero21-reroils/us/299?milestone=260625): block patrons
Needs https://github.com/rero/rero-ils-ui/pull/234

patron: add blocking functionnality

---

data/patterns.json
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/mappings/v6/holdings/holding-v0.0.1.json
rero_ils/modules/notifications/api.py
tests/api/test_patterns.py
tests/data/holdings.json
tests/fixtures/metadata.py
tests/unit/test_holdings_jsonschema.py

The frequency field indicates the publication frequency of the pattern.
Currently it is not related to any enumeration or chronology levels.
Librarian has the option to choose from a list of 15 periodicity,
annual, weekly, daily, ...etc
A new field first_expected_date is also added to indicate
the expected date of the first issue of the given pattern.
The field expected_date_for_first_issue becomes required if the
frequency is not equal to IRREGULAR.
* Adapts tests and fixtures.
* Deletes a print message from the test files
https://tree.taiga.io/project/rero21-reroils/task/1481?kanban-status=1224894
* rero/rero-ils-ui#dev
`bootstrap` + ` setup`
The patterns editor shows a new field called `frequency`, you can select the
frequency of the pattern …

holdings: add frequency field to the pattern

---

rero_ils/modules/loans/cli.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
rero_ils/modules/patron_transaction_events/mappings/v6/patron_transaction_events/patron_transaction_event-v0.0.1.json
tests/data/data.json

* Fixes `patron_transaction_events` schema.
* Fixes `patron_transaction_events` ES mapping.
* Fixes loan cli according to schema updates.
* Fixes unit test/fixture

schemas: fix patron transaction events schema

---

scripts/bootstrap
scripts/setup

Recently RERO-ils changed pipenv to poetry. The setup used a specific
option `-w` that reduced displayed messages.
It uses FLASK_SKIP_DOTENV for that. But this variable is problematic
with the new poetry system as it skip `.env` files (used for
development, production, etc.).
This commit removes this old variable and fix a bootstrap problem too.
* Deletes FLASK_SKIP_DOTENV variable
* Fixes Travis test while bootstraping
While launching `poetry run setup -P -w`, the setup didn't find the `.env` file in which I add specific customization (for example for RERO_ILS_CSS or specific REDIS ports).
This comes from `FLASK_SKIP_DOTENV` used previously with pipenv. This is not needed anymore!
* create a `.env` with …

setup: fix old pipenv environment variables

---

rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/views.py
tests/api/test_patrons_rest.py

* Adds a new API url to check if an email address exists already. It
should be one of the following forms:
* `/api/patrons/count/?q=email:"test@test.ch"
* `/api/patrons/count/?q=email:"test@test.ch" NOT pid:1
* Adds a validator to the editor to check the uniqueness.
* Removes useless comment.
- Implements US: https://tree.taiga.io/project/rero21-reroils/us/1065?milestone=263424
- Go to the editor and try to create a patron with an existing email.
- Edit an existing patron it should not complain about the email

patrons: check if a patron email is unique

---

scripts/__init__.py

We often run `poetry run server`. And we stop it with `Ctrl+C`. This
generally gives a keyboard interruption signal that stops the processus.
But this is broken: the processus is already runned!
This commit fixes the issue by sending again the interruption signal to
the runned script.
The `poetry run server` often let invenio server and celery worker running (after Ctrl+C keyboard interruption). When we launch it again: it returns an error about "Port already addressed".
This PR changes the behaviour by sending an interruption signal to launched script when using a keyboard interruption command.
* Launch `poetry run server`
* Wait few seconds (for server to be launched)
* Interrupt the server with [Ctrl] + [C] command
* `ps aux|grep …

project: fix keyboard interruption for scripts

---

rero_ils/dojson/utils.py
rero_ils/modules/ebooks/receivers.py
rero_ils/modules/ebooks/tasks.py
rero_ils/modules/ebooks/utils.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/record.py
rero_ils/modules/notifications/api.py
tests/ui/documents/test_documents_api.py
tests/ui/ebooks/test_ebooks_receivers.py

- https://tree.taiga.io/project/rero21-reroils/task/1478
- Try to harvest multiple times from ebooks and verify harvested ebooks and attached holdings

ebooks: fix holdings update when importing ebooks

---

data/documents_big.json
data/documents_small.json
rero_ils/modules/documents/api.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
rero_ils/modules/documents/listener.py
rero_ils/modules/documents/serializers.py
rero_ils/modules/notifications/api.py
rero_ils/modules/persons/api.py
tests/data/data.json
tests/data/documents.json
tests/fixtures/metadata.py
tests/ui/documents/test_documents_mapping.py
tests/ui/persons/test_persons_api.py
tests/unit/test_documents_dojson.py

* Links documents to the source authority file, such as GND or IdRef,
through the MEF server, instead of the MEF clusterized record. This
is needed to provide a stable link to the authority.
My PR depends on the following `rero-ils`'s PR(s):
* rero/rero-ils-ui#269

persons: link persons to source instead of MEF

---

poetry.lock
pyproject.toml
rero_ils/modules/documents/api.py
scripts/__init__.py
scripts/setup
tests/ui/documents/test_documents_api.py

* Fixes problem with ui/documents/test_documents_api.py noz raising
exceptions. closes #1000
* Changes setup back to not run the ebooks harvesting for normal setup.
* Corrects unused imports in scripts/__init__.py
- https://github.com/rero/rero-ils/issues/1000
- run run-test
- run setup without connection to ebooks

test: fix run-test and setup

---

rero_ils/modules/documents/views.py
rero_ils/modules/items/views.py
rero_ils/modules/views.py
setup.py
tests/api/test_availability.py
tests/api/test_documents_rest.py
tests/api/test_items_rest_views.py
tests/api/test_translations.py
tests/ui/documents/test_documents_filter.py

* Adds a new HTTP endpoint to expose the python po based translations
in JSON in order to use theses translations in single app application
instead of duplicates the translations in several projects.
* Fixes spelling in comment.
* Exposes `invenio-i18n` to the uwsgi API.
* Fixes tests with the `invenio-i18n` enabled for the API.
* Removes useless template filters and their tests.
- Related to https://tree.taiga.io/project/rero21-reroils/task/1456?kanban-status=1224894
* rero/rero-ils-ui: https://github.com/rero/rero-ils-ui/pull/271
- Start the server and try: https://localhost:5000/api/translations/<ln>.json with <ln> is one of en, fr, de, it.

translations: add translations API

---

poetry.lock
rero_ils/modules/loans/api.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
tests/api/test_items_rest.py
tests/api/test_loans_rest.py

Before using invenio-circulation 1.0.0a21, loan use datetime format for
start_date and end_date fields.
RERO-ils uses hour in datetime fields to check timezone changes.
After invenio-circulation 1.0.0a21, start_date and end_date change to
date field only (it loses the hour).
This commit takes care of hour in start_date and end_date fields.
* Changes loan start_date and end_date to datetime field (to keep
hours/minutes)
* Uses tests on timezones again
- It implements check_timezone_date again
- tests should pass
- you can test on a full year (circa 5 hours):
```bash
./scripts/all_year_days poetry run pytest -vvs --no-cov --disable-warnings tests/api/test_items_rest.py
```
or with (circa 3 hours):
```bash
./scripts/all_year_days poetry run …
```

loans: use datetime for [start|end]_date fields

---

rero_ils/modules/documents/templates/rero_ils/_documents_get.html

In the detail document view, for standard holding, a link is still
present to go on item detail view. As the item detail view is no longer
exists this link cause an error. This PR deletes the link to avoid the
error.

document: delete link to item detail view

---

README.rst

Closes #627
Read the `README.rst` file.

documentation: add an actual README to the project

---

rero_ils/modules/documents/serializers.py
rero_ils/modules/permissions.py
rero_ils/modules/serializers.py
rero_ils/modules/utils.py
rero_ils/modules/views.py
tests/api/test_record_permissions.py
tests/api/test_serializers.py
tests/unit/test_utils.py

Remove permissions from `SearchSerializer` to improve API performance.
- Try to list some resources using the search API :
* `https://localhost:5000/api/patrons`
* `https://localhost:5000/api/documents`
* `https://localhost:5000/api/items`
* `https://localhost:5000/api/patrons/3`
* `https://localhost:5000/api/items/3`
* `https://localhost:5000/api/documents/3`

Permissions : Refactoring permissions usage

---

data/patterns.json
rero_ils/modules/ebooks/utils.py
rero_ils/modules/errors.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/mappings/v6/holdings/holding-v0.0.1.json
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/permissions.py
tests/api/test_patterns.py
tests/data/holdings.json
tests/ui/holdings/test_holdings_patters.py

To allow librarians to receive new issues for holdings records. According to the
patterns of the holdings, the system correctly increments the next issues.
Librarians are able now to create irregular and exception issues.
The field first_expected_date is renamed to next_expected_date and it is now
updated automatically after a successful receive of a regular issue.
The new value of next_expected_date is the expected_date of the received issue
plus the frequency of the pattern.
The reroils patterns support now all the RDA standard frequencies.
The pattern preview API returns both the issue_display_text and expected_date.
A new API is now available to receive the next regular issue.
Only librarians of the holdings library may receive the issues  in addition
to the system_librarians of same …

serials: receive an issue

---

rero_ils/modules/views.py
tests/api/test_translations.py

Fixes bug with translations API. If an exception occurred during
execution of this API, the exception should be logged into the
`current_app` logger. But `current_app` context was never loaded from
flask module before.
This PR also hacks translation files data : if a string is not
translated, rather than return an empty string, the original string will
be used.
* Adapts unitest to check theses cases.

translation: fix translations API

---

docker/nginx/nginx.conf

* Adds a filter to nginx logging to not log access on OPTIONS requests in
kubernetes deployments.
- Deploy to an kubernetes cluster and verify there no logs with OPTIONS anymore.

nginx logging

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json

* Adds cssClass property in jsonschema to display fields inline.
* Reorders some properties in jsonschema.
It's part of https://tree.taiga.io/project/rero21-reroils/us/1296?milestone=263424 (UX of editor)
Needs https://github.com/rero/rero-ils-ui/pull/267 and https://github.com/rero/ng-core/pull/184
Please do code review only. Testing is described here: https://github.com/rero/ng-core/pull/184

editor: display fields inline 

---

Dockerfile.base
babel.ini
pyproject.toml
rero_ils/config.py
rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/modules/organisations/jsonschemas/organisations/organisation-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
rero_ils/static/scss/rero_ils/variables.scss
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
rero_ils/views.py
scripts/bootstrap
tests/data/babel_extraction.json

* Removes JSONSchema backend on the fly translations.
* Removes legacy `validationMessage` JSONSchema` property.
* Adds suffix to the validation messages keys.
* Fixes missing punctuation in the validation messages.
* Cleans babel configuration.
* Removes legacy schema form code.
- FixesL https://tree.taiga.io/project/rero21-reroils/task/1456?kanban-status=1224894
* https://github.com/rero/ng-core/pull/187
* https://github.com/rero/rero-ils-ui/pull/277
- Go to the professionnal interface
- the language menu should have the same behaviour than the public interface
- test the editor with several resources, switch the language, the label, the description the placeholder and the …

translations: adds editor translations support

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_invoices/api.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/api.py
rero_ils/modules/budgets/api.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/cli.py
rero_ils/modules/documents/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/item_types/api.py
rero_ils/modules/items/api/api.py
rero_ils/modules/libraries/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/locations/api.py
rero_ils/modules/notifications/api.py
rero_ils/modules/organisations/api.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/persons/api.py
rero_ils/modules/tasks.py
rero_ils/modules/vendors/api.py

* Fixes CLI to use the correct process bulk indexing task.
* Improves IlsRecordsIndexer class to support `stats_only` option when processing bulk queue.
* Improves CLI tu support `with-stats` option on `runindex` command.
* Updates all Indexer class to use typed bulk indexing.
When we start delayed bulk indexing, celery task use default invenio-indexer process bulk queue.
We need to use IlsRecordindexer class to process bulk indexing queue.
reindex resource persons using task:
- `poetry run invenio utils reindex -t pers --yes-i-know`
- `poetry run invenio utils runindex -d -c 2`
The MEF persons must be filtered by organisation on each view.

cli: correct wrong process bulk queue

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
tests/fixtures/circulation.py
tests/ui/circulation/test_actions_checkin.py
tests/ui/circulation/test_actions_validate_request.py

Takes part of the implementations of all actions after an effort 
to modelize extensively all the circulation uses cases.
Fixes a bug: the system allowed validation of two different requests (loans)
on the same item.
Implements all the `manual validate` actions and use cases listed here:
https://github.com/rero/rero-ils/blob/dev/doc/circulation/actions.md
* Updates tests and fixtures accordingly.
https://tree.taiga.io/project/rero21-reroils/taskboard/sprint-31-117?kanban-status=1224894
This PR requires the following PR https://github.com/rero/rero-ils/pull/1044
code review and ./run_tests.sh

circulation: implement the validate_request action

---

rero_ils/modules/documents/templates/rero_ils/_documents_get.html
rero_ils/modules/documents/views.py
tests/ui/documents/test_documents_filter.py

If an item has an attached public note, it will be displayed in the
document detail view, just below the item detail row
- https://tree.taiga.io/project/rero21-reroils/us/1351?milestone=266303
- Use the professional interface to add a public notes on an item.
- Go into the public interface on the related document detail view.
- See the public note under the item detail

documents: add public notes in document detail view 

---

babel.ini
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

The file `document_v0.0.1.json` was excluded from babel extraction. It
results a lost of all translations from document JSON schema file.
This commit solves this problem.

translation: fix string extraction from JSON file

---

.github/ISSUE_TEMPLATE/developers.md

An issue template specific for dev is missing in 60c8b97. It allows developers
to open a purely technical issue.
Check the new file.

documentation: add an issue template for dev

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
tests/ui/circulation/test_actions_extend.py

Takes part of the implementations of all actions after an effort
to modelize extensively all the circulation uses cases
Fixes bug: an extend of a checked-out item was possible even if the item
had pending loans.
Implements all the `extend item` actions and use cases listed here:
https://github.com/rero/rero-ils/blob/dev/doc/circulation/actions.md
* Updates tests and fixtures accordingly.

circulation: implement extend loan action

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/documents/utils.py
rero_ils/modules/documents/views.py

* Removes notes_text from mapping and dump.
* Creates a filter to display notes in detailed view.
* Closes #1036.
To allow the creation or edition of a document with notes.
* https://github.com/rero/rero-ils-ui/pull/288
Try to edit a document with notes.

document: fix edition with notes

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/api.py
tests/fixtures/circulation.py
tests/ui/circulation/test_actions_cancel_request.py

Takes part of the implementations of all actions after an effort
to modelize extensively all the circulation uses cases.
Implements all the `cancel item request` actions and use cases listed here:
https://github.com/rero/rero-ils/blob/dev/doc/circulation/actions.md
* Updates tests and fixtures accordingly.
https://tree.taiga.io/project/rero21-reroils/task/1509?kanban-status=1224894
`rero_ils.US1394-invenio-circulation`
code  review only

circulation: implement cancel item request action

---

rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/permissions.py
rero_ils/modules/patrons/views.py
tests/api/test_patrons_rest.py
tests/api/test_permissions_librarian.py
tests/api/test_permissions_patron.py
tests/api/test_permissions_sys_librarian.py
tests/api/test_record_permissions.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/patrons/test_patrons_api.py

Creates an API to expose which roles could be managed by the current
logged user.
This commit also introduces a restriction to disallow the current user
to delete itself.
- https://tree.taiga.io/project/rero21-reroils/task/1523?kanban-status=1224894

authorization: create role management API

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
rero_ils/modules/documents/templates/rero_ils/_documents_description.html
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/utils.py
rero_ils/modules/documents/views.py
rero_ils/templates/rero_ils/macros/macro.html
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/documents/test_documents_filter.py

* Creates a filter and a macro to display series statement.
* Displays series statement in detailed view.
* Creates filters to display partOf field.
* Displays partOf in detailed view.
* Corrects jsonschema for the editor display.
* Adds a fixture with periodical issuance subtype.
https://tree.taiga.io/project/rero21-reroils/task/1552?kanban-status=1224894 of https://tree.taiga.io/project/rero21-reroils/us/1432?milestone=268117
https://github.com/rero/rero-ils-ui/pull/283
Go to public detail view of a document, with issuance, partOf and seriesStatement fields.

document: adapt detail view for series statement

---

poetry.lock
pyproject.toml
scripts/bootstrap
tests/conftest.py

- Adds optional invenio-sip2 module to poetry dependencies.
- Adds option into bootstrap to install sip2 module.
https://tree.taiga.io/project/rero21-reroils/us/1354
- execute `poetry run bootstrap`
- check if the CLI doesn't contains `selfcheck` command : `poetry run invenio --help`
- install sip2 module with :
`poetry install --extras sip2` 
or
`poetry run bootstrap --sip2`
- check if the CLI contains `selfcheck` command
- execute  `poetry run invenio selfcheck start -h 127.0.0.1 -p 3004`
(this command start the SIP2 socket server)

install: integration of invenio-sip2 module

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py
rero_ils/modules/items/views.py
rero_ils/modules/loans/api.py
tests/api/circulation/test_actions_views_add_request.py
tests/api/test_availability.py
tests/api/test_circ_bug.py
tests/api/test_items_in_transit.py
tests/api/test_loans_rest.py
tests/api/test_notifications_rest.py
tests/api/test_patrons_views.py
tests/ui/items/test_items_ui.py
tests/ui/patrons/test_patrons_ui.py

Users have now the choice to give one of the transaction_location_pid
or transaction_library_pid when placing a request.
The add request action is now possible from the item views
and api views. The list of required parameters are clearly
noted for frontend calls.
This pull request starts the work of the refactoring of the
all circulation actions decorator add_loans_parameters_and_flush_indexes.
* Creates additional units testing for frontend calls.

circulation: ensure the add request action for frontend calls

---

rero_ils/modules/cli.py
rero_ils/modules/documents/api.py
rero_ils/modules/ext.py
rero_ils/modules/imports/api.py
rero_ils/modules/imports/serializers.py
rero_ils/modules/imports/views.py
tests/api/test_external_services.py

* Splits the document dumps function to be usable to the serializers.
* Renames `/api/import/bnf` to `/api/import_bnf` to be usable by the UI.
* Fixes year aggregation filter by forcing the terms to be a string.
* Returns empty result for empty query.
* Sorts aggregations by term counts.
* Creates a post_process function in JSON serializers.
* Creates two serializers: one without extra data for the editor one
with extra data for the document views.
* Adds a new not found result error handler.
* Makes the tests more robust to BNF changes.
- https://tree.taiga.io/project/rero21-reroils/us/1274
* rero/rero-ils-ui#286
* rero/ng-core#194

document: adapt the importation REST API to the UI

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/utils.py
tests/api/test_items_in_transit.py
tests/ui/circulation/test_actions_checkout.py

* Adds few tests for CHECKOUT on every item status
* Sets CHECKOUT actions as implemented in actions.md description file
* Fixes CHECKOUT_1_2_2 (checkout denied for loan with different patrons
on existing pending loan)
* Deactivates test_item_multiple_transit as it would be checked later
Because of [US1505, implement checkout actions](https://tree.taiga.io/project/rero21-reroils/task/1505?kanban-status=1224894).
```bash
poetry run bootstrap
poetry run run-tests
```

circulation: add tests on CHECKOUT action

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/api.py
rero_ils/modules/patrons/views.py
tests/api/circulation/test_actions_views_add_request.py
tests/api/circulation/test_actions_views_cancel_request.py
tests/api/test_circ_bug.py
tests/api/test_items_in_transit.py
tests/api/test_patrons_views.py

Replaces the cancel_loan method by cancel_item_request
Users have now the choice to give one of the transaction_location_pid
or transaction_library_pid when placing a request.
The cancel item request action is now possible from the item views
and api views. The list of required parameters are clearly
noted for frontend calls in the actions.md and api_views.
* Creates additional units testing for frontend calls.

circulation: ensure the cancel item request action for frontend calls

---

rero_ils/config.py
rero_ils/modules/cli.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/views.py
rero_ils/modules/ext.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/imports/__init__.py
rero_ils/modules/imports/api.py
rero_ils/modules/imports/serializers.py
rero_ils/modules/imports/views.py
run-tests.sh
setup.py
tests/api/test_external_services.py

US1274: Import from BnF

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/api.py
tests/api/circulation/test_actions_views_validate_request.py
tests/api/test_availability.py
tests/api/test_loans_rest.py

Replaces the api call /validate by /validate_request.
Users have now the choice to give one of the transaction_location_pid
or transaction_library_pid when placing a request.
The validate action of item request is now possible from the item views.
The list of required parameters are clearly noted for frontend calls in
the actions.md and api_views.
* Creates additional units testing for frontend calls.

circulation: ensure request validation from ui

---

poetry.lock
rero_ils/config.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/record.py
rero_ils/modules/locations/api.py
run-tests.sh
tests/api/test_items_rest_views.py
tests/conftest.py

After each new RERO-ils release, packages are updated. This commit do
needed changes for that.
* Updates packages to their last version in poetry.lock.
* Adapts run-tests command because of isort 5 (new version)
External tests failed because isort is now in version 5. This PR updates isort and adapt run-tests accordingly.
Just check tests are OK.

poetry: update packages to their last version

---

rero_ils/manual_translations.txt
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

* Adds manual translation for "other" document type (as other document
types)
* Closes rero/rero-ils#917
- In the professional interface, create a new documents with "other" as document type.
- In the public interface, choose french/italian/... language
- Display the detailed document view for your newly created document.

document: translate document type in detail view

---

doc/circulation/actions.md
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/api.py
tests/api/circulation/test_actions_views_extend_loan_request.py

* adds new prior_extend_loan_actions method used before extend_loan
action
* adds new test_actions_views_extend_loan_request test file
* uses do_jsonify_action for extend_loan action
Because of [US1580 about extend_loan action in API views](https://tree.taiga.io/project/rero21-reroils/task/1580)
Just check that Travis tests are OK

circulation: ensure the item extend loan action for frontend calls

---

scripts/bootstrap

Sometimes a bootstrap scripts failed while in step "Install npm assets
utils" without errors.
It failed on cleancss installation (because symbolic links already
exists).
To avoid this problem a clean-install of npm assets utils should resolve
the problem.
An error is now already given when it fails.
* Adds error message when npm asset utils fails.
* Uses clean-install option for npm instead of install one.
Sometimes, when installing RERO-ils with a `poetry run bootstrap` command, you get:
```bash
❯ poetry run bootstrap
PROGRAM: bootstrap                                                          
[INFO]: Install with command: poetry install 
Installing dependencies from lock file                     
No dependencies to install or update
- …
```

bootstrap scripts: fix npm utils installation

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json

According to PO, the 'responsibilities' field from document 'edition
statement' should be optional in the editor form. This commit hides this
field (if it's empty) so, now, the user must choose to add this field
(and fill a value). Editing a document without 'responsibilities' is now
allowed by default.
* Closes rero/rero-ils#906
- Try to edit a document without edition designation (`documents/249`)
- The 'responsibilities' field from 'edition statements' array is now hide by default --> you can save without fill any value.
- Try to edit again the save document. Add a 'responsibilities' and save the document.
- Try to edit again, the 'responsibilities' field is well displayed and filled with correct data.

editor: fix edition statement saving problem.

---

rero_ils/manual_translations.txt
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

* Applies PO's group feedback:
* Removes useless description.
* Adds missing placeholders.
* Corrects some fields display and validation.
* Adds strings to translate.
To apply some corrections:
* `seriesStatement.seriesTitle` should have no description; it is useless
* Placeholders for `seriesEnumeration` and `subseriesEnumeration` are missing.
* When editing a document with a series statement, the editor opens by default the subseries statement, which makes it impossible to save the document.
* The subseries statement should always be added manually (except when it already contains data), as it is quite rare.
* By default, fields `seriesTitle` and `seriesEnumeration` should be displayed inside `seriesStatement`.
* Format validation …

editor: apply PO feedback

---

rero_ils/modules/documents/views.py

* Sorts alphabetically the pickup locations as the patron place a request on an item.
- To add a sort on pickup name on request.
- Check order on menu

request: sort alphabetically pickup location

---

check_license_config.yml
rero_ils/modules/cli.py
tests/e2e/cypress/.gitignore
tests/e2e/cypress/cypress/integration/circulation/checkout-checkin.spec.js
tests/e2e/cypress/cypress/support/commands.js

run-tests.sh checks that Licenses are OK for some files.
This scripts fails when JS files use a Triple Slash Directive.
This commit change this.
* Improves check_license method to include Triple-Slash directives for
.js files (Cf.
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)
* Avoids checking screenshots directory in Cypress
* Adds a triple slash directive on 2 JS files (from Cypress).
Because Cypress tests needs to be done on RERO ILS and I need to extend developer environment to do so.
`poetry run run-tests` shouldn't give any error on Cypress JS files (that contains Triple Slash Directive)

check_license: accept Triple Slash Directive

---

rero_ils/modules/patrons/views.py
rero_ils/templates/rero_ils/header.html
rero_ils/views.py

In Cypress it's difficult to choose a specific item in the menu if you
don't know in which language you are. Each element can be in French,
English, etc.
To facilitate this work we can add id= on each element on the menu.
With a specific word. This way you don't need to know in which language
you are.
* Adds Id on all menus ('My Account' menu, languages menu, help menu,
logout, etc.) for testing purposes.
To fix problems to target menu elements with Cypress.
1. make a setup
1. open the homepage (https://localhost:5000/)
1. Open your web browser development tab (F12 on Chrome)
1. Use the "select" option to click on menu and check that the item have `id=` as attribute. For example `id=help-menu`

ui: select menu items by Cypress through ids

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json

* Implements 'oneOf' attribute in order to link issuance main type and subtype values in editor.
This PR is part of US1432 (task 1603)
https://tree.taiga.io/project/rero21-reroils/us/1432?milestone=268117
https://tree.taiga.io/project/rero21-reroils/task/1603?kanban-status=1224894
* https://github.com/rero/ng-core/pull/215
* https://github.com/rero/rero-ils-ui/pull/283
See https://github.com/rero/ng-core/pull/215 description

editor: link issuance main type and subtype values

---

rero_ils/modules/documents/listener.py
tests/data/documents.json

* Indexes host document title in order to get child document in search results.
To implement a correction asked by PO's group
Task: https://tree.taiga.io/project/rero21-reroils/task/1602?kanban-status=1224895
N/A
Find a document that has a part of field. Search the host document in public view. You should have both host and child document in search results (for example journal and article).
Try to add several child documents to host document and check that the search result is correct.

document: index host document title in child document record

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json

* Fixes the loading of 'oneOf' data when editing a record.
* Closes rero/rero-ils#1102.
Task 1619 of US1432
https://tree.taiga.io/project/rero21-reroils/task/1619?kanban-status=1224894
https://tree.taiga.io/project/rero21-reroils/us/1432?milestone=268117
* https://github.com/rero/rero-ils-ui/pull/283
* https://github.com/rero/ng-core/pull/220
See issue description.

editor: fix 'oneOf' data loading

---

rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/persons/jsonschemas/persons/person-v0.0.1.json
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json

* Updates JSON schema form to use the new select menu with order.
My PR depends on the following `ng-core`'s PR(s):
* rero/ng-core#7400a310fbeda8432ebf944c402325e6bc9878c1
- Add a document (or other ressource) and check select menu order.

json schema: use the select menu with order

---

rero_ils/modules/items/api/circulation.py

Sometimes items have Loan in CREATED state. Mainly due to circulation
action that are interrupted.
These Loan are not considered as important for the Circulation. But the
delete button on Item cannot be active if CREATED Loan exists.
This commit fixes the problem by bypassing CREATED Loan in item delete
button.
* Fixes bug about Item that have Loan in state CREATED and cannot be
deleted.
Because you cannot delete an item that have CREATED Loan.
* Attempt a checkout on an item not allowed by policy (an error should appear)
* Check that you have CREATED Loan here: http://localhost:9200/loans/_search/?q=CREATED
* Go to the item and check that the "delete" button is possible
* Click on it.

loans: item deletion allowed with CREATED loan

---

rero_ils/modules/patrons/views.py

* Adds missing parameters to renew button in patron profile public
interface
Because the renewal button on patron profile (public interface) doesn't work anymore.
* launch rero-ils server
* connect as simonneta or jules
* go to your profile
* select an item to renew
* click on renewal button
* it should renew your book

ui: adapt renewal button to new circulation

---

scripts/server
tests/e2e/cypress/cypress/integration/circulation/checkout-checkin.spec.js
tests/e2e/cypress/cypress/support/commands.js

Previously Cypress tests use a lot of code to fake a clic on the right
menu. Now that `id=` attributes are available in RERO we can simplify
Cypress tests, and improve them!
* Doesn't hide the Debug toolbar in Cypress tests as FLASK_DEBUG
should be set to False when launching the server.
* Creates new setLanguageToEnglish Cypress command to set language to
English.
* Deletes all cy.visit() method and use menus to navigate in the
application.
* Creates new logout() Cypress command.
* Creates new goToMenu() Cypress command.
* Creates new createItem() Cypress command.
* Creates new goToItem() Cypress command.
* Improves checkout-checkin.spec.js Cypress tests using new Cypress
commands.
To improve use of Cypress commands in rero-ils for …

cypress: enhance commands to improve tests

---

scripts/server

The Team uses scripts/server to launch a server with celery.
Sometimes Celery is not mandatory, and sometimes we need a different log
level.
* Adds new `-l` or `--loglevel` server script option to change Celery
log level.
* Adds new `-n` or `--no-worker` server script option to disable Celery
workers.
DEV Team needs to add more options to `server` script because of too many logs in server.
* Check `poetry run server --no-worker` first (to check with `ps aux|grep celery` that no worker belongs)
* Check then `poetry run server --loglevel FATAL` (and then `ps aux |grep celery` to check that Celery workers exists with `--loglevel FATAL`)

server: enable options to server script

---

poetry.lock
pyproject.toml

Since pytest 6.0.0, some breaking changes appears on
https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent
* Limits pytest version inferior to something inferior to 6.0.0.
Because development branch failed in Travis: https://travis-ci.org/github/rero/rero-ils/jobs/712883182#L1777
It's linked to: https://docs.pytest.org/en/stable/changelog.html#breaking-changes (from 6.0.0 version).
Solutions found:
1. change `pytest.ini` file as explained in pytest 6.0.0 breaking changes
1. wait about pytest_pep8.py file to be updated
1. limit our pytest version to less than 6.0.0 (solution choosen)
PS: A new issue opened for pytest_pep8.py file here: https://bitbucket.org/pytest-dev/pytest-pep8/issues/25/pep8it …

pytest: fix deprecation warnings on version 6.0.0

---

rero_ils/modules/cli.py
tests/data/documents.json
tests/unit/test_cli.py

* Fixes the marc21json cli function to work proberly with json schema files with $refs.

cli: marc21json cli function to use splitted json schemas

---

rero_ils/modules/items/api/circulation.py
tests/api/circulation/scenarios/test_scenario_a.py
tests/api/circulation/scenarios/test_scenario_b.py
tests/api/circulation/scenarios/test_scenario_c.py
tests/api/circulation/scenarios/test_scenario_d.py

Ensures that all circulation scenarios listed in the file
https://github.com/rero/rero-ils/blob/dev/doc/circulation/scenarios.md
are tested in the backend.
Fixes bug: a checkout was not possible for an item with two pending loans.
https://tree.taiga.io/project/rero21-reroils/us/1492?milestone=269576
`./run_tests.sh`

circulation: add units testing for circulation scenarios

---

rero_ils/jsonschemas/common/countries-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
tests/e2e/cypress/cypress/fixtures/document.json
tests/e2e/cypress/cypress/fixtures/users.json
tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
tests/e2e/cypress/cypress/support/commands.js

* Creates a test for the creation of a document with only essential
fields.
* Creates document fixture.
* Corrects jsonschema (countries, provision activity).
* Corrects checkout-checkin test to use custom ids in editor.
To implement a test of the user interface of the documents editor. First case: create a document with essential fields only.
https://tree.taiga.io/project/rero21-reroils/task/1562?kanban-status=1224894
* dev of rero-ils-ui
* dev of ng-core
You need a bootstrap and a setup, and run the server with `FLASK_DEBUG=False poetry run server`, otherwise the test will fail.
Check that `FLASK_DEBUG=False` is not overwritten in invenio.cfg.
To run the tests on command line: `poetry run …

cypress: test the creation of a simple document

---

rero_ils/modules/loans/api.py
tests/api/loans/test_loans_api_rest.py

A temporary fix until the US of the patron history is created, to
avoid returning circulation history for deleted items.
* close #1137

patron: no history returned for deleted items

---

pyproject.toml
scripts/russian_dolls

* Adds russian_dolls script that packages ng-core, includes it in
rero-ils-ui, then packages it and includes the result in rero-ils
(current project from where the script is launched).
Developping Cypress tests for RERO-ils generates the need to include ng-core into rero-ils-ui and rero-ils-ui into rero-ils. This takes some times and need to know each command to do this, wait about the result, etc.
This commit includes a script that do the job.
Get ng-core, rero-ils-ui and rero-ils.
Then:
```bash
cd rero-ils
poetry run folding -c ~/rero/ng-core -u ~/rero/rero-ils-ui
```
You should see that:
* script generates a rero-ng-core-0.7.0.tgz file in ng-core directory
* script generates a rero-rero-ils-ui-0.4.0.tgz file in rero-ils-ui directory
* …

scripts: install ng-core and ui in main project

---

rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/api_views.py

As item from multiple organisations can shared the same barcode, when a
search on barcode is done, we need to filter it by the current logged
user organisation pid.
Closes rero/rero-ils#1085
Try to reproduce https://github.com/rero/rero-ils/issues/1085

Zan #barcode by institution

---

setup.py

In a deployed environment, celery scheduler is unable to locate the method
task_clear_and_renew_subscriptions which is used to clear patron subscriptions.
This is due to the fact that task_clear_and_renew_subscriptions is configured
in config.py and its path not present in setup.py
* close #1158
To fix Sentry errors:
`
KeyError celery.worker.consumer.consumer in on_task_received
rero_ils.modules.patrons.tasks.task_clear_and_renew_subscriptions
`

patron: fix missing configuration for patron subscriptions

---

rero_ils/jsonschemas/common/languages-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_series-v0.0.1.json

Reorganizes `numbering_script` from `common/languages-v0.0.1.json`
to `documents/document_series-v0.0.1.json`.
* closes #1147

data: reorganisation of json schema.

---

rero_ils/views.py

Updates the url from the public help menu entry from 'help' to
the public help page corresponding to the interface current selected
language ('help/home/public_help_{language}')
Closes rero/rero-ils#1127
- Check the main help menu entry. Mus be point to `/help/public`

wiki: update the public help menu entry url

---

doc/circulation/scenarios.md
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/api.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_requests.html
tests/api/items/test_items_rest_views.py

Fixes a bug: the item API blocked checkout for an item_at_desk
item with pending requests.
Uses the field `loan._created` to sort requests instead of the
field `loan.transaction_date`.
Adds the property loan.request_creation_date fulfilled by loan._created.
Fixes a bug when loan state CREATED was returned in a loan search.
* close #1160 
* Adds the full description of the circulation scenario E.

circulation: fix problem when checking out an item_at_desk

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/loaders/__init__.py
rero_ils/modules/documents/loaders/marcxml.py
rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
tests/api/documents/test_marcxml_rest_api.py
tests/conftest.py
tests/data/document.xml
tests/data/documents.xml
tests/fixtures/metadata.py
tests/unit/test_documents_jsonschema.py
tests/utils.py

With this commit, authenticated users can post marcxml records using the
document REST API. The imported records receive the flag _draft as True. The
record validation for the draft records is disabled.
* Adds a new field _draft to the document json schema.
* Updates tests/fixtures accordingly.
For MARCXML import records from EZpump:
https://tree.taiga.io/project/rero21-reroils/us/1546?milestone=269576
run_tests.sh

document: add marcxml support for the document API

---

rero_ils/modules/items/api/circulation.py
tests/api/items/test_items_rest.py
tests/api/test_item_rest.py
tests/api/test_loans_rest.py

According to the new circulation specs given by the PO, requests are allowed
on loans with ITEM_IN_TRANSIT_TO_HOUSE state.
Remove the unused method is_loaned_to_patron.

circulation: allow requests on ITEM_IN_TRANSIT_TO_HOUSE loans.

---

rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/csv.py
tests/api/test_serializers.py

In item inventory list, we need to have the information about document creator.
* Adds document creator into csv file.
https://tree.taiga.io/project/rero21-reroils/task/1644
My PR depends on the following `rero-ils`'s PR(s):
* rero/rero-ils#1129
**MERGE THIS PR AFTER rero/rero-ils#1129**

inventory: export document creator field

---

rero_ils/views.py

Updates the url from the public help menu entry from 'help' to
the public help page ('help/public')
Closes rero/rero-ils#1127

help: update the public help menu entry url

---

rero_ils/query.py
tests/api/documents/test_documents_rest.py

As https://github.com/rero/rero-ils/pull/1155 allows posting
of marcxml records as draft records. With this commit, the
search results will exclude draft records in case they are
not yet validated by the librarian
https://tree.taiga.io/project/rero21-reroils/task/1662?kanban-status=1224894

document: exclude drafts from search results

---

rero_ils/modules/cli.py
rero_ils/modules/documents/permissions.py
scripts/setup
tests/api/documents/test_marcxml_rest_api.py
tests/data/document.xml
tests/data/documents.xml
tests/unit/test_cli.py

With this commit, a new role `document_importer` is created for users
creating document via the document post API only.
Currently, this role is assigned to one invenio user for ngscan tests.
A new cli to create personal OAuth token is added to the utils.
* Fixtures and tests updated accordingly.
https://tree.taiga.io/project/rero21-reroils/us/1546
1. ./run_tests.sh
2. procedure to generate an access token is here 
https://github.com/rero/developer-resources/blob/master/permissions/generate_oauth_token.md

document: allow posting documents using OAuth token

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py

When a request is canceled, if another one has to be validated, the
return statement is wrong (double dict key). This commit fixes this
problem and returns a correct actions applied list.

circulation: fix validate request return type

---

data/templates.json
data/users.json
rero_ils/config.py
rero_ils/modules/templates/__init__.py
rero_ils/modules/templates/api.py
rero_ils/modules/templates/jsonschemas/__init__.py
rero_ils/modules/templates/jsonschemas/templates/template-v0.0.1.json
rero_ils/modules/templates/mappings/__init__.py
rero_ils/modules/templates/mappings/v6/__init__.py
rero_ils/modules/templates/mappings/v6/templates/template-v0.0.1.json
rero_ils/modules/templates/models.py
rero_ils/modules/templates/permissions.py
rero_ils/modules/templates/views.py
rero_ils/query.py
scripts/setup
setup.py
tests/api/templates/test_templates_permissions.py
tests/api/templates/test_templates_rest.py
tests/api/test_monitoring_rest.py
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/templates/test_template_mapping.py
tests/ui/templates/test_templates_api.py
tests/ui/test_monitoring.py
tests/unit/conftest.py
tests/unit/test_templates_jsonschema.py

A new resource `template` is added for the records of
types document, patron, item and holdings.
A non-controlled field called `data` in the template
json schema is available for librarians to save
pre-validated data.
A template can have two visibilities either:
1. public, available for use for all users of the
organisation.
2. private, available only for use for its creator.
Users with role librarian can create private templates,
edit their own private records, and access public and
their own private records of their organisation.
Users with role system_librarian can create/edit/access/delete
any type of templates of its organisation.
* Adds pids to the users.json fixtures data file.
* Adds units testing and fixtures for the new resource. …

templates: implement record templates

---

data/templates.json
rero_ils/modules/templates/jsonschemas/templates/template-v0.0.1.json
rero_ils/modules/templates/views.py
setup.py
tests/unit/test_utils.py

* Adds templates records fixtures.
* Makes the template field `data` required in the json schema.
https://tree.taiga.io/project/rero21-reroils/task/1688?kanban-status=1224894
`bootstrap + setup`
new templates are available at:
~/api/templates/

templates: add new fixtures for different records

---

rero_ils/modules/api.py
rero_ils/modules/cli.py
rero_ils/modules/utils.py
tests/ui/test_utils_app.py
tests/unit/test_utils.py

A new method to return a record class from a given
pid_type or a record schema. This method is to group
codes used in different areas and replace it with this
method.
* Adapts areas of codes as necessary.
* Creates tests.
* Removes forgotten print line.

utils: new method to return record class

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution_role-v0.0.1.json

* Removes the contribution role default value that was preventing the
successful save of a document without contribution field.

editor: fix error 400 when saving a simple document

---

rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json

Adds a search input in the order line editor to link an order line to a
document, preventing the user to enter a valid API URL.
* Adapts order lines JSON schema.
* Updates order lines JSON schema source string for translation.
* rero/rero-ils-ui#350
- Test document typeahead in order lines editor.

acquisition: add document selector for order lines

---

rero_ils/modules/holdings/api.py
tests/api/holdings/test_patterns.py
tests/ui/holdings/test_holdings_patterns.py

With this commit, the documents of journal type and periodical issuance
type can have not only serial holdings but also standard holdings.
https://tree.taiga.io/project/rero21-reroils/task/1709?kanban-status=1224895

holdings: allow creating std holdings on journal

---

rero_ils/modules/templates/jsonschemas/templates/template-v0.0.1.json
rero_ils/modules/templates/permissions.py

* Fixes templates permissions for update method.
* Fixes JSON schema :
- user can't update template_type for a template.
- description field is now displayed as a textarea.

template: fix permissions/JSON schema

---

data/circulation_policies.json
data/item_types.json
data/libraries.json
data/locations.json
data/organisations.json
data/patron_types.json
data/users.json
rero_ils/modules/organisations/api.py
rero_ils/templates/rero_ils/frontpage.html
tests/ui/test_views.py

* Adds fixtures for cypress tests (organisation, libraries, librarians,
patrons, locations, patron type, item type and circ policy). This leverages
the creation of resources needed to test circulation scenarios
Add fixtures dedicated to cypress tests.
N/A

fixtures: add an organisation for cypress

---

rero_ils/modules/loans/api.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_requests.html
tests/e2e/cypress/cypress/fixtures/items.json
tests/e2e/cypress/cypress/fixtures/users.json
tests/e2e/cypress/cypress/integration/circulation/scenario-a.spec.js
tests/e2e/cypress/cypress/integration/templates/template-test-request.spec.js
tests/e2e/cypress/cypress/support/circulation.js
tests/e2e/cypress/cypress/support/commands.js
tests/e2e/cypress/cypress/support/navigation.js
tests/e2e/cypress/cypress/support/record.js
tests/e2e/cypress/cypress/support/user.js

* Creates scenario A test.
* Adds an id html attribute in patron profile view for element selection
with cypress.
Task 1612 of US1489
N/A
You need to include rero-ils-ui into rero-ils:
`cd rero-ils-ui`
`npm ci && npm install path/to/ng-core.tgz --no-save`
`npm run pack`
`cd rero-ils`
`poetry run bootstrap -t path/to/rero-ils-ui.tgz`
`poetry run setup`
Then run the server with `FLASK_DEBUG=False poetry run server`, otherwise the test will fail.
Check that `FLASK_DEBUG=False` is not overwritten in invenio.cfg.
`poetry run cypress` installs new version of cypress and runs all the tests.
With a GUI: `cd tests/e2e/cypress`, then `npm run cypress`. Click on the test file to launch it.
Try different browsers.

cypress: create scenario A test

---

CHANGES.rst
RELEASE-NOTES.rst
pyproject.toml
rero_ils/bundles.py
rero_ils/version.py

For the `v0.12.0` release
- Check the changes files.
- Have a look to the RELEASE-NOTES.rst file.

release: v0.12.0rc

---

rero_ils/modules/ill_requests/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_ill_requests.html
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
tests/ui/ill_requests/test_ill_requests_api.py
tests/ui/patrons/test_patrons_ui.py

Adds a tab into the patron profile to display the requests related to
the current logged patron.

circulation: display ILL request in patron profile

---

rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json

Updates regular expression used to validate the date fields.
Closes rero/rero-ils#1187

general: use better regular expression for date

---

tests/e2e/cypress/cypress/integration/circulation/scenario-a.spec.js
tests/e2e/cypress/cypress/integration/templates/template-test-request.spec.js

* Updates cypress tests after replacing 'Patrons' with 'Users' in UI.
Task 1755 of US1590
* https://github.com/rero/rero-ils-ui/pull/381
* needs bootstrap with rero-ils-ui's PR
* needs data in db
* `FLASK_DEBUG=False poetry run server`
* `poetry run cypress`

patrons: adapt cypress tests after renaming

---

data/users.json
rero_ils/config.py
rero_ils/modules/minters.py
rero_ils/modules/patrons/cli.py
rero_ils/modules/serializers.py
rero_ils/modules/templates/api.py
rero_ils/modules/templates/mappings/v7/templates/template-v0.0.1.json
scripts/setup
tests/api/templates/test_templates_rest.py
tests/api/test_monitoring_rest.py

Using the CLI `import_users` keeps some pids into the `patron_pid` db
table. This will cause problem to create new user after the setup (using
API or UI. This commit cleans the user creation.
This commit also update template resource facet configuration and ES
mapping (to allow resource name sorting).
- run `bootstrap` & `setup`
- start the UI (localhost:4200) and create a  new user (role doesn't matter).

patrons: fix patron CLI creation problem.

---

rero_ils/modules/patrons/cli.py

Remove the unrelevant 'append' argument from import_users function. This
argument are marked as required but isn't yet valid for this method.
- Run `poetry run setup`

patron: Fix user import problem.

---

rero_ils/modules/documents/views.py

When user is self registered and loggeg in, the user cannot access to document detail display.
that's raise en internal server error.
* Adapts `can_request` jinja filter.
https://github.com/rero/rero-ils/issues/1255
1. Go to the registration form and create a new account, you will receive a validation email
2. validate your account by clicking link in the email
3. Log in with your new account on rero-ils
4. Do a search and click on a document
5. You can view the detail of the document.

document: fix internal server error when display view

---

data/patterns.json
rero_ils/modules/documents/templates/rero_ils/_documents_get.html
rero_ils/modules/documents/views.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/mappings/v7/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/models.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/views.py
tests/api/holdings/test_patterns.py
tests/data/holdings.json
tests/ui/holdings/test_holdings_api.py
tests/ui/holdings/test_holdings_patterns.py
tests/ui/items/test_items_filter.py
tests/unit/test_holdings_jsonschema.py

With this commit, new optional fields are allowed for
the holdings of type serial. The fields are:
- enumerationAndChronology
- supplementaryContent
- index
- missing_issues
- notes
The new field second_call_number is available for
all types of holdings records
Item and holdings call numbers have no minimum character constraint.
Issues with status deleted are not displayed in the public interface.
* Closes #1284
* Removes the condition to have an item second call number only
if first call number exist.
* Adapts tests and fixtures accordingly.
* Adapts the public interface to display the new fields.
https://tree.taiga.io/project/rero21-reroils/taskboard/sprint-35-106?kanban-status=1224894
`bootstrap` + `setup`
To display a serial holdings with …

holdings: add optional fields for holdings display

---

rero_ils/modules/patrons/static/scss/rero_ils/patrons_profile.scss
rero_ils/modules/patrons/templates/rero_ils/_macro_profile.html
rero_ils/modules/patrons/views.py
tests/ui/patrons/test_patrons_ui.py

When a patron has some fees containing at least one 'dispute' event, the
server crash because ii tries to convert the amount of dispute (always
none) to a decimal number. This PR fix this problem checking if the
event to display has a valid 'amount' attribute. This PR also fixes some
small HTML problems on the patron profile.
Closes rero/rero-ils#1272
- Log in as admin. Go in professional view to place a dispute event on Simonetta patron account.
- Logout
- Log in as Simonetta. Display your patron profile to view the dispute event.

patron: fix patron profile for dispute event

---

rero_ils/filter.py
rero_ils/modules/ext.py
rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/templates/rero_ils/_macro_form.html
rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html
rero_ils/modules/loans/api.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_ill_requests.html
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_loans.html
rero_ils/static/scss/rero_ils/styles.scss
tests/ui/test_filters.py

When user submit the ill request form with some values, either the
server return an error either bad data are saved into the request :
* no date selected --> 'None' string was saved.
* found_in.source specified and no url --> server error
* invalid URL in found_in.url --> server error
This commit also fixes some bugs due t item call_number that is now not
required. Introducing a new Jinja filter to display an custom message if
no data is available.
- When creating an ill_request, test the form with "source" and "url" fields.
- Create an ill_request with no year.
- Display the checkout tab in the patron detail view for Simnetta. The item "Art passions" detail will display a substitution text for call number field

ill_request: fix form validation problem

---

rero_ils/jsonschemas/common/cantons-v0.0.1.json

The canton field should only be available when the country 'Switzerland'
was selected in the provisionActitivy country field.
Closes rero/rero-ils#1285
- In the document editor, play with `country` field into `provisionActivity` section. When 'Switzerland' (sz) is selected the canton field should appears, otherwise the field is hidden.

document: canton field only available for switzerland

---

rero_ils/modules/loans/api.py

When a loan was extended, the responses doens't include the correct
action name ('extend' instead of 'extend_loan'). This PR fix this
problem.
Closes rero/rero-ils#1256
Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

circulation: fix extend loan API response

---

rero_ils/config.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py
rero_ils/modules/items/decorators.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/utils.py
rero_ils/modules/notifications/tasks.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/utils.py
tests/api/circulation/test_locations_restrictions.py
tests/api/loans/test_loans_rest.py
tests/api/loans/test_loans_utils.py
tests/api/test_tasks.py
tests/ui/circulation/test_loan_utils.py

Implements the overdue_items_limit restriction : If a patron type
resource defines an 'overdue_items_limit', patrons with overdue items
can't execute any checkout operation if the limit is reached.
This commit also refactors the 'blocked_patron' restriction.

patron_type: implements overdue items restriction

---

data/patron_types.json
rero_ils/modules/loans/api.py
rero_ils/modules/patron_types/api.py
tests/api/loans/test_loans_limits.py
tests/api/loans/test_loans_rest.py

Implements the items_checkout limit restriction. When a patron tries a
checkout, the server firstly check the ITEM_ON_LOAN items linked to this
patron and determine if the new checkout can be allowed related to
checkout limits define in the linked patron_type.

patron_types: implements checkout limit restriction.

---

rero_ils/modules/loans/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/views.py
tests/api/loans/test_loans_limits.py
tests/api/patrons/test_patrons_blocked.py
tests/api/patrons/test_patrons_rest.py

Adds an API to get patron circulation loan statistics. This API return
the number of loans relate to this patron by state.
Closes rero/rero-ils#1278

patron: add circulation statistic API

---

poetry.lock
pyproject.toml
rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_person-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_role-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_electronic_locator-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_issuance-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_language-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_note-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/templates/jsonschemas/templates/template-v0.0.1.json

* Updates JSONSchema to add default values for the editor.
* Changes the way to hide a field in the editor.
- To fix: rero/rero-ils#1119.
* rero/ng-core#291
- Create a new document record. Fill optional fields, hide/show the default value should be there and the value should be the same as after the form creation.
- The editor should be tested for the document, the holding, the item and the templates.

editor: restore default value for hidden field

---

rero_ils/modules/items/api/circulation.py
tests/ui/circulation/test_actions_cancel_request.py

* Allows the cancellation of a request when there are several requests
on the item.
* Closes #1303.
To close mentioned issue.
N/A
See issue description

circulation: fix 'cancel request' with multiple requests

---

data/users.json
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/cli.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/utils.py
tests/api/notifications/test_notifications_rest.py
tests/api/test_user_authentication.py
tests/fixtures/circulation.py
tests/ui/notifications/test_notifications_api.py
tests/ui/patrons/test_patrons_api.py
tests/unit/test_patrons_jsonschema.py

* Makes the email optional.
* Updates the fixtures.
* Updates the user loading script.
* Adds an additionnal notification email for the patron.
- Implements: https://tree.taiga.io/project/rero21-reroils/us/1659
- Create a patron without email. Do a checkout. Log with the new user and consult his profile.

users: make the email optional

---

tests/e2e/cypress/cypress/fixtures/collections.json
tests/e2e/cypress/cypress/integration/application/test-login-logout.spec.js
tests/e2e/cypress/cypress/integration/circulation/scenario-a.spec.js
tests/e2e/cypress/cypress/integration/circulation/scenario-b.spec.js
tests/e2e/cypress/cypress/integration/collections/test-collections.spec.js
tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
tests/e2e/cypress/cypress/integration/examples/empty-template.spec.js.disabled
tests/e2e/cypress/cypress/integration/examples/example-test-request.spec.js
tests/e2e/cypress/cypress/integration/templates/templates-test.spec.js
tests/e2e/cypress/cypress/support/collection.js
tests/e2e/cypress/cypress/support/index.js
tests/e2e/cypress/cypress/support/navigation.js
tests/e2e/cypress/cypress/support/record.js
tests/e2e/cypress/cypress/support/user.js

* Creates e2e tests for collections.
* Replaces 'goToMenu' custom command in order not to go to the frontpage
each time we navigate in the app.
* Adds an empty template to re-use for test creation.
* Adds cookies preservation to keep authentication information between tests.
* Changes login and logout commands in order to use API calls instead of
UI actions.
* Adds a test for login and logout (UI actions).
* Allows language preservation in professional interface.
* Closes #1220.
To create cypress tests for the collections.
To improve existing tests.
* https://github.com/rero/rero-ils-ui/pull/404
- What should I test through the …

cypress: create test for collections

---

rero_ils/permissions.py
tests/data/data.json

A system librarian should have all the librarian rights.
* Removes the librarian role to the system librarian of Martigny in the
test fixtures to test this specific case.
* Closes #1340.

permissions: fix system librarian role only

---

rero_ils/accounts_views.py
rero_ils/config.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/permissions.py
tests/api/test_user_authentication.py
tests/unit/conftest.py
tests/unit/test_patrons_jsonschema.py

* Uses patron permissions without http request.
* Adds a custom invenio-accouts change password API to allow a librarian
to change a password for a patron.
- Implements https://tree.taiga.io/project/rero21-reroils/us/1659
* https://github.com/rero/rero-ils-ui/pull/411
- Test with the rero-ils-ui related PR.

login: add a change password API

---

rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json

* Fixes editor error when the patron role is selected.
- The patron editor crash if the patron role is selected.

patrons: fix patron editor

---

rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/models.py
tests/api/collections/test_collections_api.py
tests/api/holdings/test_patterns.py
tests/ui/holdings/test_holdings_patterns.py
tests/ui/items/test_items_api.py

A new late status is added to the issue JSON schema
to manage claims.
The system now saves the creation date of the issue status.
If an issue changes its status, the field
item.issue.status_date is set to current timestamp.
In the public interface, only the received issues
are shown.
* Tests are updated accordingly.
https://tree.taiga.io/project/rero21-reroils/us/1544?milestone=275632
My PR depends on the following `rero-ils`'s PR(s):
`reroils.v0.14`
1-`bootstrap + setup`
2- in the pro interface locate the journal `Art passions : [revue d'art et de culture]`.
3- edit any of its issues and move it to the status `late` instead of `received`
4- go to the public interface, and display the same journal. you should not find the issue displayed there. …

serials: manage late issues

---

.github/workflows/continuous-integration-test.yml

* Uses `actions/setup-node@v1` to force the npm version for all github
actions tests.

tests: force npm version for github actions

---

rero_ils/modules/patrons/api.py
tests/api/patrons/test_patrons_rest.py

The method to retrieve patrons without valid subscriptions doesn't
works as expected. Each day, a new subscription will be added for all
patrons linked to patron_type requiring a subscription, even if they
have a valid one.
This commit fixes this problem.
Closes rero/rero-ils#1317

patrons: fix subscriptions renewal problem.

---

rero_ils/modules/documents/templates/rero_ils/_documents_get.html
rero_ils/modules/documents/views.py
rero_ils/modules/loans/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_loans.html
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_requests.html
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/utils.py
rero_ils/modules/patrons/views.py
rero_ils/static/scss/rero_ils/styles.scss
tests/api/circulation/test_borrow_limits.py
tests/api/documents/test_documents_rest.py
tests/api/patrons/test_patrons_blocked.py
tests/api/test_availability.py
tests/ui/documents/test_documents_filter.py

If the patron can't operate an action due to circulation restrictions
(patron blocked, patron type limits, ...), circulation buttons should be
hide. In the patron profile view, adds warning/error messages depending
of patron restrictions.
Closes rero/rero-ils#1357
Closes rero/rero-ils#1356

circulation: hide buttons if action isn't available.

---

rero_ils/modules/items/api/circulation.py
tests/ui/circulation/test_actions_checkin.py

Fixes a bug when checking in an on_shelf or in_transit item (with no
loans) that did not receive the correct item status.
* Closes #1334

circulation: check in an item with no loans

---

rero_ils/modules/items/api/circulation.py

* Removes the time from the due date.
* Closes #1398.
To fix the issue #1398.
* N/A
See issue description

document: fix due date in detailed view

---

rero_ils/modules/patron_transaction_events/api.py
tests/api/test_patron_payments_rest.py

The bit representation of real number
(https://en.wikipedia.org/wiki/IEEE_754) cause problem with arithmetic
operation on them (10-9.54 = 0.460000000000085). This commit fixes this
problem by multiplying transaction amount by 100 and cast them into
integer when arithmetic operations are done.
Closes rero/rero-ils#1373

transactions: fix paid fees still opened

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/views.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_head.html
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_personal.html
tests/api/test_availability.py

In the public interface, when an item is "on loan" the due date
displayed contains the time. The time information isn't necessary to be
displayed.
The birth date should not be displayed in the patron profile view in the
public interface.
Closes rero/rero-ils#1398
Closes rero/rero-ils#1386
Closes rero/rero-ils#1385

public ui: improve displayed information

---

data/users.json
rero_ils/accounts_views.py
rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/cli.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/permissions.py
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_ill_requests.html
rero_ils/modules/patrons/utils.py
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
rero_ils/permissions.py
rero_ils/templates/rero_ils/forgot_password.html
scripts/setup
tests/api/notifications/test_notifications_rest.py
tests/api/patrons/test_patrons_rest.py
tests/api/test_user_authentication.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/documents/test_documents_api.py
tests/ui/notifications/test_notifications_api.py
tests/ui/patrons/test_patrons_api.py
tests/ui/test_api.py
tests/unit/conftest.py
tests/unit/test_patrons_jsonschema.py

- https://tree.taiga.io/project/rero21-reroils/us/1659?milestone=275632
https://github.com/rero/rero-ils-ui/pull/411
- Test all features described in the US. "fabiano" has no email anymore.
- This should also close
- https://github.com/rero/rero-ils/issues/1340
- https://github.com/rero/rero-ils/issues/1382
- https://github.com/rero/rero-ils/issues/1381
- https://github.com/rero/rero-ils/issues/1364
* Renames `PidAlradyUsed` to `PidAlreadyUsed` exception.
* Changes the email validation message in several resources.
* Fixes update email value from the professional user editor.
* Adds a `append` option to the user creation script. This force to
increment the PID counter and avoid error for new patron creation.
* Make the user email required when the librarian or system librarian
role is …

patrons: manage patrons without e-mail

---

data/patterns.json
data/vendors.json
rero_ils/config.py
rero_ils/modules/documents/templates/rero_ils/_documents_get.html
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/listener.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/serializers/json.py
rero_ils/modules/items/tasks.py
rero_ils/modules/vendors/api.py
scripts/setup
setup.py
tests/data/holdings.json
tests/fixtures/metadata.py
tests/ui/holdings/test_serial_claims.py
tests/unit/test_holdings_jsonschema.py
tests/unit/test_items_jsonschema.py

Adds a daily job to:
1. Change the issue status to LATE for all expected
issues when the expected date is passed.
2. Change the issue status to CLAIMED for LATE issues
when the corresponding holdings record has a valid vendor
with an email address and max_number_of_claims is not reached.
2.1. Change the issue status to CLAIMED for all LATE
issues when the days_for_first_claim is passed.
2.2. Increment the claims_count field for all CLAIMED
issue if the days_for_next_claim passed.
The job is scheduled to run every midnight.
* Improves inheritance between the Item, ItemIssue classes.
* Closes #1437
* Closes #1435
* Create tests and fixtures accordingly.
https://tree.taiga.io/project/rero21-reroils/task/1834?kanban-status=1224894
`bootstap + setup` …

serials: manage serial claims

---

data/templates.json
rero_ils/modules/holdings/api.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
tests/ui/holdings/test_holdings_patterns.py

With this commit, the complete list of patterns templates
is added. The most used patterns are now available
for all librarians of all organisations.
The issue expected_date is exposed to the jinja2 templates
and can be used in whole or by day, month and year to format
the issue chronology and enumeration.
Co-Authored-by: Sarah Badr <sarahbadr.ch@gmail.com>
`setup`
- take a look at the new holdings templates and try to use some of them
- In the `holdings.patterns.template`, you can now use the fields `expected_date.day`,
`expected_date.month`, …

templates: create new holdings templates

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json

Fixes issues when the vendor field in the
holdings record is mandatory (it shouldn't).
Removes the old patterns default values from
the holdings editor.
Adds placeholders for the patterns fields of the
holdings record.
Co-Authored-by: Nicolas Prongué <nicolas.prongue@rero.ch>

holdings: make vendor field optional

---

rero_ils/modules/patrons/views.py

* Fixes the translation of the patron profile link in menu by loading the menu at each app
request, not only the first time.
* Closes #1283.
To close issue mentioned above.
N/A
See issue description

frontpage: fix patron profile link translation 

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/locations/api.py

* Adds the 'request denied'  message to the string to translate.
* Adds note types (label AND value) to the string to translate.
* Closes #1367.
* Closes #1319.
TO close issues mentioned above.
N/A
See issues description

ui: fix translation issues

---

.github/workflows/continuous-integration-test.yml

* Fixes poetry install in github actions.
Unable to process command '##[add-path]/home/runner/.poetry/bin' successfully.
The `add-path` command is disabled. Please upgrade to using Environment Files or
opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS`
environment variable to `true`. For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

CI: fix github actions

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json

Fixes a problem when the title of the fields
location, circulation category and electronic_location
where displayed twice in the holdings editor.
Fixes a problem when librarian can not deselect the
vendor field in the holdings editor.
* Closes #1452
* Closes #1451
https://tree.taiga.io/project/rero21-reroils/task/1865?kanban-status=1224894

holdings: remove extra titles for some fields in editor

---

rero_ils/dojson/utils.py
tests/unit/test_documents_dojson.py

In the build_responsibility_data function, the square brackets [] are no
more considered as trailing punctuation to be removed.
* Closes #1406.
To fix the issue mentioned above.
* N/A
see issue description

data: fix responsibilityStatement conversion

---

rero_ils/config.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
tests/ui/patrons/test_patrons_api.py

* Fixes patron creation with an existing user account, closes #1454.
* Ensures that when the patron updates his/her email in the RERO ID, the
modification is synched to the patron record, closes #1458.
* Makes the email required if the communication channel is email, closes #1455.
- To fix issues for the release 0.14.1.

patrons: fix patron creation and modification

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json

Sets the note minimum length of holdings, patron and item to 1 instead
of 3 characters, to allow libraries to use notes as codes for some
internal uses cases.
https://tree.taiga.io/project/rero21-reroils/task/1880?kanban-status=1224895
You can not add holdings/patron/item notes  of size `1`

notes: allow notes of short size

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json

For migrating records from Virtua: Sets the
minimum length of the following fields to 1 character:
* patron.city
* patron.postal_code
* patron.street
* item.barcode
https://tree.taiga.io/project/rero21-reroils/task/1884?kanban-status=1224895

data: set several minLength to 1

---

rero_ils/modules/collections/views.py
tests/data/data.json
tests/fixtures/organisations.py
tests/ui/collections/test_collections_ui.py

* Corrects the preparation of the data to be displayed in the public view.
This was generating an internal server error.
* Adds tests to check the redirection to the detailed view.
* Closes #1481.
To solve an issue reported during the test of v0.14
N/A
Check https://localhost:5000/aoste/collections/3

collection: fix public view

---

rero_ils/modules/loans/api.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
tests/ui/loans/test_loans_api.py

A new boolean `keep_history` field is added to patron record to either
maintain circulation transaction history for the last 6 months or to
anonymize the transaction once it is concluded.
A loan is considered concluded if it is in the ITEM_RETURNED or
CANCELLED state and has no open patron transactions (fees).
A new field added to the loan record `to_anonymize` to set the record to
be anonymized.
https://tree.taiga.io/project/rero21-reroils/us/1422?milestone=277700
./run_tests.sh

users: set whether to keep loan history or not

---

rero_ils/views.py

In the menu of the public interface, it exists a 'menu' entry. This
entry list all available languages for the application. This commit
renamed the entry menu using the current language and change the icon
linked to this menu entry
Closes rero/rero-ils#1466

menu: update the language menu entry

---

rero_ils/modules/documents/jsonschemas/documents/document_color_content-v0.0.1.json
rero_ils/modules/items/api_views.py
rero_ils/modules/items/decorators.py
tests/api/circulation/test_borrow_limits.py

Sometimes, restrictions can disallow to execute a circulation operation.
Adding the "override_blocking" parameter to the API url allows to bypass
all restrictions.

circulation: allow overriding exception

---

tests/e2e/cypress/cypress/integration/application/test-login-logout.spec.js
tests/e2e/cypress/cypress/integration/circulation/scenario-a.spec.js
tests/e2e/cypress/cypress/integration/circulation/scenario-b.spec.js
tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
tests/e2e/cypress/cypress/integration/templates/templates-test.spec.js

* Adapts circulation scenarios tests according to new HTML template.
* Adds an alias to wait for schemaform loading before the population of
the document editor.
To fix some tests that are broken after release v0.14.0.
* https://github.com/rero/rero-ils-ui/pull/435
Checkout  https://github.com/rero/rero-ils-ui/pull/435 and dev of ng-core locally
`poetry run bootstrap`
`poetry run setup`
`poetry run folding -c path/to/rero/ng-core -u path/to/rero/rero-ils-ui`
`FLASK_DEBUG=False poetry run server -n`
`poetry run cypress`

tests: fix Cypress tests after v0.14.0

---

rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json

* Improves title and description of dates in provision activity.
* Closes #1424.
To close issue mentioned above.
N/A
See issue description.

document: improve provision activity date fields

---

rero_ils/config.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/utils.py
rero_ils/modules/utils.py
tests/api/circulation/test_actions_views_extend_loan_request.py

Closes rero/rero-ils#1470
If a circulation policy disallow checkout operation, the error message
returned was not user friendly. This commit add a check for checkout
operation on cipo; this check return a better error message.
Closes rero/rero-ils#1383
If a patron is blocked for any reasons, this user couldn't extend any
active loan.
Closes rero/rero-ils#1507
Fixes 'status' facet problem on items result list. Despite if user
choose a status to faceting the results, the facet value didn't apply.

circulation: add control on circulation operation

---

rero_ils/permissions.py

When a user that doesn't have the patron, librarian or system librarian
role, the message "Permission required" is displayed instead of
"Internal server error".
* Closes #1508

permissions: fix error message for users

---

pyproject.toml
rero_ils/modules/loans/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/patrons/templates/rero_ils/_patron_profile_personal.html
rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
tests/data/data.json
tests/ui/loans/test_loans_api.py

* Adds the `keep_history` field to the list of fields editable by the
user in the RERO ID form.
* Adds an 'edit' button to allow user to edit his profile from the
Personal data tab.
* Anonymizes loans once the patron sets the field keep_history to false.

users: allow to edit keep_history setting

---

rero_ils/modules/items/api/circulation.py
tests/api/circulation/test_actions_views_checkout.py

If a transaction end date is used for a checkout, it's possible that
this date is a business closed date for the related library. In this
case, the transaction end_date will be update on the next open day.

circulation: fix transaction end_date.

---

rero_ils/modules/patrons/templates/rero_ils/_macro_profile.html

Into the patron profile page for 'fees' tab, sometime the document title
linked to a fees was not displayed. This commit improves the management
of document title using the general function `create_title_text` already
used to display the document title into the document detailed view.
Closes rero/rero-ils#1543
- Login as a patron. 
- Go into the patron profile page
- Choose the fees tab
- Check the document title linked to the fee was correctly displayed

patrons: fix document title in the fees tab

---

.gitignore
rero_ils/modules/api.py
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
scripts/russian_dolls
tests/data/data.json
tests/fixtures/organisations.py
tests/ui/circulation/test_inhouse_cipo.py

* Changes minimum checkout duration in the circulation policy JSON
schema to allow 'less than one day' checkouts.
Task 1881 of US1759
https://tree.taiga.io/project/rero21-reroils/us/1759?milestone=277700
N/A
Please do code review only.

circulation: allow 'less than one day' checkout

---

rero_ils/config.py
rero_ils/modules/documents/templates/rero_ils/_anonymous_button.html
rero_ils/modules/documents/templates/rero_ils/_document_online.html
rero_ils/modules/documents/templates/rero_ils/_documents_get.html
rero_ils/modules/documents/templates/rero_ils/_documents_get_book.html
rero_ils/modules/documents/templates/rero_ils/_request_button.html
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/modules/items/api/record.py
rero_ils/modules/local_fields/jsonschemas/local_fields/local_field-v0.0.1.json
rero_ils/modules/patrons/views.py
rero_ils/theme/assets/scss/rero_ils/styles.scss

The layout of the book type no longer shows the holdings structure.
The buttons have been aligned vertically below the data.
* Closes #1399.
- Check book layout and serial layout.
- Check order (sort by library pid and location pid)

documents: group holdings by libraries

---

data/users.json
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
tests/api/patrons/test_patrons_rest.py
tests/fixtures/circulation.py
tests/ui/patrons/test_patrons_api.py

* Makes the main address email optional if patron communication channel
is email and the additional address email is defined.
* Adds a backend custom validation for this specific case.
* Closes #1499.

users: allows the 2nd email to be the only one

---

rero_ils/modules/documents/templates/rero_ils/_documents_get.html

In the 'get' tab from document detailed view, the item call number was
included into a too large column. It caused a display problem because
label and data were splitted in two separate lines.

document: fix call number display.

---

tests/e2e/cypress/cypress/fixtures/cipo.json
tests/e2e/cypress/cypress/fixtures/documents.json
tests/e2e/cypress/cypress/fixtures/item_types.json
tests/e2e/cypress/cypress/fixtures/items.json
tests/e2e/cypress/cypress/fixtures/patron_types.json
tests/e2e/cypress/cypress/fixtures/users.json
tests/e2e/cypress/cypress/integration/circulation/scenario-a.spec.js
tests/e2e/cypress/cypress/integration/circulation/scenario-b.spec.js
tests/e2e/cypress/cypress/integration/circulation/test-on-site-cipo.spec.js
tests/e2e/cypress/cypress/integration/editor/ci-po/create-ci-po.spec.js
tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
tests/e2e/cypress/cypress/integration/examples/example-test-request.spec.js
tests/e2e/cypress/cypress/support/api.js
tests/e2e/cypress/cypress/support/cipo.js
tests/e2e/cypress/cypress/support/circulation.js
tests/e2e/cypress/cypress/support/index.js
tests/e2e/cypress/cypress/support/navigation.js
tests/e2e/cypress/cypress/support/record.js
tests/e2e/cypress/cypress/support/utils.js

* Adds a test to control that the 'zero day checkout' works correctly.
* Adds a test to check the creation of a circulation policy.
To create cypress tests on cipo editor.
* https://github.com/rero/rero-ils-ui/pull/469

 tests: write cypress tests to check 0 day checkout

---

scripts/bootstrap
scripts/cypress
tests/e2e/cypress/cypress/integration/circulation/scenario-b.spec.js
tests/e2e/cypress/cypress/integration/editor/ci-po/create-ci-po.spec.js
tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
tests/e2e/cypress/cypress/integration/examples/example-test-request.spec.js
tests/e2e/cypress/cypress/integration/templates/templates-test.spec.js
tests/e2e/cypress/cypress/support/navigation.js
tests/e2e/cypress/package-lock.json
tests/e2e/cypress/package.json

* Updates Cypress to version 6.1.0.
* Replaces cy.route by cy.intercept because it is deprecated.
* Adds a parameter to cypress script in order to allow the update of
Cypress (-r or --reinstall).
* Corrects a typo in bootstrap script.
* Improves some tests.
Updates Cypress to v6.1.0 and adapts test consequently.
* https://github.com/rero/rero-ils-ui/pull/469
* Checkout dev of ng-core and PRs of rero-ils and rero-ils-ui locally
* `poetry run folding -c path/to/rero/ng-core -u path/to/rero/rero-ils-ui`
* `poetry run bootstrap`
* `poetry run setup -C`
* `FLASK_DEBUG=False poetry run server -n`
* `poetry run cypress -r` (this will update Cypress and launch the tests)

tests: update cypress

---

rero_ils/modules/documents/templates/rero_ils/_documents_get.html

Aligns the login button (displayed on document detailed view, when users
are not yet connected) to the right of the screen to improve it
visibility and aligns it with other buttons (request, extend).
Closes rero/rero-ils#1473

documents: increase login button visibility

---

rero_ils/modules/collections/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/serializers/csv.py
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/utils.py
tests/ui/holdings/test_holdings_api.py
tests/ui/holdings/test_holdings_patterns.py

For items of type `issue`, the parent holdings first call_number is
displayed when the item has no first call_number. This call number is
inherited in the following screens in the public interface:
* Document details view.
* Patron profile: loans, requests, history tabs.
* Collection details view.
*  Late issues and inventory CSV exports.
* Generated notifications.
* Closes #1288.
https://tree.taiga.io/project/rero21-reroils/task/1896?kanban-status=1224894

items: inherit holdings first call_number

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json

Set the barcode field as not required field. If an item is
created/updated without barcode, the backend will generated a fictive
barcode itself.
Closes rero/rero-ils#1287
Closes rero/rero-ils#1565
- receive an serial issue in the UI interface (not using quick recieve)
- don't fill the barcode field
- change any other field in the form
- save the item
- check the created item has a fictive barcode ("f-2021....")

items: improve automatic barcode generation

---

.github/workflows/stale.yml

* Exempted label should be a well formatted list.
- Fixing an issue with the YAML format: [see warning][1] 
[1]: https://github.com/rero/rero-ils/runs/1701028205?check_suite_focus=true#step:2:1

gh actions: fix wrong yaml format in stale worflow

---

.github/workflows/stale.yml

* Adds a trailing 's' to exempt_issue_labels and exempt_pr_labels.
- To fix wrong settings labels in the stale.yml file. 
- Check changes.
- The action has been tested on my repo: https://github.com/iGormilhit/rero-ils/actions?query=workflow%3A%22Mark+stale+issues+and+pull+requests%22

gh-actions: fix wrong label in stale workflow file

---

rero_ils/config.py
rero_ils/modules/ext.py
rero_ils/modules/operation_logs/jsonresolver.py
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/operation_logs/listener.py
rero_ils/modules/operation_logs/mappings/v7/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/operation_logs/permissions.py
rero_ils/modules/patrons/views.py
tests/data/data.json
tests/fixtures/metadata.py
tests/ui/test_monitoring.py
tests/unit/conftest.py
tests/unit/test_operation_logs_jsonschema.py

* Adds configuration to enable the capture of operation by resource.
* Renames field operation_log.type to operation_log.operation.
* Adds listener to add operation_log after record creation.
* Adds units testing.
Additional commit will be added to complete this work, this is only to
allow @Garfield-fr to start the UI development.

operation_logs: capture operation after record creation

---

poetry.lock
pyproject.toml
rero_ils/config.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/api_views.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/tasks.py
rero_ils/modules/loans/cli.py
rero_ils/modules/loans/utils.py
rero_ils/modules/notifications/utils.py
tests/api/circulation/test_temporary_item_type.py
tests/api/test_tasks.py
tests/ui/circulation/test_inhouse_cipo.py
tests/ui/items/test_items_api.py

If a temporary item_type is defined and valid on an item, it must be
used for circulation operation (checkout, extend, renew).

items: use temporary item_type for circulation

---

rero_ils/modules/documents/listener.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json

The following holdings fields are now indexed in the document index in
order to allow search requests on holdings data:
* holdings.call_number
* holdings.second_call_number
* holdings.index
* holdings.enumerationAndChronology
* holdings.supplementaryContent
* holdings.notes
https://tree.taiga.io/project/rero21-reroils/task/1969?kanban-status=1224895
- now you can locate a document by searching for its holdings.enumerationAndChronology or any other fields listed above.

documents: add to index some holdings fields

---

rero_ils/modules/documents/views.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/query.py

Enable longmode for holdings editor, the following
fields are by default displayed for new records:
* holdings.location
* holdings.circulation_category
* holdings.call_number
* holdings.EnumerationAnyChronology
* holdings.vendor
* holdings._masked
`note`:  the `masking` functionality will be completed after merging the refactoring of holdings/items
and implementing the `complete item record` user story.
https://tree.taiga.io/project/rero21-reroils/task/1970?kanban-status=1224895
https://tree.taiga.io/project/rero21-reroils/task/1970?kanban-status=1224895
Only few fields are available when creating new holdings record:

holdings: exlcude masked holding from public interface

---

rero_ils/modules/libraries/api.py
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
tests/api/circulation/test_temporary_item_type.py
tests/ui/circulation/test_inhouse_cipo.py

Fixes the test 'test_less_than_one_day_checkout'. If the test was
executed when the library is closed, the test failed ; So to fix this
problem, we freeze the transaction date to an opening day/hour.
Fixes the function `library.next_open()` function. This function didn't
care about hour/minutes.

test: fix test in house

---

rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/record.py

* Allows to:
* Attach holdings of serial type to any type of document.
* Attach holdings of standard type to document of type journal.
* Attach items of standard type to holdings of type serial.
* Closes #1612
https://tree.taiga.io/project/rero21-reroils/task/1883?kanban-status=1224895

holdings: attach serials to non-serials documents

---

data/circulation_policies.json
rero_ils/modules/circ_policies/api.py
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/circ_policies/mappings/v7/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/tasks.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/selfcheck/api.py
tests/api/circulation/test_borrow_limits.py
tests/api/loans/test_loans_rest.py
tests/api/notifications/test_notifications_permissions.py
tests/api/notifications/test_notifications_rest.py
tests/api/selfcheck/test_selfcheck.py
tests/api/test_tasks.py
tests/data/data.json
tests/fixtures/circulation.py
tests/unit/test_circ_policies_jsonschema.py

* Updates the `CirculationPolicy` resource JSON schema to allow multiple
reminders and incremental overdue fees.
* Updates data & fixtures.
* Updates unit test.
* Adapts/improves related code.

circulation: allows multiple reminders and overdue fees

---

rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
tests/api/holdings/test_patterns.py

Previously, a holdings is considered of type serial
if it is attached to document of type journal. With
this commit, if the holdings has the holdings_type =
serial, it is considered a serial holdings.
* Adapts units testing
* Shortens the title of the holdings fields, template and patterns
* Makes the fields EnumerationAndChronolgy as textarea

holdings: fix is_serial definition

---

rero_ils/config.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/libraries/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/cli.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/tasks.py
rero_ils/modules/utils.py
tests/api/test_tasks.py
tests/data/data.json
tests/ui/loans/test_loans_api.py
tests/unit/test_circ_policies_jsonschema.py

Initially, the task to create notification is only able to create one
DUE_SOON and one OVERDUE notifications. Improves this task to allow it
to all necessary notification not yet sent on a loan.
Adds a new parameter for the task method allowing to simulate the
execution of this task for a given timestamp.

notification: improve notification creation task

---

rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
rero_ils/modules/patrons/views.py
rero_ils/theme/assets/scss/rero_ils/styles.scss
rero_ils/theme/templates/rero_ils/header.html
rero_ils/theme/views.py

* Removes the RERO ID menu.
* Adds a "My Account" menu, which is the patron profile for patron and
invenio users for others.
* Removes breadcrumbs in the profile settings view.

public ui: merge profile menu entries

---

data/circulation_policies.json
rero_ils/config.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/circ_policies/mappings/v7/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api_views.py
rero_ils/modules/loans/cli.py
rero_ils/modules/loans/utils.py
tests/api/items/test_items_rest.py
tests/data/data.json
tests/e2e/cypress/cypress/fixtures/cipo.json
tests/e2e/cypress/cypress/support/cipo.js
tests/ui/loans/test_loans_api.py
tests/unit/test_circ_policies_jsonschema.py

Removes the `allow_checkout` field from circulation policy JSON schema.
This data is redundant with the `checkout_duration` data ; if a cipo
resource defines a `checkout_duration` data (even if duration is 0),
then the checkout is allowed, otherwise, when data is missing from
resource, the checkout is disallowed.

cipo: remove `allow_checkout` field

---

rero_ils/config.py
rero_ils/modules/circ_policies/views.py
rero_ils/modules/decorators.py
rero_ils/modules/documents/views.py
rero_ils/modules/item_types/views.py
rero_ils/modules/notifications/views.py
rero_ils/modules/patron_types/views.py
rero_ils/modules/patrons/views.py
tests/api/circ_policies/test_circ_policies_rest.py
tests/api/item_types/test_item_types_rest.py
tests/api/notifications/test_notifications_rest.py
tests/api/patron_types/test_patron_types_rest.py

Creates an API entry point to list all templates available for
notification creation. Only template directories containing files
according to the configuration setting will be considerate as valid.
- call `https://localhost:5000/notifications/templates/list` url (logged as librarian/syslib)

notification: create list of template API.

---

rero_ils/config.py
rero_ils/modules/circ_policies/views.py
rero_ils/modules/decorators.py
rero_ils/modules/documents/views.py
rero_ils/modules/item_types/views.py
rero_ils/modules/notifications/views.py
rero_ils/modules/patron_types/views.py
rero_ils/modules/patrons/views.py
tests/api/circ_policies/test_circ_policies_rest.py
tests/api/item_types/test_item_types_rest.py
tests/api/notifications/test_notifications_rest.py
tests/api/patron_types/test_patron_types_rest.py

Creates an API entry point to list all templates available for
notification creation. Only template directories containing files
according to the configuration setting will be considered as valid.

notifications: create an API to list templates

---

rero_ils/accounts_views.py
rero_ils/modules/views.py
tests/api/conftest.py
tests/api/test_users.py

* Adds a new API `/api/user_info/<username_or_email>` to get the
information of a potential future patron or professional.
- To implement: https://tree.taiga.io/project/rero21-reroils/us/1889?milestone=282105
- Register a new user from the web interface and fill all the profile fields: firstname, lastname, ...
- Connect using a librarian and try: https://localhost:5000/api/user_info/<username_or_email>

users: add user info API

---

rero_ils/modules/patron_transaction_events/mappings/v7/patron_transaction_events/patron_transaction_event-v0.0.1.json
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_transactions/listener.py
tests/api/patron_transactions/test_patron_transactions_rest.py

At this time, all PatronTransaction are either linked to a Notification,
either linked to a Patron (for subscription). But the future incremental
fees will not be linked to a Notification but need to be linked to a
Loan. Updates the JSON schema to allow a PatronTransaction to be
directly linked to a Loan resource.

patron transactions: allow to link to a loan

---

rero_ils/modules/documents/views.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/api_views.py
rero_ils/query.py
tests/api/holdings/test_holdings_rest_api.py
tests/data/data.json
tests/data/holdings.json

* Hides masked holdings from public interface.
* Indexes parent document after holdings updates.
* Adapts units testing.

holdings: fix several bugs related to version 1.0.0

---

rero_ils/modules/items/api/record.py
rero_ils/modules/items/tasks.py

When an issue is created withe item editor (slow received), the holding
was updated but not committed into the DB.
Closes rero/rero-ils#1696

items: fix holding update when receiving an issue

---

rero_ils/modules/items/cli.py

* Fixes the error `KeyError: 'subtype'` generated at the creation
of small and big item files.
error when running `setup --create_items_holdings_small --continue`
```
return callback(*args, **kwargs)
File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/items/cli.py", line 173, in create_items
for item, holding in generate(count, itemscount, missing):
File "/Users/baa/devel/rero/rero-ils/rero_ils/modules/items/cli.py", line 114, in generate
is_ebook = doc_type[0]['subtype'] == 'docsubtype_e-book'
KeyError: 'subtype'
```

documents: fix bug when generating the big and small items

---

rero_ils/modules/ill_requests/permissions.py

If the current user had role librarian AND role patron, it couln't
view/edit an ILL requests into the admin interface.
Closes rero/rero-ils#1709.

ILL request: fix permissions

---

rero_ils/modules/documents/templates/rero_ils/_document_online.html
rero_ils/modules/documents/views.py
rero_ils/modules/holdings/api.py
rero_ils/theme/assets/scss/rero_ils/thumbnail.scss
tests/data/data.json
tests/data/holdings.json
tests/fixtures/metadata.py
tests/ui/holdings/test_holdings_api.py

The enumeration and chronology optional fields are only allowed for serial holdings type.
For electronic holdings type, we need these fields too.
* Adapts extended validation for holdings resource.
* Updates jinja filter.
* Adapts template for online documents.
* Writes some tests.
* Fixes thumbnail overflow on document detail view.

holdings: allow optional fields for electronic holdings

---

pytest.ini
rero_ils/modules/patrons/api.py
tests/api/circulation/test_actions_views_extend_loan_request.py
tests/api/documents/test_documents_rest.py
tests/api/patrons/test_patrons_rest.py
tests/conftest.py
tests/fixtures/basics.py
tests/ui/documents/conftest.py
tests/ui/holdings/test_serial_claims.py
tests/ui/item_types/conftest.py
tests/ui/libraries/conftest.py
tests/ui/local_fields/conftest.py
tests/ui/locations/conftest.py
tests/ui/patrons/conftest.py

* Checkout, request and renew circulation operations are blocked if the
patron expiration date is reached.
* Introduces new utils fixtures and adapts unit tests.
* Closes rero/rero-ils#1495.

circulation: block operations for expired patron

---

rero_ils/modules/views.py

The caching for permission API must taking care of query_string. Without
this parameter, `permissions/holdings` and `permissions/holdings/1234`
HTTPS calls use the same cache and the second call return the same
result than the first one.

permissions: correct caching problems

---

data/libraries.json
rero_ils/modules/libraries/api.py
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/templates/email/_patron_address.txt
rero_ils/modules/notifications/templates/email/availability/eng.txt
rero_ils/modules/notifications/templates/email/availability/fre.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/availability/ita.txt
rero_ils/modules/notifications/templates/email/due_soon/eng.txt
rero_ils/modules/notifications/templates/email/due_soon/fre.txt
rero_ils/modules/notifications/templates/email/due_soon/ger.txt
rero_ils/modules/notifications/templates/email/due_soon/ita.txt
rero_ils/modules/notifications/templates/email/others/location_notification.txt
rero_ils/modules/notifications/templates/email/overdue/eng.txt
rero_ils/modules/notifications/templates/email/overdue/fre.txt
rero_ils/modules/notifications/templates/email/overdue/ger.txt
rero_ils/modules/notifications/templates/email/overdue/ita.txt
rero_ils/modules/notifications/templates/email/recall/eng.txt
rero_ils/modules/notifications/templates/email/recall/fre.txt
rero_ils/modules/notifications/templates/email/recall/ger.txt
rero_ils/modules/notifications/templates/email/recall/ita.txt
tests/api/notifications/test_notifications_rest.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/notifications/test_notifications_api.py

* Adds notification settings in library jsonschema and mapping.
* Adds notification settings data.
* For patron with mail communication channel the notification is sent to
the corresponding library email if it exists.
* Closes #913.
To implement task 2012 of US1922 https://tree.taiga.io/project/rero21-reroils/us/1922?milestone=282105
- https://github.com/rero/rero-ils-ui/pull/516

libraries: add notification settings in library definition

---

rero_ils/modules/decorators.py
rero_ils/modules/patrons/views.py
rero_ils/permissions.py
rero_ils/theme/views.py

* Displays the entry "my account" in the public view main menu only for a logged patron.
* Restricts the patron profile view "my account" only to a logged patron.

menu: display "my account" only for a patron

---

rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/listener.py
rero_ils/modules/patron_transactions/mappings/v7/patron_transactions/patron_transaction-v0.0.1.json
tests/api/patron_transactions/test_patron_transactions_rest.py

* Adds the library pid in the patron transaction index if the
transaction is related to a loan.
* Closes #1533.
* https://github.com/rero/rero-ils-ui/pull/552

transaction: add library for patron transactions

---

rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/theme/assets/js/reroils/ills_request.js

* Prevents the enter key to submit the form in some fields that may be
filled though a scanning device.
* Closes #1421.
* rero-ils-ui@dev

editor: prevent the enter key to submit the form

---

tests/ui/loans/test_loans_api.py

The `test_item_loans_elements` unit test doesn't work when the test is
running on a closed date for the library used by the test.

test: fix `test_item_loans_elements` unit test.

---

tests/api/test_external_services.py

tests: fix `test_documents_import_bnf_ean` for pycodestyle

---

rero_ils/config.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
rero_ils/modules/locations/api.py
rero_ils/modules/selfcheck/admin.py
rero_ils/modules/selfcheck/api.py
rero_ils/modules/selfcheck/models.py
rero_ils/modules/selfcheck/permissions.py
rero_ils/modules/selfcheck/utils.py
setup.py
tests/api/selfcheck/test_admin.py
tests/api/selfcheck/test_models.py
tests/api/selfcheck/test_selfcheck.py
tests/fixtures/sip2.py
tests/utils.py

To easiest manage selfcheck user accounts, we separate them from rero-ils users.
* Adds separate table to store selfcheck users.
* Adatps loan json schema to store terminal id on creation.
* Adds command into Dockerfile to install sip2 module.

sip2: implements selfcheck user accounts

---

poetry.lock
run-tests.sh

* Adds `safty` command in the `run-tests` script as it has been
accidentally removed.

security: update dependencies

---

rero_ils/modules/contributions/views.py

* Restores the format syntax instead of the f-string, because babel
does not support it, thus failing in extracting the strings.
- Because the message extraction is broken on the `dev` branch.
- Try to extract the translation strings.

translations: fix the extraction process

---

rero_ils/query.py

A user with librarian and patron roles can't see the requests information in the item detail view.
This commit adapts search circulation factory to allow that.
* Closes #1839.
- https://github.com/rero/rero-ils/issues/1839

search: fix circulation search factory

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_person-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_identifier-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po

* Work around for a problem in `ngx-formly` with required values in an
object in oneOf: ngx-formly/ngx-formly#2826

documents: fix json schema for identifier

---

rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json

An incremental fee limit are define by thee fields : from, to and cost.
The 'from' field minimum value must be upper or equal to 1.
Closes rero/rero-ils#1848.

Circulation category: limit fee 'from' day interval field

---

rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
scripts/setup

Some parts of the document title are already indexed (main title,
subtitle) because there are mapped into the '_text' ES field. But other
parts are not indexed (only include in ES for dump) including the host
document title. This PR includes all not yet indexed title parts into a
new indexed field.
Closes rero/rero-ils#1788.
- Search about "sept clef du pouvoir"
- You should find the main book and also the child "Samedi suprême"

Document: add host document title into index

---

rero_ils/modules/vendors/api.py
tests/api/vendors/test_vendors.py

vendors: restrict deletion

---

rero_ils/modules/contributions/templates/rero_ils/_contribution_by_source.html
rero_ils/modules/contributions/templates/rero_ils/_contribution_by_source_data.html
rero_ils/modules/contributions/templates/rero_ils/_contribution_unified.html
rero_ils/modules/contributions/templates/rero_ils/detailed_view_contribution.html
rero_ils/modules/contributions/templates/rero_ils/macros/contribution.html
tests/fixtures/metadata.py
tests/ui/contributions/test_contributions_ui.py

* Restores the contribution Jinja templates detailed view.

contributions: restore missing Jinja templates

---

poetry.lock
pyproject.toml
rero_ils/modules/cli.py
rero_ils/modules/patrons/cli.py
scripts/setup

* Adds `users_validate` cli for user fixture file validation.
` poetry run invenio utils users_validate ./data/users.json``

users: validate records through a CLI

---

rero_ils/modules/selfcheck/api.py
tests/api/selfcheck/test_selfcheck.py

There was a mistmatch in the parameters of the methods for checkin and checkout.
* Uses selfcheck terminal information to process checkin/checkout.

selfcheck: fix checkin/checkout action

---

poetry.lock
pyproject.toml

* Forces Flask version to < 2.0.0.
- Fix tests (gh-actions)

tests: constrain the Flask version to fix tests

---

data/templates.json
rero_ils/modules/templates/mappings/v7/templates/template-v0.0.1.json
tests/data/data.json
tests/ui/templates/test_templates_api.py

template: allow to user `type` field into templates

---

rero_ils/modules/cli.py

* The `wait_empty_tasks` had to be change because of celery version changes.

cli: fix wait_empty_tasks

---

rero_ils/modules/ill_requests/views.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/utils.py
rero_ils/theme/views.py

* The "ILLRequest form" user menu entry is now only visible if the
current logged user has the `patron` role.
* Closes rero/rero-ils#1895.

circulation: restrict ILL request form to patron

---

rero_ils/modules/holdings/api_views.py
rero_ils/modules/items/api/api.py
rero_ils/modules/items/listener.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/models.py
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/csv.py
rero_ils/modules/items/views/__init__.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/items/views/rest.py
rero_ils/modules/loans/api_views.py
setup.py
tests/api/test_serializers.py

The CSV export of the inventory list has an important waiting time.
With this commit, we try to improve the response time.
* Uses ciso8601 to parse date fields instead `format_date_filter`.
* Adds new api endpoint for inventory list.
* Uses streaming to process download csv file.
* Uses bunch request to reduce elasticsearch calls.
* Adds some fields in csv file.
* Closes #1456.
* Closes #1329.
- Which issue does it fix? #1456
My PR depends on `rero-ils#<xx>`'s PR(s):
* rero/rero-ils-ui#576
* rero/ng-core#384

items: improve response time for csv export

---

rero_ils/modules/libraries/api.py

* Use `datetime.now()` as default value in function argument cause
problem because the value is compute once, when code is compile. So
the date keeps same value until the app is reloaded.
* Closes rero/rero-ils#1954.

circulation: fix fees calculation

---

rero_ils/modules/contributions/views.py

* Removes `{prefix}{key}`, `{prefix}{item}` and `{prefix}{data}` from
translations.

translations: fix minor issues

---

rero_ils/modules/items/api/api.py

If a collection not define a 'description' field, the item serializer
generate an error. This error cause a javascript failure when UI try to
display the item brief view related to this collection.
Closes rero/rero-ils#1942.

collections: fix item brief view.

---

rero_ils/modules/items/api/issue.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/models.py

* Ensure than the issue.status_date field is update when an issue is created/updated.
* Closes #1654.

serials: fix issue.status_date field update

---

rero_ils/theme/templates/rero_ils/page_wiki.html

* Modifies the flask wiki page template in order to user a wider space
for content.
- To allow flask wiki to use a wider proportion of the available width. 
My PR depends on the following `flask-wiki`'s PR(s):
* rero/flask-wiki#29
- Update flask-wiki (bootstrap).
- Make sure the rero/flask-wiki#29 is merged.
- Open the help section.

wiki: improve flask-wiki integration

---

tests/conftest.py

The tests where using the wrong REDIS for external tests.
* Allows running of external tests without starting of production docker containers.

tests: fix external tests

---

docker-compose.full.yml
docker-services.yml

The restart parameter has been changed to "unless-stopped"
to avoid that containers restart when docker is launched.

docker: change value for restart parameter

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/theme/assets/scss/rero_ils/styles.scss
tests/unit/test_documents_dojson.py

* Moves online resources from the "Descriptions" tab to the header.
* Closes #1722.
- https://github.com/rero/rero-ils/issues/1722
- Check link on header for online resources

documents: improve online access information

---

rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/local_fields/jsonschemas/local_fields/local_field-v0.0.1.json
rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
rero_ils/modules/templates/jsonschemas/templates/template-v0.0.1.json
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json

During the loading of ilspilot it was revealed that additional validation
is needed for the organisation field in all resources. System accepted
bad organisation data mainly for the library resource that prevented users
from logging in. With this commit, organisation field is validated correctly.

resources: improve organisation ref link validation

---

rero_ils/manual_translations.txt

* Translates the username description that comes from
rero/invenio-userprofiles (`validators.py`).
- A string is not extracted and translated because it comes from
rero/invenio-userprofiles. 
My PR depends on the following `rero/invenio-userprofiles`'s PR(s):
* rero/invenio-userprofiles#5
- Check if the string is extracted.

user profiles: translate username description

---

rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json

Updates JSON schemas to enable the `account-select` widget for account
reference field.

acquisition: enable select-account widget config

---

rero_ils/modules/items/api/circulation.py
tests/api/test_availability.py

Masked items must be considerate as not available for circulation
operation and public view.

circulation: masked item are not available

---

scripts/load_testing.py

* Adds a script to test the server with a lot of update request.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>

tests: script to test a lot of update

---

rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/holdings/listener.py
rero_ils/modules/holdings/mappings/v7/holdings/holding-v0.0.1.json
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/listener.py
rero_ils/modules/record_extensions.py
scripts/setup
tests/api/conftest.py
tests/api/documents/test_documents_rest.py
tests/api/holdings/test_holdings_rest.py
tests/data/data.json
tests/data/holdings.json
tests/fixtures/metadata.py
tests/ui/holdings/test_holdings_api.py
tests/unit/test_holdings_jsonschema.py
tests/unit/test_items_jsonschema.py

* Adds the number of items in the holding index.
* Changes the indexing chain to items -> holdings -> documents.
* Fixes test fixtures.
* Removes some useless index flush in the tests.

holdings: add item counts

---

rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
rero_ils/modules/patrons/views.py
scripts/setup
tests/api/patrons/test_patrons_views.py

The patron authenticate api entrypoint allows to return
information about the user according to his username and password.
* Changes the position of the code field in the form.
- use API Rest client and test url (https://localhost:5000/api/patron/authenticate?access_token=xxx)
- method `POST` and Body: `{"username":"xxx", "password":"xxx"}`
xxx = Get token to user `reroilstest@gmail.com`

patrons: allow external service to authenticate users

---

rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/extensions.py
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
tests/api/acq_orders/test_acq_orders_rest.py
tests/data/acquisition.json

* Reindexes the corresponding order when an order line is indexed.
* Adds an invenio records extension to update the total before the
indexing.
* Removes the `total_amount` from the order JSONSchema.
* Adapts the test fixtures.

orders: remove the total amount from the DB

---

rero_ils/modules/documents/jsonschemas/documents/document_title-v0.0.1.json

Adds a validator to make the document `mainTitle` unique (but only in
the UI editor context - not for document REST loading).
Should be use with https://github.com/rero/ng-core/pull/409
Closes rero/rero-ils#1361.

document: make document `mainTitle` unique

---

rero_ils/modules/selfcheck/api.py
rero_ils/modules/selfcheck/utils.py
tests/api/selfcheck/test_selfcheck.py

* Fixes patron address for sip2.
* Uses item barcode instead of item pid.
Lauren-D <laurent.dubois@itld-solutions.be>

sip2: use item barcode instead item pid

---

.github/labeler.yml

* The label *acquisition* is replaced by *acquisitions*.
- To fix and extend the labeler github actions.

documentation: extend the gh-action labeler rules

---

tests/ui/libraries/test_libraries_api.py

Fixes `test_libraries_is_open` unit test : instead to use a dynamic
date, we choose a fixed date. Using dynamic date, we could check an
exception date that fails the test.

tests: fix library `is_open` unit test

---

rero_ils/modules/documents/templates/rero_ils/_documents_description.html
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

* Removes uniform resource locator in description tab.
* Improves uniform resource locator display link on header.

documents: improve display of uniform resource locator

---

rero_ils/config.py
rero_ils/modules/holdings/tasks.py
tests/ui/holdings/test_holdings_api.py

Following the recent changes to the item indexing, the feature
to automatically delete standard holdings with no items is disabled.
This commits puts back the removed logic as a cron job.

holdings: remove standard holdings with no items

---

rero_ils/modules/loans/api.py
tests/api/circulation/scenarios/test_scenario_c.py
tests/api/circulation/test_actions_views_extend_loan_request.py
tests/api/items/test_items_rest.py
tests/api/selfcheck/test_selfcheck.py
tests/ui/circulation/test_actions_extend.py

Sometimes, no loan parameter could be send to `can_extend` method. In
this case, the function skip all checks and return True. Now this
function try to load the loan based on others function arguments to be
more relevant.

circulation: fix `can_extend` check method

---

rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
rero_ils/modules/documents/serializers.py
tests/unit/test_documents_dojson_marc21.py

* Changes xml element `<record>` to `<recordData>`.
* The record type in tag 900 $a and $b are not translated any more.

sru: fix xml format and type

---

rero_ils/modules/acq_invoices/api.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/api.py
rero_ils/modules/documents/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api/record.py
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/api.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patrons/api.py
tests/ui/patrons/test_patrons_api.py
tests/ui/test_monitoring.py
tests/unit/test_documents_dojson.py

core: fix the worng way to update a record 
The way of `invenio-records` has been misunderstood. The `update` method
change only the `dict` value without any db transaction. To push the
transaction on the db, the `commit` method should be called, which is
not the case for the create. The previous implementation called the
validation twice and create two operation logs (create and update) when
a resource was created.
* Avoids multiple validations when a record is created.
* Adds a new `commit` parameter to the update, replace methods in
`ILSRecord`.
* Fixes two operation logs creation when a resource a created, one for
create one for update.
- As it is a core modification it is important to test a bit the resource creation, …

core: fix the wrong way to update a record

---

rero_ils/modules/documents/jsonschemas/documents/document_classification-v0.0.1.json

* The `title` property of `assigner` has a trailing dot, but it should
not.
- To fix a small typo in the document JSON schema. 
- Check changed file.

documents: remove a trailing dot in a title key

---

rero_ils/dojson/utils.py

* Adds º \u00ba to `bookFormat` transformation.

dojson: correct bookFormat transformation

---

poetry.lock
pyproject.toml

Celery version 5.0.6 has following error:
`TypeError: as_task_v2() got an unexpected keyword argument
'ignore_result'`

dependencies: fix celery version to = 5.0.5

---

.github/labeler.yml

* Fixes the wrong path for the fixture label.
* Adds a rule for the monitoring label.
* Adds rules for the public ui label.
* Completes the rule for the data label.
* Adds a rule for the statistics label.
- To fix or extend the gh action labeler rules. 

documentation: fix gh-actions labeler

---

rero_ils/modules/ext.py
rero_ils/modules/templates/listener.py
rero_ils/modules/templates/mappings/v7/templates/template-v0.0.1.json
tests/api/templates/test_templates_rest.py

The template `data` field contains a complete resources structure (
possibly including some other resource reference). This isn't required
into ES and cause some troubles with $ref resolution.

templates: remove `data` field from ES mapping

---

rero_ils/config.py
rero_ils/modules/stats/permissions.py
rero_ils/modules/stats/tasks.py
rero_ils/modules/stats/templates/rero_ils/detailed_view_stats.html
rero_ils/modules/stats/templates/rero_ils/stats_list.html
rero_ils/modules/stats/views.py
rero_ils/theme/views.py
scripts/setup
setup.py

* Adds a stats detailed view.
* Adds a view to see the stats in live.
* Adds a list view for stats.
* Adds a new stats entry in the tools menu for admin user.
* Adds stats admin view permissions.
* Adds a recurrent task to collect the stats every night at 01:00 UTC.
- https://tree.taiga.io/project/rero21-reroils/us/1848?milestone=294722
- bootstrap/setup
- logged in as admin
- select stats in the tools menu
- explore the interface

stats: add an admin views to visualize the stats 

---

rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_admin_metadata-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_dimensions-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_illustrative_content-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_original_language-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_responsibility_statement-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_summary-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_table_of_contents-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_titles_original-v0.0.1.json

The following fields are now in the quick access list:
identifiedBy, contentMediaCarrier, genreForm,
originalTitle, contribution, editionStatement,
seriesStatement, extent, note, originalLanguage,
tableOfContents, summary, illustrativeContent,
subjects, partOf
* Closes #1921.
- Document editor: Check quick access fields

documents: adapt the field list in quick access

---

rero_ils/theme/views.py

* Restores the ILL request menu after the implementation of the
statistics menu available to an administrator. Issue spotted on the
`v1.4.0` release candidate (see #2118).
- To fix the missing ILL request menu.
1. Log in as a patron and check that the ILL request menu is still there.
1. Navigate to an organisation view, and check that the collection menu is
still there.
1. Log in as and administrator and check that the statistics menu is available.

theme: fix missing ILL request menu

---

rero_ils/modules/users/api.py

When a user remove its email and try to save, the email was kept into
DB ; it's now possible to remove user email.

users: allow to save an user without email

---

rero_ils/modules/loans/api.py
tests/api/circulation/test_borrow_limits.py

circulation: fix method for "is loan overdue" check

---

rero_ils/modules/notifications/templates/email/due_soon/fre.txt
rero_ils/modules/notifications/templates/email/recall/fre.txt

notifications: fix email subject

---

rero_ils/modules/item_types/api.py

* Denies the deletion of item type when it's used by any item.
* Closes #2159.

item types: deny deletion with temporary item type

---

rero_ils/modules/patrons/api.py

* Adds user information for `more than one librarian account` problem.

patrons: display user PID in error message

---

rero_ils/config.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/listener.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/templates/email/availability/eng.txt
rero_ils/modules/notifications/templates/email/availability/fre.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/availability/ita.txt
rero_ils/modules/notifications/templates/email/transit_notice/eng.txt
rero_ils/modules/notifications/templates/email/transit_notice/fre.txt
rero_ils/modules/notifications/templates/email/transit_notice/ger.txt
rero_ils/modules/notifications/templates/email/transit_notice/ita.txt
tests/api/loans/test_loans_rest.py
tests/api/notifications/test_notifications_rest.py
tests/data/data.json

* Does not create a request notification when the item is on loan.
* Prevents sending multiple recall notifications.
* Fixes bad notification emails in the tests fixtures.
* Ensures booking notification are always sent.
* Fixes email recipient for transit notice and booking notifications.
* Improves availiblity notification templates.
_Note:_ Fixes A, B, D of #2152.

notifications: fix request and recall

---

rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
tests/unit/test_documents_dojson_unimarc.py

import: fix `subject_imported` field

---

rero_ils/facets.py
rero_ils/theme/templates/rero_ils/search.html

* Adds the `facets` http option support for i18n aggregation to limit
their computation on a given list.
* Fixes the two calls to the document api in the public search view.
- To increase de performances.

search: add an option to limit the `i18n_aggs`

---

rero_ils/modules/operation_logs/cli.py

operation logs: improve `dump_operation_logs` CLI

---

rero_ils/modules/items/serializers/json.py

* Makes the aggragations optional in the rero specific items serializer.

items: make the aggregations optional

---

rero_ils/modules/documents/jsonschemas/documents/document_usage_and_access_policy-v0.0.1.json

The usageAndAccessPolicy field has a type field that is hidden.
You have to set it to a default value to avoid form validation errors.
* Closes #2202.

documents: add default value on hidden type field

---

rero_ils/modules/documents/serializers.py
rero_ils/query.py
tests/api/documents/test_documents_rest.py

* Forces to compute the `organisation` aggregation values when the view
is an organisation view and the `library` aggregation is enable.
* Closes #2215.

public ui: fix missing library facet on org view

---

data/users.json
rero_ils/modules/notifications/dispatcher.py
tests/api/notifications/test_notifications_rest.py
tests/fixtures/circulation.py

* Sends the notification to the patron additional email if exists
instead of the library.
* Closes #2152.
* Adapts the fixtures to have a user with an additional email only.

notifications: fix patron with additional email

---

rero_ils/modules/notifications/templates/email/_patron_address.txt
tests/api/notifications/test_notifications_rest.py

* Adds a patron address block to a printing patron notification.
* Closes #2188.

notifications: fix patron address block missing

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/listener.py
rero_ils/modules/stats/mappings/__init__.py
rero_ils/modules/stats/mappings/v7/__init__.py
tests/api/notifications/test_notifications_rest.py

* Does not send request notification when the item has a temporary item
type with negative availability.
* Closes #2191.

notifications: fix request with temporary item type

---

rero_ils/modules/operation_logs/api.py

* Fixes problem when old record pid is loaded into the operation_log es.

operation_log: replace pid by value for operation_log indexing

---

rero_ils/modules/loans/api.py

* Hides items with a temporary circulation category with negative
availability from the list of requests to be validated.
* Closes #2225.
- Check request list: item with `temporary_item_type` with `negative_availability: true` (In acquisition)

requests: hide non available items from the list 

---

rero_ils/modules/selfcheck/api.py
rero_ils/modules/selfcheck/utils.py

* Sets `institution_id` to the patron organisation `pid`.
* Rounds the fees to cents.
* Fixes patron language, email, phone.
* Removes CR chars `\n`, `\r` from the patron address.
* Adds the `due_date` in a checkout response even if the item has been
already checked out.

selfcheck: fix patron informations

---

rero_ils/modules/contributions/templates/rero_ils/_contribution_by_source.html
rero_ils/modules/contributions/templates/rero_ils/_contribution_by_source_data.html
rero_ils/modules/contributions/templates/rero_ils/detailed_view_contribution.html
rero_ils/modules/contributions/templates/rero_ils/macros/contribution.html

* Removes the link on the RERO identifier.
* Removes the space between documents on the list.

contributions: improve display on detailed view

---

rero_ils/modules/local_fields/api.py
tests/api/local_fields/test_local_fields_rest.py

The validation of the local field forbids to have 2 records
on the same document for the same organization.
* Closes rero/rero-ils#2257
* rero/rero-ils-ui#684
- Check if possible to duplicate record local fields
- Check Display

local fields: improve validation

---

rero_ils/modules/holdings/api_views.py
rero_ils/modules/loans/utils.py
tests/api/items/test_items_rest.py
tests/ui/loans/test_loans_api.py

Checks the owning location `allow_request` property to decide if an item can be requested.
* Closes rero#2234.
* Logs an error and do a db rollback for holding views.
* Fixes tests that failed every two monthes.

circulation: fix request with different locations

---

rero_ils/modules/templates/api.py
rero_ils/modules/templates/extensions.py
tests/api/templates/test_templates_rest.py

template: remove pid from template record

---

rero_ils/modules/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/items/api/api.py
tests/api/items/test_items_issue.py
tests/ui/holdings/test_holdings_patterns.py

* Closes #1720.
Needs adoption in `rero_ils_ui` for confirmation message :
> A confirmation message is displayed before deleting: Do you really want to delete this record? This will also delete all items and issues of the holdings.

holdings: allow deletion of serials holdings

---

data/documents_small.json
rero_ils/modules/cli.py
rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
rero_ils/modules/items/cli.py

* Fixes duplicate documents.
* Corrects `reindex_item` cli.
* Corrects misspelled JsonWriter in `create` cli.
* Recreates `documents_big.json` and `documents_small.json` files.

documents: fix duplicate documents

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py
scripts/bootstrap

release: v1.4.7

---

rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
tests/api/notifications/test_notifications_rest.py
tests/fixtures/circulation.py

* Uses transaction location if pickup location exists any more.

notifications: support pickup location deletion

---

rero_ils/modules/cli.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/listener.py
rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/mappings/v7/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/models.py
rero_ils/modules/notifications/tasks.py
rero_ils/modules/notifications/utils.py
tests/api/circulation/test_borrow_limits.py
tests/api/loans/test_loans_rest.py
tests/api/notifications/test_notifications_rest.py
tests/api/selfcheck/test_selfcheck.py
tests/data/data.json
tests/fixtures/circulation.py

* Adds a new `status` notifications property.
* Cancels a requestion notification when the item is not at desk.
* Cancels a recall, overdue and duesoon notificaition when the item is
not on loan.
* Adds an update mapping utility to update the mapping of an existing
index within new properties.

notifications: add cancel notification

---

rero_ils/modules/circ_policies/api.py
tests/api/test_tasks.py

* Does not send overdue notification if the library is closed between
the end date and the processing date.
* Closes: #2303.

notifications: fix overdue without library open days

---

rero_ils/modules/loans/api.py
rero_ils/modules/loans/logs/api.py
rero_ils/modules/loans/tasks.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/listener.py
tests/ui/loans/test_loans_api.py

* Fixes the anonymization for loans with deleted patrons.

loans: handle loans without patrons

---

rero_ils/modules/loans/api.py
rero_ils/modules/loans/extensions.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
tests/api/loans/test_loans_rest.py
tests/api/test_tasks.py

* Adds a new `due_soon_date` property.
* Computes the due soon loan from elasticsearch.
* Creates a loan extension to put the new due soon property at each
update.
__Note__: need to update the es mapping and do a mass correction for the loan ON_LOAN to update the due_soon_date.

notifications: add due soon date

---

rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/mappings/v7/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/models.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_orders/listener.py
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_orders/models.py
tests/api/acq_order_lines/test_acq_order_lines_rest.py
tests/fixtures/acquisition.py
tests/unit/conftest.py
tests/unit/test_acq_order_lines_jsonschema.py
tests/unit/test_acq_orders_jsonschema.py

* Adds a 'notes' field for AcqOrder resource.
* Adds a 'notes' field for AcqOrderLine resource.
* Improve serialization for AcqOrderLine resource.

acquisition: add notes fields for order/order_line

---

rero_ils/config.py
rero_ils/modules/cli.py
rero_ils/modules/notifications/tasks.py
scripts/setup
tests/data/data.json
tests/unit/test_circ_policies_jsonschema.py

* Removes celery task to process the due soon and overdue notifications.
* Process due soon and overdue just after creation.

notifications: process due soon, overdue almost without delay

---

rero_ils/modules/locations/api.py
tests/api/notifications/test_notifications_rest.py

* If the location is used in an activ loan as pickup or transaction location,
the reeason not to delete is now returned as `links` `loans` `count`.

locations: improve reason not to delete

---

CHANGES.md
RELEASE-NOTES.rst
pyproject.toml
rero_ils/version.py

release: v1.4.9

---

rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/patron_transactions/listener.py
rero_ils/modules/patron_transactions/mappings/v7/patron_transactions/patron_transaction-v0.0.1.json
tests/api/loans/test_loans_delete_item_rest.py
tests/api/loans/test_loans_rest.py
tests/api/patron_transactions/test_patron_transactions_rest.py
tests/ui/items/test_items_api.py

Warning: the PatronTransaction data must be reindexed.
* Adds the item pid when indexing the PatronTransaction record.
* Closes rero#2102
**When integrating this PR, the `PatronTransaction` data must be reindexed**
* rero/rero-ils-ui#688

items: disable the delete action if there is a fee

---

rero_ils/modules/ext.py
rero_ils/theme/templates/rero_ils/footer.html
rero_ils/theme/views.py

footer: fix missing version

---

rero_ils/modules/api.py
rero_ils/modules/documents/serializers.py
rero_ils/modules/libraries/api.py
rero_ils/modules/organisations/api.py

- Check organisation/library facet on all application.

documents: optimize serialization

---

rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/extensions.py
tests/ui/patrons/test_patrons_api.py

Use the `pre_dump` extension hook (from invenio-records) to enrich the
patron data with the related User information. This change allow to use
user information with a specific Patron dumper class.

patrons: improve patron dumping

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/api.py
rero_ils/modules/budgets/api.py
rero_ils/modules/circ_policies/api.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/serializers.py
rero_ils/modules/holdings/api.py
rero_ils/modules/item_types/api.py
rero_ils/modules/items/api/api.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/libraries/api.py
rero_ils/modules/locations/api.py
rero_ils/modules/organisations/api.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/utils.py
rero_ils/modules/vendors/api.py
tests/api/patron_transactions/test_patron_transactions_rest.py
tests/ui/circ_policies/test_circ_policies_api.py
tests/ui/holdings/test_holdings_item.py
tests/ui/items/test_items_api.py

* Adds to the documents `reasons_not_to_delete` function the part of documents count.
* Adds `get_pids` to all `get_links_to_me` functions to get all attached pids or counts.

documents: prevent referenced document deletion

---

rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/extensions.py
tests/api/acq_orders/test_acq_orders_rest.py
tests/api/acquisition/test_acquisition_scenarios.py

* Makes cascade deleting of order lines possible when parent order
status is still PENDING.
https://tree.taiga.io/project/rero21-reroils/task/2281
My PR depends on the US `US_acquisition`

acquisition: delete order and its order lines

---

.github/labeler.yml

- Extends the data label rule to the template resource.
- Excludes the template resource from the public ui label rule.
- Adds a rule for the data-migration label in order to spot changes that
requires migration effort before deploying the next release.
- To extend the github action labeler rules. 
- Check changed file.

documentation: extend labeler rules

---

rero_ils/modules/templates/api.py
tests/ui/templates/test_templates_api.py

the `$ref` from the template data doesn't need to be resolved when the
record is indexed into ES. This should be cause indexing errors if the
related resource doesn't exists anymore and we will not consider this
spacial case.

templates: prevent resolving $ref from data field

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/api.py

When we check about notification candidates on a loan, we need to
exclude the current loan from the current request list on the related
item.

notification: fix loan notification candidates

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/listener.py
rero_ils/modules/acq_order_lines/models.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/models.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
tests/api/acquisition/test_acquisition_scenarios.py
tests/api/notifications/test_notifications_rest.py

* Calculates account encumbrance for ordered and approved order lines.
* Ignores cancelled order lines when calculating account encumbrance.
* Sets account expenditure to 0 until the invoicing logic is added.
* Replaces canceled by cancelled when found.

acquisition: calculate account encumbrance

---

rero_ils/modules/libraries/api.py

* Limits the number of terms in the libraries aggregations facets from
10 to 50.

documents: fix libraries aggregations

---

rero_ils/config.py
rero_ils/modules/acq_receipts/api.py
rero_ils/modules/acq_receipts/models.py
rero_ils/modules/acq_receipts/views.py
setup.py
tests/api/acq_receipts/test_acq_receipts_views.py

* Adds a new method to create multiple receipt line orders for a receipt.

acquisition: create an entrypoint to create lines

---

poetry.lock
pyproject.toml

* Fixes `wtforms` dependency that cause an import error with version >=
3.0.0

dependencies: fix wtform

---

poetry.lock
pyproject.toml
scripts/setup
scripts/setup_csv

* Deletes --no-info from setup script.
* Fixes `flask-wtf` dependency that cause an `Working outside of request context`
error during user creation with version >= 1.0.0

setup: fix setup script

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_orders/api.py
tests/api/acquisition/test_acquisition_workflow.py

* Fixes a problem when calculating the expenditure.
* Fixes a problem when calculating order quantity received.
* Add units testing for complete acquisition workflow.

acquisition: calculate indexed fields

---

poetry.lock
pyproject.toml
rero_ils/config.py
rero_ils/modules/items/api/circulation.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/utils.py
rero_ils/modules/libraries/api.py
rero_ils/modules/loans/api.py
tests/api/circulation/test_library_with_no_circulation.py
tests/api/items/test_items_rest.py
tests/api/libraries/test_libraries_rest.py
tests/data/data.json
tests/fixtures/circulation.py
tests/fixtures/metadata.py
tests/fixtures/organisations.py

The transaction locations of a library is selected in the list of pickup
locations of the library.  This causes issues with libraries that have
no pickup location setted.
With this commit, for libraries with no pickup locations the system
considers the first library location as transaction location for
circulation transactions. These libraries can now checkout items
directly from other libraries and once checked-in back they go
in_transit.
It is still mandatory to setup library hours and notification
settings before checkout items.
* Upgrades to invenio-circulation v1.0.0a34.
* Supports checkout of items of libraries with no opening hours externally.
* Supports fixed checkout of items of libraries with no opening hours externally.
* Fixes problem when in transit flash message was always …

circulation: support non-circulating libraries

---

rero_ils/config.py
rero_ils/modules/acq_order_lines/models.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_receipt_lines/api.py
rero_ils/modules/acq_receipt_lines/dumpers.py
rero_ils/modules/acq_receipts/api.py
rero_ils/modules/acq_receipts/listener.py
rero_ils/modules/acq_receipts/mappings/v7/acq_receipts/acq_receipt-v0.0.1.json
rero_ils/modules/acq_receipts/serializers.py
rero_ils/modules/ext.py
tests/api/acq_receipts/test_acq_receipts_rest.py
tests/api/test_serializers.py
tests/ui/acq_receipts/test_acq_receipts_api.py

Adds additional data when indexing a `AcqReceipt` :
* total_item_quantity
* receipt_lines basic informations
* document information (title, pid, isbn)
* reception_date
* quantity
* amount
* notes content
* total_amount

acquisition: add data into receipt ElasticSearch index

---

rero_ils/config.py
rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_order_lines/mappings/v7/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_receipt_lines/jsonschemas/acq_receipt_lines/acq_receipt_line-v0.0.1.json

- allow to sort receipts (and orders) by receipt_date
https://tree.taiga.io/project/rero21-reroils/task/2337

acquisition: sort receipts by receipt_date

---

rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_order_lines/api.py
rero_ils/modules/acq_receipt_lines/api.py
rero_ils/modules/acq_receipts/api.py
rero_ils/modules/acq_receipts/extensions.py
rero_ils/modules/acq_receipts/jsonschemas/acq_receipts/acq_receipt-v0.0.1.json
tests/api/acq_receipts/test_acq_receipts_rest.py
tests/api/acquisition/test_acquisition_reception_workflow.py

* Deletes all receipt lines when attempting to delete a receipt.
* Reindexes corresponding order lines after deletion.
https://tree.taiga.io/project/rero21-reroils/task/2350

acquisition: delete receipt and its lines

---

rero_ils/config.py
rero_ils/modules/cli/utils.py
rero_ils/modules/contributions/api.py
rero_ils/modules/contributions/views.py
rero_ils/modules/documents/api.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/tasks.py
rero_ils/modules/documents/utils.py
rero_ils/modules/holdings/api.py
scripts/setup
tests/api/documents/test_documents_rest.py
tests/api/documents/test_documents_tasks.py
tests/data/data.json
tests/ui/documents/test_documents_filter.py
tests/ui/test_api.py

* Searches and replaces contribution identifiedBy values with $refs.

documents: find and replace identifiedBy

---

rero_ils/modules/loans/api.py
rero_ils/modules/notifications/utils.py
tests/api/circulation/test_borrow_limits.py
tests/api/loans/test_loans_rest.py
tests/api/notifications/test_notifications_rest.py
tests/api/selfcheck/test_selfcheck.py
tests/api/test_tasks.py

The overdue notification creation doesn't work as expected after loan
extension. It's possible to send an overdue notification before the
extension. If the user extend the loan but continue to keep book, this
loan can be overdue again. In this case, a second 'first overdue'
notification must be created.
Closes rero/rero-ils#2470.

notifications: fix overdue notification creation

---

rero_ils/config.py
rero_ils/modules/documents/serializers.py
tests/api/documents/test_documents_rest.py

ui: add a location level in facets
* Adds a third level in facet Organization/Libraries to filter locations. 
- To add a third level to organization facet
n/a
- Open public view or professional view and expand Organisation/Libraries Facet. You should see 3 levels now.

ui: add a location level in facets

---

rero_ils/modules/holdings/api_views.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/patrons/api.py
tests/api/holdings/test_provisional_items.py

When patron places a request on a holdings record, patron
must provide two required information: pickup_location and
description of the issue.
At the receiving of the request, system attempts to create
a new item of type `provisional`, attach it to the holdings
record and finally reserve it to the patron.
This exact same behaviour executed for requests placed by
librarian on behalf of the patron.
https://tree.taiga.io/project/rero21-reroils/task/2353

holdings: place a circulation request

---

rero_ils/modules/acq_order_lines/dumpers.py
rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/listener.py
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
tests/data/acquisition.json
tests/ui/acq_orders/test_acq_orders_api.py

All notes from resources related to an AcqOrder should be indexed into
the AcqOrder index in order to allow searching into any note content.

acquisition: indexing `AcqOrder` related notes

---

rero_ils/dojson/utils.py

* Fixes links for contributors with DNB identifiers when importing from the Web (automatic link to MEF).
N/A
- In the prof. interface: search for isbn 9783110632439 in SLSP. Try to import the book. You should see contributors automatically linked to MEF entries.

import: fix links for contributors with DNB identifiers

---

rero_ils/config.py
rero_ils/modules/items/tasks.py
rero_ils/modules/items/utils.py
scripts/setup
tests/api/holdings/test_provisional_items.py

* Adds a daily task to delete checked-in provisional items having not associated fees.
* Migration instructions:
This task need to be enabled for the production instance
- invenio reroils scheduler enable_tasks -n delete-provisional-items -v
https://tree.taiga.io/project/rero21-reroils/task/2356

items: delete checked-in provisional items

---

rero_ils/modules/loans/api.py
rero_ils/modules/notifications/utils.py
tests/api/notifications/test_notifications_rest.py

Before creating a reminder notification, we need to known if a previous
notification was already created since the last transaction date. We
can't just let the notification process cancel this notification because
a `PatronTransaction` could be created when a reminder notification is
created, despite if this notification is cancelled during notification
dispatch process.

notifications: fix multiple notification creation

---

rero_ils/modules/patron_transaction_events/api.py

It was unable to create a `PatronTransactionEvent` without amount.
However, it must be allowed for some event (like a dispute).

PatronTransaction: fix event creation

---

data/acq_accounts.json
rero_ils/config.py
rero_ils/modules/acq_accounts/api.py
rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
rero_ils/modules/acq_accounts/mappings/v7/acq_accounts/acq_account-v0.0.1.json
rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json

Updates the mapping of `AcqAccount` and `AcqOrder` resources for unique
fields detection. Fields must be indexed as 'text' for search but also
as 'keyword' for unique value detection/facet.

acquisition: fix unique fields detection

---

rero_ils/modules/acq_receipt_lines/api.py
rero_ils/modules/acq_receipt_lines/jsonschemas/acq_receipt_lines/acq_receipt_line-v0.0.1.json
rero_ils/modules/acq_receipt_lines/mappings/v7/acq_receipt_lines/acq_receipt_line-v0.0.1.json
tests/api/acquisition/test_acquisition_reception_workflow.py
tests/ui/acq_receipt_lines/test_acq_receipt_lines_api.py
tests/unit/conftest.py
tests/unit/test_acq_receipt_lines_jsonschema.py

Adds a new field into each reception line to specify the VAT rate to use
for this line.

acquisition: add VAT rate field for receipt line

---

rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
rero_ils/theme/templates/rero_ils/address_block/eng.tpl.txt
rero_ils/theme/templates/rero_ils/address_block/fre.tpl.txt
rero_ils/theme/templates/rero_ils/address_block/ger.tpl.txt
rero_ils/theme/templates/rero_ils/address_block/ita.tpl.txt
tests/api/acq_orders/test_acq_orders_views.py
tests/data/data.json

Adds a field to allow extra setting (VAT number, special note, ...) for
any informations related to acquisition setting into the `Library`
resource.

library: add `extra` field for acquisition setting

---

rero_ils/modules/loans/api_views.py
tests/api/loans/test_loans_rest_views.py

Creates an API endpoint to allow dumping the circulation
policies informations related to a loan.

loans: dumping related circulation policy

---

rero_ils/modules/loans/api.py
rero_ils/modules/patron_transactions/api.py

The overdue fees steps was not correctly calculated depending of the
related library timezone.
Closes rero/rero-ils#2550.

circulation: fix overdue fees timestamp calculation

---

rero_ils/modules/documents/jsonschemas/documents/document_original_language-v0.0.1.json

* Fixes the behavior by going back to several selects (one per language).
* Closes #2416.

documents: fix translation on original language field

---

rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json

The following fields are not allowed normally to have
a value of zero. with exclusiveMinimum, this ensures a
value greater than zero.
cipo.reminders.fee_amount
cipo.overdue_fees.fee_amount
cipo.maximum_total_amount
patron_transaction_event.amount
patron_transaction_event.steps.amount
* Changes street fields to multi-line text input.

jsonschema: introduce exclusiveMinimum for fields

---

rero_ils/modules/api.py
rero_ils/modules/monitoring/api.py

* Corrects `get_all_pids` function with limit offset search.

modules: fix get_all_pids

---

rero_ils/modules/loans/api.py

* Fixes `elasticsearch.helpers.errors.ScanError: Scroll request has only
succeeded on X (+0 skipped) shards out of Y.` error during
notification reation.

notifications: fix creation

---

rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/subclasses/circulation.py
tests/api/notifications/test_notifications_rest.py

The `reply-to` recipients should be an array but CirculationNotification
classes returned only a string. This caused bad `reply-to` message header
only containing the first letter of the email.
before
after

notification: fix `reply-to` recipient

---

rero_ils/config.py
rero_ils/modules/stats/api.py
rero_ils/modules/stats/cli.py
rero_ils/modules/stats/jsonschemas/stats/stat-v0.0.1.json
rero_ils/modules/stats/mappings/v7/stats/stat-v0.0.1.json
rero_ils/modules/stats/permissions.py
rero_ils/modules/stats/serializers.py
rero_ils/modules/stats/tasks.py
rero_ils/modules/stats/templates/rero_ils/detailed_view_stats.html
rero_ils/modules/stats/templates/rero_ils/stats_list.html
rero_ils/modules/stats/views.py
rero_ils/theme/menus.py
scripts/setup

- Adds basic statistics for librarians and system librarians
- Adds view 'Statistics librarian' in Tools
US Basic statistics
https://tree.taiga.io/project/rero21-reroils/us/1744?milestone=306074
- Log in as admin, librarian or system librarian.
- In section Tools: 
if logged in as admin there are two options: Statistics billing, Statistics, 
if logged in as librarian or system librarian there is only Statistics
-  In Statistics there should be the list of statistics from Jan 2021 to Dec 2021
- The monthly statistics contains the statistics for each library: 
A librarian can see only the statistics for his/her libraries.
A system librarian can see the statistics for his/her libraries and the libraries of his/her organization. 
An admin can …

statistics: implement basic statistics for librarians

---

rero_ils/jsonschemas/common/languages-v0.0.1.json

Add `bul-latn` and `bul-cyrl` as language scripts to describe Bulgarian
resources.
Closes rero/rero-ils#2628.

document: add Bulgarian script languages

---

data/patron_types.json
rero_ils/alembic/90d857fb5c23_unpaid_subscription_limit.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
rero_ils/modules/patron_types/mappings/v7/patron_types/patron_type-v0.0.1.json
rero_ils/modules/patrons/api.py
tests/api/circulation/test_borrow_limits.py
tests/data/data.json

Add a circulation operation restriction if a patron has pending unpaid
subscriptions. If this limit is enabled, any output circulation
operation should be denied (checkout/renew/request).
Closes rero/rero-ils#1530.
An alembic script is available to migrate existing PatronTypes : `90d857fb5c23_unpaid_subscription_limit`

patron_types: add a limit for unpaid subscription

---

rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json

Currently the `phone number` field for order section allow only digits.
It isn't flexible enough.

vendor: allow more flexibility on phone number.

---

rero_ils/config.py
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/csv.py
rero_ils/modules/items/serializers/json.py
rero_ils/modules/serializers.py
tests/api/items/test_items_rest.py
tests/api/test_serializers.py

* Adds temporary item type facet.
* Adds temporary location facet.
* Adds the checkout_date and the due_date fields to the export.
* Closes rero#2364.
* Closes rero#2611.
* rero/rero-ils-ui#773
1. New added facets
- Login as librarian and go to the Inventory List on professionnal view
- The facet temporary_item_type and temporay_location will being displayed.
- Try and check filtering
2 New fields into the export
- In the Inventory List, try to find items on loan and export the results as csv.
- The checkout_date and the due_date columns must be filled

search: add facets for inventory list

---

rero_ils/modules/loans/listener.py
rero_ils/modules/notifications/api.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_transaction_events/extentions.py
rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
rero_ils/modules/patron_transaction_events/models.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/utils.py
rero_ils/modules/patron_types/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/views.py
rero_ils/modules/selfcheck/api.py
tests/api/circulation/test_actions_views_checkin.py
tests/api/patron_transaction_events/test_patron_payments_rest.py
tests/api/patron_transactions/test_patron_transactions_rest.py
tests/ui/loans/test_loans_api.py
tests/ui/patron_transaction_events/test_patron_transaction_events_api.py

* Creates an extension to check if event amount contains a maximum of 2
decimals.
* Reorganizing some codes from `PatronTransaction` resource to be more
readable/usable.
* Closes rero/rero-ils#2602.

 patron transaction event: fix decimal amount

---

rero_ils/alembic/54134957af7d_loan_checkout_location_pid.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/extensions.py
rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/listener.py
rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
rero_ils/modules/loans/utils.py
tests/ui/circulation/test_actions_extend.py

Calculates overdue fees based on checkout location even if this loan has
been extended on an other libraries.
Closes rero/rero-ils#2640.
Closes rero/rero-ils#2683.
Launch the "Alembic" script present into the PR : `54134957af7d_loan_checkout_location_pid`

circulation: compute fees on checkout location

---

rero_ils/config.py
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/api.py
tests/api/notifications/test_notifications_rest.py

Creates an new configuration variable allowing to disable some
notification creation based on notification type. Using this
configuration it's now possible to disable all 'recall' notification
creations by example.
Closes rero/rero-ils#2665.

notification: disable notifications creation by config

---

rero_ils/theme/templates/rero_ils/header.html

* Removes useless css class on `<i></i>` tag.
Caret in mobile menu isn't correctly align on text
- go to public view with mobile screen (or resize your browser) 
- in the menu, caret will be align to the text

menu: fix bad caret alignment in mobile menu

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json

The issue 'received_date' field must be only required when the issue
status is received. Otherwise this field isn't required and should be
hided.

issues: fix 'received_date' required conditions.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/correction.md
.github/ISSUE_TEMPLATE/developers.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/labeler.yml
.github/workflows/stale.yml

Quick fix for Github labeler to account for current label titles in repo and improvement of the issue templates.

documentation: update PR labeler to new Github label list

---

.github_changelog_generator
CHANGELOG.md

- add default params file to improve use of github_changelog_generator
- rename CHANGES.md to CHANGELOG.md for consistency across projects

documentation: improve changelog generation

---

rero_ils/modules/holdings/tasks.py

* Adds try, exception to delete of holding.

holding: better delete_standard_holdings_having_no_items

---

rero_ils/config.py
rero_ils/modules/contributions/api.py
rero_ils/modules/contributions/tasks.py

contributions: better update_contributions

---

poetry.lock
pyproject.toml
rero_ils/config.py
rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html
rero_ils/modules/ill_requests/views.py
rero_ils/modules/patrons/views.py
rero_ils/modules/users/api.py
rero_ils/modules/users/templates/rero_ils/user_password.html
rero_ils/modules/users/templates/rero_ils/user_profile.html
rero_ils/modules/users/views.py
rero_ils/theme/menus.py
setup.py
tests/api/users/test_users_rest.py
tests/fixtures/metadata.py
tests/ui/ill_requests/test_ill_requests_ui.py
tests/ui/users/test_users_ui.py

The change of the user's data as well as the change of
the password has been transferred to the Angular user profile.
* Adds functionality for editing user data in angular.
* Adds functionality to change user password in angular.
* Closes https://github.com/rero/rero-ils/issues/2000.
* Closes https://github.com/rero/rero-ils/issues/2101.
* Closes https://github.com/rero/rero-ils/issues/2195.
* [patron: select the current profile view](https://github.com/rero/rero-ils-ui/pull/801)
* [users: make user profiles read-only](https://github.com/rero/invenio-userprofiles/pull/6)
- Test the data editing functionality in the "Personal data" tab.
- Test the password change functionality in the "Personal …

interface: keep the viewcode in the urls

---

rero_ils/modules/items/api/circulation.py
tests/ui/circulation/test_actions_cancel_request.py
tests/ui/circulation/test_in_transit_actions.py

Case when an item has an in_transit_for_pickup loan with other
pending loans. If the in_transit_for_pickup is cancelled, the
system will validate the first pending loan at the pickup
location of the cancelled loan. This will ensure that the
loan to validate will receive the correct state according
to the validation logic.
* Closes #2454

circulation: cancel intransit request with loans

---

rero_ils/modules/stats/api.py
rero_ils/modules/stats/cli.py
rero_ils/modules/stats/permissions.py
rero_ils/modules/stats/serializers.py
rero_ils/modules/stats/templates/rero_ils/detailed_view_stats.html
rero_ils/modules/stats/templates/rero_ils/stats_list.html
rero_ils/modules/stats/views.py
tests/api/stats/conftest.py
tests/api/stats/test_stats_rest.py

- Adds tests for librarian statistics
- Solves issue of user with more than one patron account (https://github.com/rero/rero-ils/issues/2697)
- Adds query: number of loan transactions by item location
- Adds button to download csv file of specific queries
- Changes name of queries labels and order output data (https://github.com/rero/rero-ils/issues/2675)
https://tree.taiga.io/project/rero21-reroils/task/2371
Solves issue: https://github.com/rero/rero-ils/issues/2697
Solves issue: https://github.com/rero/rero-ils/issues/2675

statistics: add tests, query and csv download button for librarian statistics

---

rero_ils/modules/items/dumpers.py
rero_ils/modules/loans/serializers.py
tests/ui/items/test_items_dumpers.py

Adds inherited parent holding call numbers into the item dumped data for
item serialization for custom `rero+json` content type.
Part of the solution to solve rero/rero-ils#2751. 
The main resolution part will be in a separate UI PR.

item: fix item serialization

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

Fixes the issue https://github.com/rero/rero-ils/issues/2691 of the document summary not displaying when it contains double quotes.
Fixes https://github.com/rero/rero-ils/issues/2691

documents: escape double quotes in summary

---

data/acq_accounts.json
data/acq_invoices.json
data/acq_order_lines.json
data/acq_orders.json
data/acq_receipt_lines.json
data/acq_receipts.json
data/budgets.json
data/libraries.json
rero_ils/modules/cli/fixtures.py
scripts/setup

* Complete acquisition for libraries.
* Adds complete fixtures for accounts, orders and order_lines.
* Adds optional way to load receipts, receipt_lines and invoices (needed for the BN project).
* Closes #2687
- setup
- check the admin interface for acqz orders/lines

acquisition: complete fixtures for some resources

---

tests/api/acquisition/test_acquisition_scenarios.py

The `acq_account` API could return some translated messages. As these
messages could be tested we need to ensure that no translation is done
during unitests. Now we mock the translation function to return the same
value than input value.

tests: fix acquisition translation problem

---

rero_ils/modules/documents/api.py
rero_ils/modules/documents/utils.py
tests/api/documents/test_documents_rest.py
tests/unit/test_documents_dojson_dc.py
tests/unit/test_documents_utils.py

* All parts of a title are included into the title label to display for
end-user.
* Closes rero/rero-ils#2703.

document: fix `title_format_text` for a document

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json

Allows to a specify the new 'access type' note for holdings resources.

holdings: add 'access' note type

---

rero_ils/modules/items/api/circulation.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/extensions.py
rero_ils/modules/loans/logs/api.py
tests/ui/circulation/test_actions_cancel_request.py
tests/ui/circulation/test_actions_expired_request.py

If a request was cancelled when the item is at_desk in an other library
than the owning library, then the item should be return to the owning
library and the loan status must be "TRANSIT_TO_HOUSE". The cancelling
operation must also be logged as an OperationLog.
Closes rero/rero-ils#2710.

circulation: fix request not cancelled

---

rero_ils/modules/documents/views.py

In the document detailed view, the figure caption behind the thumbnail
was vertically displayed. The reason was that the `document_types` jinja
filter return only a string (splitted on list of char) instead of a list
of string.
Before
After

document: fix thumbnail caption

---

rero_ils/modules/holdings/listener.py
rero_ils/modules/patrons/listener.py
scripts/setup

* Uses insinstance instead of get_schema_for_resource when possible.
Co-Authored-by: Aly Badr <aly.badr@rero.ch> the UI?

schema: correct errored values of https

---

rero_ils/modules/ill_requests/forms.py
rero_ils/modules/ill_requests/utils.py
rero_ils/modules/ill_requests/views.py

The select menu no longer selects the first available location.
The "Select..." option has been added to the top of the values.
* Closes #2772.

ill request: improve pickup location menu

---

data/documents_small.json
rero_ils/alembic/0387b753585f_correct_subjects_bf_Organization.py
rero_ils/modules/cli/index.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/dnb/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/kul/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/ugent/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
tests/unit/test_documents_dojson.py

* To unify the writing of bf:Organization we will temporary change
bf:Organization to bf:Organisation in subjects because it is written
like this anywhere else.
* In the future we have to change this everywhere to bf:Organization.
Also in MEF.

subjects: change bf:Organization to bf:Organisation

---

rero_ils/modules/cli/utils.py
rero_ils/modules/contributions/api.py
rero_ils/modules/contributions/cli.py
rero_ils/modules/contributions/tasks.py
rero_ils/modules/documents/tasks.py
rero_ils/modules/documents/utils_mef.py
tests/api/documents/test_documents_tasks.py

contribution: fix replace ReplaceMefIdentifiedBy

---

rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py

ebooks: fix dojson subjects

---

rero_ils/alembic/74ab9da9f078_update_patron_communication_channels.py
rero_ils/config.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/cli.py
rero_ils/modules/patrons/models.py
rero_ils/modules/users/api.py
rero_ils/modules/users/views.py
tests/api/patrons/test_patrons_rest.py
tests/api/test_permissions_sys_librarian.py
tests/api/users/test_users_profile_updates.py
tests/fixtures/circulation.py
tests/ui/patrons/test_patrons_api.py

No reset password notifications are sent after any changes made
to the patron/user record for both admin and public interfaces.
The communication channel is updated automatically after updates
made to the patron profile by the patron himself.
* Fixes #2313
* Fixes #2281
* Fixes #1580
* Fixes #2887
1.1- connect to the admin interface as librarian or system_librarian
1.2- edit any patron profile and test the adding/changing/removal of email
1.3- there will be no password notifications sent to the patron
2.1- connect to the public interface as patron
2.2- edit your profile and test the adding/changing/removal of email
2.3- there will be no password notifications sent to the patron
3.1- connect to the public interface as patron
3.2- edit your …

notifications: not sent after patron changes

---

rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
rero_ils/modules/loans/api.py
rero_ils/modules/notifications/extensions.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/models.py
rero_ils/modules/notifications/subclasses/at_desk.py
rero_ils/modules/notifications/templates/email/at_desk/eng.txt
rero_ils/modules/notifications/templates/email/at_desk/fre.txt
rero_ils/modules/notifications/templates/email/at_desk/ger.txt
rero_ils/modules/notifications/templates/email/at_desk/ita.txt
rero_ils/modules/notifications/templates/email/request/fre.txt
rero_ils/modules/notifications/templates/email/transit_notice/fre.txt
tests/api/notifications/test_notifications_rest.py
tests/data/data.json

When an item arrives 'at_desk' a notification was already sent to the
patron to alert it that the item is now available (availability
notification). A sibling notification is now sent to the transaction
library (at_desk notification) ; mainly for printing usage.
Closes rero/rero-ils#2695.

notification: create 'at_desk' notification

---

rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json

The `minItems` setting about subject subdivisions cause some trouble for
the editor (because subdivision is into OneOf section). Set these
settings to 0 value to solve the problem.

document: fix subject subdivisions min items

---

rero_ils/modules/loans/logs/api.py
rero_ils/modules/patrons/api.py
tests/ui/loans/test_loans_operation_logs.py

tests: fix test_loan_operation_log

---

rero_ils/modules/notifications/subclasses/at_desk.py
rero_ils/modules/notifications/subclasses/circulation.py

Ensures that the patron related to the `at_desk` notification is the
patron related to the AT_DESK loan state.
Closes rero/rero-ils#2938.

notification: fix `at_desk` notification context.

---

rero_ils/modules/acq_orders/api.py
rero_ils/modules/acq_orders/dumpers.py
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/eng.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/fre.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/ger.tpl.txt
rero_ils/modules/acq_orders/templates/rero_ils/vendor_order_mail/ita.tpl.txt
rero_ils/modules/commons/identifiers.py
rero_ils/modules/documents/dumpers.py

* Fixes missing order date. Because order date derivates from order
lines, and order lines are updated after notification dispatch, the
order date was always missing. Now we use the current timestamp as
notification order date.
* Fixes notification template indentation problem.
* Fixes billing informations into template.
* Adds qualifier for ISBN included into notification.
* Closes rero/rero-ils#2647.
* Closes rero/rero-ils#2880.

acquisition: fix acquisition notification templates

---

rero_ils/config.py
rero_ils/modules/documents/serializers/__init__.py
rero_ils/modules/documents/serializers/base.py
rero_ils/modules/documents/serializers/dc.py
rero_ils/modules/documents/serializers/json.py
rero_ils/modules/documents/serializers/ris.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/response.py
rero_ils/modules/serializers.py
tests/api/documents/test_export_serializers.py
tests/conftest.py

This commit add a new JSON serializer to process only document
metadata without any other information like the aggregations, links...
The search serialization implements also a stream results with context.
It mainly used to export documents.
* Adds export button in detail view.
* Adds custom JSON serializer to export record.
* Closes #2780.
* rero/rero-ils-ui#848
1. **Test export button**
a. _Export documents in public search:_
- Go to the public search. 
- A new export button is added on right top of the search.
- Test JSON and RIS export.
b. _Export document in public detail view:_
- Go to detail view of a …

documents: export record

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/documents/utils_mef.py
rero_ils/schedulers.py

* Uses f strings for printing.
* Adds `replace-idby-subjects-imported` scheduled task.

scheduler: improvments

---

rero_ils/jsonschemas/common/cantons-v0.0.1.json
rero_ils/jsonschemas/common/languages-v0.0.1.json
rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_document_relation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_electronic_locator-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_identifier-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_intended_audience-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_scale_cartographic-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_types-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_work_access_point-v0.0.1.json
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json

Fields involved:
supplement, supplementTo, otherEdition, otherPhysicalFormat,
issuedWith, precededBy, succeededBy, relatedTo, hasReproduction,
reproductionOf, work_access_point
* Removes templateOptions on the country jsonschema.
* Fixes typo on the type entry (lower case t).
* Adds the card wrapper on vendors jsonschema.
* Closes https://github.com/rero/rero-ils/issues/2275.
* Closes https://github.com/rero/rero-ils/issues/2388.
* Closes https://github.com/rero/rero-ils/issues/2766.
* Closes https://github.com/rero/rero-ils/issues/2659.
* Closes https://github.com/rero/rero-ils/issues/2649.
* Closes https://github.com/rero/rero-ils/issues/2340.
* Closes #1924.
⚠️  Elasticsearch reindexing.
- Test the above mentioned fields

documents: add identifiedBy on some fields

---

rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json

* Closes https://github.com/rero/rero-ils/issues/2948

jsonschemas: extend validation limit for `provisionActivity` dates

---

rero_ils/theme/assets/scss/rero_ils/thumbnail.scss

document: fix size of the thumbnail on mobile detail view

---

rero_ils/theme/templates/rero_ils/frontpage.html
rero_ils/theme/templates/rero_ils/header.html

- The test server alert message is moved just under the navbar in the header template so that it is displayed across the app. 
- On test deployments (including bib.test), use config `RERO_ILS_STATE_PRODUCTION = False` to show the alert

Move test server alert to app header

---

rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json

* Reset minItems=0 for subject subdivisions
* Greatly improves editor performance for documents with many subject
fields
With new ng-core version, setting minItems = 1 for subject subdivisions worsens the performance for this field when there are a lot of subjects in a document. This is a workaround. The next formly major version might be better.
- See that for document with many subjects (example https://bib.rero.ch/professional/records/documents/edit/2110433), adding a subject takes even more time in RC 1.12.0 than in production. 
- With this fix, the performance should be greatly improved.

editor: fix subject field performance

---

rero_ils/modules/items/models.py
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/collector.py
rero_ils/modules/items/serializers/csv.py
tests/api/test_serializers.py

* Fixes #2704
* Fixes #2793
- run the `Inventory list` report  for a given instance.
- the fields extracted from the `document` record are now prefixed with the string `document_`
- the fields extracted from the `item` record are now prefixed with the string `item_`
- the `local_fields` are now extracted for both `documents` and `items`
- all the fields mentioned in the issue https://github.com/rero/rero-ils/issues/2704 are added
- loan information are correctly extracted according to https://github.com/rero/rero-ils/issues/2793

items: add new fields to inventory list

---

rero_ils/config.py
rero_ils/modules/documents/templates/rero_ils/_ill_request_button.html
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/documents/views.py
rero_ils/modules/ill_requests/utils.py
rero_ils/modules/ill_requests/views.py
tests/ui/ill_requests/test_ill_requests_ui.py

* Adds the configuration to hide/show button on global view.
* Adds the populate ill form with record data.
* Closes #2950.

documents: add interlibrary loan button on global view

---

rero_ils/modules/documents/jsonschemas/documents/document_types-v0.0.1.json

* Adds docsubtype_projected_image on docmaintype_image.
* Adds docsubtype_pictorial_book on docmaintype_book.
* Closes #2884.

documents: add 2 subtypes

---

rero_ils/jsonschemas/common/countries-v0.0.1.json
rero_ils/jsonschemas/common/languages-v0.0.1.json

* Show be, gw, fr, it, sz, xxk, xxu first in countries list
* Show dut, eng, fre, ger, ita first in languages list

fix: show most used values first in lists

---

rero_ils/modules/notifications/subclasses/at_desk.py

Use a delay to be sure the notification is sent AFTER the loan has
been indexed (avoid problem due to server load).
* Adds a delay before notification sent.
* Closes #3005.

notifications: at desk notification gets cancelled

---

rero_ils/dojson/utils.py
rero_ils/modules/cli/utils.py
rero_ils/modules/holdings/api_views.py
rero_ils/modules/loans/api.py
tests/api/holdings/test_patterns.py
tests/api/notifications/test_notifications_rest.py
tests/api/patron_transaction_events/test_patron_transaction_events_rest.py
tests/api/patron_transactions/test_patron_transactions_rest.py
tests/api/patron_types/test_patron_types_rest.py
tests/api/patrons/test_patrons_rest.py
tests/ui/holdings/test_holdings_api.py

The new version of pydocstyle is more strict and returns an error when
the `del` statement is used as a function.

tests: fix tests for the new pydocstyle version

---

rero_ils/modules/ebooks/utils.py

* Adds flushing of indexes for ebook harvesting.

ebooks: better ebook harvesting

---

rero_ils/config.py
rero_ils/modules/acq_accounts/serializers.py
rero_ils/modules/acq_invoices/serializers.py
rero_ils/modules/acq_orders/serializers.py
rero_ils/modules/acq_receipt_lines/serializers.py
rero_ils/modules/collections/serializers.py
rero_ils/modules/documents/serializers/__init__.py
rero_ils/modules/holdings/serializers.py
rero_ils/modules/ill_requests/serializers.py
rero_ils/modules/imports/serializers/__init__.py
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/json.py
rero_ils/modules/loans/serializers/__init__.py
rero_ils/modules/operation_logs/serializers.py
rero_ils/modules/patron_transaction_events/serializers.py
rero_ils/modules/patron_transactions/serializers.py
rero_ils/modules/patrons/serializers.py
rero_ils/modules/serializers/__init__.py
rero_ils/modules/serializers/mixins.py
rero_ils/modules/serializers/response.py
tests/api/test_serializers.py

As the serializer object is instancied once during the initialization of
the application, the cache was never reset. This PR introduce a new
method to serialize search where the serializer object is reset for each
serialization request ; so the cache will reset.
Co-authored-by: Renaud Michotte <renaud.michotte@gmail.com>

serialization: fix caching reset problem

---

data/documents_small.json
rero_ils/config.py
rero_ils/facets.py
rero_ils/modules/documents/listener.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/serializers/json.py
rero_ils/modules/documents/utils.py
rero_ils/query.py
tests/api/documents/test_documents_rest.py

- Added more facets for documents search
- Implemented post filters
- This PR requires a document re-indexing
Closes https://github.com/rero/rero-ils/issues/2763
* rero/rero-ils-ui#867
* https://github.com/rero/ng-core/pull/503/
Please test:
* for the OR facets (listed in the [US](https://github.com/rero/rero-ils/issues/2763)) it is possible to select multiple values of the same facet. 
Example: it is possible to select several values of Document type.
* the results count and the facets counts change accordingly to the selection made.
* a list of chosen filters is displayed. It is possible to remove a filter by clicking on the X next to the filter name.
* when there are no results a …

documents: add more facets for documents search 

---

data/role_policies.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/ext.py
rero_ils/modules/organisations/permissions.py
rero_ils/modules/patron_types/permissions.py
rero_ils/modules/permissions.py
tests/api/organisations/test_organisations_permissions.py
tests/api/patron_types/test_patron_types_permissions.py
tests/data/role_policies.json

* Refactoring Organisation policy access using `Permission` framework.
* Adapts `PatronType` policy.
* Adapts unitest

permissions: refactoring organisation policy

---

rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json

* Adds field to the quick access for easy adding.
* Closes #3032.

item editor: add acquisition_date to quick access

---

rero_ils/modules/documents/api.py
rero_ils/modules/holdings/tasks.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/loans/api.py

* Uses logger on current_app in `is_available` method.
* Fixes elasticsearch timeout when executing some tasks.

documents: fix flask attribute error.

---

rero_ils/config.py
rero_ils/facets.py
rero_ils/query.py

* Adds filters also if no facet list are specified in the URL.
* Uses `Q()` instead of query for facet filters.
* Adds support for facet filter configuration.
* Removed hard coded facet filter (subjects).

documents: fix facets subject and genre form

---

rero_ils/modules/holdings/mappings/v7/holdings/holding-v0.0.1.json
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json

* Fixes inconsistent mapping between documents and items/holdings for
call numbers.
* Closes #2908.
:warning: Requires ES update mapping!
:warning: Requires reindexing of `call_number` and `second_call_number`
for all items and holdings, as well as `inherited_first_call_number` for
items of type `issue`.

mappings: index call_numbers as text

---

rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json

holdings: extend `note.content` max length

---

rero_ils/modules/documents/serializers/marc.py
rero_ils/modules/utils.py

* Removes control characters from SRU export.

SRU: fix illegal characters

---

Dockerfile.base
poetry.lock

* Updates Dockerfile.base to use `python:3.9-slim-bullseye`.

 dependencies: update the dependencies lock file

---

rero_ils/config.py
tests/ui/documents/test_documents_ui.py

The Zotero plugin use `export/json` as endpoint to retrieve document data. With previous works on export, we have changed endpoint format to `raw`. This commit revert changes.
* Uses `json` instead `raw`in RECORDS_UI_EXPORT_FORMATS config.

export: fix zotero plugin error

---

rero_ils/modules/documents/api.py
tests/ui/documents/test_documents_api.py

We need to prevent internal server error when MEF resolver returns no metadata for the linked agent.
* Updates `replace_refs` method.

document: fix contribution error

---

rero_ils/modules/items/serializers/collector.py
tests/api/test_serializers.py

* When no `provisionActivity` of type `bf:publication` is present, the collector returns None rather than an empty generator.
* Fixes RT 412.
* Fixes Sentry RERO-ILS-2D1.

serializers: fix error when no `bf:Publication`

---

poetry.lock
pyproject.toml

Breaking change with version `1.0.0` of jsonref package. Fix the version to `0.3.0`. Remove this restriction when package requiring this dependency will be fixed.

dependency: fix `jsonref` python package version.

---

rero_ils/modules/utils.py

* Adds context manager to `JsonWriter` for using of: `with JsonWriter('test.txt') as file:`

utils: add context manager to JsonWriter

---

rero_ils/config.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/ugent/model.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
tests/unit/documents/test_documents_dojson_unimarc.py

* Adds a new parameter in config.py in order to map subjects to "subject_imported" or "subjects"
* Adapts the code for each source.
* Closes https://github.com/rero/rero-ils/issues/3079
- This PR addresses the issue https://github.com/rero/rero-ils/issues/3079
- It allows the set the way an instance of RERO-ILS maps/stores subjects from MARC21 to JSON.
- None
- Edit config.py and set variable RERO_ILS_IMPORT_6XX_TARGET_ATTRIBUTE to 'subjects' or 'subjects_imported' 
- Try to import document from BnF, LoC, SLSP,.... It should set the content of tags 6XX in the JSON attribute you define in config.py.

import: customize subjects mapping by instance

---

rero_ils/dojson/utils.py
tests/unit/documents/test_documents_dojson.py

* Uses Mef latest api in the function `get_contribution_link`.

dojson: use MEF latest api for contribution link

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
tests/unit/documents/test_documents_dojson.py
tests/unit/documents/test_documents_dojson_slsp.py

dojson : remove punctuation for work_access_point

---

rero_ils/modules/notifications/subclasses/availability.py
rero_ils/modules/notifications/templates/email/availability/eng.txt
rero_ils/modules/notifications/templates/email/availability/fre.txt
rero_ils/modules/notifications/templates/email/availability/ger.txt
rero_ils/modules/notifications/templates/email/availability/ita.txt
tests/ui/notifications/test_notifications_api.py

* Adds item's informations in context for availability notification.
* Adapts availability notification templates.
* Closes rero#2693.

notification: enrich availability context

---

rero_ils/modules/contributions/views.py

* Returns `abort(404, 'Record not found')` for non existing records.

contribution: fixes PIDDoesNotExistError

---

rero_ils/config.py

* Uses 'Fictions' and 'Films de fiction' for the `subject_fiction` and `subject_no_fiction` facets.

documents: better facets fiction

---

rero_ils/accounts_views.py
rero_ils/config.py
tests/api/test_user_authentication.py

* Provides same message to the user on login attempt if the password or username is invalid, to prevent security exploits.

security: uniformize failed login message

---

poetry.lock
rero_ils/config.py
rero_ils/modules/selfcheck/api.py
tests/api/selfcheck/test_selfcheck.py

* Adds config to map summary fields by loan state.
* Adapts patron_information method.
* Adds some test.
* Updates invenio-sip2 dependency to v0.6.19.
* Closes rero#3173.

selfcheck: fix summary fields in patron information

---

poetry.lock
pyproject.toml
run-tests.sh
tests/ui/circulation/test_actions_extend.py

When the test is run during the Christmas period, the fees_after_extend
test is in error, because the defined interval is not correct.
* Adds packages exception for safety.
* Fixes cryptography on the latest version 38.
* Fixes pydocstyle on the latest version 6.1.
* Fixes the test_fees_after_extend.

dependencies: fix vulnerabilites

---

rero_ils/modules/api.py
rero_ils/modules/patron_transaction_events/serializers/csv.py
tests/api/patron_transactions/test_patron_transactions_rest.py
tests/api/test_exports.py
tests/api/test_serializers.py

If patron transaction related resources are delete, the search and export caused error. This PR fix all these problems.

fix: reinforce search/export of patron transaction 

---

rero_ils/config.py
rero_ils/modules/notifications/api.py
rero_ils/modules/patron_transaction_events/api.py
rero_ils/modules/patron_transactions/api.py
rero_ils/modules/patron_transactions/extensions.py
rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
rero_ils/modules/patron_transactions/utils.py
tests/api/patron_transactions/test_patron_transactions_rest.py

* Adds library field on patron_transactions schema.
* Adds a sort option for patron transaction.
* Adds extensions for patron transactions.
* Transfer of event creation to the extension.
* Fixes some tests.
* Closes #3143.
Co-Authored-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>

patron transaction: add manuel fee

---

data/users.json
pyproject.toml
rero_ils/config.py
rero_ils/modules/users/api.py
rero_ils/modules/users/api_views.py
rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
rero_ils/modules/utils.py
tests/api/conftest.py
tests/api/users/test_user_api.py
tests/api/users/test_users_rest.py
tests/e2e/cypress/cypress/fixtures/common.json
tests/fixtures/circulation.py
tests/ui/conftest.py
tests/unit/test_utils.py

* Adds entrypoint to generate a new password.
* Adds entrypoint to validate a password.
* Updates users api to use the new password generator and validator.
* Updates users fixtures to add the password field.
https://github.com/rero/rero-ils-ui/pull/915
https://github.com/rero/ng-core/pull/531

user: add entrypoints api for the password

---

pyproject.toml
rero_ils/config.py
rero_ils/modules/commons/schemas.py
rero_ils/modules/documents/loaders/marcxml.py
rero_ils/modules/patrons/views.py
rero_ils/modules/serializers/base.py
rero_ils/modules/templates/api.py
rero_ils/modules/templates/extensions.py
rero_ils/modules/templates/loaders/__init__.py
rero_ils/modules/templates/schemas/__init__.py
rero_ils/modules/templates/schemas/json.py
tests/api/templates/test_templates_marshmallow.py
tests/api/templates/test_templates_rest.py
tests/fixtures/metadata.py

* Creates marshmallow schema for template resources.
* Controls "public" template creation through REST API.

templates: use marshmallow for API control

---

poetry.lock
pyproject.toml
rero_ils/accounts_views.py
rero_ils/config.py
rero_ils/filter.py
rero_ils/modules/ext.py
rero_ils/modules/message.py
rero_ils/modules/patrons/api.py
rero_ils/modules/users/api_views.py
rero_ils/modules/users/forms.py
rero_ils/modules/users/listener.py
rero_ils/modules/users/validators.py
rero_ils/modules/utils.py
rero_ils/theme/templates/rero_ils/_info_test.html
rero_ils/theme/templates/rero_ils/login_user.html
rero_ils/theme/templates/rero_ils/page_cover.html
rero_ils/theme/templates/rero_ils/register_user.html
rero_ils/utils.py
tests/api/patrons/test_patrons_views.py
tests/api/selfcheck/test_selfcheck.py
tests/api/test_accounts_rest_auth.py
tests/api/test_user_authentication.py
tests/api/users/test_user_api.py
tests/data/data.json
tests/ui/ill_requests/test_ill_requests_ui.py
tests/ui/loans/test_loans_operation_logs.py
tests/ui/test_message.py
tests/ui/test_permissions.py
tests/ui/users/test_forms.py
tests/utils.py

* Adds beautifulsoup4 package for test.
* Disables account rest api endpoint.
* Adds validations on the change password api.
* Updates password on the interface test information.
* Adds the possibility to put a message in the cache
and display it on the html page.
* Changes of the API response on invalid login.

user: improve register and forgot password

---

rero_ils/modules/commons/identifiers.py
tests/api/documents/test_documents_rest.py

Invalid EAN identifiers were not dumped into ES during indexing process. Now, even invalid EAN are indexed and could be searched. 
Closes rero/rero-ils#3220.
execute the script :
```python
from rero_ils.modules.documents.api import DocumentsSearch, DocumentsIndexer
from elasticsearch_dsl.query import Q
query = DocumentsSearch().filter('nested',
path='nested_identifiers',
query=Q('bool', must=[
Q('term', nested_identifiers__type='bf:Ean'),
~Q('exists', field='nested_identifiers.value')
])).source(False)
uuids = [hit.meta.id for hit in query.scan()]
indexer = DocumentsIndexer()
indexer.bulk_index(uuids)
_, (indexer_count, error_count) = indexer.process_bulk_queue()
print(f'{indexer_count} documents indexed, {error_count} errors') …
```

document: fix EAN identifier indexing

---

data/role_policies.json
poetry.lock
rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/commons/models.py
rero_ils/modules/contributions/sync.py
rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
rero_ils/modules/notifications/api.py
rero_ils/modules/patrons/api.py
rero_ils/modules/patrons/extensions.py
rero_ils/modules/patrons/loaders/__init__.py
rero_ils/modules/patrons/permissions.py
rero_ils/modules/patrons/schemas/__init__.py
rero_ils/modules/patrons/schemas/json.py
rero_ils/modules/patrons/utils.py
rero_ils/modules/patrons/views.py
rero_ils/modules/templates/loaders/__init__.py
rero_ils/modules/templates/schemas/json.py
rero_ils/modules/users/api.py
rero_ils/modules/users/views.py
tests/api/patrons/test_patrons_marshmallow.py
tests/api/patrons/test_patrons_permissions.py
tests/api/selfcheck/test_selfcheck.py
tests/api/users/test_users_profile_updates.py
tests/ui/patrons/test_patrons_api.py
tests/ui/test_api.py
tests/utils.py

Use Marshmallow schema to control `Patron` resources through API. The
`role` field is now controlled to limit changes depending to current
connected user.

patrons: use marshmallow for API control

---

rero_ils/config.py
rero_ils/modules/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/holdings/cli.py
rero_ils/modules/holdings/utils.py
rero_ils/modules/items/api/issue.py
rero_ils/modules/items/api/record.py
rero_ils/modules/items/extensions.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/listener.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/models.py
rero_ils/modules/items/tasks.py
rero_ils/modules/items/utils.py
tests/api/holdings/test_provisional_items.py
tests/ui/holdings/test_holdings_patterns.py
tests/ui/holdings/test_serial_claims.py

* Adds new `sort_date` for issue item. Used to sort issue regardless expected date.
* Adds extensions on `Item` resource to control/manage issue status and issue sort_date.
* Updates `late_issue_process` to include already created issue if expected_date has been manually changed by manager.
* Item/Holding code refactoring.
* Closes rero/rero-ils#2921.
🚨 Update mapping for `item` resource 🚨
```python
from rero_ils.modules.items.api import ItemsIndexer, ItemsSearch
query = ItemsSearch().filter('term', type='issue').source(False)
uuids = [hit.meta.id for hit in query.scan()]
indexer = ItemsIndexer()
indexer.bulk_index(uuids)
_, (indexer_count, error_count) = indexer.process_bulk_queue()
print(f'{indexer_count} items indexed, …
```

items: issue sorting & late issue schedule task

---

rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json

Changing the json schema to use the multicheckbox type for the role field.
ng-core: https://github.com/rero/ng-core/pull/530

patron: use of checkboxes for roles

---

rero_ils/modules/notifications/tasks.py
rero_ils/modules/utils.py
tests/api/test_monitoring_rest.py

* Adds `name` to timestamps for better json parsing in monitoring software.
* Saves also 0 values for `notification-creation` timestamp.

utils: timestamps

---

poetry.lock
rero_ils/alembic/5f0b086e4b82_patron_role_migration.py
rero_ils/alembic/8145a7cdef99_reindex_items_with_invalid_ean.py

* Adds a script to reindex documents with invalid EAN identifier.
* Adds a script to reindex serial issue item due to complete ES record with required `sort_date` field.

alembic: scripts for data migration

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_person-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_copyright_date-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_dimensions-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_table_of_contents-v0.0.1.json

* Removed unicodes from jsonschemas as they cause translations extraction problems.

translations: fix unicode characters in jsonschema

---

rero_ils/modules/items/api/record.py
rero_ils/modules/loans/utils.py
tests/api/circulation/test_locations_restrictions.py

Fixes the behavior of `can_be_requested` method use by Invenio circulation to deal with `item.temporary_location`. Without this fix, it's always the item.holding_location_pid (owning location) that will be used.

circulation: fix `can_be_requested` circulation method

---

poetry.lock
rero_ils/modules/contributions/api.py
rero_ils/modules/documents/tasks.py
rero_ils/modules/documents/utils_mef.py

* Uses MEF `latest` API for concepts records retrival.

dependencies: fix security issues

---

data/documents_small.json
rero_ils/alembic/a710021979fe_migrate_contribution_to_entity.py
rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/jsontodc/model.py
rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/ugent/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/extensions/provision_activities.py
rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/serializers/base.py
rero_ils/modules/documents/utils.py
rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
rero_ils/modules/entities/models.py
tests/data/data.json
tests/data/documents.json
tests/unit/documents/test_documents_dojson.py

* Removes `$ref` field into the `provisionActivity.places` structure :
`places` authority are not yet supported by MEF project so none link
could be done.
* Updates alembic tree dependencies for scripts into the `US-entity`
branch.
Co-authored-by: Renaud Michotte <renaud.michotte@gmail.com>

documents: delete `$ref` possibility on `provisionActivity.places`

---

data/locations.json
rero_ils/alembic/e3eb396b39bb_migration_ill_pickup.py
rero_ils/modules/ill_requests/cli.py
rero_ils/modules/ill_requests/serializers.py
rero_ils/modules/ill_requests/utils.py
rero_ils/modules/locations/api.py
rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
rero_ils/modules/locations/mappings/v7/locations/location-v0.0.1.json
tests/api/locations/test_locations_rest.py
tests/data/data.json

Add the possibility to define a location as an ill pickup and to give it a ill pickup name.
* Adds is_ill_pickup and ill_pickup_name on location resource.
* Updates serializer ton use the new ill_pickup_name.
* Updates fixtures.
* Closes #3124.
[ill request: ill pickup name (968)](https://github.com/rero/rero-ils-ui/pull/968)

ill request: add ill pickup name on location

---

rero_ils/modules/notifications/api.py
rero_ils/modules/notifications/dispatcher.py
rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
rero_ils/modules/notifications/mappings/v7/notifications/notification-v0.0.1.json
tests/api/notifications/test_notifications_rest.py

* Adds new `effective_recipients` field into the `Notification` resource. This field will stored the recipients if the notification is successfully sent.
* Fixes rero/rero-ils#3288.

notifications: add `effective_recipients` field.

---

data/documents_small.json
rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/jsonschemas/documents/document_work_access_point-v0.0.1.json
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/documents/views.py
tests/ui/documents/test_documents_filter.py
tests/unit/documents/test_documents_dojson.py
tests/unit/documents/test_documents_dojson_slsp.py

* Updates `document.work_access_point` field : rename field 'agent' to
'creator'.
* Fixes missing ES mapping for this field.

documents: refactoring work_access_point field

---

rero_ils/modules/holdings/api.py
tests/ui/holdings/test_holdings_api.py

The harvested document must be able to have a holdings that is not electronic
* Closes #3147.

documents: load harvested not electronic

---

rero_ils/config.py
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json
rero_ils/modules/entities/proxy.py
rero_ils/modules/entities/utils.py
rero_ils/modules/entities/views.py
rero_ils/modules/utils.py
rero_ils/modules/views.py
tests/api/entities/test_entities_rest.py
tests/api/test_commons_api.py
tests/conftest.py
tests/data/mef.json
tests/fixtures/mef.py
tests/utils.py

Refactors MEF Proxy view to allow more flexibility. Now the proxy
accept a search category and search terms. Depending of these
parameters the remove MEF query is build and MEF server response are
standardized for each categories.

entities: refactoring of MEF proxy

---

rero_ils/modules/notifications/tasks.py

* Corrects notification processed counts.
* Deletes double time stamps for notifications.

notifications: correct process counts

---

rero_ils/modules/items/decorators.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/listener.py
tests/api/patron_transactions/test_patron_transactions_rest.py
tests/ui/loans/test_loans_api.py

* Transforms some class methods to instance methods for `Loan` objects.
* Implements best open transactions detection (skipping Notification step).
* Closes rero/rero-ils#3121.

loans: clean `can_anonymize` method

---

data/vendors.json
rero_ils/alembic/e63e5dfa2416_new_vendor_serial_contact.py
rero_ils/modules/vendors/api.py
rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
rero_ils/modules/vendors/mappings/v7/vendors/vendor-v0.0.1.json
rero_ils/modules/vendors/models.py
tests/api/acq_orders/test_acq_orders_views.py
tests/api/acquisition/test_acquisition_reception_workflow.py
tests/data/acquisition.json
tests/ui/vendors/test_vendors_api.py
tests/unit/conftest.py
tests/unit/test_vendors_jsonschema.py

* Refactors contacts block into `Vendor` resource.
* Allow a new "serial" contact block
* Adds alembic migration script
* Adapts unitest and fixture

vendors: allow new 'serial' contact block

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_entity_link-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_contribution_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_entity_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form_link-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_genre_form_local-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
rero_ils/translations/ru/LC_MESSAGES/messages.po
rero_ils/translations/zh_Hant/LC_MESSAGES/messages.po

* Renamed subfields titles to be clearer for the user. Removed mentions of MEF in the editor.
* Set the default oneOf value to "link entites" for all concerned fields as it is the more frequent case.
* Corrected some placeholder examples.
* Renamed link contribution jsonschema for accuracy.

entites schemas: adapt field titles and defaults

---

rero_ils/modules/acquisition/acq_order_lines/extensions.py
tests/api/acquisition/test_acquisition_scenarios.py

If the related account of an order line changes, the destination account balance was no checked if the order line total amount doesn't change. This was cause some troubles with acquisition balance on account.

acquisition: fix account changes for order line

---

rero_ils/modules/documents/jsonschemas/documents/document_contribution_entity_link-v0.0.1.json

* bf:Organisation should be differentiated from RERO ILS organisation for translations. bf:Organisation is RDA term "corporate body".

fix bf:Organisation labels

---

rero_ils/modules/acquisition/acq_orders/extensions.py
rero_ils/modules/local_fields/extensions.py
tests/ui/local_fields/test_local_fields_api.py

When using the `pre_delete` hook to delete some related records, we need to ensure than corresponding indexes are cleaned too.

records: fix related resources indexes deletion problem

---

rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json

* A librarian can select an invoice payment method so that they can keep a trace of fees that have been externally invoiced.
* Requires patron_transaction_events update mapping
* https://github.com/rero/rero-ils-ui/pull/997

fees: add invoice payment method

---

rero_ils/modules/loans/api.py
rero_ils/modules/notifications/templates/email/recall/fre.txt
tests/api/notifications/test_notifications_rest.py

* When a checkout is operated on an item with pending requests (other than current patron) a recall notification should be sent to user.
* Closes rero/rero-ils#2673.

Notification: send recall on checkout

---

rero_ils/modules/libraries/api.py
rero_ils/modules/libraries/extensions.py
rero_ils/modules/libraries/tasks.py
rero_ils/modules/loans/api.py
rero_ils/modules/loans/extensions.py
rero_ils/modules/utils.py
tests/api/circulation/test_library_calendar_changes.py

* Creates extension to detect any changes into library calendar (regular hours & exception dates). If changes are detected, run this extension starts a tasks to update related loans.
* Creates a task to update loans related a library if calendar changes.
* Closes rero/rero-ils#2663.

library: detect changes on library open hours

---

rero_ils/modules/stats/api.py
tests/api/stats/test_stats_rest.py

- Fixes ill request stats processing for billing so only validated ill requests are counted.
- The stats collector counts all ill_requests that were created or updated.
- If a request changes to `validated` multiple times it will be counted multiple times.
- Adds no unit tests; they will be added later for the full module.
- Closes #3359.

billing stats: process only validated ill_requests

---

rero_ils/alembic/add75cbcad66_migrate_obsolete_country_codes.py

* Uses formatted string litterals on splitted string

alembic: fix log output format

---

rero_ils/modules/stats/api.py

- Fixed the stats collector trigger in the query for `validated_requests`. Problem discovered since the `loan.trigger` field is declared as a keyword in operation_logs mapping.

stats: fix validated requests count

---

rero_ils/config.py

* Change `notification-creation` to 3:00 o'clock.
* Change `ebooks-harvester` to 22:22 o'clock.

scheduler: change timings

---

rero_ils/modules/items/api/record.py
rero_ils/modules/patrons/api.py
tests/api/circulation/test_borrow_limits.py
tests/api/conftest.py
tests/api/documents/test_documents_rest.py
tests/api/items/test_items_rest.py
tests/api/patrons/test_patrons_rest.py
tests/data/data.json
tests/fixtures/circulation.py
tests/ui/items/test_items_api.py
tests/ui/local_fields/test_local_fields_api.py
tests/ui/patrons/test_patrons_api.py
tests/unit/documents/test_documents_dojson_marc21.py

- Adds an extended validation method to patrons and items to ensure that barcode fields are unique.
- Deletes barcodes in item test fixtures so that they are generated and avoid duplicate barcode errors on item creation.
- Fixes test errors related to duplicate item and patron barcodes.
- Closes #3386.

items+patrons: fix unique barcodes

---

rero_ils/modules/commons/exceptions.py
rero_ils/modules/items/dumpers.py
rero_ils/modules/items/views/api_views.py
rero_ils/modules/libraries/dumpers.py
tests/api/items/test_items_issue.py
tests/ui/items/test_items_dumpers.py
tests/ui/libraries/test_libraries_dumpers.py

* Closes rero/rero-ils#3379.
* Checks if all requires data are available to render the claim notification content. If not, return a specific exception to specify the missing data.

claims: manage missing data for claim notification

---

rero_ils/modules/entities/replace.py

entities: fix replace identified by

---

README.md

Very minor fix, but mentioning "Catholic University of Leuven" is pointing at the wrong university.
UCLouvain (University of Louvain) ≠ KU Leuven (University of Leuven)

Update README.md: Louvain (≠ Leuven)

---

rero_ils/modules/loans/logs/api.py
tests/ui/loans/test_loans_operation_logs.py

* Existing invalid data will be corrected manually as an Alembic script would take 5 days to run with several million operation logs.

operation logs: anonymization respects jsonschema

---

rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json

* Corrects the label of the oneOf to be clearer for librarians.

editor: correct label for Media Type

---

rero_ils/modules/loans/dumpers.py
rero_ils/modules/locations/api.py

* Adds the location pickup_name field on circulation information.
* Closes #3433.

loan: add location pickup_name on dump

---

rero_ils/config.py
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json

Items sorting on standard holdings takes into consideration the numerical values in the character string.
* Closes #2243.
* Fixes noquery configuration on items sort.
⚠️  migration: items reindexing.

items: sorting for standard holdings

---

rero_ils/modules/acquisition/acq_orders/api.py

Line sorting is now done on the PID to keep the same order as the command.
* Closes #2653.

acquisitions: sort lines in order

---

rero_ils/config.py
rero_ils/modules/documents/jsonschemas/documents/document_subjects_entity_link-v0.0.1.json
rero_ils/modules/entities/remote_entities/jsonschemas/remote_entities/remote_entity-v0.0.1.json
rero_ils/modules/entities/remote_entities/proxy.py
tests/api/entities/remote_entities/test_remote_entities_rest.py
tests/conftest.py
tests/data/data.json
tests/data/mef.json
tests/fixtures/mef.py
tests/fixtures/metadata.py
tests/ui/entities/remote_entities/test_remote_entities_api.py

entities: add place

---

rero_ils/config.py
rero_ils/modules/acquisition/acq_orders/views.py
rero_ils/modules/notifications/subclasses/acq_order.py

If the vendor's communication language is not defined, we use the default language (eng).
* Closes #2714.

acquisition: fix default vendor language

---

rero_ils/modules/entities/remote_entities/replace.py

entity: better replace identifiedBy

---

rero_ils/dojson/utils.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/loc/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/imports/serializers/serializers.py
tests/unit/documents/test_documents_dojson.py

* Make SLSP import more robust against wrong MARC21 for example 019 has no subfields.
* Closes https://github.com/rero/rero-ils/issues/3468.

import: fix import SLSP

---

rero_ils/modules/acquisition/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
rero_ils/modules/entities/local_entities/jsonschemas/local_entities/local_entity_organisation-v0.0.1.json
rero_ils/modules/entities/local_entities/jsonschemas/local_entities/local_entity_work-v0.0.1.json
rero_ils/translations/ar/LC_MESSAGES/messages.po
rero_ils/translations/de/LC_MESSAGES/messages.po
rero_ils/translations/en/LC_MESSAGES/messages.po
rero_ils/translations/eo/LC_MESSAGES/messages.po
rero_ils/translations/es/LC_MESSAGES/messages.po
rero_ils/translations/fr/LC_MESSAGES/messages.po
rero_ils/translations/it/LC_MESSAGES/messages.po
rero_ils/translations/messages.pot
rero_ils/translations/nl/LC_MESSAGES/messages.po
rero_ils/translations/ru/LC_MESSAGES/messages.po
rero_ils/translations/zh_Hant/LC_MESSAGES/messages.po

* Unicode values are not correctly translated, so we should avoid using them in the jsonschemas.

translations: fix unicode chars in jsonschemas

---

rero_ils/modules/notifications/subclasses/availability.py

* The delay for availability notification is set in minutes in the ui/data but must be passed in seconds to the dispatcher.
* Closes #3467.

notifications: fix availability delay

---

rero_ils/modules/stats/api/pricing.py
tests/api/stats/test_stats_rest.py
tests/ui/stats/test_stats_pricing.py

* Fix the count of number of ILL request to be coherent with RERO+'s pricing criteria. All ILL requests created within the timeframe except those with the status "denied" are counted.
* The calculation is simplified and does not use operation logs, which created problems.

pricing stats: fix number of ill requests

---

rero_ils/modules/entities/remote_entities/cli.py
rero_ils/modules/entities/remote_entities/replace.py
tests/ui/entities/remote_entities/test_remote_entities_api.py

* Corrects handling of rero only and not found identifiers.

entity: better replace_identified_by

---

rero_ils/modules/entities/remote_entities/tasks.py

* Uses in memory for the sync task.

entity: use in memory for sync task

---

rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json

* A delay too high can cause problems in the workers if a task is not acknowledged after the chosen RabbitMQ delay.

notifications: set a maximum delay

---

rero_ils/modules/entities/remote_entities/cli.py

* Adds default value `None` (all) for option -f --field.

remote entities: fix replace-identified-by cli

---

rero_ils/config.py
rero_ils/modules/documents/api_views.py
rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
rero_ils/modules/patrons/views.py
tests/api/documents/test_documents_rest.py

* Adds configuration for enabled/disabled advanced search.
* Adds a new field in the document schema to group
call number for holdings and items.
* Adds a new endpoint for advanced search config.
⚠️  update ES mapping and reindex ES documents

document: advanced search config and endpoint

---

rero_ils/modules/stats/api/librarian.py

When this fix is deployed, we need to correct the numbers with this script: 
```python
from rero_ils.modules.stats.api.librarian import StatsForLibrarian
from rero_ils.modules.stats.api.api import Stat, StatsSearch
search = StatsSearch()\
.filter('range', _created={'gte': '2023-05-30'})
for hit in list(search.source('pid').scan()):
try:
stat = Stat.get_record(hit.meta.id)
if stat['type'] == 'librarian':
compute = StatsForLibrarian()
compute.date_range = stat['date_range']
for val in stat.get('values', []):
lib_pid = val['library']['pid']
new_new_active_patrons_by_postal_code = compute.active_patrons_by_postal_code(lib_pid, new_patrons=True)
val['new_active_patrons_by_postal_code'] = new_new_active_patrons_by_postal_code
stat.update(stat, commit=True, dbcommit=True, reindex=True)
except …
```

librarian stats: fix incorrect new active patrons

---

rero_ils/config.py

* The field `status` is now labelled "request_status". Adapts the facet title to adhere to this.

ill requests: adapt facet label

---

rero_ils/modules/items/dumpers.py
tests/ui/items/test_items_dumpers.py

* The UI needs to display the number of current pending requests for an item-loan couple so we add it in the dumper.

fix: add pending requests count to dumper

---

poetry.lock
pyproject.toml

* Safety>=3.0.0 creates a conflict between pyjwt and jwt.
* Updates poetry lock dependencies.

chore(dependencies): fix safety conflict

---

rero_ils/modules/items/api/api.py
tests/ui/items/test_items_api.py

* Items without loans that are in_transit should be marked as unavailable.
* Closes #2827.

fix(items): availability for in_transit items

---

data/documents_small.json
rero_ils/modules/documents/dojson/contrib/marc21tojson/rero/model.py
rero_ils/modules/documents/dojson/contrib/marc21tojson/utils.py
rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
rero_ils/modules/documents/jsonschemas/documents/document_part_of-v0.0.1.json
tests/data/data.json
tests/unit/documents/test_documents_dojson.py
tests/unit/documents/test_documents_dojson_unimarc.py

* Closes #3570.
* Closes #1818.
* ⚠️ On migration, we need to convert the fields
`document.partOf.numbering.volume` and `document.partOf.numbering.issue`
from integers to strings in the db (the mappings stay the same).

partof: allow strings for volume and issue

---

rero_ils/modules/api.py

* Standard usage warnings should be ignored in Sentry.
* Close: #3600

monitoring: better standard usage warnings

---

rero_ils/modules/items/views/api_views.py
tests/api/items/test_items_rest_views.py

To obtain the correct count, operation logs must be filtered using loan records only.
* Closes #3656.

fix(operation_log): circulation operation count

---

rero_ils/config.py
rero_ils/theme/templates/rero_ils/trackingcode.html
tests/ui/test_views.py

The key can be customised in the application configuration.
⚠️  add RERO_ILS_GOOGLE_ANALYTICS_TAG_ID on the configuration.

chore: add google analytics configuration

---

rero_ils/query.py

* If we display "validated" requests, the filter is useless.

fix(ill): only show 6m+ ill if pending

---

rero_ils/modules/holdings/listener.py
tests/ui/holdings/test_holdings_patterns.py
tests/ui/holdings/test_issues_reindex.py
tests/ui/holdings/test_serial_claims.py

* Serial items should correctly inherit their inherited_call_numbers
in the index after editing the parent serial holdings.
* Refactored the `update_items_locations_and_types` function.
* Fixed incorrect tests for item-issue fields inheritance.

fix(holdings): items inherit call numbers 

---

data/items_big.json
data/items_small.json
rero_ils/modules/items/cli.py
rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
rero_ils/modules/items/serializers/__init__.py
rero_ils/modules/items/serializers/collector.py
rero_ils/modules/items/views/api_views.py
tests/api/items/test_items_rest_views.py
tests/api/items/test_items_serializer.py
tests/data/data.json
tests/unit/test_items_jsonschema.py

* RERO+ clients still need this field.

fix(items): restore legacy checkout count

---

rero_ils/modules/documents/api.py
rero_ils/modules/entities/api.py
tests/data/mef.json
tests/ui/entities/remote_entities/test_remote_entities_api.py
tests/unit/documents/test_documents_dojson_marc21.py

* Adds organisation pids for `subjects` and `genreForm`` during document reindexing.
* Closes: #3672

entities: add organisation pids

---

rero_ils/modules/acquisition/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
rero_ils/modules/acquisition/acq_receipt_lines/jsonschemas/acq_receipt_lines/acq_receipt_line-v0.0.1.json
rero_ils/modules/acquisition/acq_receipts/jsonschemas/acq_receipts/acq_receipt-v0.0.1.json
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json

* minItems: 0 prevents some fields to be displayed in edit mode, especially the notes field in acquisition receipts and orders.
* Closes #3709.

fix(jsonschemas): fix minItems

---

poetry.lock
pyproject.toml
scripts/setup

* Fix setuptools version to fix tests.
* To save time for local testing, the default setup
(without `--deployment`) doesn't load files fixtures by default.

fix(tests): pin setuptools version

---

rero_ils/modules/circ_policies/api.py
rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
tests/ui/circ_policies/test_circ_policies_api.py

* Reorders jsonschema to be more coherent.
* Adds hide and required expressions for the cipo editor so that checkouts and renewals settings are consistent with one another.
* Adds an extended validation to prevent circulation policies with renewals enabled but no renewal_duration, which would lead to an error when trying to renew.

fix(circulation policies): improve data consistency

---

rero_ils/modules/documents/jsonschemas/documents/document_series-v0.0.1.json

* Workaround for default value problem in third level arrays. See: https://github.com/ngx-formly/ngx-formly/issues/3974.

fix(editor): seriesStatement becoming invalid if deleted and re-added

---

rero_ils/config.py
rero_ils/modules/documents/tasks.py
tests/ui/documents/test_documents_api.py

fix(documents): delete orphan harvested documents

---

rero_ils/modules/acquisition/acq_invoices/api.py
rero_ils/modules/acquisition/acq_orders/api.py
rero_ils/modules/acquisition/acq_receipts/api.py
rero_ils/modules/holdings/api.py
rero_ils/modules/loans/api.py
rero_ils/modules/locations/api.py
scripts/test
tests/api/circulation/test_locations_restrictions.py
tests/ui/circulation/test_loan_utils.py

loan: fix organisation_pid function

---

pyproject.toml
rero_ils/modules/patrons/views.py
rero_ils/oauth/scopes.py
setup.py
tests/api/patrons/test_patrons_rest.py

* Adds `user_id`.
* Adds `patron_info` scope with patron pid, patron type, institution
and expiration_date.
* Marks `patron_types` as deprecated.
* Closes #3778.

oauth: adds user_id and patron_info

---

rero_ils/config.py
rero_ils/modules/acquisition/acq_order_lines/api.py
rero_ils/modules/acquisition/cli.py
rero_ils/modules/acquisition/rollover.py
tests/api/acquisition/test_acquisition_rollover.py

* Adds logging file parameter to rollover cli.
* Adds time stamp to log file if no file parameter is given.
* Closes #3560.

acquisition: add logging file to rollover cli

---

rero_ils/modules/loans/logs/api.py
tests/ui/loans/test_loans_operation_logs.py

fix(loans): anonymize notification's recipients

---

.github/workflows/continuous-integration-test.yml
poetry.lock
pyproject.toml
pytest.ini
rero_ils/dojson/utils.py
rero_ils/modules/serializers/__init__.py
rero_ils/modules/utils.py
rero_ils/modules/views.py
tests/ui/locations/test_locations_other.py
tests/ui/patron_transactions/test_patron_transactions_api.py
tests/ui/test_filters.py
tests/ui/test_permissions.py

- Constraints isort>=6.0.0 to make sure tests pass and fixes code style errors.
- Constraints black version to pass tests.
- Constraints babel version to fix date_filter comma problem.
- Fixes unwanted warning annotations in github actions
with `pytest-github-actions-annotate-failures`>0.3.0.

fix(tests): fix test problems

---

rero_ils/modules/stats/api/pricing.py
tests/ui/stats/test_stats_pricing.py

- The correct date range for number_of_active_patrons in the pricing stats should be 12 months and not the default `RERO_ILS_STATS_BILLING_TIMEFRAME_IN_MONTHS`.

fix(stats): make active patrons period 12 months

---

rero_ils/modules/entities/templates/rero_ils/_remote_person.html

* Entities' dates are string fields, they should not be formatted by the interface, otherwise they display wrong data. E.g. if "date of birth" is only a year (very frequent), the formatting will add a day/month.

fix(entities): wrong date in public view

---

rero_ils/config.py
tests/api/acq_orders/test_acq_orders_rest.py

* Points the order_date facet to the correct field, which was moved from the order_line directly to the order.

fix(acq_orders): order date facet content

---

rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html

Linked to https://github.com/rero/rero-ils-ui/pull/1311.

fix(babeltheque): prevent "more info" to display before the ng app

---

rero_ils/modules/acquisition/acq_order_lines/api.py
rero_ils/modules/acquisition/acq_order_lines/permissions.py
rero_ils/modules/acquisition/acq_receipt_lines/api.py
rero_ils/modules/acquisition/acq_receipt_lines/permissions.py
rero_ils/modules/acquisition/acq_receipts/api.py
rero_ils/modules/acquisition/acq_receipts/permissions.py
scripts/test
tests/api/acq_receipts/test_acq_receipts_permissions.py
tests/api/acq_receipts/test_acq_receipts_rest.py
tests/ui/acq_receipts/test_acq_receipts_jsonresolver.py

* Adds a message when a receipt, receipt line, order cannot be deleted due to the order status.

chore(permissions): add details for acquisition permissions
