rero/rero-ils

- AUTHORS.rst
- CONTRIBUTING.rst
- INSTALL.rst
- README.rst
* update installation documentation
* update contributing documentation
Co-authored-by: Nicolas Labat <nicolas.labat@rero.ch>
- get the PR
- check the `INSTALL.rst` file
- test the installation method
- check the `CONTRIBUTING.rst` file
- run the tests
> documentation: installation and contributing

- run-tests.sh
> fix: add exception on pipenv check

- .gitignore
- MANIFEST.in
- rero_ils/bundles.py
- rero_ils/config.py
- rero_ils/modules/documents_items/static/templates/rero_ils/brief_view_documents_items.html
- rero_ils/modules/documents_items/templates/rero_ils/detailed_view_documents_items.html
- rero_ils/static/css/rero_ils/thumbnail.scss
- rero_ils/static/js/rero_ils/detailed_app.js
- rero_ils/static/js/rero_ils/search_app.js
- rero_ils/static/js/rero_ils/thumbnail.js
- rero_ils/templates/rero_ils/search.html
- setup.py
Co-authored-by: Peter Weber <peter.weber@rero.ch>
Co-authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
> feat: add cover render services to brief and full view

- rero_ils/bundles.py
- rero_ils/config.py
- rero_ils/filter.py
- rero_ils/modules/ext.py
- rero_ils/modules/items/views.py
- rero_ils/modules/persons/static/templates/rero_ils/brief_view_mef_persons.html
- rero_ils/modules/persons/templates/rero_ils/_person_merged.html
- rero_ils/modules/persons/templates/rero_ils/_person_separated.html
- rero_ils/modules/persons/templates/rero_ils/_person_separated_data.html
- rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
- rero_ils/modules/persons/views.py
- rero_ils/static/css/rero_ils/search.css
- setup.py
- tests/modules/conftest.py
- tests/modules/persons/test_persons_filter.py
- tests/modules/test_filter.py
To test:
Nedded: rero-ils with mef records
See: http://localhost:5002/persons/1
> person detailed view

- rero_ils/config.py
- rero_ils/modules/persons/mappings/v6/persons/mef-person-v0.0.1.json
- rero_ils/modules/persons/static/templates/rero_ils/brief_view_mef_persons.html
- rero_ils/static/css/rero_ils/search.css
- scripts/setup
Co-authored-by: Peter Weber <peter.weber@rero.ch>
> feat: add source facet and source badge on briew view person

- rero_ils/bundles.py
- rero_ils/static/js/rero_ils/search_app.js
- rero_ils/static/js/rero_ils/thumbnail.js
- rero_ils/templates/rero_ils/search.html
> feat: Remove invenioSearchConfig and replace with invenioConfig

- data/oaisources.yml
- rero_ils/modules/cli.py
- rero_ils/modules/ebooks/cli.py
- rero_ils/modules/ebooks/utils.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/organisations_members/cli.py
- rero_ils/modules/patrons/cli.py
fix: oaiharharvest port 8443
feat: invenio cli utils display of schedules
feat: update of oaiharvest configurations
> oaiharvest port 8443

- .gitignore
* add files to .gitignore
**PLEASE**, let me know if there's some more files or directories to be ignored!
> git: gitignore extension

- rero_ils/modules/items/views.py
> missing format_date_filter in items/view

- rero_ils/modules/apiharvester/cli.py
- rero_ils/modules/apiharvester/tasks.py
- rero_ils/modules/apiharvester/utils.py
- rero_ils/modules/ebooks/receivers.py
- scripts/server
- scripts/setup
new parameter -m --max for
`invenio apiharvester harvest -n mef`
>  mef max harvest

- Pipfile
- Pipfile.lock
- rero_ils/manual_translations.txt
- rero_ils/modules/persons/templates/rero_ils/_person_merged.html
- rero_ils/modules/persons/templates/rero_ils/_person_separated_data.html
- rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
* FIX: make the MEF Persons labels extractable
* BETTER: update the translations
> User interface: translations

- Pipfile
- Pipfile.lock
- requirements-devel.txt
- rero_ils/config.py
- rero_ils/modules/documents_items/api.py
- rero_ils/modules/items/api.py
* NEW makes invenio circ APIs available
To test:
- ./scripts/bootstrap
- ./scripts/setup
- ./run_tests.sh
To test some circulation transactions, check examples in Taiga:
https://tree.taiga.io/project/rero21-reroils/task/708?kanban-status=1224894
> Circulation: integration of invenio-circulation APIs

- rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
* NEW: Add title on tab list of presentation
* closes #137
> Issue: Identify the two separate displays in the person detailed view

- rero_ils/config.py
- rero_ils/modules/patrons/form_options/patrons/patron-v0.0.1.json
- rero_ils/modules/patrons/utils.py
* FIX: patron parcode missing
* closes #37
* closes #48
> ISSUSES: patron parcode

- .travis.yml
- Pipfile.lock
- rero_ils/config.py
* FIX: fix transitions circulation configuration due to refactoring
Co-authored-by: Johnny Mariéthoz <johnny.mariéthoz@rero.ch>
> Circulation: configuration

- rero_ils/modules/api.py
- tests/modules/test_api.py
> replace function

- data/organisations-libraries-locations.json
* BETTER: exception dates for all librarieswq
Signed-off-by: Nicolas Labat <n-labat@hotmail.com>
To test : 
Check that all libraries have opening hours and date exceptions
> FIXTURE: libraries opening hours and exception dates

- rero_ils/modules/api.py
- rero_ils/modules/documents_items/api.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/libraries_locations/api.py
- rero_ils/modules/organisations_libraries/api.py
- rero_ils/modules/utils.py
- tests/conftest.py
- tests/modules/libraries/test_libraries_api.py
* NEW: library is_open function
open the console and try to test the new date functions from library
> API: library is open

- rero_ils/config.py
- rero_ils/modules/documents_items/cli.py
- rero_ils/modules/documents_items/templates/rero_ils/detailed_view_documents_items.html
- rero_ils/modules/documents_items/views.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/items/views.py
- rero_ils/modules/items_types/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/utils.py
- rero_ils/modules/patrons/api.py
- tests/conftest.py
- tests/e2e/modules/items/test_items_views.py
- tests/modules/items/test_items_api.py
- tests/modules/items/test_items_cli.py
NEW: Basic circulation policies
BETTER: Circulation APIs
Co-Authored-by: Gianni Pante gianni.pante@rero.ch
To Test:
get the PR branch
./scripts/bootstrap
./run_tests.sh
> Basic circulation policies

- Pipfile
- Pipfile.lock
- rero_ils/views.py
- run-tests.sh
* FIX closes #164
Try to create a new user.
> User: critical bug at menu initialization

- data/circulation_policies.json
- data/items_types.json
- data/patrons_types.json
- rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
NEW: Circ policies settings
To Test:
get the PR branch
./run_tests.sh
> Circulation policies settings

- rero_ils/modules/documents_items/templates/rero_ils/detailed_view_documents_items.html
- rero_ils/modules/documents_items/templates/rero_ils/export_documents_items.html
* BETTER: implement new layout to the document view
----------
- display a document detailed view
- clic on the export JSON link at the page bottom
> Layout: document export view

- rero_ils/config.py
- scripts/setup
BETTER: Limit Mef harvesting to 1000 records
Signed-off-by: Aly Badr aly.badr@rero.ch
To Test:
Nothing really to test but you may follow these:
get the PR branch
./run_tests.sh
> Scripts: MEF harvesting

- Pipfile
- Pipfile.lock
- rero_ils/config.py
- rero_ils/modules/__init__.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/circ_policies/views.py
- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/ebooks/tasks.py
- rero_ils/modules/item_types/api.py
- rero_ils/modules/item_types/views.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/items/views.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/locations/api.py
- rero_ils/modules/mef_persons/api.py
- rero_ils/modules/organisations/api.py
- rero_ils/modules/patron_types/api.py
- rero_ils/modules/patron_types/views.py
- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/jsonschemas/form_patrons/patron-v0.0.1.json
- rero_ils/modules/patrons/listener.py
- rero_ils/modules/patrons/views.py
- tests/api/test_locations_rest.py
* Fixes new isort version.
* Fixes resolve param in REST API.
* Adds test for resolve param.
* NEW Default circulation policiy for requests.
* Fixes json indentations.
Signed-off-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>
> all: several fixes

- data/circulation_policies.json
- data/item_types.json
- data/patron_types.json
- data/users.json
- rero_ils/config.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/utils.py
- rero_ils/modules/patrons/api.py
- tests/api/test_items_rest.py
- tests/conftest.py
- tests/data/data.json
- tests/ui/items/test_items_api.py
NEW: Integrate Circ policies with invenio circulation
How to test:
* ./scripts/bootstrap
* ./scripts/setup
* localhost:5000, place checkout/renewal and make sure due date is correctly calculated according to configured circ policies
> Circulation: Circ policies backend

- rero_ils/modules/serializers.py
* FIX: check value on resolve serializer
> SERIALIZER: Fix resolve

- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/circ_policies/mappings/v6/circ_policies/circ_policy-v0.0.1.json
- tests/conftest.py
- tests/data/data.json
- tests/ui/circ_policies/test_circ_policies_utils.py
- tests/utils.py
* NEW Changes cipo mapping settings to nested
* FIX Fixes elasticsearch queries to locate policies
* NEW lists loaded resources for unittest sessions
Signed-off-by: Gianni Pante <gianni.pante@rero.ch>
- `./script/bootstrap`
- `./scripts/setup`
- UI: Place a checkout transaction and make sure you are using the correct circ policy
> Circulation: nested mapping for cipo settings

- data/circulation_policies.json
- rero_ils/modules/items/api_views.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/loans/utils.py
- tests/api/test_items_rest.py
- tests/utils.py
- ui/src/app/circulation/items.service.ts
- ui/src/app/circulation/main-checkin-checkout/main-checkin-checkout.component.ts
* NEW Adds circ policies logic to circulation UI and APIs
* FIX Fixes circ policy fixtures for no-checkout itemtype
* BETTER Replaces hard-coded item_type by circ policies
Signed-off-by: Gianni Pante <gianni.pante@rero.ch>
- `./script/bootstrap`
- `./scripts/setup`
- Test circ transactions in circulation UI
> Circulation: Policy adapting for CIRC UI

- rero_ils/modules/loans/mappings/v6/loans/loan-ils-v0.0.1.json
- scripts/setup
* FIX: loan ,mapping settings
* DELETE: loan mappings from invenio-cerculations
Signed-off-by: Peter Weber <peter.weber@rero.ch>
> ES: loan mapping

- rero_ils/modules/item_types/api.py
- rero_ils/modules/patron_types/api.py
* FIX Fixes es query for finding item and patron types links
closes #227
- Try to delete an item_type or patron_type that is linked to a circulation policy, you will receive an alert.
> RECORDS: can_delete fix for item and patron types

- ui/src/app/records/custom-editor/libraries/library-form.service.ts
- ui/src/app/records/custom-editor/libraries/library.component.ts
* FIX Fixes existing data for multiple library editor calls, closes #221.
> UI: clear library form after edit

- Pipfile
- Pipfile.lock
- setup.py
* Fixes translations cli commands since the `invenio-search-ui` removal.
> TRANSLATIONS: translations command line resolution

- rero_ils/config.py
- ui/src/app/core/manual-translations.ts
- ui/src/assets/i18n/de.json
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/en_US.json
- ui/src/assets/i18n/fr.json
- ui/src/assets/i18n/it.json
* FIX Fixes missing subject facet.
> API: subject facet resolution

- tests/api/test_items_rest.py
* FIX Fixes the assert problem on items rest api tests.
Signed-off-by: Aly Badr aly.badr@rero.ch
To test: 
./run-tests.sh
> fix: a fix for loan extension assert problem

- rero_ils/modules/circ_policies/__init__.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/circ_policies/jsonschemas/__init__.py
- rero_ils/modules/circ_policies/mappings/__init__.py
- rero_ils/modules/circ_policies/mappings/v6/__init__.py
- rero_ils/modules/circ_policies/models.py
- rero_ils/modules/circ_policies/views.py
- tests/api/test_circ_policies_rest.py
- tests/ui/circ_policies/test_circ_policies_api.py
- tests/ui/circ_policies/test_circ_policies_utils.py
- tests/unit/test_circ_policies_jsonschema.py
* BETTER Increase test coverage and add docs for cipo.
./run-tests.sh
test coverage for rero_ils/modules/circ_policies is 100%
> global: test coverage and docs for cipo

- rero_ils/modules/item_types/api.py
- rero_ils/modules/item_types/jsonresolver.py
- rero_ils/modules/item_types/jsonschemas/__init__.py
- rero_ils/modules/item_types/mappings/__init__.py
- rero_ils/modules/item_types/mappings/v6/__init__.py
- rero_ils/modules/item_types/views.py
- tests/api/test_item_types_rest.py
- tests/ui/item_types/test_item_types_api.py
- tests/ui/item_types/test_item_types_jsonresolver.py
* BETTER increase test coverage and add docs for item types.
./run-tests.sh
test coverage for rero_ils/modules/item_types is 100%
> global: test coverage and docs for item types

- rero_ils/modules/patron_types/__init__.py
- rero_ils/modules/patron_types/api.py
- rero_ils/modules/patron_types/jsonresolver.py
- rero_ils/modules/patron_types/jsonschemas/__init__.py
- rero_ils/modules/patron_types/mappings/__init__.py
- rero_ils/modules/patron_types/mappings/v6/__init__.py
- rero_ils/modules/patron_types/views.py
- tests/api/test_patron_types_rest.py
* BETTER increase test coverage and add docs for patron types.
> global: test coverage and docs for patron types

- ui/src/app/records/search/brief-view/patrons-brief-view.component.ts
* FIX Changes id to name on patron brief view.
- bootstrap
> user interface: patron type name and library name

- rero_ils/modules/organisations/jsonresolver.py
- rero_ils/modules/organisations/jsonschemas/__init__.py
- tests/api/test_organisations_rest_api.py
- tests/ui/organisations/test_organisations_jsonresolver.py
* BETTER increase test coverage and add docs for organisations.
./run_tests should show that modules/organisations coverage is at 100%
> global: test coverage and docs for organisations

- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/loans/api.py
- tests/api/test_items_rest.py
- tests/conftest.py
- tests/data/data.json
- ui/src/app/circulation/main-checkin-checkout/main-checkin-checkout.component.ts
* FIX Fixes #235: automatic validation for checked-in items at requested location.
* FIX Fixes #58: librarian notified after check-in of a requested item.
- ./scripts/bootstrap
- UI: check-in of requested item generates librarian notification and item correct status
> circulation: correct item status after checkin a requested item

- .coveragerc
- MANIFEST.in
- rero_ils/modules/libraries/__init__.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/libraries/jsonresolver.py
- rero_ils/modules/libraries/jsonschemas/__init__.py
- rero_ils/modules/libraries/mappings/__init__.py
- tests/api/test_libraries_rest.py
- tests/data/data.json
- tests/ui/libraries/test_libraries_api.py
- tests/ui/libraries/test_libraries_jsonresolver.py
- tests/unit/test_libraries_jsonschema.py
* BETTER increase test coverage and add docs for libraries.
* NEW exclude cli files from code coverage
> global: test coverage and docs for libraries

- rero_ils/modules/errors.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/items/jsonschemas/__init__.py
- rero_ils/modules/items/mappings/__init__.py
- rero_ils/modules/items/mappings/v6/__init__.py
- rero_ils/modules/items/views.py
- tests/api/test_items_rest.py
- tests/api/test_items_rest_views.py
- tests/data/data.json
- tests/fixtures/circulation.py
- tests/ui/items/test_items_api.py
* BETTER increase test coverage and add docs for items.
> global: test coverage and docs for items

- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/jsonresolver.py
- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/documents/views.py
- tests/api/test_documents_rest.py
- tests/api/test_items_rest_views.py
- tests/fixtures/metadata.py
- tests/ui/documents/test_documents_api.py
- tests/ui/documents/test_documents_jsonresolver.py
- tests/ui/documents/test_documents_ui.py
- tests/unit/test_documents_jsonschema.py
* BETTER increase test coverage and add docs for documents.
> global: test coverage and docs for documents

- data/locations.json
- rero_ils/config.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/ext.py
- rero_ils/modules/items/listener.py
- rero_ils/modules/items/mappings/v6/items/item-v0.0.1.json
- rero_ils/modules/locations/listener.py
- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/listener.py
- rero_ils/modules/patrons/mappings/v6/patrons/patron-v0.0.1.json
- rero_ils/permissions.py
- rero_ils/query.py
- tests/api/test_circ_policies_rest.py
- tests/api/test_documents_rest.py
- tests/api/test_item_types_rest.py
- tests/api/test_items_rest.py
- tests/api/test_libraries_rest.py
- tests/api/test_locations_rest.py
- tests/api/test_patron_types_rest.py
- tests/api/test_patrons_rest.py
- tests/data/data.json
- tests/fixtures/circulation.py
- tests/fixtures/metadata.py
- tests/ui/items/test_items_api.py
- tests/ui/locations/test_locations_api.py
- tests/ui/patrons/test_patrons_api.py
* NEW Filter list result for REST API by organisation.
> rest API: organisation filter

- rero_ils/filter.py
- rero_ils/modules/api.py
- rero_ils/modules/circ_policies/views.py
- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/item_types/views.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/patron_types/views.py
- rero_ils/modules/patrons/listener.py
- rero_ils/permissions.py
- rero_ils/views.py
- tests/ui/conftest.py
- tests/ui/items/test_items_api.py
- tests/ui/loans/test_loans_api.py
- tests/ui/mef_persons/test_mef_persons_api.py
- tests/ui/mef_persons/test_mef_persons_ui.py
- tests/ui/patron_types/test_patron_types_api.py
- tests/ui/patron_types/test_patron_types_jsonresolver.py
- tests/ui/patrons/test_patrons_api.py
- tests/ui/test_api.py
- tests/ui/test_views.py
- tests/unit/test_filter.py
- tests/utils.py
* BETTER increase test coverage and add docs for non modules.
> global: test coverage and docs for non modules

- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/loans/utils.py
- rero_ils/modules/patrons/api.py
- tests/api/test_items_rest_views.py
* FIX Fixes issue when patron type pid was not right.
./run_tests.sh
> fix: patron type pid shortcut

- Pipfile
- Pipfile.lock
* FIX Fixes error message `TypeError: can't serialize datetime.datetime` in the log server.
> tasks: celery version constraint addition

- rero_ils/permissions.py
- tests/ui/test_permissions.py
* FIX Fixes problem when displaying document with items.
> fix: document with items failure to display

- .gitmessage.txt
- CONTRIBUTING.rst
> documentation: update commit message template

- rero_ils/config.py
- rero_ils/modules/ext.py
- tests/api/test_patrons_rest.py
- tests/api/test_patrons_views.py
* FIX Fixes error during an non-existing patron creation.
> API: Patron creation problem

- rero_ils/config.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/patrons/api.py
- rero_ils/permissions.py
- tests/api/test_permissions_librarian.py
- tests/api/test_permissions_patron.py
- tests/api/test_permissions_sys_librarian.py
- tests/fixtures/circulation.py
- tests/ui/circ_policies/test_circ_policies_api.py
* NEW Grants full rights to sytem_librarian.
* NEW Denies librarian rights to edit, delete, add a system_librarian.
* BETTER Improves permission factoreis.
./run_tests.sh
- a librarian receives 403 when trying to add system_librarian role or edit/delete a system_librarian user
- system_librarian has full right
- patron, no rights
> permissions: secure patron records api

- rero_ils/config.py
- rero_ils/permissions.py
- tests/api/test_permissions_librarian.py
* Reduces librarian rights to the library level for the resource patron
> permissions: allows librarian to manipulate users of its library only

- rero_ils/modules/patrons/api.py
- rero_ils/permissions.py
- tests/api/test_documents_rest.py
- tests/api/test_items_rest.py
- tests/api/test_items_rest_views.py
- tests/api/test_loans_rest.py
- tests/api/test_patron_types_rest.py
- tests/api/test_patrons_rest.py
- tests/api/test_patrons_views.py
- tests/api/test_permissions_librarian.py
- tests/api/test_permissions_patron.py
- tests/api/test_permissions_sys_librarian.py
- tests/data/data.json
- tests/fixtures/circulation.py
- tests/ui/patrons/test_patrons_api.py
Improves users for tests: each user has only one role, patron, librarian
or system librarian. New users has been created to be close to a real
system.
> tests: add several users for testing

- rero_ils/modules/loans/api.py
- tests/api/test_loans_rest.py
* Adds automatically a due soon notification when a checked-out item is requested.
> notifications: create due soon notification

- rero_ils/modules/loans/api.py
- rero_ils/modules/notifications/api.py
- tests/api/test_loans_rest.py
* Adds first reminder notification when a checked-out item is overdue.
> notifications: first reminder notification

- rero_ils/modules/loans/api.py
- rero_ils/modules/notifications/api.py
- tests/api/test_documents_rest.py
- tests/api/test_loans_rest.py
- tests/api/test_notifications_rest.py
- tests/api/test_patrons_views.py
- tests/data/data.json
- tests/fixtures/circulation.py
- tests/fixtures/metadata.py
- tests/fixtures/organisations.py
- tests/ui/loans/test_loans_api.py
- tests/ui/loans/test_loans_jsonresolver.py
- tests/ui/notifications/test_notifications_api.py
- tests/ui/patrons/test_patrons_ui.py
- tests/unit/test_notifications_jsonschema.py
* Adds additional units tests for notifications.
* Deletes unused-imports from some files.
> notifications: complete units tests

- rero_ils/config.py
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/serializers.py
- rero_ils/modules/utils.py
- rero_ils/permissions.py
- tests/api/test_circ_policies_rest.py
- tests/api/test_documents_rest.py
- tests/api/test_item_types_rest.py
- tests/api/test_items_rest_views.py
- tests/api/test_loans_rest.py
- tests/api/test_serializers.py
- tests/conftest.py
- tests/ui/test_permissions.py
- tests/utils.py
- ui/src/app/records/records.service.ts
> REST API: add permission informations

- rero_ils/modules/loans/api.py
- rero_ils/modules/notifications/__init__.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/notifications/dispatcher.py
- rero_ils/modules/notifications/jsonschemas/__init__.py
- rero_ils/modules/notifications/listener.py
- rero_ils/modules/notifications/mappings/__init__.py
- rero_ils/modules/notifications/mappings/v6/__init__.py
- rero_ils/modules/notifications/models.py
- rero_ils/modules/notifications/tasks.py
- rero_ils/modules/notifications/templates/email/availability_eng.txt
- rero_ils/modules/notifications/templates/email/due_soon_eng.txt
- rero_ils/modules/notifications/templates/email/overdue_eng.txt
- rero_ils/modules/notifications/templates/email/recall_eng.txt
- rero_ils/modules/notifications/views.py
- rero_ils/utils.py
- tests/api/test_notifications_rest.py
- tests/api/test_patrons_views.py
- tests/conftest.py
- tests/fixtures/circulation.py
- tests/ui/notifications/test_notifications_api.py
* Adds notification dispatchers
Try to create a notification and verify received email.
> notifications: create notification dispatcher

- tests/ui/notifications/test_notifications_api.py
* Improves units testing to have a separate test for functionality.
> notifications: split notifications es and creations tests.

- rero_ils/modules/serializers.py
* Fixes When a record doesn't exist in the database (ie MEF records), then the permissions are obviously denied.
> serializer: permissions on a non-existing record

- data/300.json
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- tests/unit/test_documents_dojson.py
* Fixes publishers data to 264
> Fixtures: dojson RDA transformation

- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
* Adds call_number on item in document.
> document: call_number on item

- rero_ils/modules/documents/jsonresolver_mef_person.py
- rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
- rero_ils/utils.py
- tests/unit/test_utils.py
* Adds MEF variante_name on author.
> document: MEF variant_name for author

- rero_ils/modules/items/api.py
> issues: fix issue when wrong patron displayed after a checkin

- rero_ils/modules/documents/listener.py
- rero_ils/modules/items/listener.py
- rero_ils/modules/loans/listener.py
- rero_ils/modules/locations/listener.py
- rero_ils/modules/notifications/listener.py
- rero_ils/modules/patrons/listener.py
Run the tests. Or linting should be enough.
> documentation: rewrite bad syntax in docstrings

- rero_ils/modules/mef_persons/__init__.py
- rero_ils/modules/mef_persons/api.py
- rero_ils/modules/mef_persons/jsonschemas/__init__.py
- rero_ils/modules/mef_persons/mappings/__init__.py
- rero_ils/modules/mef_persons/mappings/v6/__init__.py
- rero_ils/modules/mef_persons/models.py
- rero_ils/modules/mef_persons/receivers.py
- rero_ils/modules/mef_persons/static/js/rero_ils/mef_persons.js
- rero_ils/modules/mef_persons/static/scss/rero_ils/person.scss
- rero_ils/modules/mef_persons/tasks.py
- rero_ils/modules/mef_persons/templates/rero_ils/_person_by_source.html
- rero_ils/modules/mef_persons/templates/rero_ils/_person_by_source_data.html
- rero_ils/modules/mef_persons/templates/rero_ils/_person_unified.html
- rero_ils/modules/mef_persons/templates/rero_ils/detailed_view_persons.html
- rero_ils/modules/mef_persons/templates/rero_ils/macros/person.html
- rero_ils/modules/mef_persons/views.py
> license: move from GPLv2 to AGPLv3 (MEF Persons)

- rero_ils/modules/locations/__init__.py
- rero_ils/modules/locations/api.py
- rero_ils/modules/locations/jsonresolver.py
- rero_ils/modules/locations/jsonschemas/__init__.py
- rero_ils/modules/locations/listener.py
- rero_ils/modules/locations/mappings/__init__.py
- rero_ils/modules/locations/mappings/v6/__init__.py
- rero_ils/modules/locations/models.py
> license: move from GPLv2 to AGPLv3 (locations)

- rero_ils/modules/loans/__init__.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/loans/jsonresolver.py
- rero_ils/modules/loans/jsonschemas/__init__.py
- rero_ils/modules/loans/listener.py
- rero_ils/modules/loans/mappings/__init__.py
- rero_ils/modules/loans/mappings/v6/__init__.py
- rero_ils/modules/loans/utils.py
> license: move from GPLv2 to AGPLv3 (loans)

- rero_ils/modules/items/__init__.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/items/jsonresolver.py
- rero_ils/modules/items/jsonschemas/__init__.py
- rero_ils/modules/items/listener.py
- rero_ils/modules/items/mappings/__init__.py
- rero_ils/modules/items/mappings/v6/__init__.py
- rero_ils/modules/items/models.py
- rero_ils/modules/items/signals.py
- rero_ils/modules/items/templates/rero_ils/detailed_view_items.html
- rero_ils/modules/items/views.py
> license: move from GPLv2 to AGPLv3 (items)

- rero_ils/modules/item_types/__init__.py
- rero_ils/modules/item_types/api.py
- rero_ils/modules/item_types/jsonresolver.py
- rero_ils/modules/item_types/jsonschemas/__init__.py
- rero_ils/modules/item_types/mappings/__init__.py
- rero_ils/modules/item_types/mappings/v6/__init__.py
- rero_ils/modules/item_types/models.py
- rero_ils/modules/item_types/views.py
> license: move from GPLv2 to AGPLv3 (item_types)

- rero_ils/modules/ebooks/__init__.py
- rero_ils/modules/ebooks/cli.py
- rero_ils/modules/ebooks/dojson/__init__.py
- rero_ils/modules/ebooks/dojson/contrib/__init__.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/__init__.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- rero_ils/modules/ebooks/receivers.py
- rero_ils/modules/ebooks/search.py
- rero_ils/modules/ebooks/tasks.py
- rero_ils/modules/ebooks/utils.py
> license: move from GPLv2 to AGPLv3 (ebooks)

- rero_ils/modules/documents/__init__.py
- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/bundles.py
- rero_ils/modules/documents/dojson/__init__.py
- rero_ils/modules/documents/dojson/contrib/__init__.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/__init__.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/dojson/contrib/unimarctojson/__init__.py
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/documents/jsonresolver.py
- rero_ils/modules/documents/jsonresolver_mef_person.py
- rero_ils/modules/documents/jsonschemas/__init__.py
- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/mappings/__init__.py
- rero_ils/modules/documents/mappings/v6/__init__.py
- rero_ils/modules/documents/models.py
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/documents/static/js/rero_ils/detailed_app.js
- rero_ils/modules/documents/static/js/rero_ils/documents.js
- rero_ils/modules/documents/static/js/rero_ils/thumbnail.js
- rero_ils/modules/documents/static/scss/rero_ils/thumbnail.scss
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/documents/templates/rero_ils/export_documents.html
- rero_ils/modules/documents/views.py
> license: move from GPLv2 to AGPLv3 (documents)

- rero_ils/modules/circ_policies/__init__.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/circ_policies/jsonschemas/__init__.py
- rero_ils/modules/circ_policies/mappings/__init__.py
- rero_ils/modules/circ_policies/mappings/v6/__init__.py
- rero_ils/modules/circ_policies/models.py
- rero_ils/modules/circ_policies/views.py
* Circulation policies module.
> license: move from GPLv2 to AGPLv3 (circ_pol)

- rero_ils/modules/libraries/__init__.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/libraries/jsonresolver.py
- rero_ils/modules/libraries/jsonschemas/__init__.py
- rero_ils/modules/libraries/mappings/__init__.py
- rero_ils/modules/libraries/mappings/v6/__init__.py
- rero_ils/modules/libraries/models.py
- rero_ils/modules/libraries/views.py
> license: move from GPLv2 to AGPLv3 (libraries)

- tests/api/test_documents_rest.py
* Improves units testing of bnf service.
> tests: workaround when bnf service is down

- Pipfile
- Pipfile.lock
- rero_ils/config.py
- rero_ils/modules/items/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- rero_ils/modules/loans/mappings/v6/loans/loan-ils-v0.0.1.json
- rero_ils/modules/loans/utils.py
- rero_ils/modules/notifications/api.py
- tests/api/test_loans_rest.py
- tests/api/test_tasks.py
* Adds $ref to item in then loan record.
* Improves circulation exceptions and parameters.
- bootstrap
> circulation: upgrade to invenio circulation v1.0.0a14

- Pipfile.lock
- setup.py
* updates invenio to verion 3.1.1
* security releases of Invenio v3 that fixes moderate severity vulnerabilities
> security: update to invenio version 3.1.1

- rero_ils/modules/api.py
- rero_ils/modules/items/api.py
- tests/ui/test_api.py
* Adds indexation class property to IlsRecord
> indexation class: add indexation property to IlsRecord

- Pipfile
- Pipfile.lock
- rero_ils/modules/cli.py
- scripts/setup
* Adds a new cli to manuipulate records.
Co-Authored-by: Peter Weber peter.weber@rero.ch
> cli: replaces invenio records by invenio fixtures

- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- tests/unit/test_documents_dojson.py
Only transformation code and unit test for identifiers are included in this PR.
No testing can be done at this stage.
> data model: transform marc21 field containing identifiers

- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
- rero_ils/modules/documents/mappings/v6/documents/document.json
- rero_ils/modules/ebooks/receivers.py
- rero_ils/modules/ebooks/tasks.py
- tests/data/data.json
- tests/ui/documents/test_documents_api.py
- tests/unit/test_documents_jsonschema.py
* Adds identifiedBy to json schema and mapping.
* Removes old field identifiers.
* Adapts unit testing.
* Adds harvested boolean field to identify record is harvested or not.
> data model: schema and mapping and unit testing adaptation for identifiedby

- data/items10k.json
- data/items300.json
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
- rero_ils/modules/documents/mappings/v6/documents/document.json
- tests/data/data.json
- tests/unit/test_documents_jsonschema.py
* Adapts languages to json schema and mapping.
* Adapts unit testing.
> data model: schema and mapping and unit testing adaptation for languages

- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/form_documents/document-v0.0.1.json
* Adapts editor for new fields.
Co-Authorred-by: Johnny Mariéthoz Johnny.Mariethoz@rero.ch
> data mode: adapt editor for language and identifiedBy

- rero_ils/modules/notifications/__init__.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/notifications/dispatcher.py
- rero_ils/modules/notifications/jsonschemas/__init__.py
- rero_ils/modules/notifications/listener.py
- rero_ils/modules/notifications/mappings/__init__.py
- rero_ils/modules/notifications/mappings/v6/__init__.py
- rero_ils/modules/notifications/models.py
- rero_ils/modules/notifications/tasks.py
- rero_ils/modules/notifications/views.py
> license: move from GPLv2 to AGPLv3

- .github/ISSUE_TEMPLATE/bug_report.md
> documentation: add an issue template

- rero_ils/modules/notifications/api.py
- rero_ils/modules/notifications/dispatcher.py
* Adapts the url of the notified patron to have the organisation view code.
Co-Authored-by: [Aly Badr] <aly.badr@rero.ch>
> notifications: url of the account of the notified patron

- ui/src/app/circulation/items-list/items-list.component.html
- ui/src/app/circulation/items-list/items-list.component.ts
* Fixes a view code on url of document and item.
How to test:
- `script/bootstrap`.
- Circulation ui: check url for document and item.
> circulation ui: view code on document and item link

- rero_ils/modules/holdings/api.py
- rero_ils/modules/holdings/templates/rero_ils/detailed_view_holdings.html
- rero_ils/modules/holdings/views.py
- rero_ils/modules/items/api.py
- tests/ui/holdings/test_holdings_item.py
Co-Authored-by: Bertrand Zuchuat bertrand.zuchuat@rero.ch
> holdings: re-linking item to a new holding after edition

- ui/src/assets/i18n/de.json
- ui/src/assets/i18n/fr.json
- ui/src/assets/i18n/it.json
> translation: fix missing translated strings

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
> document: fix notes field

- rero_ils/modules/items/templates/rero_ils/detailed_view_items.html
- ui/src/app/records/search/brief-view/documents-brief-view.component.ts
* Fixes display buttons on item detailed view.
* Fixes display buttons on admin documents brief view.
* Closes #390 
> item: fix display of the buttons

- rero_ils/modules/item_types/jsonschemas/form_item_types/item_type-v0.0.1.json
- rero_ils/modules/libraries/jsonschemas/form_libraries/library-v0.0.1.json
- rero_ils/modules/patron_types/jsonschemas/form_patron_types/patron_type-v0.0.1.json
- ui/src/app/records/editor/remote-select/remote-select.component.ts
* Closes #389 
How to test:
- `script/bootstrap`.
- Check select menu on item_type, patron_type and library.
> admin: Wrong organisation on select menu

- data/holdings300.json
- data/items300.json
- rero_ils/modules/cli.py
- rero_ils/modules/holdings/api.py
- rero_ils/modules/holdings/models.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/cli.py
- rero_ils/modules/minters.py
- rero_ils/modules/providers.py
- scripts/setup
- tests/api/test_items_rest.py
* Removes automatic holding creation for the items of the fixtures.
* Adds separate json files for holdings data.
> fixtures: fixes slowness of setup after holding integration

- rero_ils/modules/items/api.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/loans/listener.py
- rero_ils/modules/loans/utils.py
- tests/ui/holdings/test_holdings_item.py
- ui/src/app/records/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.html
* Adapts circulation policies to look for items info from parent holding record.
>  circulation: holdings level adaptation

- ui/src/app/records/custom-editor/libraries/exception-dates-edit/exception-dates-edit.component.ts
- ui/src/app/records/custom-editor/libraries/library-exception-form.service.ts
> libraries date exceptions: fix bug on repeat button

- rero_ils/modules/items/api.py
- ui/src/app/circulation/main-checkin-checkout/main-checkin-checkout.component.ts
> circulation ui: check if item or patron is in same organisation

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
> document detailed view: fix missing message on item delete button

- rero_ils/modules/items/api_views.py
- ui/src/app/circulation/main-checkin-checkout/main-checkin-checkout.component.ts
* Adds invenio logger message.
* Fixes user message in circulation UI.
_**TO TEST**_
* ./scripts/bootstrap
> circulation_ui: add error logs for item API

- Pipfile
- rero_ils/modules/documents/views.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/items/views.py
- tests/api/test_availability.py
* Adapts existing item availability.
* Provides availability reasons when item is not available.
Co-Authored-by: Laurent Dubois <laurent.dubois@uclouvain.be>
> interface: item availability

- rero_ils/modules/holdings/api.py
- rero_ils/modules/holdings/api_views.py
- rero_ils/modules/patrons/api.py
- tests/api/test_availability.py
* Adds holding availability.
* Provides availability loan conditions for holdings records.
Co-Authored-by: Laurent Dubois <laurent.dubois@uclouvain.be>
> holdings: implement record availability

- rero_ils/views.py
* Fixes user initials not displayed correctly.
How to test:
Try `dev` and this fix with following command running:
`watch -n 0.1 curl -X OPTIONS localhost:5000`
> fix user initials view

- data/organisations.json
- rero_ils/config.py
- rero_ils/modules/fees/api.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/organisations/jsonschemas/organisations/organisation-v0.0.1.json
- rero_ils/modules/organisations/mappings/v6/organisations/organisation-v0.0.1.json
- tests/api/test_fees.py
- tests/data/data.json
- tests/unit/test_organisations_jsonschema.py
* Adds default currency by organisation.
how to test:
* run script/bootsrap
* run script/setup
> Fee: better currency management

- rero_ils/modules/apiharvester/models.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/items/views.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/loans/utils.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/utils.py
- tests/api/test_availability.py
- tests/api/test_items_rest.py
- tests/api/test_libraries_rest.py
- tests/api/test_loans_rest.py
- tests/ui/libraries/test_libraries_api.py
* Fixes areas where utc timezone was not set.
> global: standardize timezone

- data/circulation_policies.json
- data/item_types.json
- data/locations.json
- tests/api/test_item_types_rest.py
- tests/data/data.json
- tests/fixtures/organisations.py
* Adds online locations.
* Adds online item types.
> fixture: implement ebooks holdings rero-ils and unit test fixtures

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/documents/views.py
- rero_ils/templates/rero_ils/macros/macro.html
- tests/unit/test_documents_dojson.py
* Displays the publication statement on detailed view.
Co-Authored-by: [Alicia Zangger] <alicia.zangger@rero.ch>
> UI:display the publication statement

- scripts/server
`sset` was used instead of `set` at ./script/server first line
> scripts: wrong command in server script

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
> document: fix default icon thumbnail on fullview

- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/mappings/v6/documents/document.json
- rero_ils/modules/documents/views.py
- ui/src/app/records/search/brief-view/documents-brief-view.component.ts
- ui/src/app/records/search/brief-view/public-documents-brief-view.component.ts
* Adds publication statement to admin and public brief document view.
> ui: correct document brief views

- tests/api/test_external_services.py
> tests: fix external tests after availability implementation

- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- tests/api/test_items_rest_views.py
- tests/api/test_loans_rest.py
* Closes #484
* Moves prior_checkout_actions() function from api_views.py to api.py
> circulation : fix issue two loans instead of one

- rero_ils/modules/documents/views.py
> documents: fix language

- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- tests/unit/test_documents_dojson_ebooks.py
* Implements the publication statement transformation for ebooks.
> data model: implement publication statement transformation for ebooks

- rero_ils/static/scss/rero_ils/frontpage.scss
US976, task #978
May close #381 (check front page responsiveness)
Test:
- Go to home page and toggle device toolbar to emulate mobile device resolutions
- Check responsiveness of the page with several resolutions (no vertical overlap)
Code review check list:
> ui: fix front page responsiveness #381

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
* hide number of item(s)
* hide availability
> document: fix hide elements on harvested document

- docker-services.yml
> docker: update elasticsearch and kibana to version 6.6.2

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
* Closes #547
- Test json export in document detail view
> document: fix json export

- rero_ils/modules/items/api.py
- tests/api/test_items_rest.py
- tests/api/test_items_rest_views.py
*Fixes an existing issue, may closes #462
Co-Authored-by: Benoit Erken erken.benoit@gmail.com
Co-Authored-by: Laurent Dubois laurent.dubois@itld-solutions.be
> circulation : fix checkin of item that should go in transit

- .github/ISSUE_TEMPLATE.md
Sometimes to resolve issues on RERO-ILS we need to know from which version the user come from.
> github: add new info on github issue template

- rero_ils/static/scss/rero_ils/frontpage.scss
- rero_ils/templates/rero_ils/frontpage.html
* Corrects html in frontpage.
* Adapts element display order for mobile devices.
* Removes rounded corner for mobile screens.
Implements task 1104 of US1082
Check home page with different screen resolutions. 
Element display order: test/catalog/project.
Rounded corner should be removed for mobile screen resolution.
> ui: adapt frontpage for mobile devices

- rero_ils/modules/circ_policies/api.py
- tests/fixtures/organisations.py
- tests/ui/circ_policies/test_circ_policies_api.py
- tests/ui/circ_policies/test_circ_policies_utils.py
* Fixes circulation policies as until now the policies was not filtered
by organisation.
- The tests done for the workshop show that the default policy was not applied. 
- choose a patron and item where de default policy should be applied. Do a loan and return it. Change the default policy (loan duration), redo the loan and compare the end date.
> circulation: fix circulation policies

- .github/PULL_REQUEST_TEMPLATE.md
- rero_ils/modules/patrons/views.py
* BETTER Updates PR template to include translation process.
To update PR template in order to include translation process.
N/A
The new template needs to be on master to be used automatically.
> template: update pr template

- ui/src/app/records/custom-editor/circulation-settings/circulation-policy-form.service.ts
> circulation policies: fix settings bug

- rero_ils/modules/documents/views.py
- rero_ils/modules/indexer_utils.py
- tests/ui/test_indexer_utils.py
* Fixes mef person index suppression problem when a document is deleted
* Fixes redirection after document suppression
* Closes #601, #552
- v0.5.2
- login as "Astrid" (reroils+test@rero.ch)
- Try to delete the document 241 (after deleting linked item)
- If all succeed, then you will redirect to `search/documents` page
> documents: fix document suppression problems

- rero_ils/bundles.py
- rero_ils/config.py
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/templates/rero_ils/professional.html
- rero_ils/templates/rero_ils/search.html
- rero_ils/views.py
- scripts/bootstrap
- setup.py
* Uses invenio assets (NpmBundle) to include the angular app.
* Fixes professional view page reload.
* Fixes edit document and add item links in the document detailed view.
* Removes webpack command in the ./scripts/bootstrap script.
- To implement the US #986
- ./script/bootstrap
- A first version of the public search and professional (https://localhost:5000/professional) should be available.
> assets: use invenio assets to serve angular app

- rero_ils/templates/rero_ils/frontpage.html
* Corrects frontpage.
To correct frontpage.
Closes #646 
Check that there is no typo in the blue block on the frontpage.
> ui: correct frontpage typo

- Pipfile.lock
- rero_ils/views.py
- run-tests.sh
- scripts/setup
- tests/api/test_external_services.py
* Fixes pep8 error in rero_ils/views.py.
* Fixes external test
* Fixes pursue parameter in setup script.
* Adds creation of json files to run_tests.sh.
- error on travis
> travis: fix errors

- MANIFEST.in
- rero_ils/modules/apiharvester/utils.py
- tests/data/babel_extraction.json
- tests/data/ebook1.xml
- tests/data/ebook2.xml
- tests/fixtures/metadata.py
- tests/ui/apiharvester/test_apiharvester_utils.py
- tests/ui/ebooks/test_ebooks_receivers.py
- tests/ui/ebooks/test_ebooks_utils.py
- tests/ui/mef_persons/test_mef_persons_api.py
- tests/ui/mef_persons/test_mef_persons_receivers.py
- tests/ui/mef_persons/test_mef_persons_tasks.py
- tests/unit/test_babel_extractors.py
* Adds tests for mef-persons tasks.
* Adds tests for ebook recivers.
* Adds tests for apiharvester.
- To improve test coverage
- ./run-tests.sh
> tests: improve test coverage

- data/libraries.json
- Fixes change opening hours start time with 01:00 (bug with 00:00).
- Edit library and check opening hours availability
> fixtures: change library opening hours for organisation 3

- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
> translation: edition & responsability

- rero_ils/config.py
- rero_ils/modules/serializers.py
- To remove facets configuration on aggregations _settings key.
- Check aggregations data on result list
> serializer: remove _settings key on aggregations

- rero_ils/modules/cli.py
- Find pid fixture dependency errors.
- use the cli command `check_pid_dependencies` to find pid dependency errors.
> cli: pid fixture dependencies

- data/vendors.json
- rero_ils/config.py
- rero_ils/modules/vendors/__init__.py
- rero_ils/modules/vendors/api.py
- rero_ils/modules/vendors/jsonresolver.py
- rero_ils/modules/vendors/jsonschemas/__init__.py
- rero_ils/modules/vendors/jsonschemas/form_vendors/vendor-v0.0.1.json
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
- rero_ils/modules/vendors/mappings/__init__.py
- rero_ils/modules/vendors/mappings/v6/__init__.py
- rero_ils/modules/vendors/mappings/v6/vendors/vendor-v0.0.1.json
- rero_ils/modules/vendors/models.py
- scripts/setup
- setup.py
- tests/api/test_vendors.py
- tests/conftest.py
- tests/data/acquisition.json
- tests/fixtures/acquisition.py
* Adds vendor resource.
* Creates tests.
* Creates fixtures.
- Implement US1185 : Organisation vendor
- run bootstrap & setup
- login as librarian
- you can display the vendors at url :  /api/vendors
Note: vendors are filtered on the organisation of logged in librarian
> vendor: create new vendor resource

- rero_ils/config.py
- rero_ils/modules/libraries/mappings/v6/libraries/library-v0.0.1.json
- Adds configuration for sorting library by name
> libraries: add sort by name configuration

- rero_ils/modules/budgets/api.py
- tests/api/test_budgets_rest.py
- tests/data/acquisition.json
- tests/data/data.json
- tests/fixtures/acquisition.py
- tests/ui/budgets/test_budgets_jsonresolver.py
* Improves tests and fixtures.
https://tree.taiga.io/project/rero21-reroils/task/1234?kanban-status=1224894
- only units testing, should be able to test with the interface when https://tree.taiga.io/project/rero21-reroils/task/1220?kanban-status=1224894 is implemented
> budgets: block the deletion of the organisation's current budget

- rero_ils/config.py
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/persons/views.py
- rero_ils/templates/rero_ils/professional.html
- rero_ils/templates/rero_ils/search.html
* Adds a serializer to push authors name in the documents.
* Adds a small vertical space between header and the search results.
* Adds a datepicker for the author birth date.
- To back port several fixes done for the workshops.
> many: add several fixes from the workshop

- data/budgets.json
- rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json
- tests/data/acquisition.json
> budgets: change budget dates format to date

- data/vendors.json
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
- rero_ils/modules/vendors/mappings/v6/vendors/vendor-v0.0.1.json
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- tests/data/acquisition.json
* Adds currency and TVA rate to vendor resource.
* Which task/US does it implement?
https://tree.taiga.io/project/rero21-reroils/task/1240
> vendors: update vendor jsonschema

- Dockerfile
- rero_ils/config.py
- rero_ils/templates/rero_ils/frontpage.html
- scripts/bootstrap
* Adds rero-ils-ui hash to frontpage.
* Updates Dockerfile to use of rero-ils-ui package file.
- Frontpage can be tested by changing `RERO_ILS_APP_GIT_HASH` and `RERO_ILS_UI_GIT_HASH` in 
`config.py`
- real deployment can be tested with`minikube` or `docker-desktop kubernetes` and the deployment scripts.
> deployment: adaptions for rero-ils-ui

- rero_ils/modules/persons/api.py
* Corrects the indexation of persons when creating documents
- https://tree.taiga.io/project/rero21-reroils/task/1265
- after setup not all persons were indexed
- run setup and verify all persons are indexed
> indexer: fix person indexing

- data/patron_transaction_events.json
- rero_ils/config.py
- rero_ils/modules/patron_transaction_events/__init__.py
- rero_ils/modules/patron_transaction_events/api.py
- rero_ils/modules/patron_transaction_events/jsonresolver.py
- rero_ils/modules/patron_transaction_events/jsonschemas/__init__.py
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transaction_events/mappings/__init__.py
- rero_ils/modules/patron_transaction_events/mappings/v6/__init__.py
- rero_ils/modules/patron_transaction_events/mappings/v6/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transaction_events/models.py
- setup.py
* Creation of 'patron_transaction_events'.
https://tree.taiga.io/project/rero21-reroils/task/1250?kanban-status=1224894
Other pull requests will follow, only code review is needed.
> patron_transaction_events: create new resource :: jsonschema and mapping. 

- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- To filter location on Item editor (rero-ils-ui)
> item: add field location on form configuration

- .tx/config
- babel.ini
- data/vendors.json
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
- rero_ils/modules/vendors/mappings/v6/vendors/vendor-v0.0.1.json
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- tests/data/acquisition.json
- tests/ui/documents/test_documents_filter.py
* Updates transifex config according to the new resource slug.
* Ignores webpack assets when extracting strings from JS and JSON files.
* Ignores compiled documents JSON schemas when extracting strings from
JSON files.
* Extracts new strings and updates catalogs.
* Prefixes language codes, country codes and canton codes to avoid the
same code beeing used multiple times.
* Restores language codes, country codes and canton codes translations.
* Changes TVA to VAT.
* Fixes some transifex issues, like the interface switch label, or some
statements in the document JSON schema.
* Corrects a description in the document JSON schema file.
* Updates tests with lang_ prefixes.
- To fix issues …
> translations: restore and improve translations

- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
* Hides status field in editor.
To fix issue nb 6 of https://github.com/rero/rero-ils-ui/issues/108
Try to add or edit a holding item.
> editor: fix "required status" error in item editor

- rero_ils/config.py
- rero_ils/modules/patrons/mappings/v6/patrons/patron-v0.0.1.json
* Adds default sort config for resources.
* Adds fields on patron for sort option.
- To sort alphabetically
- Check on resource list.
> config: add default sort on resources

- rero_ils/modules/loans/utils.py
- tests/ui/loans/test_loans_api.py
- https://github.com/rero/rero-ils-ui/issues/108 point 30 [backend]
> loans: fix problem when api returns an invalid checkout loan period

- rero_ils/modules/acq_accounts/api.py
- tests/api/test_acq_accounts_rest.py
- tests/api/test_acq_orders_rest.py
- https://github.com/rero/rero-ils-ui/issues/108 point 37
> acq_account: disable account deletion when it has orders linked to it.

- MANIFEST.in
- rero_ils/modules/cli.py
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- https://tree.taiga.io/project/rero21-reroils/task/1287
- run `pipenv run invenio utils bnf_import_test -v -S 9782220063201` or `pipenv run invenio utils bnf_import_test -e -v` (taks a long time)
> improve bnf import

- AUTHORS.rst
- Missing contributors since few months in AUTHORS.rst page (included in documentation)
Fetch the repository and do:
```bash
pipenv run sphinx-build -qnNW docs docs/_build/html
```
then open **./docs/_build/html/authors.html**.
Check that all involved people in the project are displayed.
> documentation: complete authors page

- rero_ils/modules/loans/cli.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/patron_transaction_events/api.py
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transaction_events/mappings/v6/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/api.py
- rero_ils/modules/patron_transactions/listener.py
- rero_ils/modules/patron_transactions/mappings/v6/patron_transactions/patron_transaction-v0.0.1.json
- tests/api/test_notifications_rest.py
- tests/api/test_patron_transactions_rest.py
- tests/data/data.json
- tests/unit/test_patron_transaction_events_jsonschema.py
- Adapts PatronTransaction[Event]s resource.
> patron_transaction : Adapt PatronTransaction resource

- rero_ils/modules/loans/api.py
- rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
- rero_ils/modules/patrons/views.py
- rero_ils/translations/messages.pot
- tests/ui/patrons/test_patrons_ui.py
* Adds history tab for logged in patrons to display history of last 6 months.
https://tree.taiga.io/project/rero21-reroils/task/1279?kanban-status=1224894
> patrons: display checkout history for patron

- check_license_config.yml
- rero_ils/modules/cli.py
- rero_ils/templates/rero_ils/_info_help.html
- rero_ils/templates/rero_ils/_info_pilot.html
- rero_ils/templates/rero_ils/_info_test.html
- rero_ils/templates/rero_ils/frontpage.html
* Adds new homepage informations for pilot instance.
* Fixes licence checking cli.
- To change info on homepage for pilot libraries
- Check the text on pilot site
> homepage: add homepage informations for pilot instance

- rero_ils/modules/items/api.py
- rero_ils/modules/items/api_views.py
- tests/api/test_items_rest.py
* Adds current library pid as parameter to apply actions.
Corrects 33. of https://github.com/rero/rero-ils-ui/issues/108
> circulation: correct pickup location for actions

- rero_ils/bundles.py
> ui: move to rero-ils-ui@0.0.10

- rero_ils/translations/fr/LC_MESSAGES/messages.po
> translation: fix error with translation file

- rero_ils/config.py
- Fix loading inline image on admin view
- Check logo on admin view
> config: allow loading inline image in the security configuration

- rero_ils/modules/ebooks/tasks.py
- fix ebooks indexing for oai import
> ebooks: fix ebook import indexing

- rero_ils/config.py
- Check ebook images
- Check load external script (googleanalytics) => Not error on console
> config: allow loading external script

- rero_ils/modules/items/api.py
* Fixes automatic_checkin return informations
* Closes #770
- Try to reproduce behavior of https://github.com/rero/rero-ils/issues/770
- The result should be
> items: fix automatic checkin return informations

- data/users.json
* Fixes users.json about "Wan Shi Tong"
* Closes #695
> data: correction on users data

- rero_ils/config.py
- rero_ils/modules/loans/transitions.py
- tests/api/test_circ_bug.py
* Overwrites bugged invenio-circulation check-in transitions.
* Closes #780
> circulation: fix item status after a check-in

- rero_ils/modules/items/api.py
> circulation: fix loan after a checkin of a validated request

- rero_ils/bundles.py
> ui: move to rero-ils-ui 0.0.11

- rero_ils/version.py
- Release `v0.6.0` preparation
- To be deployed on `ilsdev.test.rero.ch`
> release: v0.6.0

- rero_ils/bundles.py
> ui: move to rero-ils-ui 0.0.12

- rero_ils/version.py
> release: v0.6.1

- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/translations/messages.pot
* Adds placeholders for phone number and date of birth fields.
* Closes #538.
* Closes #804.
> patron editor: add placeholders

- data/documents_big.json
- data/documents_small.json
- data/documents_small.xml
- data/persons_big.json
- data/persons_small.json
- rero_ils/modules/cli.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/documents/mappings/v6/documents/document.json
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/documents/views.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- rero_ils/modules/ebooks/utils.py
- rero_ils/modules/utils.py
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- tests/data/data.json
- tests/fixtures/metadata.py
- tests/ui/documents/test_documents_api.py
- tests/unit/test_documents_dojson.py
- tests/unit/test_documents_dojson_ebooks.py
* Adds electronicLocator resource (tag 856).
- https://tree.taiga.io/project/rero21-reroils/us/1262
- see in detailed view access and other access links
> metadata: electronicLocator

- rero_ils/config.py
- Add sort on pickup_name field on location resource.
> configuration: add sort on pickup_name location

- rero_ils/modules/utils.py
- tests/ui/test_utils_app.py
- https://tree.taiga.io/project/rero21-reroils/task/1306
> utils: $ref from pid

- rero_ils/modules/patron_transaction_events/api.py
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/api.py
- tests/api/test_patron_payments_rest.py
- tests/api/test_patron_transactions_rest.py
- tests/ui/patron_transaction_events/test_patron_transaction_events_api.py
- tests/ui/patron_transactions/test_patron_transactions_api.py
* Updates 'resolved' event type to 'cancel'.
* Overdues are always create by system, no need to store 'oeprator' field for these events.
* Fixes unit test
> patron_transaction: adapt features after PO testing

- INSTALL.rst
* Adds instruction to set the right version of pipenv
Co-Authored-By: Alicia Zangger <alicia.zangger@rero.ch>
To update documentation on how to install rero-ils
N/A
> documentation: update INSTALL.rst

- rero_ils/modules/providers.py
* The sequence indentifier was calculated wrongly
- https://tree.taiga.io/project/rero21-reroils/task/1370
> db: fix sequence indentifier

- rero_ils/modules/items/api_views.py
- rero_ils/translations/messages.pot
* Reformulates messages:
Circulation policies do not allow request on this item > Request not allowed by the circulation policy
Your new request has been registered > Request registered
To implement task 1353 of US657
https://tree.taiga.io/project/rero21-reroils/task/1353?kanban-status=1224894
See https://gitter.im/rero/reroils-PO?at=5e65f10102dbe022a175fa76
N/A
> request: fix request made by a librarian

- data/locations.json
Fixes loc#17 in data (for setup). The location#17 is defined as pickup_location
but without "pickup_name".
- Fix data
- run `pipenv run setup`
> data: fix location data problem

- data/documents_big.json
- data/documents_small.json
- rero_ils/dojson/utils.py
- rero_ils/modules/cli.py
- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/__init__.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/documents/mappings/v6/documents/document.json
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/documents/utils.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- tests/api/test_documents_rest.py
- tests/data/data.json
- tests/ui/documents/test_documents_mapping.py
- tests/unit/test_documents_dojson.py
- tests/unit/test_documents_dojson_ebooks.py
data model: implement title and variants transformation
* Implements title and variants transformation for Marc21.
* Implements title and variants transformation for Marc21 eBook.
* Adapts ES mapping.
* Adapts JSON schemas.
* Adapts detailed document view.
- implement title and variants transformation
Go to public detail view of documents and check the display of the title.
Select arabic documents and check that Title, Variant title and Statement of responsibility are displayed if they exist in the bibliographic record.
Check other records.
records/documents/detail/34 should display all fields.
> data model: implement title and variants transformation

- rero_ils/modules/libraries/jsonresolver.py
- rero_ils/modules/patron_transaction_events/api.py
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/api.py
- rero_ils/modules/patron_types/api.py
- rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
- rero_ils/modules/patron_types/mappings/v6/patron_types/patron_type-v0.0.1.json
- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/patrons/mappings/v6/patrons/patron-v0.0.1.json
- rero_ils/modules/utils.py
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- tests/api/test_acq_invoices_rest.py
- tests/api/test_patron_transaction_events_rest.py
- tests/api/test_patron_transactions_rest.py
- tests/api/test_patron_types_rest.py
- tests/api/test_patrons_rest.py
- tests/data/data.json
- tests/unit/test_patron_types_jsonschema.py
- tests/unit/test_utils.py
Updates some ressources to allow the creation of patron subscription feature. This PR also introduced some
specific methods to create a patron subscription. Updated resources are :
- Patron
- PatronType
- PatronTransactionEvent
* Adapts resources to allow patron subscriotion.
* Adds functionnalities to create/check patron subscripion.
* Adds unit testing
https://tree.taiga.io/project/rero21-reroils/us/1297?milestone=257446
- Try to edit/add patron type with a subscription amount
- `./run-test.sh` to test all new methods
> resources: update resources to allow patron subscription

- data/holdings_small.json
- data/items_small.json
- data/patterns.json
- rero_ils/modules/documents/api.py
- rero_ils/modules/ebooks/utils.py
- rero_ils/modules/holdings/api.py
- rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
- rero_ils/modules/items/api.py
- rero_ils/modules/items/cli.py
- rero_ils/permissions.py
- tests/api/test_holdings_rest.py
- tests/api/test_patterns.py
- tests/data/holdings.json
- tests/unit/test_holdings_jsonschema.py
Three types of holdings are now available. The serial holdings type is used by the journal documents
i.e. documents with serial as RDA issuance mode.
The electronic holdings type is used by the ebooks documents, i.e. harvested documents.
The standard holdings type is used by all other type of documents.
* Disallows the creation/update/deletion of non-standard type of holdings.
* Adds the number of holdings as a condition to block a document deletion.
* Fixes the holdings json schema required fields and description.
* Regenerates the big and small data files because of the changes made to the holdings json schema.
* Defines better the patterns examples, to make clear difference between the enumeration and chronology captions. …
> holdings: add new holdings types

- Pipfile
- Pipfile.lock
- rero_ils/config.py
- rero_ils/modules/api.py
- rero_ils/modules/items/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- rero_ils/modules/loans/listener.py
- rero_ils/modules/loans/mappings/v6/loans/loan-ils-v0.0.1.json
- rero_ils/modules/locations/api.py
- rero_ils/modules/patrons/api.py
- tests/ui/loans/test_loans_api.py
This PR does not address the units testing and json data files changes.
* Adapts reroils config files.
https://tree.taiga.io/project/rero21-reroils/task/1405?kanban-status=1224894
It is normal that Travis did not pass testing this PR.
This PR is only for code review. no testing needed.
> invenio: upgrade to invenio circulation v1.0.0a21

- rero_ils/manual_translations.txt
- rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
- rero_ils/modules/acq_invoices/api.py
- rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
- rero_ils/modules/acq_invoices/mappings/v6/acq_invoices/acq_invoice-v0.0.1.json
- rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_order_lines/mappings/v6/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
- rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- rero_ils/views.py
- tests/data/acquisition.json
When translating on transifex, translators identify some source strings
that have to be improved or amended. This commit fixes a good part of
the current issues. The description fields of the schema of patron
transaction and patron transaction event have been removed in order to
avoid the need to translate them on transifex.
* Updates sources files.
* Updates source language files.
* Update translation files.
* Extracts messages.
* Updates catalogs.
To fix source string issues identified on transifex.
- Check changes.
- Run tests.
> translation: fix key source issues

- CHANGES.rst
- RELEASE-NOTES.rst
Updates the files for the v0.7.0 release.
* Update the RELEASE-NOTES.rst file.
* Update the CHANGES.rst file.
> documentation: update release notes and changelog

- rero_ils/config.py
- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/tasks.py
- tests/api/test_patrons_rest.py
- tests/api/test_tasks.py
Create daily tasks to check/clean old patron subscription and automatic subscription renewal. 
> subscriptions : create daily tasks

- tests/api/test_locations_rest.py
* Adds test to increase location code coverage to test `extended_validation` function.
> location: add test to increase code coverage

- Pipfile
- Pipfile.lock
- run-tests.sh
* Fixes version of Sphinx to < 3.0.2: https://github.com/mozilla-services/python-dockerflow/issues/42
* Adds test for appnope in Pipfile.lock
* Fixes pipenv version to 2018.10.9
* Cleans run-test.sh
- test where not working any more in travis
> test: fix run-test

- Pipfile
- rero_ils/dojson/utils.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- rero_ils/modules/ebooks/tasks.py
* Implements fault save ebook harvesting.
* Tests if subfield is empty for marc21 to json transformation.
Co-Authored-by:  Peter Weber <peter.weber@rero.ch>
- https://tree.taiga.io/project/rero21-reroils/task/1434
- Run a ebook harvesting and verify the harvesting is not interrupted.
`invenio oaiharvester harvest -n ebooks -f 1990-01-01`
> fault save ebook harvesting

- tests/conftest.py
pytest-invenio introduces a bug in a recent release. A pull request is
pending (https://github.com/inveniosoftware/pytest-invenio/pull/44).
This is a temporary fix and should be removed once pytest-invenio will
be released with the resolution. This appens only for a local
installation that change the `INVENIO_INSTANCE_PATH` variable.
Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
> tests: fix pytest-invenio static path location

- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
* Corrects patron JSON schema.
> subscription: adapt code after PO reviewing

- rero_ils/config.py
- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/organisations/api.py
- rero_ils/query.py
* Adapts filter to filter results by org in admin view.
* Removes unused code in post process search serializer.
This is a partial implementation of task 1377 of US 1208:
https://tree.taiga.io/project/rero21-reroils/task/1377?kanban-status=1224894
Please do only code review.
This PR is related to:
* https://github.com/rero/rero-ils-ui/pull/208
* https://github.com/rero/ng-core/pull/151
> document: adapt serializer to filter by org in admin view

- rero_ils/config.py
- tests/api/test_organisations_rest_api.py
* Fixes organisation update permission into configuration file
> permission: fix organisation permission

- .github/PULL_REQUEST_TEMPLATE.md
Updates the github PR template to add a section for PR dependencies
across projects.
To add a dependencies section in the PR template. See also https://github.com/rero/rero-ils-ui/pull/257.
Check updated files.
> documentation: add dependencies in PR template

- rero_ils/manual_translations.txt
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
* Pull translations from transifex.
* Removes unnecessary descriptions in document JSON schema.
* Turn labels into natural language in document JSON schema.
* Removes codes from the manual translation files that are translated
through the label in the JSON schema form option.
* Copy the document JSON schema to the minimal document JSON schema.
- To improve the document JSON schema, specifically the strings that needs translations.
- To remove strings that are not anymore useful on transifex (duplicate).
- To pull existing translations from transifex.
Check the changed files.
> translation: update translations, improve schema

- data/documents_big.json
- data/documents_small.json
- rero_ils/dojson/utils.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- tests/api/test_external_services.py
- tests/data/data.json
- tests/data/holdings.json
- tests/unit/test_documents_dojson.py
- tests/unit/test_documents_dojson_ebooks.py
- tests/unit/test_documents_dojson_unimarc.py
- tests/unit/test_documents_jsonschema.py
Implement: extent, duration, format, illustrations colors and physical details.
* Implements transformation for Marc21.
* Implements transformation for UNIMARC.
* Adapts transformation for eBooks.
* Adapts ES mapping.
* Adapts JSON schemas.
https://tree.taiga.io/project/rero21-reroils/us/1305?milestone=260625
https://tree.taiga.io/project/rero21-reroils/us/1311?milestone=260625
> data model: implement physical description transformation

- rero_ils/modules/api.py
- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/documents/static/js/rero_ils/thumbnail.js
- rero_ils/modules/documents/static/scss/rero_ils/thumbnail.scss
- rero_ils/modules/documents/templates/rero_ils/_documents_description.html
- rero_ils/modules/documents/templates/rero_ils/_documents_get.html
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/documents/utils.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
- rero_ils/templates/rero_ils/macros/macro.html
- tests/api/test_documents_rest.py
- tests/ui/documents/test_documents_filter.py
* Adds GET and DETAILS tabs to detailed view of document.
- https://tree.taiga.io/project/rero21-reroils/task/1429
- verify detailed view of documents
> view: detailed documents view

- poetry.lock
- rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
- rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
- rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
- rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json
- rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
- rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
- rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
- rero_ils/modules/organisations/jsonschemas/organisations/organisation-v0.0.1.json
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
- rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/persons/jsonschemas/persons/person-v0.0.1.json
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
- tests/data/babel_extraction.json
This will allow to use interesting new features such as the IF statement
our schema and hopefully in the editor.
https://tree.taiga.io/project/rero21-reroils/task/1385?kanban-status=1224894
> data: update JSON schema to draft 07

- data/documents_big.json
- data/documents_small.json
- rero_ils/dojson/utils.py
- tests/unit/test_documents_dojson.py
* Corrects transformation for duration.
To implement corrections asked by PO group on duration field.
N/A
> data model: remove parenthesis of duration field

- .gitignore
- MANIFEST.in
- docker-compose.full.yml
- poetry.lock
- pyproject.toml
- rero_ils/config.py
- rero_ils/schedulers.py
- scripts/server
- scripts/setup
- setup.py
- tests/scheduler/conftest.py
- tests/scheduler/test_scheduler.py
- so we can change dynamically scheduled tasks
You have to start a `celery worker beat`. For using this backend we have to call `celery` with following parameter:
`-S rero_ils.schedulers.RedisScheduler`
Example (This is normally in the `server` startup script):
`celery worker -A invenio_app.celery --beat -S rero_ils.schedulers.RedisScheduler`
- run bootstrap
- run setup
- try to start stop scheduled tasks with `invenio scheduler --help`
> celery: redis scheduler backend

- data/documents_big.json
- data/documents_small.json
- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/persons/api.py
- tests/data/data.json
- tests/data/documents.json
- tests/fixtures/metadata.py
- tests/ui/documents/test_documents_mapping.py
- tests/ui/persons/test_persons_api.py
- tests/unit/test_documents_dojson.py
* Persons are now linked in the document by references to there resources
(IDREF, GND, ...)
- run setup and verify everythink works as before
- https://tree.taiga.io/project/rero21-reroils/us/1241
- https://tree.taiga.io/project/rero21-reroils/task/1465
> persons link by resource

- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
* Removes redundant label.
* Hides fields with unique value (bf:Place).
Implements task 1473 of US1296
https://tree.taiga.io/project/rero21-reroils/us/1296?milestone=263424
https://tree.taiga.io/project/rero21-reroils/task/1473?kanban-status=1224894
My PR depends on the following PR(s): 
* https://github.com/rero/rero-ils-ui/pull/267
* https://github.com/rero/ng-core/pull/182
Do code review only. This task should be tested on ng-core PR.
> editor: improve display with horizontal fields

- babel.ini
- rero_ils/manual_translations.txt
- rero_ils/modules/documents/jsonschemas/documents/document-minimal-v0.0.1_src.json
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
To sync github and transifex.
Check the translations files.
> v0.9.0 translations

- CHANGES.rst
- RELEASE-NOTES.rst
- poetry.lock
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/version.py
To finalise the v0.9.0 release.
- Check the changed files.
> release: v0.9.0

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
Co-Authored-by: Aly Badr  <aly.badr@rero.ch>
> serials: extract messages for transifex

- CHANGES.rst
- README.rst
- RELEASE-NOTES.rst
- rero_ils/bundles.py
- rero_ils/version.py
**There are two commits** because I had to slightly amend the README.rst file.
This patch is needed because #1013 is missing in `v0.9.0`, resulting in many
user interface elements that are missing.
- Check the detailed document view, the back button should be there, and the
first tab should be labelled "Get". 
- Check the changed files.
> release: v0.9.1

- doc/circulation/actions.md
> docs: add the missing references to the add_request circulation action.

- scripts/server
* Corrects server script to not create a local file.
- Start server, verify everything works (scheduler) and no file rero_ils.schedulers.RedisScheduler is created
> scripts: correct server script

- rero_ils/bundles.py
- rero_ils/modules/persons/bundles.py
- rero_ils/modules/persons/static/js/rero_ils/person_jq.js
- rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html
- rero_ils/static/js/rero_ils/rero_keep_tab.js
- setup.py
* Keeps current tab for documents and persons detailed view on page
reloads.
- selected tabs where lost during reload of page
- select a tab in documents or persons detailed view, select a tab and reload the page or change the language. The selected tab should not change.
> ui: keep selected tab active on reload

- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1_src.json
* Removes redundant label.
* Hides fields with unique value (bf:Place).
> merge US1296 to dev (UX of editor)

- rero_ils/schedulers.py
* Uses enabled state of task already saved in REDIS. closes #1033
- https://github.com/rero/rero-ils/issues/1033
- see: https://github.com/rero/rero-ils/issues/1033
> scheduler: use saved enabled state of tasks

- rero_ils/modules/documents/views.py
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
This commit extracts string for the item notes US and update all
languages files.
> translations: extract string related to item notes

- rero_ils/config.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/ext.py
- rero_ils/modules/holdings/api_views.py
- rero_ils/modules/imports/__init__.py
- rero_ils/modules/imports/api.py
- rero_ils/modules/imports/serializers.py
- rero_ils/modules/imports/views.py
- rero_ils/modules/notifications/cli.py
- run-tests.sh
- setup.py
- tests/api/test_external_services.py
* Adds general class for imports.
* Adds BNF specific import class.
> import: class for external records

- poetry.lock
- pyproject.toml
This version makes use of the config CIRCULATION_LOAN_LOCATIONS_VALIDATION
to allow validation of loan locations
> circulation: upgrade to invenio circulation v1.0.0a25

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
To get new translation from transifex.
Check changed files.
> translations: fetch new translations

- CHANGES.rst
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/version.py
To release the `v0.10.0` version.
Check the changed files.
> release: v0.10.0

- CHANGES.rst
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/version.py
This patch in necessary because of two commits missing in the previous release.
Check the changed files.
> release: v0.10.1

- doc/circulation/actions.md
- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/loans/api.py
- tests/api/circulation/test_actions_views_checkout.py
- tests/api/test_availability.py
- tests/api/test_circ_bug.py
- tests/api/test_items_in_transit.py
- tests/api/test_loans_rest.py
- tests/api/test_notifications_rest.py
- tests/api/test_tasks.py
- tests/ui/circulation/test_actions_checkout.py
[US1567](https://tree.taiga.io/project/rero21-reroils/task/1567)
Check Travis results.
> circulation: ensure the item checkout action for frontend calls

- rero_ils/modules/items/api/api.py
- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/items/api/record.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/loans/api.py
- tests/api/test_availability.py
- tests/api/test_item_rest.py
- tests/api/test_loans_rest.py
- tests/ui/items/test_items_api.py
* Fixes bug: two methods exist to validate items.
* Removes the item_lose method.
* Adds missing units testing.
* Adds more description for circulation methods.
> circulation: remove unused methods

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- run-tests.sh
To prepare translation files for weblate.
- `poetry run tests` 
- Check the changed files, especially `run-tests.sh`.
> translations: prepare project for weblate

- rero_ils/manual_translations.txt
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
The following changes were requested after testing the user story on the
data model filed 'series' (see PR rero/rero-ils#1069).
* Removes useless description.
* Adds missing placeholders.
* Corrects the display and validation of some fields.
* Adds strings to the translation mechanism.
https://github.com/rero/rero-ils/pull/1073 seems not to have been merged correctly in US1432 branch. New attempt.
> editor: implements small improvements

- poetry.lock
- pyproject.toml
This version fixes a problem of requests with concurrency.
RERO circulation can now making several renewals whitout any errors.
To fix problems of renewals in https://github.com/rero/rero-ils-ui/pull/308
* https://github.com/rero/rero-ils-ui/pull/308
After a setup of this branch, check on https://github.com/rero/rero-ils-ui/pull/308 (https://localhost:4200/) that you can make several renewals ('Renew all' button).
> invenio: upgrade to invenio circulation v1.0.0a26

- Dockerfile.base
* Change to node 12 in `Dockerfile.base`.
- Wrong node version was used in deployment.
> deployment: node 12

- .github/PULL_REQUEST_TEMPLATE.md
- README.rst
To slightly improve the README with a weblate bagde.
- Check the README.rst on my repository.
> documentation: add a weblate badge to the README

- README.rst
To fix the weblate badge
Check the readme on my repo branch.
> documentation: fix README weblate badge

- rero_ils/config.py
- rero_ils/modules/documents/api.py
- rero_ils/modules/items/api/__init__.py
- rero_ils/modules/items/api/api.py
- rero_ils/modules/items/listener.py
- rero_ils/modules/items/mappings/v6/items/item-v0.0.1.json
- rero_ils/modules/items/serializers/__init__.py
- rero_ils/modules/items/serializers/csv.py
- rero_ils/modules/items/serializers/json.py
- tests/api/test_items_rest.py
- tests/api/test_serializers.py
- tests/conftest.py
- tests/utils.py
This part implements backend to perform inventory list reports in CSV format.
* Adds CSVSerializer to render search results in CSV.
* Adds ItemJSONSerializer to post process item search.
* Adapts configuration of item rest endpoint to add serializer.
* Adds library to elasticsearch mapping for item.
* Adapts listener to add library_pid into item before indexing.
* Writes tests.
https://tree.taiga.io/project/rero21-reroils/task/1589
N.B.: translation strings will be extracted once branch US1491-item-inventory is ready to merge on dev.
* rero/rero-ils-ui#307 (not ready to test at this time)
1. bootstrap and setup
2. go to : …
> reports: create inventory list based on item resource

- CHANGES.rst
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/version.py
> release: v0.11.0

- rero_ils/modules/loans/api.py
* Changes loan.item_pid into loan.item_pid.value.
To adapt patron profile view to the new "circulation module".
Task 1657 of US1489
https://tree.taiga.io/project/rero21-reroils/task/1657?kanban-status=1224894
https://tree.taiga.io/project/rero21-reroils/us/1489?milestone=269576
No dependency
`bootstrap` & ` setup`
Log in as a patron and go to patron profile view.
> patron: adapt profile view for new 'circulation module'

- tests/api/loans/test_loans_api_rest.py
* Adds missing parameter transaction_user_pid for checkin and checkout
actions.
Unit tests were failing after the rebase. The quick fix integrated for patron profile view was not adapted for new circulation actions because they need some additional parameters now.
N/A
Run `poetry run run-tests` locally
> tests: adapt test to use new circulation actions required parameters

- rero_ils/modules/patrons/templates/rero_ils/_patron_profile_loans.html
* Added trimmed option on translation tag.
> patron profile: fix for plural translation

- rero_ils/modules/loans/api.py
Adds more informations when loans has dump for circulation UI.
Informations added are the item destination library name and item
destination location name. These informations were already present for
some data ; now these informations are always present.
> circulation: add more informations on loan dump

- .travis.yml
- pyproject.toml
- rero_ils/config.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/patron_transactions/api.py
- rero_ils/modules/selfcheck/__init__.py
- rero_ils/modules/selfcheck/api.py
- rero_ils/modules/selfcheck/utils.py
- scripts/bootstrap
- tests/api/test_selfcheck.py
- tests/conftest.py
- tests/fixtures/sip2.py
On the selfcheck machine, a patron can be view all of information about own profile
like fees, overdue items, checked out items, requested items, and more.
This commit implement base of Automated Circulation System.
* Upgrades Invenio-SIP2 module version.
* Adds SIP2 configuration.
* Adds SIP2 base handlers configuration.
* Implements base sip2 system handlers.
* Implements patron information handlers.
* write some tests.
* Adapts bootstrap script. 
* Adapts travis configuration.
https://tree.taiga.io/project/rero21-reroils/us/1356
> SIP2: implement patron information

- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/items/api/circulation.py
- tests/api/circulation/scenarios/test_scenario_a.py
- tests/api/circulation/scenarios/test_scenario_b.py
- tests/api/circulation/scenarios/test_scenario_c.py
- tests/api/circulation/scenarios/test_scenario_d.py
- tests/api/circulation/test_actions_views_add_request.py
- tests/api/circulation/test_actions_views_cancel_request.py
- tests/api/circulation/test_actions_views_change_pickup.py
- tests/api/circulation/test_actions_views_checkin.py
- tests/api/circulation/test_actions_views_validate_request.py
- tests/api/items/test_items_rest.py
- tests/api/test_item_rest.py
- tests/api/test_loans_rest.py
- tests/ui/circ_policies/test_circ_policies_api.py
- tests/ui/circ_policies/test_circ_policies_utils.py
- tests/ui/circulation/test_actions_cancel_request.py
- tests/ui/circulation/test_actions_extend.py
- tests/ui/circulation/test_actions_validate_request.py
- tests/ui/circulation/test_loan_utils.py
- tests/ui/item_types/test_item_types_api.py
* Deletes all unused imports indicated by autoflake
- Deleting all unused imports from imports.
- `poetry run run-tests`
> test: fix autoflake errors

- rero_ils/config.py
- rero_ils/modules/api.py
- rero_ils/modules/cli.py
- rero_ils/modules/documents/jsonschemas/documents/document-v0.0.1.json
- rero_ils/modules/documents/loaders/__init__.py
- rero_ils/modules/documents/loaders/marcxml.py
- rero_ils/modules/documents/mappings/v6/documents/document-v0.0.1.json
- rero_ils/modules/documents/permissions.py
- rero_ils/query.py
- scripts/setup
- tests/api/documents/test_documents_rest.py
- tests/api/documents/test_marcxml_rest_api.py
- tests/conftest.py
- tests/data/document.xml
- tests/data/documents.xml
- tests/fixtures/metadata.py
- tests/unit/test_cli.py
- tests/unit/test_documents_jsonschema.py
- tests/utils.py
> US1546 marcxml support

- poetry.lock
- pyproject.toml
* Fixes security flask-cors 3.0.8.
> package: update dependencies

- rero_ils/modules/documents/jsonschemas/documents/document_contribution_role-v0.0.1.json
To fix the agent relation role of the contribution field, in order to get the
correct translations
- Check the changed files, verify that the codes are consistent.
> document: replace role label content with values

- data/documents_big.json
- data/documents_small.json
- docker/nginx/nginx.conf
- docker/uwsgi/uwsgi_rest.ini
- docker/uwsgi/uwsgi_ui.ini
- rero_ils/dojson/utils.py
- rero_ils/manual_translations.txt
- rero_ils/modules/api.py
- rero_ils/modules/cli.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_contribution_role-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_dimensions-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_extent-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_note-v0.0.1.json
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
- rero_ils/modules/holdings/api.py
- rero_ils/modules/items/api/api.py
- rero_ils/modules/items/api/record.py
- rero_ils/modules/patrons/cli.py
- rero_ils/modules/utils.py
- scripts/bootstrap
- scripts/setup
- tests/unit/test_documents_dojson.py
* note
* numbering
* subtitle
* issuance
Co-Authored-by: Peter Weber  <peter.weber@rero.ch>
> marc21tojson: fix transformation errors

- rero_ils/config.py
- rero_ils/modules/templates/jsonschemas/templates/template-v0.0.1.json
- rero_ils/modules/templates/permissions.py
- tests/api/templates/test_templates_permissions.py
- tests/api/templates/test_templates_rest.py
* Creates facets in order to filter templates by resource type and
visibility.
Task 1690 of US1642
* https://github.com/rero/rero-ils-ui/pull/351
Please do code review only
> templates: create facets

- rero_ils/modules/persons/api.py
- scripts/setup
* Fixes total count in public search view for a selected organisation.
> persons: fix public search count

- .gitignore
- rero_ils/modules/documents/templates/rero_ils/_documents_get.html
- tests/e2e/cypress/cypress.json
- tests/e2e/cypress/cypress/fixtures/documents.json
- tests/e2e/cypress/cypress/fixtures/items.json
- tests/e2e/cypress/cypress/fixtures/users.json
- tests/e2e/cypress/cypress/integration/circulation/checkout-checkin.spec.js
- tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
- tests/e2e/cypress/cypress/integration/templates/template-test-request.spec.js
- tests/e2e/cypress/cypress/support/circulation.js
- tests/e2e/cypress/cypress/support/commands.js
- tests/e2e/cypress/cypress/support/navigation.js
- tests/e2e/cypress/cypress/support/record.js
- tests/e2e/cypress/cypress/support/user.js
- tests/e2e/cypress/package-lock.json
- tests/e2e/cypress/package.json
* Creates a test in order to make test creation easier and to have a list
of good practices.
* Adds id html attribute in document detail view.
* Adapts checkout-checkin test.
* Corrects custom commands.
* Updates Cypress to v4.12.1.
* Sets default values for viewport in order to not repeat the instruction
for each test.
* Sets custom default values for time out.
* Replaces 'cy.wait()' by timeouts or wait on aliases for a better
robustness where it's possible.
To create a template test with examples and good practices.
* https://github.com/rero/rero-ils-ui/pull/349
You need to include rero-ils-ui into rero-ils:
`cd rero-ils-ui`
`npm ci && npm install path/to/ng-core.tgz --no-save` …
> cypress: create model test

- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- tests/unit/test_documents_dojson_unimarc.py
* closes #1219
* Fixes start and end date from tag 100.
* Fixes transformation for tag 210.
* Fixes country code transformation for unimarc.
> dojson: fix unimarc publishers provision activity

- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
- rero_ils/modules/patrons/templates/rero_ils/_macro_profile.html
* Fixes translation on fees tab.
- Fix translation
> patron: fix profile translations

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
French currently translated at 100.0% (1910 of 1910 strings)
English currently translated at 100.0% (1910 of 1910 strings)
Spanish currently translated at 100.0% (1910 of 1910 strings)
German currently translated at 100.0% (1910 of 1910 strings)
Italian currently translated at 94.0% (1796 of 1910 strings)
Co-authored-by: Pascal Repond <pascalr.92@gmail.com>
Co-authored-by: ManaDeweerdt <anne-marie.deweerdt@uclouvain.be>
Translate-URL: https://hosted.weblate.org/projects/rero_plus/rero-ils/es/
Translate-URL: …
> translations: translate for release v0.12.0

- CHANGES.rst
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/version.py
> release: v0.12.0

- rero_ils/modules/loans/api.py
* Corrects the display of loan patron name.
* Closes #1230.
To close #1230 
N/A
See #1230 description
> loan: fix patron name

- rero_ils/modules/cli.py
- rero_ils/modules/monitoring.py
- tests/api/test_monitoring_rest.py
- tests/ui/test_monitoring.py
* Calculation of es duplicate in monitoring was very slow for big data
sets.
> monitoring: fix es duplicate monitoring

- pyproject.toml
> celery: fix 'celery-config' fixture

- rero_ils/modules/cli.py
- rero_ils/modules/documents/api.py
- rero_ils/modules/persons/api.py
- rero_ils/modules/persons/tasks.py
- scripts/setup
- tests/ui/persons/test_persons_api.py
* Fixes race condition during parallel indexing of documents with
persons creation.
> indexer: fix bulk indexing

- docker/uwsgi/uwsgi_rest.ini
- docker/uwsgi/uwsgi_ui.ini
* Adds specific uwsgi options to solve lxml errors during deployment,
see: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/88
for more details.
- To be able to deploy the application on kubernetes.
> deploy: fix lxml error

- docker-compose.full.yml
- poetry.lock
- pyproject.toml
- rero_ils/modules/cli.py
- scripts/server
- scripts/setup
> celery: use celery 5.0.0

- rero_ils/modules/notifications/templates/email/due_soon/eng.txt
- rero_ils/modules/notifications/templates/email/due_soon/fre.txt
- rero_ils/modules/notifications/templates/email/due_soon/ger.txt
- rero_ils/modules/notifications/templates/email/due_soon/ita.txt
* Remove hardcoded field "Note" in due_soon templates.
* Closes #1264.
- Remove hardcoded field "Note" in due_soon templates.
- Do a checkout, wait to receive the courtesy notice and check there is no "Note" field in the body.
> circulation: change text in courtesy notification

- rero_ils/jsonschemas/common/languages-v0.0.1.json
- rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
- rero_ils/modules/budgets/jsonschemas/budgets/budget-v0.0.1.json
- rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_color_content-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_electronic_locator-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_note-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_production_method-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_title-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_types-v0.0.1.json
- rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
- rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
- rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- rero_ils/modules/notifications/jsonschemas/notifications/notification-v0.0.1.json
- rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/persons/jsonschemas/persons/person-v0.0.1.json
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
* Removes the editor field wrapper configuration as it is automatically done by the ng-core library.
* Adds configuration for date validators.
> data model: remove useless field wrappers

- rero_ils/modules/collections/templates/rero_ils/detailed_view_collections.html
- rero_ils/modules/collections/views.py
- rero_ils/modules/documents/templates/rero_ils/_documents_get.html
- tests/ui/collections/test_collections_utils.py
* Removes location at item level.
* Adds library at collection level.
> collection: fix public detailed view

- rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
- rero_ils/modules/documents/views.py
> collection: Fix in collection filter

- rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
> collection: change some title and description

- rero_ils/modules/monitoring.py
* Adds /api/monitoring/db_connection_counts to monitoring.
* Adds /api/monitoring/db_connections to monitpring.
> monitoring: display db connection counts

- rero_ils/modules/acq_invoices/jsonschemas/acq_invoices/acq_invoice-v0.0.1.json
- rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_orders/jsonschemas/acq_orders/acq_order-v0.0.1.json
- rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
- rero_ils/modules/item_types/jsonschemas/item_types/item_type-v0.0.1.json
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/libraries/jsonschemas/libraries/library-v0.0.1.json
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/jsonschemas/patron_transactions/patron_transaction-v0.0.1.json
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/persons/templates/rero_ils/_person_by_source_data.html
- rero_ils/modules/persons/templates/rero_ils/_person_unified.html
- rero_ils/modules/persons/templates/rero_ils/macros/person.html
- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
* Adds form options entry if an enumeration is present.
* Fixes displaying languages on the person.
- Check translations
> translation: standardization of enumerations with form options

- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
- scripts/setup
- Fixes more than one result when a patron is search by barcode
containing a dash i.e. `cypress-1`. This was due to a bad index
configuration.
- Removes `status` duplicates in the items JSONSchema.
- Fixes token generation for easypump.
> patrons: fix patrons search api

- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/items/api_views.py
- tests/api/items/test_items_rest.py
Updates some functions to improve item circulation webservice
performances.
Closes rero/rero-ils#1246
> circulation: increase loan API performance

- CHANGES.rst
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- rero_ils/version.py
> release: 0.13.0

- data/patron_types.json
- rero_ils/modules/patron_types/api.py
- rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
- rero_ils/modules/patron_types/mappings/v7/patron_types/patron_type-v0.0.1.json
- tests/unit/test_patron_types_jsonschema.py
* Adapts the patron_type JSON schema to include a section about borrow
limits.
* Adds some unit tests to validate the schema constraints
> patron_type: implements checkouts restrictions

- rero_ils/config.py
- rero_ils/query.py
- tests/api/documents/test_documents_rest.py
- tests/data/data.json
- tests/fixtures/metadata.py
* Adds i18n term filter.
* Adapts documents filters in configuration file.
* Adapts tests.
- Filtering by author does not work in documents search.
- go to public search and try to filter by author.
NB: the behavior must be the same in professional interface
> facets: fix contribution filter

- rero_ils/modules/items/api_views.py
Trying to execute a checkout operation for an item with request cause a
server error. This commit fixes this bug.
- Add some request for an item
- Try to execute a checkout for the first requester
> circulation: fix bug on checkout with request

- rero_ils/templates/rero_ils/forgot_password.html
* Adds a warning message to the user without email address.
> login: update reset password message

- rero_ils/modules/documents/jsonschemas/documents/document_contribution_role-v0.0.1.json
* Changes the document JSON schema form options from select to
selectWithSort on the contribution roles in order to sort them
alphabetically in the editor.
* Closes #1231
My PR depends on the following `ng-core`'s PR(s):
* rero/ng-core#281
> document: sort contribution roles

- CHANGES.rst
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/version.py
For the v0.13.1 release
- Check the changed files, especially the release notes for v0.13.0 and v0.13.1
> release: v0.13.1

- rero_ils/config.py
* Adds a new option to sort API response by the resource creation date.
This option is available for all resource.
* Corrects the loan sort options.
> config: add sort parameter on creation date

- tests/e2e/cypress/cypress/fixtures/documents.json
- tests/e2e/cypress/cypress/fixtures/items.json
- tests/e2e/cypress/cypress/fixtures/templates.json
- tests/e2e/cypress/cypress/fixtures/users.json
- tests/e2e/cypress/cypress/integration/circulation/scenario-a.spec.js
- tests/e2e/cypress/cypress/integration/circulation/scenario-b.spec.js
- tests/e2e/cypress/cypress/integration/editor/document/create-simple-document.spec.js
- tests/e2e/cypress/cypress/integration/examples/example-test-request.spec.js
- tests/e2e/cypress/cypress/integration/templates/templates-test.spec.js
- tests/e2e/cypress/cypress/support/api.js
- tests/e2e/cypress/cypress/support/collection.js
- tests/e2e/cypress/cypress/support/navigation.js
- tests/e2e/cypress/cypress/support/record.js
- tests/e2e/cypress/cypress/support/user.js
- tests/e2e/cypress/cypress/support/utils.js
* Removes useless code.
* Replaces UI actions by API calls where possible in order to save time
during the tests.
* Replaces UI navigation by cy.visit instruction when it's relevant
for the test.
* Adds a method to get current date and hour in order to use it in the
API requests.
* Adds methods to create a document and an item with API call.
* Updates fixtures for the requests body.
To improve and fix cypress tests (they will need less time).
* dev of rero-ils-ui
* dev of ng-core
You may need a bootstrap and a setup, depending on your local state.
You must have the correct branchs of rero-ils-ui and ng-core locally (see dependencies above).
`poetry run folding -c …
> cypress: improve tests

- data/patterns.json
- data/vendors.json
- rero_ils/modules/holdings/api.py
- rero_ils/modules/holdings/cli.py
- rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
- rero_ils/modules/holdings/mappings/v7/holdings/holding-v0.0.1.json
- rero_ils/modules/organisations/api.py
- scripts/setup
- tests/data/holdings.json
- tests/ui/organisations/test_organisations_api.py
New fields are added to the holdings records to manage
the late and claimed issues.
- max_number_of_claims
- days_before_first_claim
- days_before_next_claim
- vendor
* Tests and fixtures are updated accordingly.
> serials: new fields to holdings records

- rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
- rero_ils/modules/documents/templates/rero_ils/_documents_description.html
- rero_ils/modules/documents/views.py
- tests/ui/documents/test_documents_filter.py
* Displays qualifier, status and note for identifiers.
* Adds identifier types to translated strings.
* Closes #1403.
* Closes #918.
To close the issues mentioned above.
* https://github.com/rero/rero-ils-ui/pull/421
See issue descriptions.
> document: fix identifier display in detail view

- Dockerfile.base
> deployment: fix poetry version to < 1.1.0

- tests/api/documents/test_documents_rest.py
> tests: fix sort title error

- CHANGES.md
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/bundles.py
- rero_ils/version.py
* Uses rero-ils-ui v0.8.0.
- For the `v0.14.1` release. 
- See changed files
> release: v0.14.1

- rero_ils/templates/rero_ils/header.html
- rero_ils/views.py
Updates the account menu entry by using the full patron name instead of
initials (limited to 30 characters).
Closes rero/rero-ils#1332
> UI: improve account menu entry visibility

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/correction.md
- .github/ISSUE_TEMPLATE/developers.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
* Removes the pre filled title, as users often forget to change it.
* Adds the missing reference for links.
* Puts the instructions in HTML comments in order to prevent them to be
displayed after the issue creation.
- To improve the issue templates.
- See changed files.
> documentation: improve issues templates

- .github/PULL_REQUEST_TEMPLATE.md
* Adds a check point about Cypress test in PR template.
To remind people to run Cypress tests if relevant.
> git: update PR template

- rero_ils/config.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/permissions.py
- rero_ils/modules/loans/tasks.py
- rero_ils/query.py
- scripts/setup
- setup.py
- tests/api/loans/test_loans_api_rest.py
- tests/ui/loans/test_loans_api.py
A new daily job in place to anonymize loans for
all organisations, scheduled for execution at 7h00.
Loans are automatically anonymized after updates.
Anonymized loans are not returned for public and
pro searches.
> circulation: anonymize loans by tasks

- poetry.lock
> dependencies: update after v0.14.1

- poetry.lock
- pyproject.toml
> package: update lxml to version 4.6.2

- poetry.lock
- pyproject.toml
- rero_ils/config.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/selfcheck/api.py
- rero_ils/modules/selfcheck/utils.py
- tests/api/selfcheck/test_selfcheck.py
Allows the patron to do a checkout on the selfcheck machine.
* Adds checkout handler.
* Adds patron status handler.
* Adapts and write some tests.
* Adapts invenio-sip2 package to use latest version.
- https://tree.taiga.io/project/rero21-reroils/task/1857
NB: tests failed because we need a new release of invenio-sip2
> sip2: implement checkout

- rero_ils/config.py
- rero_ils/modules/selfcheck/api.py
- tests/api/selfcheck/test_selfcheck.py
Allows the patron to do a checkin on the selfcheck machine.
* Adds checkin handler.
* Adapts and write some tests.
- https://tree.taiga.io/project/rero21-reroils/task/1856
> sip2: implement checkin

- data/users.json
- rero_ils/modules/patrons/templates/rero_ils/_patron_profile_personal.html
* Adapts fixtures for patrons.
> patrons: enhance keep_history description in profile

- data/ill_requests.json
- rero_ils/config.py
- rero_ils/modules/ill_requests/api.py
- rero_ils/modules/ill_requests/cli.py
- rero_ils/modules/ill_requests/forms.py
- rero_ils/modules/ill_requests/jsonschemas/ill_requests/ill_request-v0.0.1.json
- rero_ils/modules/ill_requests/listener.py
- rero_ils/modules/ill_requests/mappings/v7/ill_requests/ill_request-v0.0.1.json
- rero_ils/modules/ill_requests/models.py
- rero_ils/modules/ill_requests/permissions.py
- rero_ils/modules/ill_requests/serializers.py
- rero_ils/modules/ill_requests/templates/rero_ils/_macro_form.html
- rero_ils/modules/ill_requests/templates/rero_ils/ill_request_form.html
- rero_ils/modules/patrons/templates/rero_ils/_patron_profile_ill_requests.html
- rero_ils/modules/serializers.py
- tests/api/ill_requests/test_ill_requests_permissions.py
- tests/api/ill_requests/test_ill_requests_rest.py
- tests/api/test_serializers.py
- tests/ui/ill_requests/test_ill_requests_api.py
- tests/unit/test_ill_requests_jsonschema.py
* Allows to manage manually the loan status.
* Adds notes (public/staff) to an ILL request.
* Configures request resource to allow faceting.
* Fixes search serializer configuration to include created and updated
date into search results.
* Fixes object serializer with `resolve` argument. 'created' and
'updated' keys were null, date are now correct.
Closes rero/rero-ils#1320
> circulation: update ILL request JSON schema

- rero_ils/modules/vendors/jsonschemas/vendors/vendor-v0.0.1.json
> vendors: do not translate currency codes

- rero_ils/modules/items/api/issue.py
When an error is encountered on processing serials claims, the task
stops prematuraly. Late or claimed issues are not processed.
* Adds try statement to catch and log the error.
> serials: fix claim task

- rero_ils/modules/selfcheck/api.py
Returns checkin or checkout notes to the selfchek machine.
* Adds checkout or checkin note to the selfchek handler.
* Adds try statement to catch error on patron checkin/checkout
> sip2: return circulation notes

- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- tests/unit/test_documents_dojson.py
> data: fix field partOf multiple generation

- .github/workflows/continuous-integration-test.yml
- pyproject.toml
* Deletes caches in github action because of problems.
> ci: fix github actions

- data/users.json
- pyproject.toml
- rero_ils/config.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
- rero_ils/modules/loans/permissions.py
- rero_ils/modules/loans/tasks.py
- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
- rero_ils/modules/patrons/templates/rero_ils/_patron_profile_personal.html
- rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
- rero_ils/query.py
- scripts/setup
- setup.py
- tests/api/loans/test_loans_api_rest.py
- tests/data/data.json
- tests/ui/loans/test_loans_api.py
- US 1422: https://tree.taiga.io/project/rero21-reroils/us/1422
> Implement the keep loan history patron setting (US 1422)

- rero_ils/config.py
Adds 'notification' to resources allowing to be sorted using API.
> configuration: allow notifications sorting

- poetry.lock
- pyproject.toml
This version brings some minor changes:
* Set now as transaction date default in loader.
* Skips permissions when outside request context.
* Allows to customize the Loan datamodel.
> invenio-circulation: upgrade to version v1.0.0a29

- CHANGES.md
- RELEASE-NOTES.rst
- pyproject.toml
- scripts/bootstrap
> release: v0.15.0

- poetry.lock
- pyproject.toml
* Adds py dependency.
* Adds a constraint for jsonpickles.
> tests: fix poetry dependencies

- .github/workflows/continuous-integration-test.yml
Fixes an issue when GitHub actions submit to `coveralls` API.
Authored-by: Aly Badr <aly.badr@rero.ch>
> ci: fix coveralls issue

- rero_ils/es_templates/v7/record.json
- rero_ils/modules/acq_accounts/mappings/v7/acq_accounts/acq_account-v0.0.1.json
- rero_ils/modules/acq_invoices/mappings/v7/acq_invoices/acq_invoice-v0.0.1.json
- rero_ils/modules/acq_order_lines/mappings/v7/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_orders/mappings/v7/acq_orders/acq_order-v0.0.1.json
- rero_ils/modules/budgets/mappings/v7/budgets/budget-v0.0.1.json
- rero_ils/modules/circ_policies/mappings/v7/circ_policies/circ_policy-v0.0.1.json
- rero_ils/modules/collections/mappings/v7/collections/collection-v0.0.1.json
- rero_ils/modules/contributions/mappings/v7/contributions/contribution-v0.0.1.json
- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
- rero_ils/modules/holdings/mappings/v7/holdings/holding-v0.0.1.json
- rero_ils/modules/ill_requests/mappings/v7/ill_requests/ill_request-v0.0.1.json
- rero_ils/modules/item_types/mappings/v7/item_types/item_type-v0.0.1.json
- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
- rero_ils/modules/libraries/mappings/v7/libraries/library-v0.0.1.json
- rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
- rero_ils/modules/local_fields/mappings/v7/local_fields/local_field-v0.0.1.json
- rero_ils/modules/locations/mappings/v7/locations/location-v0.0.1.json
- rero_ils/modules/notifications/mappings/v7/notifications/notification-v0.0.1.json
- rero_ils/modules/organisations/mappings/v7/organisations/organisation-v0.0.1.json
- rero_ils/modules/patron_transaction_events/mappings/v7/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/mappings/v7/patron_transactions/patron_transaction-v0.0.1.json
- rero_ils/modules/patron_types/mappings/v7/patron_types/patron_type-v0.0.1.json
- rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
- rero_ils/modules/templates/mappings/v7/templates/template-v0.0.1.json
- rero_ils/modules/vendors/mappings/v7/vendors/vendor-v0.0.1.json
- tests/ui/circulation/test_inhouse_cipo.py
* Adds an setting template for elasticsearch with `number_of_shards`, `number_of_replicas` and `max_result_window`.
* Cleans all other elastic search mapping files.
Co-Authored-by:  Peter Weber <Peter.Weber@rero.ch>
> search: improve ES template for configuration

- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/imports/api.py
- rero_ils/modules/imports/views.py
- scripts/setup
* closes #1571
* rero/rero-ils-ui#479
> search: fix author facet of BnF import search view

- .github/workflows/stale.yml
- rero_ils/modules/documents/dojson/contrib/unimarctojson/model.py
- rero_ils/modules/imports/api.py
- rero_ils/modules/imports/views.py
- rero_ils/modules/items/api/record.py
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- scripts/setup
- tests/unit/test_items_jsonschema.py
Adapts the item JSON schema and ES mapping to introduce the 'temporary
item type` entry.
> items: Adapts JSON schema for temporary item type

- rero_ils/config.py
- rero_ils/filter.py
- rero_ils/modules/ext.py
- rero_ils/theme/templates/security/email/reset_instructions.txt
- rero_ils/theme/templates/security/email/reset_notice.html
- rero_ils/theme/templates/security/email/reset_notice.txt
- tests/api/test_user_authentication.py
- tests/ui/patrons/test_patrons_api.py
* Improves reset instruction notification.
* Adds a custom template for reset notice notification.
* Closes #1387.
To solve #1387.
N/A
Go to login page and ask to change the password of a user. The template of the emails are logged on the server console.
> notification: improve password reset notifications

- poetry.lock
- pyproject.toml
- rero_ils/config.py
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/items/api/api.py
- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/items/api/record.py
- rero_ils/modules/items/api_views.py
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
- rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
- rero_ils/modules/items/tasks.py
- rero_ils/modules/loans/cli.py
- rero_ils/modules/loans/utils.py
- rero_ils/modules/notifications/utils.py
- tests/api/circulation/test_temporary_item_type.py
- tests/api/test_tasks.py
- tests/ui/circulation/test_inhouse_cipo.py
- tests/ui/items/test_items_api.py
- tests/unit/test_items_jsonschema.py
Merging US `tmp_itty` to `dev`
> Us1376 temporary item type

- rero_ils/config.py
- rero_ils/modules/ext.py
- rero_ils/modules/operation_logs/jsonresolver.py
- rero_ils/modules/operation_logs/listener.py
- rero_ils/modules/operation_logs/models.py
- rero_ils/modules/operation_logs/permissions.py
- tests/api/operation_logs/test_operation_logs_permissions.py
- tests/api/operation_logs/test_operation_logs_rest.py
- tests/data/data.json
- tests/ui/operation_logs/test_operation_logs_api.py
- tests/ui/operation_logs/test_operation_logs_jsonresolver.py
- tests/ui/operation_logs/test_operation_logs_mapping.py
- tests/ui/test_monitoring.py
* Captures operation after record creation of the following resources:
* documents
* holdings
* items
* Adds units testing.
> operation_logs: capture operations

- rero_ils/theme/templates/rero_ils/frontpage.html
- rero_ils/theme/templates/rero_ils/header.html
- Presents the suggestions as the query is typed to the user defined locale.
- Closes rero/rero-ils#1509.
*https://github.com/rero/rero-ils-ui/pull/481
- Test search bar with different language and show translated suggestions.
> search: adapt suggestions to the locale

- data/circulation_policies.json
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
- rero_ils/modules/circ_policies/mappings/v7/circ_policies/circ_policy-v0.0.1.json
- rero_ils/modules/loans/api.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/notifications/dispatcher.py
- rero_ils/modules/notifications/tasks.py
- rero_ils/modules/patron_transactions/api.py
- rero_ils/modules/selfcheck/api.py
- tests/api/circulation/test_borrow_limits.py
- tests/api/loans/test_loans_rest.py
- tests/api/notifications/test_notifications_permissions.py
- tests/api/notifications/test_notifications_rest.py
- tests/api/selfcheck/test_selfcheck.py
- tests/api/test_tasks.py
- tests/data/data.json
- tests/fixtures/circulation.py
- tests/unit/test_circ_policies_jsonschema.py
* Updates the `CirculationPolicy` resource JSON schema to allow multiple
reminders and incremental overdue fees.
* Updates data & fixtures.
* Updates unit test.
* Adapts/improves related code.
> circulation: allows multiple reminders and overdue fees

- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
> editor: display EnumerationAndChronology item field

- rero_ils/config.py
- rero_ils/modules/ebooks/receivers.py
- rero_ils/modules/items/tasks.py
- rero_ils/modules/loans/tasks.py
- rero_ils/modules/monitoring.py
- rero_ils/modules/notifications/tasks.py
- rero_ils/modules/patrons/tasks.py
- rero_ils/modules/tasks.py
- rero_ils/modules/utils.py
- rero_ils/permissions.py
- scripts/setup
- tests/api/test_monitoring_rest.py
* Adds monitoring of redis.
* Adds monitoring@rero.ch user for monitoring access.
> monitoring: monitor redis and add monitoring user

- tests/e2e/cypress/cypress/fixtures/documents.json
- tests/e2e/cypress/cypress/fixtures/templates.json
- tests/e2e/cypress/cypress/integration/templates/templates-test.spec.js
- tests/e2e/cypress/cypress/support/api.js
- tests/e2e/cypress/cypress/support/record.js
* Updates api document create and tests according to new document types.
To repare Cypress test on dev branch.
* Dev of https://github.com/rero/rero-ils-ui
* Dev of https://github.com/rero/ng-core
See the documentation to run the tests: https://github.com/rero/developer-resources/blob/master/tests/cypress.md
> tests: fix cypress tests

- rero_ils/modules/documents/templates/rero_ils/_anonymous_button.html
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
> public ui: fix login button on holdings section

- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
- tests/api/test_external_services.py
- tests/ui/documents/test_documents_mapping.py
> search: index ISBN 10 and 13 format

- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/holdings/templates/rero_ils/detailed_view_holdings.html
> public ui: fix standard coverart in detailed view

- CHANGES.md
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/version.py
- scripts/bootstrap
- `v1.0.0` release. 
- Check the updated files.
> release: 1.0.0

- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/decorators.py
- rero_ils/modules/libraries/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/api_views.py
- rero_ils/modules/loans/listener.py
- rero_ils/modules/loans/utils.py
- rero_ils/modules/patron_transaction_events/listener.py
- rero_ils/modules/patron_transactions/api.py
- rero_ils/modules/patrons/views.py
- setup.py
- tests/api/circulation/test_actions_views_checkin.py
- tests/api/items/test_items_rest.py
- tests/ui/loans/test_loans_api.py
* Adds method on `Loan` resource to compute incremental fees if the loan
is in overdue.
* Adds an API entry point to preview the due fees when the loan will be
returned.
* Updates check-in process to compute and saved the fees if the loan is
in overdue.
> circulation: implement incremental fees

- rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
- tests/ui/circ_policies/test_circ_policies_api.py
> circulation policies: update json schema for Formly

- rero_ils/modules/monitoring.py
* Adds elastic search cluster monitoring.
> monitoring: configure ElasticSearch monitoring

- data/pid_dependencies.json
- poetry.lock
- pyproject.toml
- rero_ils/modules/api.py
- rero_ils/modules/cli.py
- rero_ils/modules/documents/jsonschemas/documents/document_types-v0.0.1.json
- rero_ils/modules/items/api/record.py
- rero_ils/modules/monitoring.py
- rero_ils/modules/utils.py
- scripts/setup
pilot: several improvements
* Implements lazy reading of xml files.
* Adds xml record extraction.
* Adds operation_logs pid dependencies checking.
* Adds paramter for error records saving during record creation.
> various: fix and improve several things

- poetry.lock
- pyproject.toml
* Forces jinja2 > 2.11.2.
* Forces cryptography > 3.3.1.
> dependencies: fix security issues

- CHANGES.md
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/version.py
- scripts/bootstrap
> release: v1.0.1

- poetry.lock
- pyproject.toml
- rero_ils/modules/libraries/api.py
- rero_ils/modules/loans/api.py
* Fixes for invenio 3.4 compatibility for default state assignment in Loan.
* Fixes type in library class.
> circulation: update invenio-circulation to v1.0.0a30

- babel.ini
- data/circulation_policies.json
- package-lock.json
- rero_ils/modules/circ_policies/api.py
- rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
- rero_ils/modules/items/tasks.py
- rero_ils/modules/loans/listener.py
- rero_ils/modules/notifications/api.py
- rero_ils/modules/notifications/dispatcher.py
- rero_ils/modules/patron_transaction_events/api.py
- rero_ils/modules/patron_transaction_events/jsonschemas/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transaction_events/mappings/v7/patron_transaction_events/patron_transaction_event-v0.0.1.json
- rero_ils/modules/patron_transactions/api.py
- rero_ils/modules/patrons/views.py
- tests/api/circulation/test_actions_views_checkin.py
- tests/api/notifications/test_notifications_rest.py
- tests/data/data.json
- tests/e2e/cypress/cypress/integration/editor/ci-po/create-ci-po.spec.js
- tests/e2e/cypress/cypress/support/cipo.js
- tests/ui/notifications/test_notifications_api.py
- tests/unit/test_circ_policies_jsonschema.py
- tests/unit/test_patron_transaction_events_jsonschema.py
Creating an event for each incremental step was a poor idea (regarding
performance issues). Indeed, for old loan with a lot of incremental fee,
we created a PatronTransactionEvent and reindex it. This process take a
lot of time. To Solve this problem, we create only one event with a set
of step. So only one PatronTransactionEvent is created ; and only one
reindex is neceesary.
> transactions: optimise incremental creation

- tests/ui/loans/test_loans_api.py
The `test_loan_get_overdue_fees` unit test failed when it was running on
a closed date. Updates the test to fix this problem.
> test: fix break test.

- poetry.lock
> security: update dependencies

- rero_ils/config.py
- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/loans/utils.py
- tests/api/circulation/test_inhouse_cipo.py
- tests/ui/loans/test_loans_api.py
> circulation: Fix in-house checkout

- rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
> document: add 'bf:Lccn' as identifier type

- rero_ils/modules/documents/utils.py
During processing only the last subfield appeared in the result.
All subfields are now available in the result.
* Closes #1745.
> document: resolve the processing of the title field

- rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
> document: place field required for provision activity

- rero_ils/modules/libraries/api.py
- tests/api/libraries/test_libraries_rest.py
- tests/data/data.json
- tests/ui/libraries/test_libraries_api.py
> library: correct exception dates behavior.

- rero_ils/modules/patrons/templates/rero_ils/patron_profile.html
- rero_ils/theme/templates/rero_ils/page_settings.html
- rero_ils/theme/views.py
Removing the left side menu and inserting items in the user's menu.
- Optimize screen
> user profile: reorganize menu

- CHANGES.md
- RELEASE-NOTES.rst
- pyproject.toml
- rero_ils/version.py
- scripts/bootstrap
> release: v1.1.0

- rero_ils/modules/collections/api.py
- rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
- rero_ils/modules/documents/listener.py
- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
- rero_ils/modules/items/api/api.py
Currently, it is impossible, through the document search, to find a
document by its collection. With this PR, the collection title and
description are indexed into the document index.
Closes rero/rero-ils#1583.
Closes rero/rero-ils#1584.
> Document: index collection title and description.

- .coveragerc
- .github/workflows/continuous-integration-test.yml
- poetry.lock
- pyproject.toml
- rero_ils/modules/ext.py
- rero_ils/modules/imports/api.py
- rero_ils/modules/imports/views.py
- run-tests.sh
- scripts/__init__.py
- tests/api/documents/test_documents_rest.py
- tests/api/test_external_services.py
- tests/conftest.py
- tests/data/bnf_anywhere_all_peter.xml
- tests/data/bnf_ean_any_123.xml
- tests/data/bnf_ean_any_9782070541270.xml
- tests/data/bnf_ean_any_9782072862014.xml
- tests/data/bnf_recordid_all_FRBNF370903960000006.xml
* The BNF service for document retrieval was not relayable. That's why all BNF requests were mocked.
> tests: mocked BNF tests

- rero_ils/config.py
- rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
- rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
- rero_ils/modules/locations/api.py
- rero_ils/modules/selfcheck/admin.py
- rero_ils/modules/selfcheck/api.py
- rero_ils/modules/selfcheck/models.py
- rero_ils/modules/selfcheck/permissions.py
- rero_ils/modules/selfcheck/utils.py
- setup.py
- tests/api/selfcheck/test_admin.py
- tests/api/selfcheck/test_models.py
- tests/api/selfcheck/test_selfcheck.py
- tests/fixtures/sip2.py
- tests/utils.py
> US2014 SIP2 implementation at RERO

- data/users.json
- rero_ils/config.py
- rero_ils/modules/decorators.py
- rero_ils/modules/patrons/api.py
- rero_ils/modules/patrons/cli.py
- rero_ils/modules/patrons/views.py
- rero_ils/utils.py
- tests/api/patrons/test_patrons_rest.py
- tests/ui/patrons/test_patrons_api.py
- tests/ui/patrons/test_patrons_ui.py
* Changed logged user structure.
* Updated users import cli to accept multiple patron on same user.
- To authorize multiple patrons on same user
> patron: multiple patron on same user

- rero_ils/modules/items/api/issue.py
* Fixes incorrect spelling of Exception.
> fix Exception

- rero_ils/modules/cli.py
> records: fix bug when reading the input file of pids

- rero_ils/modules/documents/jsonschemas/documents/document_identified_by-v0.0.1.json
> documents: improve editor

- rero_ils/modules/collections/jsonschemas/collections/collection-v0.0.1.json
- rero_ils/theme/views.py
* Closes #1672
- Rename "Collection" in "Exhibition/course"
- Check if all the changes in "Exhibition/race" are effective.
> collections: rename into "Exhibition/course"

- data/documents_small.json
- rero_ils/dojson/utils.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document_admin_metadata-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_classification-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_summary-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_titles_original-v0.0.1.json
- tests/unit/test_documents_dojson.py
* Implements transformation from Marc21 to JSON RERO ILS  for:
* intendedAudience (L26).
* summary (L27).
* contentMediaCarrier (L30).
* original_language (L31).
* note (L35).
* originalTitle (L36).
* adminMetadata (L34, L37, 45).
* classification (L38).
* sequence_numbering (L39).
* dissertation (L40).
* credits from (L41).
* supplementaryContent from 504 (L42).
* acquisitionTerms (L43).
* tableOfContents (L44).
* genreForm (L49).
* subjects (L50).
* subjects_imported (L53).
* genreForm_imported (L54).
Co-Authored-by: Gianni Pante gianni.pante@rero.ch
> documents: complete the data conversion

- rero_ils/modules/cli.py
A new option, `create_or_update`, is added to the create the CLI that
allows to load new versions of existing records in database.
https://tree.taiga.io/project/rero21-reroils/us/2011?milestone=289558
> data: allow to update existing records

- rero_ils/config.py
* Adds `autocomplete_title` to documents search boosting.
> documents: improve search result boosting

- rero_ils/modules/patron_transaction_events/api.py
- tests/api/patron_transactions/test_patron_transactions_rest.py
- tests/data/data.json
- tests/fixtures/circulation.py
The creation of a photocopy fee raised a JSON validation error because
the initial event was not well generate.
Co-Authored-By: Renaud Michotte <renaud.michotte@gmail.com>
> fees: fix creation of not overdue fee

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/eo/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
English currently translated at 99.9% (2565 of 2566 strings)
French currently translated at 89.8% (2297 of 2566 strings)
German currently translated at 89.6% (2300 of 2566 strings)
Spanish currently translated at 87.2% (2240 of 2566 strings)
Esperanto currently translated at 42.6% (946 of 2217 strings)
Co-authored-by: ManaDeweerdt <anne-marie.deweerdt@uclouvain.be>
Co-authored-by: Ambros Gattlen <ambros.gattlen@admin.vs.ch>
Co-authored-by: phlostically <phlostically@mailinator.com>
Co-authored-by: Adolfo Jayme Barrientos <fitojb@ubuntu.com>
Translate-URL: …
> translations: translate v1.2.0

- rero_ils/modules/documents/api.py
- rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
- rero_ils/modules/documents/templates/rero_ils/detailed_view_documents.html
- rero_ils/modules/documents/views.py
* Fixes the display of subjects with the new implementation.
- Check subjects on documents
> documents: update subject display

- rero_ils/config.py
- rero_ils/modules/items/api/issue.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/utils.py
- tests/api/loans/test_loans_rest.py
- tests/api/test_tasks.py
- tests/ui/loans/test_loans_api.py
> notifications: fix reminder notification problems.

- rero_ils/config.py
- rero_ils/modules/acq_accounts/mappings/v7/acq_accounts/acq_account-v0.0.1.json
> Acq accounts: default sort on name field

- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
- rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
- tests/unit/test_patrons_jsonschema.py
> patrons: allow multiple local codes

- rero_ils/modules/holdings/jsonschemas/holdings/holding-v0.0.1.json
- rero_ils/modules/items/api/issue.py
- tests/data/holdings.json
- tests/ui/holdings/test_serial_claims.py
> issue: fix creation of late issue

- rero_ils/modules/circ_policies/jsonschemas/circ_policies/circ_policy-v0.0.1.json
- rero_ils/modules/items/jsonschemas/items/item-v0.0.1.json
Closes rero/rero-ils#1796.
Closes rero/rero-ils#1830.
Closes rero/rero-ils#1813.
> Item: Allow 'expected' as issue status

- rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
This commit is needed to import actual data from the legacy system.
https://tree.taiga.io/project/rero21-reroils/us/2011?milestone=289558
> users: set local_code field minLength to 1

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/eo/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
English currently translated at 99.6% (2544 of 2554 strings)
French currently translated at 96.1% (2456 of 2554 strings)
German currently translated at 96.9% (2477 of 2554 strings)
Italian currently translated at 92.9% (2374 of 2554 strings)
Spanish currently translated at 87.9% (2245 of 2554 strings)
Co-authored-by: ManaDeweerdt <anne-marie.deweerdt@uclouvain.be>
Co-authored-by: Ambros Gattlen <ambros.gattlen@admin.vs.ch>
Co-authored-by: Adolfo Jayme Barrientos <fitojb@ubuntu.com>
Translate-URL: …
> translations: translate further v1.2.0

- CHANGES.md
- RELEASE-NOTES.rst
- poetry.lock
- pyproject.toml
- rero_ils/version.py
- scripts/bootstrap
* Release commit.
* Upgrades invenio-sip2 module.
- Release commit. 
> release: v1.2.0

- rero_ils/config.py
- rero_ils/modules/contributions/api.py
- rero_ils/modules/documents/dojson/contrib/jsontomarc21/__init__.py
- rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
- rero_ils/modules/documents/serializers.py
- rero_ils/modules/documents/utils.py
- rero_ils/modules/holdings/api.py
- rero_ils/modules/items/api/record.py
- tests/api/documents/test_documents_rest.py
- tests/unit/conftest.py
- tests/unit/test_documents_dojson_marc21.py
* Adds dojson for json to marc21 transformation.
> SRU: convert JSON to MARC21

- scripts/bootstrap
* Copies the `manifest.json` to ${INVENIO_INSTANCE_PATH}/static/dist,
something changed in `invenio-assets` and this file is missing.
> tests: copy manifest.json to fix tests

- rero_ils/query.py
- https://github.com/rero/rero-ils/issues/1824
> search: improve control of the simple parameter

- .github/labeler.yml
- .github/workflows/labeler.yml
- Adds a file that contains the rules, attributing a specific label as
files under specific folders are updated.
- Adds a workflow that implements the above rules as a PR is opened.
- To help triaging PR. This is a first implementation. The rule files can be
completed later. 
- I've tested it on my fork. The following labels have been automatically set: https://github.com/iGormilhit/rero-ils/pulls
> gh actions: add the labeler workflow

- poetry.lock
- scripts/bootstrap
> tests: remove manifest fix

- data/ill_requests.json
- rero_ils/modules/acq_accounts/mappings/v7/acq_accounts/acq_account-v0.0.1.json
- rero_ils/modules/budgets/mappings/v7/budgets/budget-v0.0.1.json
- rero_ils/modules/collections/mappings/v7/collections/collection-v0.0.1.json
- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
- rero_ils/modules/holdings/mappings/v7/holdings/holding-v0.0.1.json
- rero_ils/modules/ill_requests/mappings/v7/ill_requests/ill_request-v0.0.1.json
- rero_ils/modules/items/mappings/v7/items/item-v0.0.1.json
- rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
- rero_ils/modules/notifications/mappings/v7/notifications/notification-v0.0.1.json
- rero_ils/modules/patron_types/mappings/v7/patron_types/patron_type-v0.0.1.json
- rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
- rero_ils/modules/vendors/mappings/v7/vendors/vendor-v0.0.1.json
* Adds missing elastic search mappings.
* Closes #1873, last bullet point of https://github.com/rero/rero-ils/issues/1873#issuecomment-832002648.
> search: add missing mappings

- data/pid_dependencies_big.json
- data/pid_dependencies_small.json
- rero_ils/dojson/utils.py
- rero_ils/modules/cli.py
- rero_ils/modules/patrons/cli.py
- tests/unit/test_csv.py
* Replaces `.format`with f''.
* Corrects verbose message for updated records.
> cli: fix several things

- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
* Adds analyzer to field `authorized_access_point`.
> documents: fix elasticsearch mapping

- .github/labeler.yml
- documentation: add rules to labeler github action
- documentation: extend the gh-action labeler
- To improve the labeler github action.
> update gh labeler

- README.rst
- README file: adds info about how to contribute to translations and updates the copyright line (year and mention to UCLouvain)
> readme: add translation info and update copyright

- data/documents_small.json
- data/documents_small.xml
- rero_ils/dojson/utils.py
- rero_ils/modules/documents/dojson/contrib/marc21tojson/model.py
- rero_ils/modules/documents/jsonschemas/documents/document_classification-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_content_media_carrier-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation_link-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_contribution_person-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_document_relation-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_genre_form-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_identifier-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_provision_activity-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json
- rero_ils/modules/documents/jsonschemas/documents/document_temporal_coverage-v0.0.1.json
- rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json
- rero_ils/modules/utils.py
- tests/unit/test_documents_dojson.py
* Closes #1885.
* Improves json schema reference definitions.
* Closes #1873, last bullet point of https://github.com/rero/rero-ils/issues/1873#issuecomment-832002648.
* Adds identifiedBY values to subjects, genreForm and contribution if possible.
> documents: store source of authority identifiers

- rero_ils/modules/api.py
- rero_ils/modules/ebooks/dojson/contrib/marc21/model.py
* Corrects the deletion of ES indexes in the api.
* Corrects the name of ebook dojson issuance function.
> api: fix delete in api and dojson issuance

- rero_ils/modules/utils.py
* Adds JsonWriter class to write json data well formatted to a file.
> utils: add JSON writer

- data/templates.json
* Adapts fixtures for document templates to work correctly with the
complete JSON schema.
* Closes #1905.
> fixtures: adapt templates to the complete document schema

- rero_ils/modules/contributions/receivers.py
- rero_ils/modules/documents/utils.py
- rero_ils/modules/documents/views.py
- rero_ils/modules/ebooks/receivers.py
- rero_ils/modules/holdings/api.py
- rero_ils/modules/loans/api.py
- rero_ils/modules/notifications/dispatcher.py
- rero_ils/query.py
- rero_ils/schedulers.py
- run-tests.sh
- tests/utils.py
* https://docs.python-guide.org/writing/gotchas/
> fix: empty list in function parameters

- rero_ils/accounts_views.py
- rero_ils/modules/contributions/views.py
* Adds `USER_DOES_NOT_EXIST` to translations.
* Removes `{prefix}{key}`, `{prefix}{item}` and `{prefix}{data}` from
translation.
> translations: fix minor issues

- rero_ils/modules/patrons/mappings/v7/patrons/patron-v0.0.1.json
> patrons: correct city facet mapping

- data/acq_accounts.json
- poetry.lock
- pyproject.toml
- rero_ils/config.py
- rero_ils/modules/acq_accounts/api.py
- rero_ils/modules/acq_accounts/extensions.py
- rero_ils/modules/acq_accounts/jsonschemas/acq_accounts/acq_account-v0.0.1.json
- rero_ils/modules/acq_accounts/listener.py
- rero_ils/modules/acq_accounts/mappings/v7/acq_accounts/acq_account-v0.0.1.json
- rero_ils/modules/acq_accounts/serializers.py
- rero_ils/modules/acq_accounts/views.py
- rero_ils/modules/acq_order_lines/jsonschemas/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_order_lines/mappings/v7/acq_order_lines/acq_order_line-v0.0.1.json
- rero_ils/modules/acq_order_lines/models.py
- rero_ils/modules/budgets/listener.py
- rero_ils/modules/decorators.py
- rero_ils/modules/ext.py
- scripts/setup
- setup.py
- tests/api/acq_accounts/test_acq_accounts_rest.py
- tests/api/acq_accounts/test_acq_accounts_scenario.py
- tests/data/acquisition.json
- tests/unit/test_acq_accounts_jsonschema.py
* Adds fields on the `acq_account` resources and update mapping.
* Updates fixtures.
* Adds API to transfer funds between tow accounts.
> account: add features about acquisition account.

- rero_ils/modules/loans/api.py
- rero_ils/modules/loans/listener.py
- rero_ils/modules/loans/logs/__init__.py
- rero_ils/modules/loans/logs/api.py
- rero_ils/modules/operation_logs/api.py
- rero_ils/modules/operation_logs/es_templates/v7/operation_logs.json
- rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
- setup.py
- tests/ui/loans/test_loans_operation_logs.py
- tests/ui/operation_logs/test_operation_logs_api.py
Adds specific information for loans records in operation logs.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
> logs: log loans

- rero_ils/config.py
- rero_ils/es_templates/v7/record.json
- rero_ils/modules/operation_logs/mappings/v7/operation_logs/operation_log-v0.0.1.json
* Changes MAX_RESULT_WINDOW to 100000.
> search: increase API limit

- rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
* Releases constrain on the firstname and lastname (`minLength` set to
1) to allow user with very short names to be created or imported.
* Closes #1993.
- To fix issue 1993.
> users: release constraint on the first & last name

- .github/labeler.yml
- To improve labeler gh actions
> documentation: extend the gh-actions labeler rules

- rero_ils/modules/api.py
- rero_ils/modules/holdings/api.py
- rero_ils/modules/items/api/api.py
- rero_ils/modules/items/api/circulation.py
- rero_ils/modules/items/api/record.py
- tests/ui/holdings/test_holdings_item.py
* Replaces flush indexing by an es parameter `refresh='true'`.
* Changes the status in the document index instead of reindex the whole
document for the circulation operations.
* Updates the maked value of an holding only if the `_masked` field has
been touched.
* Adds various optimizations.
> resources: speed up the indexing

- rero_ils/modules/loans/cli.py
* Fixes problem when renewals of migrated loans was not possible.
* Fixes #1983
* Fixes #1974
> items: fix status according to migrated loans

- rero_ils/modules/loans/logs/api.py
- rero_ils/modules/operation_logs/es_templates/v7/operation_logs.json
- rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json
- tests/data/data.json
- tests/ui/loans/test_loans_operation_logs.py
* Converts birthdate to age in patron.
* Adds local codes in patron.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
> operation logs: update loan logs

- rero_ils/translations/ar/LC_MESSAGES/messages.po
- rero_ils/translations/de/LC_MESSAGES/messages.po
- rero_ils/translations/en/LC_MESSAGES/messages.po
- rero_ils/translations/eo/LC_MESSAGES/messages.po
- rero_ils/translations/es/LC_MESSAGES/messages.po
- rero_ils/translations/fr/LC_MESSAGES/messages.po
- rero_ils/translations/it/LC_MESSAGES/messages.po
- rero_ils/translations/messages.pot
- rero_ils/translations/nl/LC_MESSAGES/messages.po
- tests/api/test_user_authentication.py
English currently translated at 100.0% (2573 of 2573 strings)
French currently translated at 99.8% (2568 of 2573 strings)
German currently translated at 96.2% (2476 of 2573 strings)
Italian currently translated at 92.2% (2373 of 2573 strings)
Spanish currently translated at 89.5% (2304 of 2573 strings)
Esperanto currently translated at 36.1% (929 of 2573 strings)
Co-authored-by: ManaDeweerdt <anne-marie.deweerdt@uclouvain.be>
Co-authored-by: Ambros Gattlen <ambros.gattlen@admin.vs.ch>
Co-authored-by: Adolfo Jayme Barrientos <fitojb@ubuntu.com>
Translate-URL: …
> translations: translate v1.3.0

- poetry.lock
- pyproject.toml
- rero_ils/acquisition/__init__.py
- rero_ils/acquisition/config.py
- rero_ils/acquisition/ext.py
- rero_ils/acquisition/proxies.py
- setup.py
This commit prepare the migration of acquisition resources to invenio-records-resource.
* Creates new acquisition extension.
* Adds invenio-records-resources packages.
* Updates setup.py.
> acquisitions: create new extension

- rero_ils/modules/patrons/cli.py
* Adds the test of multiple librarien roles to `users_validate` cli.
> patrons: tests multiple librarian roles

- rero_ils/config.py
- rero_ils/modules/patrons/views.py
- rero_ils/oauth/scopes.py
- rero_ils/theme/templates/rero_ils/oauth/base.html
- setup.py
- tests/api/patrons/test_patrons_rest.py
- tests/data/data.json
* Configures scopes.
* Configures OAuth base template.
* Adds a rest endpoint to retrieve patron information.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
> authentication: implement OAuth server
